---
title: "Human and mouse cluster similarity"
author: "Antoine Beauchamp"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(RMINC))
suppressPackageStartupMessages(library(MRIcrotome))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(gridExtra))
```

```{r functions}
source("../../src/utils.R")
source("../../src/processing.R")
source("../../src/analysis.R")
```

```{r directories}
#Output directory
output_dir <- "outputs"

#Similarity pipeline
version <- "v1"
pipeline_dir <- "../../data/cross_species/"
pipeline_dir <- file.path(pipeline_dir, version)

#Human parameters
human_resolution <- 0.8
human_es_method <- "normative-growth"
human_es_df <- 3
human_cluster_map_method <- "mean"

#Mouse parameters
mouse_resolution <- 0.2
mouse_cluster_map_method <- human_cluster_map_method

#Similarity parameters
metric <- "correlation"

metadata <- file.path(pipeline_dir, "metadata.csv")
params <- fetch_params_metadata(metadata = metadata,
                                human_resolution = human_resolution,
                                human_es_method = human_es_method,
                                human_es_df = human_es_df,
                                human_cluster_map_method = human_cluster_map_method,
                                metric = metric)
# params
```

```{r parameters}
#Parameter set ID
params_id <- 405

#Human parameter set ID
human_params_id <- params %>% 
  filter(id == params_id) %>% 
  pull(human_id)

#Mouse parameter set ID
mouse_params_id <- params %>% 
  filter(id == params_id) %>% 
  pull(mouse_id)

#Pipeline directory
pipeline_dir <- file.path(pipeline_dir, params_id, "similarity")

#Human pipeline directory
human_pipeline_dir <- "../../data/human/derivatives/"
human_pipeline_dir <- file.path(human_pipeline_dir, version, human_params_id)

#Mouse pipeline directory
mouse_pipeline_dir <- "../../data/mouse/derivatives/"
mouse_pipeline_dir <- file.path(mouse_pipeline_dir, "v2", mouse_params_id)

#Output directory
output_dir <- file.path(output_dir, version, params_id)
if (!(dir.exists(output_dir))) {dir.create(output_dir, recursive = TRUE)}
```


```{r}
jacobians <- c("absolute", "relative")
similarity_files <- list.files(pipeline_dir, full.names = TRUE)
similarity <- vector(mode = "list", length = length(jacobians))
names(similarity) <- jacobians
for (i in 1:length(similarity)) {
  similarity[[i]] <- read_csv(similarity_files[i], show_col_types = FALSE)
}
```

```{r}
for (i in 1:length(similarity)) {
  similarity[[i]] <- similarity[[i]] %>% 
    mutate(human_nk = human_img %>% basename() %>% str_extract("_nk_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric(),
           human_k = human_img %>% basename() %>% str_extract("_k_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric(),
           mouse_nk = mouse_img %>% basename() %>% str_extract("_nk_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric(),
           mouse_k = mouse_img %>% basename() %>% str_extract("_k_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric()) %>% 
    unite(col = "human_cluster_id", human_nk, human_k, sep = "-", remove = FALSE) %>% 
    unite(col = "mouse_cluster_id", mouse_nk, mouse_k, sep = "-", remove = FALSE)
}
```

# Mouse-human cluster similarity

```{r}
h_nk <- 6
m_nk <- 4
```

```{r}
similarity_nk <- vector(mode = "list", length = length(similarity))
names(similarity_nk) <- names(similarity)
for (i in 1:length(similarity_nk)) {
  similarity_nk[[i]] <- similarity[[i]] %>% 
    filter(human_nk == h_nk,
           mouse_nk == m_nk) %>% 
    mutate(human_cluster_id = factor(human_cluster_id, 
                                     levels = sort(unique(human_cluster_id))),
           mouse_cluster_id = factor(mouse_cluster_id, 
                                     levels = sort(unique(mouse_cluster_id))))
}
```

```{r}
df_sim_abs <- similarity_nk[["absolute"]]
heatmap_range_abs <- c(min(df_sim_abs[["similarity"]]), max(df_sim_abs[["similarity"]]))
heatmap_range_dist <- heatmap_range_abs[2] - heatmap_range_abs[1]

heatmap_colours <- rev(brewer.pal(n = 7, name = "RdYlBu"))
palette_length <- 255
heatmap_palette <- colorRampPalette(heatmap_colours)(palette_length)

heatmap_breaks_abs <- seq(heatmap_range_abs[1], heatmap_range_abs[2], length.out = palette_length)

p_sim_abs <- ggplot(df_sim_abs, 
                    aes(x = human_cluster_id, 
                        y = fct_rev(mouse_cluster_id), 
                        fill = similarity)) + 
  geom_tile(col = "grey50") + 
  labs(x = "Human clusters",
       y = "Mouse clusters",
       fill = metric,
       title = "Similarity based on absolute effect sizes") + 
  scale_fill_gradientn(colors = heatmap_palette) +
  scale_x_discrete(expand = expansion(mult = 0), position = "top") + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  theme_bw() + 
  theme(axis.ticks = element_blank())

p_sim_abs
```

```{r}
df_sim_rel <- similarity_nk[["relative"]]

p_sim_rel <- ggplot(df_sim_rel, 
                    aes(x = human_cluster_id, 
                        y = fct_rev(mouse_cluster_id), 
                        fill = similarity)) + 
  geom_tile(col = "grey50") + 
  labs(x = "Human clusters",
       y = "Mouse clusters",
       fill = metric,
       title = "Similarity based on relative effect sizes") + 
  scale_fill_gradientn(colors = heatmap_palette) +
  scale_x_discrete(expand = expansion(mult = 0), position = "top") + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  theme_bw() + 
  theme(axis.ticks = element_blank())

p_sim_rel
```


```{r}
df_sim_combined <- bind_rows(df_sim_abs %>% 
                               mutate(jacobians = "absolute"),
                             df_sim_rel %>% 
                               mutate(jacobians = "relative")) %>% 
  group_by(human_cluster_id, mouse_cluster_id) %>% 
  summarise(similarity = mean(similarity), .groups = "drop")

p_sim_combined <- ggplot(df_sim_combined, 
                         aes(x = human_cluster_id, 
                             y = fct_rev(mouse_cluster_id), 
                             fill = similarity)) + 
  geom_tile(col = "grey50") + 
  labs(x = "Human clusters",
       y = "Mouse clusters",
       fill = metric,
       title = "Combined similarity matrices") + 
  scale_fill_gradientn(colors = heatmap_palette) +
  scale_x_discrete(expand = expansion(mult = 0), position = "top") + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  theme_bw() + 
  theme(axis.ticks = element_blank())

p_sim_combined
```

# Mouse and human cluster centroid maps

```{r}
nk_mouse <- 4
k_mouse <- 4

nk_human <- 6
k_human <- 6
```

```{r}
mouse_anat_file <- "../../data/mouse/atlas/DSURQE_CCFv3_average_200um.mnc"
mouse_anat <- mincGetVolume(mouse_anat_file)
mouse_anat_vol <- mincArray(mouse_anat)

#Human anatomy
human_anat_file <- "../../data/human/registration/v1/reference_files/model_0.8mm.mnc"
human_anat <- mincGetVolume(human_anat_file)
human_anat_vol <- mincArray(human_anat)

#Cropped human images along sagittal and transverse planes
human_slices_dim_1 <- 25:200
human_slices_dim_3 <- 25:220
human_anat_vol_cropped <- human_anat_vol[human_slices_dim_1,,human_slices_dim_3]

#Human mask
human_mask <- "../../data/human/registration/v1/reference_files/mask_0.8mm.mnc"

#Mouse mask
mouse_mask <- "../../data/mouse/atlas/coronal_200um_coverage_bin0.8.mnc"
```

```{r}
#Human cluster map directories
human_cluster_map_dirs <- file.path(human_pipeline_dir, "cluster_maps")
human_cluster_map_dirs <- file.path(human_cluster_map_dirs, str_c("resolution_", human_resolution))
human_cluster_map_dirs <- file.path(human_cluster_map_dirs, jacobians)
names(human_cluster_map_dirs) <- jacobians

#Mouse cluster map directories
mouse_cluster_map_dirs <- file.path(mouse_pipeline_dir, "cluster_maps")
mouse_cluster_map_dirs <- file.path(mouse_cluster_map_dirs, str_c("resolution_", mouse_resolution))
mouse_cluster_map_dirs <- file.path(mouse_cluster_map_dirs, jacobians)
names(mouse_cluster_map_dirs) <- jacobians  
```

```{r}
signed <- params %>% 
  filter(id == params_id) %>% 
  pull(signed)

threshold <- params %>% 
  filter(id == params_id) %>% 
  pull(threshold)

threshold_value <- params %>% 
  filter(id == params_id) %>% 
  pull(threshold_value)

threshold_symmetric <- params %>% 
  filter(id == params_id) %>% 
  pull(threshold_symmetric)
```

```{r fig.height = 10, fig.width = 3}
list_human_clusters <- vector(mode = "list", length = length(jacobians))
for (i in 1:length(list_human_clusters)) {
  list_human_clusters[[i]] <-  import_cluster_map(imgdir = human_cluster_map_dirs[[i]],
                                                  mask = human_mask,
                                                  nk = nk_human, k = k_human,
                                                  threshold = threshold,
                                                  threshold_value = threshold_value,
                                                  threshold_symmetric = threshold_symmetric)
}

ss_human_grob <- sliceSeries(nrow = 10, ncol = 1, begin = 50, end = 200) %>% 
  anatomy(human_anat_vol_cropped, low = 3, high = 7) %>% 
  overlay(mincArray(list_human_clusters[[1]])[human_slices_dim_1,,human_slices_dim_3], 
          low = 0.2, high = 1, symmetric = TRUE) %>% 
  addtitle(jacobians[1]) %>% 
  sliceSeries() %>% anatomy() %>%
  overlay(mincArray(list_human_clusters[[2]])[human_slices_dim_1,,human_slices_dim_3], 
          low = 0.2, high = 1, symmetric = TRUE) %>% 
  addtitle(jacobians[2]) %>% 
  legend("Effect size") %>% 
  grobify()
```

```{r fig.height = 10, fig.width = 4}
list_mouse_clusters <- vector(mode = "list", length = length(jacobians))
for (i in 1:length(list_mouse_clusters)) {
  list_mouse_clusters[[i]] <-  import_cluster_map(imgdir = mouse_cluster_map_dirs[[i]],
                                                  mask = mouse_mask,
                                                  nk = nk_mouse, k = k_mouse,
                                                  threshold = threshold,
                                                  threshold_value = threshold_value,
                                                  threshold_symmetric = threshold_symmetric)
}

ss_mouse_grob <- sliceSeries(nrow = 10, ncol = 1, begin = 10, end = 50) %>% 
  anatomy(mouse_anat_vol, low = 700, high = 1400) %>% 
  overlay(mincArray(list_mouse_clusters[[1]]), 
          low = 0.2, high = 1, symmetric = TRUE) %>% 
  addtitle(jacobians[1]) %>% 
  sliceSeries() %>% anatomy() %>%
  overlay(mincArray(list_mouse_clusters[[2]]), 
          low = 0.2, high = 1, symmetric = TRUE) %>% 
  addtitle(jacobians[2]) %>% 
  legend("Effect size") %>% 
  grobify()
```

```{r fig.width = 6, fig.height = 10}
ss_grob <- arrangeGrob(ss_human_grob, ss_mouse_grob,
                       layout_matrix = rbind(c(1,2)),
                       widths = unit(c(0.45, 0.55), 'npc'))

grid.newpage()
grid.draw(ss_grob)
```



