# ----------------------------------------------------------------------------
# create_neuro_pairs.R
# Author: Antoine Beauchamp
# Created: August 4th, 2021
#
# Description
# -----------
# This script defines a set of canonical neuroanatomical pairs between the
# mouse and human brain atlases

# Packages -------------------------------------------------------------------

suppressPackageStartupMessages(library(optparse))
suppressPackageStartupMessages(library(tidyverse))

# Command line arguments -----------------------------------------------------

option_list <- list(
  make_option("--outdir",
              type = "character",
              default = "data/",
              help = paste("Directory in which to save the output files (.csv)",
                           "[default %default]"))
)

args <- parse_args(OptionParser(option_list = option_list))

# Mouse labels 67 / Human labels 88 -------------------------------------------

dfMouseHumanMatches_H88M67 <- tibble::tibble(Mouse = c("Claustrum", 
                                                       "Piriform area",
                                                       "Subiculum",
                                                       "Field CA1", 
                                                       "Field CA2",
                                                       "Field CA3",
                                                       "Dentate gyrus",
                                                       "Anterior cingulate area",
                                                       "Primary auditory area",
                                                       "Primary motor area",
                                                       "Primary somatosensory area",
                                                       "Visual areas",
                                                       "Pallidum",
                                                       "Striatum ventral region",
                                                       "Caudoputamen",
                                                       "Cortical subplate-other",
                                                       "Inferior colliculus",
                                                       "Superior colliculus, sensory related",
                                                       "Medulla",
                                                       "Pons",
                                                       "Hypothalamus",
                                                       "Thalamus",
                                                       "Lingula (I)",
                                                       "Declive (VI)",
                                                       "Folium-tuber vermis (VII)",
                                                       "Pyramus (VIII)",
                                                       "Uvula (IX)", 
                                                       "Nodulus (X)", 
                                                       "Simple lobule",
                                                       "Crus 1",
                                                       "Crus 2",
                                                       "Paramedian lobule",
                                                       "Copula pyramidis",
                                                       "Flocculus",
                                                       "Paraflocculus",
                                                       "Cerebellar nuclei",
                                                       "fiber tracts",
                                                       "ventricular systems"),
                                             Human = c("claustrum",
                                                       "piriform cortex",
                                                       "subiculum",
                                                       "CA1 field",
                                                       "CA2 field",
                                                       "CA3 field",
                                                       "dentate gyrus",
                                                       "cingulate gyrus",
                                                       "Heschl's gyrus", 
                                                       "precentral gyrus", 
                                                       "postcentral gyrus",
                                                       "cuneus",
                                                       "globus pallidus",
                                                       "nucleus accumbens",
                                                       "caudate nucleus",
                                                       "amygdala",
                                                       "inferior colliculus",
                                                       "superior colliculus",
                                                       "myelencephalon",
                                                       "pons",
                                                       "hypothalamus",
                                                       "thalamus",
                                                       "vermal I-II",
                                                       "vermal VI", 
                                                       "vermal VIIAf",
                                                       "vermal VIIIA", 
                                                       "vermal IX", 
                                                       "vermal X",
                                                       "VI",
                                                       "crus I",
                                                       "crus II",
                                                       "VIIB",
                                                       "VIIIA", 
                                                       "X",
                                                       "IX",
                                                       "cerebellar nuclei",
                                                       "white matter",
                                                       "sulci & spaces"),
                                             name = c("Claustrum",
                                                      "Piriform area",
                                                      "Subiculum",
                                                      "Field CA1",
                                                      "Field CA2",
                                                      "Field CA3",
                                                      "Dentate gyrus",
                                                      "Cingulate area",
                                                      "Primary auditory area",
                                                      "Primary motor area",
                                                      "Primary somatosensory area",
                                                      "Visual areas",
                                                      "Pallidum",
                                                      "Nucleus accumbens",
                                                      "Caudoputamen",
                                                      "Amygdala",
                                                      "Inferior colliculus",
                                                      "Superior colliculus",
                                                      "Medulla",
                                                      "Pons",
                                                      "Hypothalamus",
                                                      "Thalamus",
                                                      "Lingula (I)",
                                                      "Declive (VI)",
                                                      "Folium-tuber vermis (VII)",
                                                      "Pyramus (VIII)",
                                                      "Uvula (IX)", 
                                                      "Nodulus (X)", 
                                                      "Simple lobule",
                                                      "Crus 1",
                                                      "Crus 2",
                                                      "Paramedian lobule",
                                                      "Copula pyramidis",
                                                      "Flocculus",
                                                      "Paraflocculus",
                                                      "Cerebellar nuclei",
                                                      "White matter",
                                                      "Ventricles"))

outfile <- "MouseHumanMatches_H88M67.csv"
outfile <- file.path(args[["outdir"]], outfile)
readr::write_csv(x = dfMouseHumanMatches_H88M67, 
                 file = outfile)


# Mouse labels 23 / Human labels 23 -------------------------------------------

dfMouseHumanMatches_H23M23 <- tibble::tibble(Mouse = c("Claustrum", 
                                                       "Piriform area",
                                                       "Hippocampal formation",
                                                       "Anterior cingulate area",
                                                       "Primary auditory area",
                                                       "Primary motor area",
                                                       "Primary somatosensory area",
                                                       "Visual areas",
                                                       "Pallidum",
                                                       "Striatum ventral region",
                                                       "Caudoputamen",
                                                       "Cortical subplate-other",
                                                       "Inferior colliculus",
                                                       "Superior colliculus, sensory related",
                                                       "Medulla",
                                                       "Pons",
                                                       "Hypothalamus",
                                                       "Thalamus",
                                                       "Vermal regions",
                                                       "Hemispheric regions",
                                                       "Cerebellar nuclei",
                                                       "fiber tracts",
                                                       "ventricular systems"),
                                             Human = c("claustrum",
                                                       "piriform cortex",
                                                       "hippocampal formation",
                                                       "cingulate gyrus",
                                                       "Heschl's gyrus", 
                                                       "precentral gyrus", 
                                                       "postcentral gyrus",
                                                       "cuneus",
                                                       "globus pallidus",
                                                       "nucleus accumbens",
                                                       "caudate nucleus",
                                                       "amygdala",
                                                       "inferior colliculus",
                                                       "superior colliculus",
                                                       "myelencephalon",
                                                       "pons",
                                                       "hypothalamus",
                                                       "thalamus",
                                                       "vermis",
                                                       "cerebellar hemispheres",
                                                       "cerebellar nuclei",
                                                       "white matter",
                                                       "sulci & spaces"),
                                             name = c("Claustrum", 
                                                      "Piriform area",
                                                      "Hippocampal formation",
                                                      "Anterior cingulate area",
                                                      "Primary auditory area",
                                                      "Primary motor area",
                                                      "Primary somatosensory area",
                                                      "Visual areas",
                                                      "Pallidum",
                                                      "Nucleus accumbens",
                                                      "Caudoputamen",
                                                      "Amygdala",
                                                      "Inferior colliculus",
                                                      "Superior colliculus",
                                                      "Medulla",
                                                      "Pons",
                                                      "Hypothalamus",
                                                      "Thalamus",
                                                      "Cerebellar vermis",
                                                      "Cerebellar hemispheres",
                                                      "Cerebellar nuclei",
                                                      "White matter",
                                                      "Ventricles"))

outfile <- "MouseHumanMatches_H23M23.csv"
outfile <- file.path(args[["outdir"]], outfile)
readr::write_csv(x = dfMouseHumanMatches_H23M23, 
                 file = outfile)



# Mouse labels 9 / Human labels 10 -------------------------------------------

dfMouseHumanMatches_H10M09 <- tibble(Mouse = c("Cerebral cortex",
                                               "Cerebral nuclei",
                                               "Interbrain",
                                               "Midbrain",
                                               "Pons",
                                               "Medulla",
                                               "Cerebellar cortex",
                                               "Cerebellar nuclei",
                                               "fiber tracts",
                                               "ventricular systems"),
                                     Human = c("cerebral cortex",
                                               "cerebral nuclei",
                                               "diencephalon",
                                               "mesencephalon",
                                               "pons",
                                               "myelencephalon",
                                               "cerebellar cortex",
                                               "cerebellar nuclei",
                                               "white matter",
                                               "sulci & spaces"),
                                     name = c("Cerebral cortex",
                                              "Cerebral nuclei",
                                              "Interbrain",
                                              "Midbrain",
                                              "Pons",
                                              "Medulla",
                                              "Cerebellar cortex",
                                              "Cerebellar nuclei",
                                              "White matter",
                                              "Ventricles"))

outfile <- "MouseHumanMatches_H10M09.csv"
outfile <- file.path(args[["outdir"]], outfile)
readr::write_csv(x = dfMouseHumanMatches_H10M09, 
                 file = outfile)