#!/bin/bash

absolute_dir=data/human/registration/jacobians/absolute/smooth/
relative_dir=data/human/registration/jacobians/relative/smooth/

echo "Decompressing absolute jacobians files..."
gunzip -f -k ${absolute_dir}*.nii.gz

echo "Converting absolute jacobians to MINC format..."
files=(${absolute_dir}*.nii)
for file in ${files[@]};
do
	nii2mnc -quiet -clobber $file
	rm $file
done

echo "Decompressing relative jacobians files..."
gunzip -f -k ${relative_dir}*.nii.gz

echo "Converting relative jacobians to MINC format..."
files=(${relative_dir}*.nii)
for file in ${files[@]};
do
	nii2mnc -quiet -clobber $file
	rm $file
done
