#!/bin/bash

files=(/projects/jacob/ClusteringAutism_125Models_Mar2020/Data/Outputs/Clusters/Group_*_200_*.mnc)

outdir=data/mouse/cluster_maps/

#echo ${files[@]}

for file in ${files[@]};
do
	ln -s $file ${outdir}
done
