#!/bin/bash

source activate_venv


#python3 downsample_human_images.py \
#	--imgdir data/human/effect_sizes/testdir/ \
#	--outdir data/human/effect_sizes/testdir/downsampled/ \
#	--isostep 3.0 \
#	--parallel false \
#	--nproc 4

python3 downsample_images.py \
	--imgdir data/human/effect_sizes/absolute/ \
	--outdir data/human/effect_sizes/absolute/downsampled/ \
	--isostep 3.0 \
	--parallel true \
	--nproc 4

python3 downsample_images.py \
	--imgdir data/human/effect_sizes/relative/ \
	--outdir data/human/effect_sizes/relative/downsampled/ \
	--isostep 3.0 \
	--parallel true \
	--nproc 4

deactivate
