#!/bin/bash

source activate_venv

#Extract jacobians and convert to minc
#python3 extract_jacobian_images.py \
#	--imgdir data/human/registration/jacobians/absolute/smooth/ \
#	--parallel true \
#	--nproc 8

#python3 extract_jacobian_images.py \
#	--imgdir data/human/registration/jacobians/relative/smooth/ \
#	--parallel true \
#	--nproc 8

#Calculate human effect sizes based on relative and absolute volumes
Rscript calculate_effect_sizes.R \
	--demographics data/human/registration/DBM_input_demo_passedqc.csv \
	--imgdir data/human/registration/jacobians/absolute/smooth/ \
	--outdir data/human/effect_sizes/absolute/resolution_0.5/ \
	--maskfile data/human/registration/reference_files/mask.mnc \
	--ncontrols 10 \
	--parallel true \
	--nproc 4

Rscript calculate_effect_sizes.R \
	--demographics data/human/registration/DBM_input_demo_passedqc.csv \
	--imgdir data/human/registration/jacobians/relative/smooth/ \
	--outdir data/human/effect_sizes/relative/resolution_0.5/ \
	--maskfile data/human/registration/reference_files/mask.mnc \
	--ncontrols 10 \
	--parallel true \
	--nproc 4

#Downsample model and mask files
autocrop -quiet -clobber -isostep 3.0 \
	data/human/registration/reference_files/model.mnc \
	data/human/registration/reference_files/model_downsampled_3.0mm.mnc

autocrop -quiet -clobber -isostep 3.0 \
	data/human/registration/reference_files/mask.mnc \
	data/human/registration/reference_files/mask_downsampled_3.0mm.mnc

#Downsample human effect size images 
python3 downsample_images.py \
	--imgdir data/human/effect_sizes/absolute/resolution_0.5/ \
	--outdir data/human/effect_sizes/absolute/resolution_3.0/ \
	--isostep 3.0 \
	--parallel true \
	--nproc 4

python3 downsample_images.py \
	--imgdir data/human/effect_sizes/relative/resolution_0.5/ \
	--outdir data/human/effect_sizes/relative/resolution_3.0/ \
	--isostep 3.0 \
	--parallel true \
	--nproc 4

#Create matrices for human effect sizes
python3 build_effect_size_matrix.py \
	--imgdir data/human/effect_sizes/absolute/resolution_3.0/ \
	--outdir data/human/effect_sizes/ \
	--outfile human_effect_sizes_absolute_3.0mm.csv \
	--mask data/human/registration/reference_files/mask_downsampled_3.0mm.mnc \
    
python3 build_effect_size_matrix.py \
	--imgdir data/human/effect_sizes/relative/resolution_3.0/ \
	--outdir data/human/effect_sizes/ \
	--outfile human_effect_sizes_relative_3.0mm.csv \
	--mask data/human/registration/reference_files/mask_downsampled_3.0mm.mnc \
	
#Cluster human effect sizes
Rscript cluster_human_data.R \
	--file1 data/human/effect_sizes/human_effect_sizes_absolute_3.0mm.csv \
	--file2 data/human/effect_sizes/human_effect_sizes_relative_3.0mm.csv \
	--rownames imagefile \
	--nclusters 10 \
	--K 10 \
	--t 20 \
	--alpha 0.5 \
	--metric cor \
	--outfile data/human/clustering/clusters_groups10_3.0mm.csv


deactivate
