#!/bin/bash

#source pipeline_transcriptomic

#source pipeline_human

source activate_venv

#Create masks indicating which voxels are in the cluster
python3 create_cluster_masks.py \
    --datadir data/mouse/cluster_maps/ \
    --outdir data/mouse/cluster_masks \
    --threshold 0.5 \
    --symmetric true 
    
python3 create_cluster_masks.py \
    --datadir data/human/clustering/cluster_maps/resolution_3.0/ \
    --outdir data/human/clustering/cluster_masks/resolution_3.0/ \
    --threshold 0.5 \
    --symmetric true 

#Create cluster signatures for mouse clusters
python3 create_cluster_signatures.py \
	--clusterdir data/mouse/cluster_masks/ \
	--exprdir data/MLP_outcomes/ \
	--exprglob MLP_labels67_layers3_units200_L21e-06_mousetransform*.csv \
	--mask data/mouse/atlas/coronal_200um_coverage_bin0.8.mnc \
	--outdir data/ \
	--outfile MouseClusterSignatures_latentspace.csv \
	--parallel true \
	--nproc 8
    
    
deactivate
