#!/bin/bash

source activate_venv

python3 create_average_latent_space.py \
	--datadir data/MLP_outcomes/ \
	--outdir data/ \
	--fileglob MLP_labels67_layers3_units200_L21e-06_mousetransform*.csv

deactivate
