#!/bin/bash

source activate_venv

#python3 build_voxel_matrix.py \
#	--datadir /projects/abeauchamp/Projects/MouseHumanMapping/Paper_TranscriptomicSimilarity/AMBA/data/expression/ \
#	--dataset coronal \
#	--outdir data/mouse/ \
#	--mask data/mouse/atlas/average_template_200um_mask.mnc \
#	--log2 true \
#	--groupexp true \
#	--threshold 0.2 \
#	--impute true \
#	--parallel true \
#	--nproc 4

echo "Filtering homologous genes..."

python3 intersect_gene_homologs.py \
	--mouse data/mouse/MouseExpressionMatrix_voxel_coronal_log2_grouped_imputed.csv \
	--human data/human/HumanExpressionMatrix_samples_pipeline_v1.csv \
	--homologs data/MouseHumanGeneHomologs.csv \
	--outdir data/ \
	--verbose true

echo "Labelling expression matrices..."

Rscript label_expression_matrix.R \
	--species mouse \
	--matrix data/MouseExpressionMatrix_voxel_coronal_log2_grouped_imputed_homologs.csv \
	--tree data/mouse/MouseExpressionTree_DSURQE.RData \
	--treelabels data/TreeLabels.RData \
	--nlabels 67 \
	--labels data/mouse/atlas/DSURQE_CCFv3_labels_200um.mnc \
	--mask data/mouse/atlas/coronal_200um_coverage_bin0.8.mnc \
	--greymatter true \
	--verbose true

Rscript label_expression_matrix.R \
	--species human \
	--matrix data/HumanExpressionMatrix_samples_pipeline_v1_homologs.csv \
	--tree data/human/HumanExpressionTree.RData \
	--treelabels data/TreeLabels.RData \
	--nlabels 88 \
	--greymatter true \
	--verbose true

echo "Processing expression matrices..."

Rscript process_expression_matrix.R \
	--infile data/MouseExpressionMatrix_voxel_coronal_log2_grouped_imputed_homologs_labelled_region67.csv \
	--transpose false \
	--scale true \
	--aggregate false \
	--outdir data/ \
	--verbose true

Rscript process_expression_matrix.R \
	--infile data/HumanExpressionMatrix_samples_pipeline_v1_homologs_labelled_region88.csv \
	--transpose false \
	--scale true \
	--aggregate false \
	--outdir data/ \
	--verbose true

deactivate
