---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(tidyverse)

npts <- 500
x <- 1:500
x_data <- c(100, 400)
y_data <- c(5, 2)

df_data <- tibble(x = x_data, 
                  y = y_data)

ggplot(df_data, aes(x = x, y = y)) + 
  geom_point() + 
  coord_cartesian(xlim = c(min(x), max(x)),
                  ylim = c(0, 10))
```

```{r}
sigma <- 50
i <- 1
for (i in 1:nrow(df_data)){
  x_i <- df_data[[i, "x"]]
  y_i <- df_data[[i, "y"]]
  kernel_i <- sqrt(2*pi)*sigma*dnorm(x = x, mean = x_i, sd = sigma)
  if (i == 1) {
    df_kernel <- tibble(xi = x_i,
                        yi = y_i,
                        x = x,
                        y = kernel_i)  
  } else {
    df_kernel <- bind_rows(df_kernel, 
                           tibble(xi = x_i,
                                  yi = y_i,
                                  x = x,
                                  y = kernel_i)  )
  }
  
}

ggplot(df_kernel, aes(x = x, y = y)) + 
  geom_line(aes(group = xi)) + 
  geom_point(aes(x = xi, y = yi), 
             col = "red") + 
  theme_bw()
```

Then what? 

```{r}
tmp <- df_kernel %>% 
  select(xi, x, y) %>% 
  mutate(xi = str_c("y", xi)) %>% 
  pivot_wider(id = "x", names_from = "xi", values_from = "y") 

A1 <-5.0
A2 <- 2.0
tmp <- tmp %>% 
  mutate(fx = A1*y100 + A2*y400)

ggplot(tmp, aes(x = x, y = fx)) + 
  geom_line()
```


