---
title: "Human cluster characteristics"
author: "Antoine Beauchamp"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(RMINC))
suppressPackageStartupMessages(library(SNFtool))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(MRIcrotome))
suppressPackageStartupMessages(library(RColorBrewer))
```

```{r functions}
source("../../src/utils.R")
source("../../src/processing.R")
source("../../src/analysis.R")
```

```{r directories}
#Output directory
output_dir <- "outputs"

#Human pipeline
# version <- "v1"
version <- "v2"

registration_dir <- "../../data/human/registration/"
pipeline_dir <- "../../data/human/derivatives/"

registration_dir <- file.path(registration_dir, version)
pipeline_dir <- file.path(pipeline_dir, version)
```

```{r human-params}
resolution <- 0.8
# es_method <- "normative-growth"
es_method <- "propensity-matching"
# es_df <- 3
es_df <- NA
es_ncontrols <- 10
# es_ncontrols <- NA
cluster_map_method <- "mean"

metadata <- file.path(pipeline_dir, "metadata.csv")
params <- fetch_params_metadata(metadata = metadata,
                                resolution = resolution,
                                es_method = es_method,
                                es_df = es_df,
                                es_ncontrols = es_ncontrols,
                                cluster_map_method = cluster_map_method)
params
```

```{r params}
#Parameter set IDs
# params_id <- 256
params_id <- 700
# params_id <- 547

#Clustering directories
cluster_dir <- file.path(pipeline_dir, params_id, "clusters")

params <- fetch_params_metadata(metadata = metadata, 
                                id = params_id)
cluster_resolution <- params[["cluster_resolution"]]
cluster_resolution <- sprintf("%.1f", cluster_resolution)
cluster_dir <- file.path(cluster_dir, str_c("resolution_", cluster_resolution))

output_dir <- file.path(output_dir, version, str_c("H", params_id))
if (!(dir.exists(output_dir))) {dir.create(output_dir, recursive = TRUE)}
```

```{r import}
#Human cluster assignments
cluster_file <- file.path(cluster_dir, "clusters.csv")
df_clusters <- read_csv(cluster_file, show_col_types = FALSE)

#Human affinity matrix
affinity_file <- file.path(cluster_dir, "affinity.csv")
df_affinity <- read_csv(affinity_file, show_col_types = FALSE)
mat_affinity <- as.matrix(df_affinity)
rownames(mat_affinity) <- colnames(mat_affinity)

#Humnan demographics
demographics_file <- file.path(registration_dir, 
                               "subject_info",
                               "demographics.csv")
demographics <- read_csv(demographics_file, show_col_types = FALSE)
```

```{r}
nk <- 4
```

```{r fig.width = 6, fig.height = 5}
#Human affinity df long form
df_affinity_long <- df_affinity %>% 
  mutate(patient_1 = colnames(df_affinity)) %>% 
  pivot_longer(cols = -patient_1, names_to = "patient_2", values_to = "affinity")


#Get human cluster labels for given nk
df_labels_nk <- tibble(patient = colnames(df_affinity),
                       k = spectralClustering(affinity = mat_affinity,
                                              K = nk))

#Arrange patients by cluster assignment
patient_lvls <- df_labels_nk %>% 
  arrange(k) %>% 
  pull(patient)

#Clamp affinity values
threshold <- 0.01
df_affinity_long_clamped <- df_affinity_long %>% 
  mutate(affinity = ifelse(affinity >= threshold, threshold, affinity),
         patient_1 = factor(patient_1, levels = patient_lvls),
         patient_2 = factor(patient_2, levels = patient_lvls))

p_affinity_matrix <- ggplot(df_affinity_long_clamped, 
                            aes(x = patient_1,
                                y = fct_rev(patient_2),
                                fill = affinity)) + 
  geom_tile() + 
  scale_x_discrete(expand = expansion()) +
  scale_y_discrete(expand = expansion()) +
  scale_fill_gradientn(colours = c("white", brewer.pal(n = 9, name = "Reds")), na.value = "white") + 
  labs(fill = "Affinity",
       x = "Patient",
       y = "Patient",
       title = paste("Human affinity matrix for nk =", nk),
       caption = paste("Affinity values clamped at", threshold)) + 
  theme_bw() + 
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

outfile <- paste0("affinity_matrix_nk_", nk, ".pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile, 
    width = 10,
    height = 8)
print(p_affinity_matrix)
dev.off()

p_affinity_matrix
```

```{r}
df_clusters_nk <- df_clusters %>% 
  select(ID, k = str_c("nk", nk))

df_cluster_counts <- df_clusters_nk %>% 
  group_by(k) %>% 
  count()

ggplot(df_cluster_counts, 
       aes(x = factor(k), y = n)) +
  geom_col(fill = "grey70", col = "grey20") + 
  scale_y_continuous(breaks = seq(0, 1000, by = 40)) + 
  labs(x = "Cluster",
       y = "Count",
       title = "Number of patients in human clusters") +
  theme_bw()
```
```{r}
demographics <- demographics %>% 
  filter(file %in% df_clusters_nk[["ID"]])

df_clusters_nk_demo <- df_clusters_nk %>% 
  inner_join(demographics,
             by = c("ID" = "file"))
```

```{r}
df_clusters_nk_demo %>% 
  group_by(k, Dataset) %>% 
  count() %>% 
  ggplot(aes(x = factor(k), y = n, fill = Dataset)) + 
  geom_col(position = "dodge") +
  labs(x = "Cluster", 
       y = "Count",
       title = "Cluster breakdown by dataset") + 
  theme_bw()
```
```{r}
df_clusters_nk_demo %>% 
  group_by(k, Sex) %>% 
  count() %>% 
  ggplot(aes(x = factor(k), y = n, fill = Sex)) + 
  geom_col(position = "dodge") +
  labs(x = "Cluster", 
       y = "Count",
       title = "Cluster breakdown by sex") + 
  theme_bw()
```
```{r}
df_clusters_nk_demo %>% 
  mutate(Site_Scanner = str_c(Site, Scanner, sep = "_")) %>% 
  group_by(k, Site_Scanner) %>% 
  count() %>% 
  ggplot(aes(x = factor(k), y = n, fill = Site_Scanner)) + 
  geom_col(position = "dodge") +
  labs(x = "Cluster", 
       y = "Count",
       title = "Cluster breakdown by site and scanner") + 
  theme_bw()
```
```{r}
ggplot(df_clusters_nk_demo, 
       aes(x = factor(k), y = Age, col = Sex)) + 
  geom_jitter(width = 0.2,
              col = "grey70",
              alpha = 0.4) + 
  geom_boxplot(outlier.shape = NA,
               alpha = 0.5) + 
  labs(x = "Cluster", 
       y = "Age",
       title = "Cluster age distributions") + 
  theme_bw()
```

```{r}
dx_levels <- c("ASD", 
               "ADHD", "Sub-threshold ADHD", 
               "OCD", "Sub-threshold OCD", 
               "Anxiety",
               "Intellectual Disability only",
               "Fragile X",
               "Tourette Syndrome",
               "Other")

df_clusters_nk_demo %>% 
  group_by(k, DX) %>% 
  count() %>% 
  mutate(k = factor(k),
         DX = factor(DX, levels = dx_levels)) %>% 
  ggplot(aes(x = k, y = n, fill = DX)) +
  geom_col(position = "dodge") +
  labs(x = "Cluster", 
       y = "Count",
       title = "Cluster breakdown by diagnosis") + 
  theme_bw()
```
```{r}
df_dx_coarse <- tibble(
  DX = c("ASD", 
         "ADHD", "Sub-threshold ADHD", 
         "OCD", "Sub-threshold OCD", 
         "Anxiety",
         "Intellectual Disability only",
         "Fragile X",
         "Tourette Syndrome",
         "Other"),
  DX_coarse = c("ASD", 
                "ADHD", "ADHD", 
                "OCD", "OCD", 
                "Anxiety",
                "Intellectual Disability only",
                "Fragile X",
                "Tourette Syndrome",
                "Other")
)

dx_levels_coarse <- c("ASD", 
                      "ADHD",
                      "OCD",
                      "Anxiety",
                      "Intellectual Disability only",
                      "Fragile X",
                      "Tourette Syndrome",
                      "Other")

df_clusters_nk_demo %>% 
  left_join(df_dx_coarse, by = "DX") %>% 
  group_by(k, DX_coarse) %>%
  count() %>%
  mutate(k = factor(k),
         DX_coarse = factor(DX_coarse, levels = dx_levels_coarse)) %>% 
  ggplot(aes(x = k, y = n, fill = DX_coarse)) +
  geom_col(position = "dodge") +
  labs(x = "Cluster", 
       y = "Count",
       title = "Cluster breakdown by diagnosis (coarse)") + 
  theme_bw()
```

```{r}
#Human anatomy
anat_file <- "../../data/human/registration/v1/reference_files/model_0.8mm.mnc"
anat <- mincGetVolume(anat_file)
anat_vol <- mincArray(anat)

#Cropped human images along sagittal and transverse planes
slices_dim_1 <- 25:200
slices_dim_3 <- 25:220
anat_vol_cropped <- anat_vol[slices_dim_1,,slices_dim_3]

#Human mask
mask <- "../../data/human/registration/v1/reference_files/mask_0.8mm.mnc"

jacobians <- c("absolute", "relative")
```

```{r}
cluster_map_dir <- file.path(pipeline_dir, params_id, "cluster_maps", paste0("resolution_", resolution))


cluster_maps <- vector(mode = "list", length = length(jacobians))
names(cluster_maps) <- jacobians
for (j in 1:length(jacobians)) {
  input_dir <- file.path(cluster_map_dir, jacobians[j])
  cluster_maps[[j]] <- vector(mode = "list", length = nk)
  for (k in 1:nk) {
    cluster_map <- import_cluster_map(imgdir = input_dir,
                                      mask = mask,
                                      nk = nk, k = k,
                                      flatten = FALSE)
    cluster_maps[[j]][[k]] <- cluster_map[slices_dim_1,,slices_dim_3]
  }
}
```

```{r}
overlay_low <- 0.1
overlay_high <- 1

list_ss_grobs <- vector(mode = "list", length = nk)
for (k in 1:nk) {
  list_ss_grobs[[k]] <- sliceSeries(nrow = 8, ncol = 1, begin = 50, end = 200) %>% 
    anatomy(anat_vol_cropped, low = 3, high = 7) %>% 
    overlay(cluster_maps[["absolute"]][[k]], symmetric = TRUE, low = overlay_low, high = overlay_high) %>%
    addtitle("Abs.") %>% 
    sliceSeries() %>% anatomy() %>% 
    overlay(cluster_maps[["relative"]][[k]], symmetric = TRUE, low = overlay_low, high = overlay_high) %>%
    addtitle("Rel.") %>% 
    legend("Effect size") %>% 
    grobify()
}
```

```{r fig.width = 10, fig.height = 10}
ss_grob <- arrangeGrob(textGrob(label = "k = 1", x = 0.3),
                       textGrob(label = "k = 2", x = 0.3),
                       textGrob(label = "k = 3", x = 0.3),
                       textGrob(label = "k = 4", x = 0.3),
                       list_ss_grobs[[1]],
                       list_ss_grobs[[2]],
                       list_ss_grobs[[3]],
                       list_ss_grobs[[4]],
                       layout_matrix = rbind(c( 1,  2,  3,  4),
                                             c( 5,  6,  7,  8)),
                       widths = unit(c(0.25, 0.25, 0.25, 0.25), units = 'npc'),
                       heights = unit(c(0.1, 0.9), units = 'npc'))

grid.newpage()
grid.draw(ss_grob)
```

```{r}
pond_neuro <- "../../data/human/registration/v2/subject_info/pond-neuroanatomy20230111.csv"
df_pond_neuro <- read_csv(pond_neuro)
tmp <- df_pond_neuro %>% 
  select(scan, BRAIN_VOL) %>% 
  mutate(ID = str_c(scan, ".denoise.extracted_fwhm_2mm.mnc")) %>% 
  right_join(df_clusters_nk_demo, by = "ID")

tmp %>% 
  filter(!is.na(BRAIN_VOL)) %>% 
  ggplot(aes(x = factor(k), y = BRAIN_VOL)) + 
    geom_jitter(width = 0.2,
              col = "grey70",
              alpha = 0.4) + 
  geom_boxplot(outlier.shape = NA,
               alpha = 0.5) + 
  labs(x = "Cluster", 
       y = "Brain volume",
       title = "Cluster total volume distributions") + 
  theme_bw()
```


```{r}
df_clusters_nk_demo %>% 
  group_by(k, Dataset) %>% 
  count
```

