---
title: "Untitled"
author: "Antoine Beauchamp"
date: '2022-11-09'
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
source("cluster_similarity/analysis_tools_v2.R")
source("../functions/buildSimilarityMatrix.R")
```


```{r}
simfile <- "../data/similarity_matrix//anatomical_similarity.csv"
df_sim <- read_csv(simfile, show_col_types = FALSE)


df_pallidum_latentspace <- df_sim %>% 
  select(Human, Pallidum)
```


```{r}
mouse_input_space <- "../data/mouse/expression/input_space/MouseExpressionMatrix_voxel_coronal_log2_grouped_imputed_homologs_scaled.csv"
human_input_space <- "../data/human/expression/input_space/HumanExpressionMatrix_samples_pipeline_abagen_homologs_scaled.csv"

df_mouse_inputspace <- as_tibble(data.table::fread(mouse_input_space, header = TRUE))
df_human_inputspace <- as_tibble(data.table::fread(human_input_space, header = TRUE))
```

```{r}
mouse_labels <- "../data/mouse/atlas/DSURQE_CCFv3_labels_200um.mnc"
mouse_mask <- "../data/mouse/atlas/coronal_200um_coverage_bin0.8.mnc"
mouse_tree <- "../data/mouse/expression/MouseExpressionTree_DSURQE.RData"
human_dir <- "../data/human/expression/latent_space/"
human_tree <- "../data/human/expression/HumanExpressionTree.RData"
human_metadata <- "../data/human/expression/SampleInformation_pipeline_abagen.csv"
tree_labels <- "../data/TreeLabelsReordered.RData"
```

```{r}
#Trees
load(mouse_tree)
tree_mouse <- Clone(treeMouseExpr)
rm(treeMouseExpr)

load(human_tree)
tree_human <- Clone(treeHumanExpr)
rm(treeHumanExpr)

#Tree labels
load(tree_labels)

#Prune mouse tree to desired level
mouse_regions <- c(listLabelsMouseReordered$Region67, 
                   "fiber tracts", 
                   "ventricular systems")
tree_mouse_pruned <- Clone(tree_mouse)
pruneAnatTree(tree_mouse_pruned, 
              nodes = mouse_regions, 
              method = "BelowNode")

#Pruned human tree to desired level
human_regions <- c(listLabelsHumanReordered$Region88, 
                   "white matter", 
                   "sulci & spaces")
tree_human_pruned <- Clone(tree_human)
pruneAnatTree(tree_human_pruned, 
              nodes = human_regions, 
              method = "BelowNode")

#Mouse labels and mask
mouse_labels <- mincGetVolume(mouse_labels)
mouse_mask <- mincGetVolume(mouse_mask)

#Human microarray sample IDs
human_sample_ids <- data.table::fread(human_metadata, header = TRUE) %>% 
  as_tibble() %>% 
  pull(SampleID)
```




```{r}
mat_mouse <- df_mouse_inputspace %>% 
  label_mouse_data(tree = tree_mouse_pruned,
                   labels  = mouse_labels,
                   mask = mouse_mask) %>% 
  filter(!is.na(name)) %>% 
  aggregate_data(groupby = "name",
                 output = "matrix") %>% 
  t()

mat_human <- df_human_inputspace %>% 
  label_human_data(tree = tree_human_pruned,
                   samples = human_sample_ids) %>% 
  filter(!is.na(name)) %>% 
  aggregate_data(groupby = "name", 
                 output = "matrix") %>% 
  t()

mat_sim <- buildSimilarityMatrix(x1 = mat_human,
                                 x2 = mat_mouse,
                                 method = "correlation")

df_sim_inputspace <- mat_sim %>% 
  as_tibble(rownames = "Human")

df_pallidum_inputspace <- df_sim_inputspace %>% 
  select(Human, Pallidum)
```

```{r}
df_pallidum_latentspace %>% 
  arrange(desc(Pallidum))
```

```{r}
df_pallidum_latentspace %>% 
  arrange(desc(Pallidum)) %>% 
  mutate(Rank = 1:nrow(.)) %>% 
  filter(Human == "globus pallidus")
```


```{r}
df_pallidum_inputspace %>% 
  arrange(desc(Pallidum))
```

```{r}
df_pallidum_inputspace %>% 
  arrange(desc(Pallidum)) %>% 
  mutate(Rank = 1:nrow(.)) %>% 
  filter(Human == "globus pallidus")
```


```{r}
df_human_labelled <- df_human_inputspace %>% 
  label_human_data(tree = tree_human_pruned,
                   samples = human_sample_ids) %>% 
  filter(!is.na(name))
```

```{r}
ind_pallidum <- which(df_human_labelled$name == "globus pallidus")
pallidum_samples <- human_sample_ids[ind_pallidum]
```


```{r}
microarray_coordinates_defs <- "../data/human/expression/AHBA_microarray_coordinates_mni_defs.csv"

df_microarray_defs <- read_csv(microarray_coordinates_defs, show_col_types = FALSE)

df_pallidum_defs <- df_microarray_defs %>% 
  filter(sample_id %in% pallidum_samples)

pallidum_labels <- df_pallidum_defs %>% 
  pull(label)

microarray_labels <- "../data/human/expression/AHBA_microarray_labels_studyspace_1.0mm.mnc"
library(RMINC)
microarray_labels <- mincGetVolume(microarray_labels)

ind_pallidum_labels <- microarray_labels %in% pallidum_labels
labels_out <- numeric(length(microarray_labels))
labels_out[ind_pallidum_labels] <- 1
attributes(labels_out) <- attributes(microarray_labels)

mincWriteVolume(buffer = labels_out,
                output.filename = "pallidum_samples.mnc",
                like.filename = "../data/human/expression/AHBA_microarray_labels_studyspace_1.0mm.mnc")
```

```{r}
mat_pallidum_samples <- df_human_labelled %>%
  mutate(sample_id = human_sample_ids) %>% 
  filter(name == "globus pallidus") %>% 
  select(-name) %>% 
  column_to_rownames("sample_id") %>% 
  as.matrix() %>% 
  t()

pallidum_cor <- cor(mat_pallidum_samples)
tibble(x = pallidum_cor[upper.tri(pallidum_cor)]) %>% 
  ggplot(aes(x = x)) + 
  geom_histogram(col = "black",
                 fill = "grey70",
                 binwidth = 0.01) +
  theme_bw()
```

```{r}
df_mouse_labelled <- df_mouse_inputspace %>% 
  label_mouse_data(tree = tree_mouse_pruned,
                   labels  = mouse_labels,
                   mask = mouse_mask) %>% 
  filter(!is.na(name))  


mat_pallidum_mouse <- df_mouse_labelled %>%
  filter(name == "Pallidum") %>% 
  select(-name) %>% 
  mutate(voxel_id = str_c("V", 1:nrow(.))) %>% 
  column_to_rownames("voxel_id") %>% 
  as.matrix() %>% 
  t()

pallidum_cor_mouse <- cor(mat_pallidum_mouse)
tibble(x = pallidum_cor_mouse[upper.tri(pallidum_cor_mouse)]) %>% 
  ggplot(aes(x = x)) + 
  geom_histogram(col = "black",
                 fill = "grey70",
                 binwidth = 0.01) +
  theme_bw()
```

