---
title: "Radar plots"
author: "Antoine Beauchamp"
date: '2023-01-06'
output: html_document
---

```{r}
#Packages
suppressPackageStartupMessages(library(tidyverse))
```

```{r}
coord_radar <- function (theta = "x", start = 0, direction = 1) {
  
  theta <- match.arg(theta, c("x", "y"))
  r <- if (theta == "x") 
    "y"
  else "x"
  
  #dirty
  rename_data <- function(coord, data) {
    if (coord$theta == "y") {
      plyr::rename(data, c("y" = "theta", "x" = "r"), warn_missing = FALSE)
    } else {
      plyr::rename(data, c("y" = "r", "x" = "theta"), warn_missing = FALSE)
    }
  }
  
  theta_rescale <- function(coord, x, scale_details) {
    rotate <- function(x) (x + coord$start) %% (2 * pi) * coord$direction
    rotate(scales::rescale(x, c(0, 2 * pi), scale_details$theta.range))
  }
  
  r_rescale <- function(coord, x, scale_details) {
    scales::rescale(x, c(0, 0.4), scale_details$r.range)
  }
  
  ggproto("CoordRadar", CoordPolar, theta = theta, r = r, start = start, 
          direction = sign(direction),
          is_linear = function(coord) TRUE,
          render_bg = function(self, scale_details, theme) {
            scale_details <- rename_data(self, scale_details)
            
            theta <- if (length(scale_details$theta.major) > 0)
              theta_rescale(self, scale_details$theta.major, scale_details)
            thetamin <- if (length(scale_details$theta.minor) > 0)
              theta_rescale(self, scale_details$theta.minor, scale_details)
            # thetafine <- seq(0, 2 * pi, length.out = 100)
            thetafine <- theta
            
            rfine <- c(r_rescale(self, scale_details$r.major, scale_details))
            
            # This gets the proper theme element for theta and r grid lines:
            #   panel.grid.major.x or .y
            majortheta <- paste("panel.grid.major.", self$theta, sep = "")
            minortheta <- paste("panel.grid.minor.", self$theta, sep = "")
            majorr     <- paste("panel.grid.major.", self$r,     sep = "")
            
            ggplot2:::ggname("grill", grid::grobTree(
              ggplot2:::element_render(theme, "panel.background"),
              if (length(theta) > 0) ggplot2:::element_render(
                theme, majortheta, name = "angle",
                x = c(rbind(0, 0.45 * sin(theta))) + 0.5,
                y = c(rbind(0, 0.45 * cos(theta))) + 0.5,
                id.lengths = rep(2, length(theta)),
                default.units = "native"
              ),
              if (length(thetamin) > 0) ggplot2:::element_render(
                theme, minortheta, name = "angle",
                x = c(rbind(0, 0.45 * sin(thetamin))) + 0.5,
                y = c(rbind(0, 0.45 * cos(thetamin))) + 0.5,
                id.lengths = rep(2, length(thetamin)),
                default.units = "native"
              ),
              
              ggplot2:::element_render(
                theme, majorr, name = "radius",
                x = rep(rfine, each = length(thetafine)) * sin(thetafine) + 0.5,
                y = rep(rfine, each = length(thetafine)) * cos(thetafine) + 0.5,
                id.lengths = rep(length(thetafine), length(rfine)),
                default.units = "native"
              )
            ))
          })
}
```

```{r}
#Simulated data
categories <- c("A", "B", "C", "D", "E")
values1 <- sample(x = 1:5, size = length(categories), replace = TRUE)
values2 <- sample(x = 1:5, size = length(categories), replace = TRUE)
df <- tibble(theta = categories,
             r1 = values1,
             r2 = values2)

#Convert categories to factor
df <- df %>% 
  mutate(theta = factor(theta, levels = categories))
```

```{r}
#Hacky stuff to make lines connect
#Basically create an extra factor level that is empty
lvls <- categories
lvls <- c(" ", lvls)
df_dummy <- df %>% 
  mutate(theta = as.character(theta)) %>% 
  filter(theta == lvls[length(lvls)]) %>% 
  mutate(theta = " ")
df <- bind_rows(df, df_dummy)
df <- mutate(df, theta = factor(theta, levels = lvls))

df
```

```{r}
#Plot parameters
theta_start <- -(2*pi)/length(categories)
r_start <- 0
r_end <- 5
r_step <- 1
r_breaks <- seq(r_start, r_end, by = r_step)

#Data frame containing radial labels
df_labels <- tibble(theta = levels(df$theta)[2],
                    r1 = r_breaks)

#Base plot
polar_base <- ggplot(df, aes(x = theta, y = r1, group = 1)) + 
  geom_line() + 
  geom_text(data = df_labels,
            mapping = aes(label = r1), 
            nudge_y = 0.1,
            vjust = 0) + 
  coord_radar(start = theta_start) + 
  scale_x_discrete(expand = expansion()) +
  scale_y_continuous(breaks = seq(r_start, r_end, by = r_step), 
                     limits = c(r_start, r_end+1))

polar_base
```

```{r}
#Clean up the plot with theme elements
polar_base + 
  theme_bw() +
  theme(axis.title = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank())
```




```{r}
df_groups <- df %>% 
  pivot_longer(cols = -theta, names_to = "group", values_to = "r")

df_labels <- df_labels %>% 
  rename(r = r1)

ggplot(df_groups, aes(x = theta, y = r, col = group, fill = group, group = group)) + 
  geom_area(alpha = 0.4,
            position = "identity")  + 
  # geom_text(data = df_labels,
  #           mapping = aes(label = r, group = 1), 
  #           nudge_y = 0.1,
  #           vjust = 0) + 
  coord_radar(start = theta_start) + 
  scale_x_discrete(expand = expansion()) +
  scale_y_continuous(breaks = seq(r_start, r_end, by = r_step), 
                     limits = c(r_start, r_end+1)) + 
  theme_bw() +
  theme(axis.title = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank())
```

```{r}
values <- sample(x = 1:5, size = length(categories), replace = TRUE)
df <- tibble(theta = categories,
             r = values)
```


