---
title: ""
author: "Antoine Beauchamp"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(RMINC))
suppressPackageStartupMessages(library(MRIcrotome))
```

```{r functions}
SRCPATH <- Sys.getenv("SRCPATH")

source(file.path(SRCPATH, "utils.R"))
source(file.path(SRCPATH, "processing.R"))
source(file.path(SRCPATH, "analysis.R"))
```

```{r directories}
# Output directory
output_dir <- "outputs/control_cv/"

# Human pipeline
human_version <- "v3"
human_pipeline_dir <- "../../data/human/derivatives/"
human_pipeline_dir <- file.path(human_pipeline_dir, human_version)
```

```{r human-params}
dataset <- "POND-SickKids"
human_es_group <- "controls"

#Identify human parameter set ID
human_metadata <- file.path(human_pipeline_dir, "metadata.csv")
human_params <- fetch_params_metadata(metadata = human_metadata,
                                      dataset = dataset,
                                      es_group = human_es_group)
human_params
```

```{r directories-2}
# Human parameter set ID
human_params_id <- "916"

# Jacobians
jacobians <- c("absolute", "relative")

# Human resolution
human_resolution <- human_params %>% 
  filter(id == human_params_id) %>% 
  pull(resolution)

# Human registration directory
human_registration_dir <- "../../data/human/registration/"
human_registration_dir <- file.path(human_registration_dir, human_version)

# Human pipeline directory
human_pipeline_dir <- "../../data/human/derivatives/"
human_pipeline_dir <- file.path(human_pipeline_dir, human_version, human_params_id)

# Output directory
if (!(dir.exists(output_dir))) {dir.create(output_dir, recursive = TRUE)}
```

```{r images-params}
# Human mask
human_mask_file <- paste0("mask_", sprintf("%.1f", human_resolution), "mm.mnc")
human_mask_file <- file.path(human_registration_dir, "reference_files", human_mask_file)
human_mask <- mincGetVolume(human_mask_file)

# Human anatomy
human_anat_file <- paste0("model_", sprintf("%.1f", human_resolution), "mm.mnc")
human_anat_file <- file.path(human_registration_dir, "reference_files", human_anat_file)
human_anat <- mincGetVolume(human_anat_file)
human_anat[human_mask != 1] <- 0
human_anat_vol <- mincArray(human_anat)

# Cropped human images along sagittal and transverse planes
human_slices_dim_1 <- 25:230
human_slices_dim_3 <- 25:220
human_anat_vol_cropped <- human_anat_vol[human_slices_dim_1,,human_slices_dim_3]

# Image thresholding options
threshold <- "top_n"
threshold_value <- 0.2
threshold_symmetric <- TRUE
```

```{r}
cv_dir <- file.path(human_pipeline_dir, "cross_validation")
cv_dirs <- list.files(cv_dir)
# cv_dirs <- paste0("sample_", 1:10)
list_centroid_dirs <- vector(mode = "list", length = length(cv_dirs))
names(list_centroid_dirs) <- cv_dirs
for (i in 1:length(list_centroid_dirs)) {
  list_centroid_dirs[[i]] <- file.path(cv_dir, cv_dirs[i], "centroids", str_c("resolution_", sprintf("%.1f", human_resolution)), jacobians)
  names(list_centroid_dirs[[i]]) <- jacobians
}
```


```{r human-centroids}
# Iterate over cluster solutions
nk_max <- 2
for (i in 1:length(list_centroid_dirs)) {
  
  print(paste0("Cross-validation sample ", names(list_centroid_dirs)[i]))
  
  for (nk in 2:nk_max) {
    for (k in 1:nk) {
      
      print(paste0(nk, "-", k))
      
      # Iterate over jacobians
      list_human_centroids <- vector(mode = "list", length = length(jacobians))
      list_human_overlay <- vector(mode = "list", length = length(jacobians))
      names(list_human_centroids) <- jacobians
      names(list_human_overlay) <- jacobians
      for (j in jacobians) {
        
        # Import centroid image for specific cluster using threshold
        img <- import_cluster_map(imgdir = list_centroid_dirs[[i]][[j]],
                                  mask = human_mask_file,
                                  nk = nk, k = k,
                                  threshold = threshold,
                                  threshold_value = threshold_value,
                                  threshold_symmetric = threshold_symmetric)
        
        # Compute slice series overlay thresholds
        list_human_overlay[[j]] <- numeric(2)
        list_human_overlay[[j]][1] <- min(abs(img[img != 0]))
        list_human_overlay[[j]][2] <- 0.8*max(abs(img[img != 0]))
        list_human_overlay[[j]] <- round(list_human_overlay[[j]], 2)
        
        # Crop image
        img <- mincArray(img)
        # img <- img[human_slices_dim_1,,human_slices_dim_3]
        
        list_human_centroids[[j]] <- img
      }
      
      # Slice series for absolute and relative centroid
      ss <- sliceSeries(nrow = 6, ncol = 2, begin = 50, end = 250) %>% 
        anatomy(human_anat_vol_cropped, low = 40, high = 110) %>% 
        overlay(list_human_centroids[["absolute"]], 
                low = list_human_overlay[["absolute"]][1],
                high = list_human_overlay[["absolute"]][2],
                symmetric = TRUE) %>% 
        legend("Effect size") %>% addtitle("Absolute") %>% 
        sliceSeries() %>% anatomy() %>% 
        overlay(list_human_centroids[["relative"]], 
                low = list_human_overlay[["relative"]][1],
                high = list_human_overlay[["relative"]][2],
                symmetric = TRUE) %>% 
        legend("Effect size") %>% addtitle("Relative")
      
      # Export plot
      outfile <- paste0("cv_", names(list_centroid_dirs)[i], "_centroid_", nk, "-", k, ".pdf")
      outfile <- file.path(output_dir, outfile)
      pdf(file = outfile,
          width = unit(10, "in"),
          height = unit(10, "in"))
      draw(ss)
      dev.off()
      
    }
  }
}
```

```{r}
slices_dim_1 <- 27:220
slices_dim_2 <- 10:280
slices_dim_3 <- 10:220
human_anat_vol_cropped <- human_anat_vol[slices_dim_1, slices_dim_2, slices_dim_3]

nk <- 2
list_ss <- vector(mode = "list", length = length(list_centroid_dirs))
names(list_ss) <- paste0("sample_", 1:length(list_ss))
for (i in 1:length(list_ss)) {
  
  message(paste0("Cross-validation sample ", i))
  
  imgdir <- list_centroid_dirs[[names(list_ss)[i]]][["relative"]]
  
  list_ss[[i]] <- vector(mode = "list", length = nk)
  for (k in 1:nk) {
    
    print(k)
    
    # Import centroid image and threshold
    img <- import_cluster_map(imgdir = imgdir,
                              mask = human_mask_file,
                              nk = nk, k = k,
                              threshold = threshold,
                              threshold_value = threshold_value,
                              threshold_symmetric = threshold_symmetric)
    
    # Compute overlay thresholds
    overlay_threshold <- numeric(2)
    overlay_threshold[1] <- min(abs(img[img != 0]))
    overlay_threshold[2] <- 0.8*max(abs(img[img != 0]))
    overlay_threshold <- round(overlay_threshold, 2)
    
    # Convert mincSingleDim to mincArray and crop
    img <- mincArray(img)
    img <- img[slices_dim_1, slices_dim_2, slices_dim_3]
    
    list_ss[[i]][[k]] <- sliceSeries(nrow = 1, ncol = 1, 
                                     dimension = 1, 
                                     slices = 82) %>% 
      anatomy(human_anat_vol_cropped, low = 40, high = 110) %>% 
      overlay(img, 
              low = overlay_threshold[1], 
              high = overlay_threshold[2], 
              symmetric = TRUE) %>% 
      grobify()
    
  }
}
```

```{r}
library(grid)
library(gridExtra)

human_width_px <- dim(human_anat_vol_cropped)[2]
human_height_px <- dim(human_anat_vol_cropped)[3]

padding_width_pt <- 6

ss_width_pt <- 100
ss_height_pt <- ss_width_pt*(human_height_px/human_width_px)

ss_widths_pt <- c(ss_width_pt, padding_width_pt)
ss_heights_pt <- c(rep(ss_height_pt, 2), padding_width_pt)


list_ss_samples <- vector(mode = "list", length = length(list_ss))
names(list_ss_samples) <- names(list_ss)
for (i in 1:length(list_ss_samples)) {
  list_ss_samples[[i]] <- arrangeGrob(list_ss[[i]][[1]],
                                      list_ss[[i]][[2]],
                                      zeroGrob(),
                                      zeroGrob(),
                                      layout_matrix = rbind(c(1, 3),
                                                            c(2, 3),
                                                            c(4, 4)),
                                      widths = unit(ss_widths_pt, unit = "bigpts"),
                                      heights = unit(ss_heights_pt, unit = "bigpts"))
}
```


```{r}
ngrobs <- length(list_ss_samples)
ncols <- 4
nrows <- 4

layout_matrix <- matrix(1:ngrobs, nrow = nrows, ncol = ncols, byrow = TRUE)

widths_pt <- rep(sum(ss_widths_pt), ncols)
heights_pt <- rep(sum(ss_heights_pt), nrows)

ss_grid <- arrangeGrob(grobs = list_ss_samples,
                       layout_matrix = layout_matrix,
                       widths = unit(widths_pt, unit = "bigpts"),
                       heights = unit(heights_pt, unit = "bigpts"))

out_width_pt <- sum(widths_pt)
out_height_pt <- sum(heights_pt)

out_width_in <- out_width_pt/72
out_height_in <- out_height_pt/72

# Export plot
outfile <- "control_cv_centroids.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(out_width_in, "in"),
    height = unit(out_height_in, "in"))
grid.draw(ss_grid)
dev.off()
```

```{r}
slices_dim_1 <- 27:220
slices_dim_2 <- 10:280
slices_dim_3 <- 10:220
human_anat_vol_cropped <- human_anat_vol[slices_dim_1, slices_dim_2, slices_dim_3]

centroid_dir <- "../../data/human/derivatives/v3/700/centroids/resolution_0.8/relative/"
nk <- 2
list_ss <- vector(mode = "list", length = nk)
for (k in 1:nk) {
  
  print(k)
  
  # Import centroid image and threshold
  img <- import_cluster_map(imgdir = centroid_dir,
                            mask = human_mask_file,
                            nk = nk, k = k,
                            threshold = threshold,
                            threshold_value = threshold_value,
                            threshold_symmetric = threshold_symmetric)
  
  # Compute overlay thresholds
  overlay_threshold <- numeric(2)
  overlay_threshold[1] <- min(abs(img[img != 0]))
  overlay_threshold[2] <- 0.8*max(abs(img[img != 0]))
  overlay_threshold <- round(overlay_threshold, 2)
  
  # Convert mincSingleDim to mincArray and crop
  img <- mincArray(img)
  img <- img[slices_dim_1, slices_dim_2, slices_dim_3]
  
  list_ss[[k]] <- sliceSeries(nrow = 1, ncol = 1, 
                              dimension = 1, 
                              slices = 82) %>% 
    anatomy(human_anat_vol_cropped, low = 40, high = 110) %>% 
    overlay(img, 
            low = overlay_threshold[1], 
            high = overlay_threshold[2], 
            symmetric = TRUE) %>% 
    grobify()
  
}
```


```{r}
human_width_px <- dim(human_anat_vol_cropped)[2]
human_height_px <- dim(human_anat_vol_cropped)[3]

padding_width_pt <- 6

ss_width_pt <- 100
ss_height_pt <- ss_width_pt*(human_height_px/human_width_px)

ss_heights_pt <- rep(ss_height_pt, 2)

ss_grid <- arrangeGrob(list_ss[[1]],
                       list_ss[[2]],
                       layout_matrix = rbind(c(1),
                                             c(2)),
                       widths = unit(ss_width_pt, unit = "bigpts"),
                       heights = unit(ss_heights_pt, unit = "bigpts"))


out_width_pt <- ss_width_pt
out_height_pt <- sum(ss_heights_pt)

out_width_in <- out_width_pt/72
out_height_in <- out_height_pt/72

# Export plot
outfile <- "POND_nk_2_centroids.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(out_width_in, "in"),
    height = unit(out_height_in, "in"))
grid.draw(ss_grid)
dev.off()
```

# Similarity 


```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(RMINC))
suppressPackageStartupMessages(library(MRIcrotome))
```

```{r functions}
SRCPATH <- Sys.getenv("SRCPATH")

source(file.path(SRCPATH, "utils.R"))
source(file.path(SRCPATH, "processing.R"))
source(file.path(SRCPATH, "analysis.R"))
```

```{r}
# Output directory
output_dir <- "outputs/control_cv/"

pipeline_dir <- "../../data/cross_species/v3/control_cv"

similarity_dir <- file.path(pipeline_dir, "similarity")

permutations_dir <- file.path(pipeline_dir, "permutations", "similarity")

```

```{r}
input_file <- file.path(similarity_dir, "similarity.csv")

# Import similarity
df_similarity <- read_csv(input_file, show_col_types = FALSE)

# Extract sample and cluster information
df_similarity <- df_similarity %>% 
  mutate(img1_k = img1 %>% 
           basename() %>% 
           str_extract("_k_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img1_jacobians = img1 %>% 
           str_extract("absolute|relative"),
         img2_k = img2 %>% 
           basename() %>% 
           str_extract("_k_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img2_jacobians = img2 %>% 
           str_extract("absolute|relative"),
         img2_sample = img2 %>% 
           str_extract("sample_[0-9]+") %>% 
           str_remove("sample_") %>% 
           as.numeric())  

# Aggregate Jacobians
df_similarity <- df_similarity %>% 
  group_by(img2_sample, img1_k, img2_k) %>% 
  summarise(similarity = mean(similarity),
            .groups = "drop")

# Define the mapping to relabel the clusters based on maximal similarity
df_relabelling <-
  df_similarity %>% 
  group_by(img2_sample, img1_k) %>% 
  filter(similarity == max(similarity)) %>% 
  ungroup() %>% 
  select(-similarity) %>% 
  rename(img2_k_new = img1_k)

# Relabel the clusters
df_similarity <- df_similarity %>% 
  left_join(df_relabelling, by = c("img2_sample", "img2_k")) %>% 
  select(-img2_k) %>% 
  rename(img2_k = img2_k_new)

```

```{r}
permutation_files <- list.files(permutations_dir)

np <- length(permutation_files)
list_permutations <- vector(mode = "list", length = np)
for (i in 1:length(list_permutations)) {
  
  permutation_file <- permutation_files[i]
  
  # Permutation number
  p <- permutation_file %>% 
    str_extract("[0-9]+") %>% 
    as.numeric()
  
  permutation_file <- file.path(permutations_dir, permutation_file)
  
  df_permutation_i <- read_csv(permutation_file, show_col_types = FALSE) %>% 
    mutate(img1_k = img1 %>% 
             basename() %>% 
             str_extract("_k_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img1_jacobians = img1 %>% 
             str_extract("absolute|relative"),
           img2_k = img2 %>% 
             basename() %>% 
             str_extract("_k_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img2_jacobians = img2 %>% 
             str_extract("absolute|relative"),
           img2_sample = img2 %>% 
             str_extract("sample_[0-9]+") %>% 
             str_remove("sample_") %>% 
             as.numeric())
  
  # Aggregate Jacobians
  df_permutation_i <- df_permutation_i %>% 
    group_by(img2_sample, img1_k, img2_k) %>% 
    summarise(similarity = mean(similarity),
              .groups = "drop")
  
  # Relabel the clusters
  df_permutation_i <- df_permutation_i %>% 
    left_join(df_relabelling, by = c("img2_sample", "img2_k")) %>% 
    select(-img2_k) %>% 
    rename(img2_k = img2_k_new)
  
  df_permutation_i <- df_permutation_i %>% 
    mutate(permutation = p)
  
  list_permutations[[i]] <- df_permutation_i
  
}

df_permutations <- bind_rows(list_permutations)
```

```{r}
sample_ids <- df_similarity %>% 
  pull(img2_sample) %>% 
  unique() %>% 
  sort()

list_sample_pvals <- vector(mode = "list", length = length(sample_ids))
for (s in 1:length(sample_ids)) {
  
  df_similarity_s <- df_similarity %>% 
    filter(img2_sample == sample_ids[s])
  
  df_permutations_s <- df_permutations %>% 
    filter(img2_sample == sample_ids[s])
  
  df_similarity_s[["pval"]] <- 0
  
  for (i in 1:nrow(df_similarity_s)) {
    df_similarity_s[[i, "pval"]] <- sum(df_permutations_s[["similarity"]] >= df_similarity_s[[i, "similarity"]])/nrow(df_permutations_s)
  }
  
  list_sample_pvals[[s]] <- df_similarity_s 
  
}

df_similarity_pvals <- bind_rows(list_sample_pvals)
```

```{r}
df_plot <- df_similarity_pvals %>% 
  mutate(img1_label = paste0("POND k = ", img1_k),
         img2_label = paste0("CV sample k = ", img2_k))

p <- ggplot(df_plot, aes(x = pval)) + 
  geom_histogram() +
  facet_grid(img1_label ~ img2_label) +
  labs(x = "p-value",
       y = "Number of samples") + 
  theme_bw()

outfile <- "control_cv_pval_dist.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(6, "in"),
    height = unit(6, "in"))
print(p)
dev.off()
```

```{r}
df_plot <- df_similarity_pvals %>% 
  filter(img1_k == img2_k) %>% 
  rename(k = img1_k) %>% 
  mutate(label = paste0("k = ", k)) %>% 
  select(-img2_k)

p <- ggplot(df_plot, aes(x = pval)) + 
  geom_histogram(fill = "grey70",
                 col = "grey20") +
  facet_wrap(~label, nrow = 2) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) + 
  scale_y_continuous(breaks = seq(0, 10, by = 1)) + 
                     # , sec.axis = sec_axis(~./50)) + 
  labs(x = "p-value",
       y = "Number of samples") +
  theme_bw() + 
  theme(panel.grid.minor.y = element_blank(),
        axis.title = element_text(size = 7),
        axis.text = element_text(size = 7),
        strip.text = element_text(size = 7))

outfile <- "control_cv_pval_dist_diagonal.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(263/72, "in"),
    height = unit(320/72, "in"))
print(p)
dev.off()
```

```{r}
df_diagonal <- df_similarity_pvals %>% 
  filter(img1_k == img2_k) %>% 
  mutate(k = img1_k) %>% 
  select(-img1_k, -img2_k) 

alpha_seq <- seq(0, 1, by = 0.01)
list_diagonal_alpha <- vector(mode = "list", length = length(alpha_seq))
for (i in 1:length(list_diagonal_alpha)) {
  list_diagonal_alpha[[i]] <- df_diagonal %>% 
    mutate(sig = pval <= alpha_seq[i]) %>% 
    group_by(k) %>% 
    summarise(prop = sum(sig)/length(sample_ids)) %>% 
    ungroup() %>% 
    mutate(alpha = alpha_seq[i])
}

df_diagonal_alpha <- bind_rows(list_diagonal_alpha)

p <- ggplot(df_diagonal_alpha, aes(x = alpha, y = prop, col = factor(k))) + 
  geom_line() + 
  geom_point(size = 1) + 
  coord_equal() + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) + 
  scale_y_continuous(breaks = seq(0, 1, by = 0.1)) + 
  labs(x = "p-value",
       y = "Proportion of samples",
       col = "k") +
  theme_bw()

outfile <- "control_cv_pval_prop.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(6, "in"),
    height = unit(6, "in"))
print(p)
dev.off()
```

```{r}
p <- ggplot(df_diagonal_alpha, aes(x = alpha, y = prop, col = factor(k))) + 
  geom_line() + 
  geom_point() + 
  coord_cartesian(xlim = c(0, 0.15),
                  ylim = c(0, 0.40)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.05)) + 
  scale_y_continuous(breaks = seq(0, 1, by = 0.05)) + 
  labs(x = "p-value",
       y = "Proportion of samples",
       col = "k") +
  theme_bw()

outfile <- "control_cv_pval_prop_zoom.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(6, "in"),
    height = unit(6, "in"))
print(p)
dev.off()
```

```{r}
df_plot <- df_diagonal %>% 
  mutate(sig = pval < 0.05,
         label = paste("k =", k))

p <- ggplot(df_plot, aes(x = img2_sample, y = similarity, col = sig)) + 
  geom_segment(aes(xend = img2_sample, yend = 0), alpha = 0.5) + 
  geom_point(size = 0.8) +
  facet_grid(.~label) +
  coord_flip(ylim = c(0.5, 1.0)) + 
  scale_x_reverse(breaks = c(1, seq(5, 100, 5))) + 
  scale_color_manual(values = c("grey40", "red"), labels = c("p >= 0.05", "p < 0.05")) + 
  labs(x = "Cross-validation sample",
       y = "Correlation",
       col = NULL) + 
  theme_bw() +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.title = element_text(size = 7),
        axis.text = element_text(size = 7),
        strip.text = element_text(size = 7),
        legend.title = element_text(size = 7),
        legend.text = element_text(size = 7),
        legend.position = "bottom",
        legend.direction = "horizontal")

outfile <- "control_cv_diag_similarity.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(263/72, "in"),
    height = unit(346/72, "in"))
print(p)
dev.off()
```
```{r}
df_permutations_1 <- df_permutations %>% 
  filter(img2_sample == 1)

ggplot(df_permutations_1, aes(x = similarity)) + 
  geom_histogram(fill = "grey80", col = "grey20") + 
  theme_bw()
```

```{r}
p <- df_permutations %>% 
  filter(img2_sample %in% 1:10) %>% 
  ggplot(aes(x = similarity, fill = factor(img2_sample), col = factor(img2_sample))) +
  geom_density(alpha = 0.1) + 
  coord_cartesian(xlim = c(0.2, 1.0)) + 
  scale_x_continuous(breaks = seq(0, 1, 0.1)) + 
  labs(x = "Similarity",
       y = "Density",
       fill = "Sample",
       col = "Sample") + 
  theme_bw()

outfile <- "control_cv_perm_dist.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(6, "in"),
    height = unit(4, "in"))
print(p)
dev.off()
```
```{r}

df_permutations_POND_MICe <- import_similarity_permutations(param_id = "375",
                                                            pipeline_dir = "../../data/cross_species/v3/",
                                                            combine_jacobians = TRUE)
df_permutations_POND_MICe <- df_permutations_POND_MICe %>% 
  filter(img1_nk == 2, img2_nk == 2)

df_permutations_HBN_MICe <- import_similarity_permutations(param_id = "861",
                                                           pipeline_dir = "../../data/cross_species/v3/",
                                                           combine_jacobians = TRUE)
df_permutations_HBN_MICe <- df_permutations_HBN_MICe %>% 
  filter(img1_nk == 2, img2_nk == 2)

df_permutations_POND_HBN <- import_similarity_permutations(param_id = "779",
                                                           pipeline_dir = "../../data/cross_species/v3/",
                                                           combine_jacobians = TRUE)
df_permutations_POND_HBN <- df_permutations_POND_HBN %>% 
  filter(img1_nk == 2, img2_nk == 2)
```


```{r}
df_permutations_NDDs <- bind_rows(df_permutations_POND_MICe %>% 
                                    mutate(data = "POND-MICe"),
                                  df_permutations_HBN_MICe %>% 
                                    mutate(data = "HBN-MICe"),
                                  df_permutations_POND_HBN %>% 
                                    mutate(data = "POND-HBN"))

p <- ggplot(df_permutations_NDDs, aes(x = similarity, fill = data, col = data)) + 
  geom_density(alpha = 0.2) + 
  coord_cartesian(xlim = c(0.2, 1.0)) + 
  scale_x_continuous(breaks = seq(0, 1, 0.1)) + 
  labs(x = "Similarity",
       y = "Density",
       fill = "Dataset",
       col = "Dataset") + 
  theme_bw()

outfile <- "NDDs_perm_dist.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(6, "in"),
    height = unit(4, "in"))
print(p)
dev.off()
```
```{r}
human_pipeline_dir <- "../../data/human/derivatives/v3/916/"

cv_dir <- file.path(human_pipeline_dir, "cross_validation")
cv_dirs <- list.files(cv_dir)
# cv_dirs <- paste0("sample_", 1:10)
list_centroid_dirs <- vector(mode = "list", length = length(cv_dirs))
names(list_centroid_dirs) <- cv_dirs
for (i in 1:length(list_centroid_dirs)) {
  list_centroid_dirs[[i]] <- file.path(cv_dir, cv_dirs[i], "centroids", "resolution_0.8", "relative")
}
```

```{r}
library(RMINC)

human_registration_dir <- "../../data/human/registration/v3/"
human_resolution <- 0.8
human_mask_file <- paste0("mask_", sprintf("%.1f", human_resolution), "mm.mnc")
human_mask_file <- file.path(human_registration_dir, "reference_files", human_mask_file)

df_centroid_paths <- df_relabelling %>% 
  rename(img1_k = img2_k_new) %>% 
  mutate(path = file.path(cv_dir, paste0("sample_", img2_sample), 
                          "centroids", "resolution_0.8", "relative",
                          paste0("centroid_nk_2_k_", img2_k, ".mnc"))) 

list_centroids_mean <- vector(mode = "list", length = 2)
for (k1 in 1:2) {
  df_centroid_paths_k1 <- filter(df_centroid_paths, img1_k == k1)
  
  img <- mincMean(filenames = df_centroid_paths_k1$path, 
                  mask = human_mask_file)
  
  img <- mincArray(img)
  
  img <- threshold_image(img)
  
  list_centroids_mean[[k1]] <- img
}
```


```{r}
slices_dim_1 <- 27:220
slices_dim_2 <- 10:280
slices_dim_3 <- 10:220
human_anat_vol_cropped <- human_anat_vol[slices_dim_1, slices_dim_2, slices_dim_3]

nk <- 2
list_ss_centroid_means <- vector(mode = "list", length = nk)
for (k in 1:nk) {
  
  img <- list_centroids_mean[[k]]
  
  # Compute overlay thresholds
  overlay_threshold <- numeric(2)
  overlay_threshold[1] <- min(abs(img[img != 0]))
  overlay_threshold[2] <- 0.8*max(abs(img[img != 0]))
  overlay_threshold <- round(overlay_threshold, 2)
  
  # Convert mincSingleDim to mincArray and crop
  img <- mincArray(img)
  img <- img[slices_dim_1, slices_dim_2, slices_dim_3]
  
  list_ss_centroid_means[[k]] <- sliceSeries(nrow = 1, ncol = 1, 
                                             dimension = 1, 
                                             slices = 82) %>% 
    anatomy(human_anat_vol_cropped, low = 40, high = 110) %>% 
    overlay(img, 
            low = overlay_threshold[1], 
            high = overlay_threshold[2], 
            symmetric = TRUE) %>% 
    grobify()
  
}
```

```{r}
library(grid)
library(gridExtra)

human_width_px <- dim(human_anat_vol_cropped)[2]
human_height_px <- dim(human_anat_vol_cropped)[3]

padding_width_pt <- 6

ss_width_pt <- 100
ss_height_pt <- ss_width_pt*(human_height_px/human_width_px)

ss_heights_pt <- rep(ss_height_pt, 2)

ss_grid <- arrangeGrob(list_ss_centroid_means[[1]],
                       list_ss_centroid_means[[2]],
                       layout_matrix = rbind(c(1),
                                             c(2)),
                       widths = unit(ss_width_pt, unit = "bigpts"),
                       heights = unit(ss_heights_pt, unit = "bigpts"))


out_width_pt <- ss_width_pt
out_height_pt <- sum(ss_heights_pt)

out_width_in <- out_width_pt/72
out_height_in <- out_height_pt/72

# Export plot
outfile <- "control_cv_average_centroids.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(out_width_in, "in"),
    height = unit(out_height_in, "in"))
grid.draw(ss_grid)
dev.off()
```

