---
title: "Untitled"
author: "Antoine Beauchamp"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggalluvial))
suppressPackageStartupMessages(library(RMINC))
suppressPackageStartupMessages(library(MRIcrotome))
```

```{r functions}
source("../src/utils.R")
source("../src/processing.R")
source("../src/analysis.R")
```

```{r pipeline-params}
# Output directory
output_dir <- "figure_supp_mouse/"
if (!(dir.exists(output_dir))) {dir.create(output_dir, recursive = TRUE)}

# Similarity pipeline
version <- "v2"
pipeline_dir <- "../data/mouse/derivatives/"
pipeline_dir <- file.path(pipeline_dir, version)

# Parameters
resolution <- 0.2
cluster_map_method <- "mean"

# Fetch parameter set
metadata <- file.path(pipeline_dir, "metadata.csv")
params <- fetch_params_metadata(metadata = metadata,
                                resolution = resolution,
                                cluster_map_method = cluster_map_method)
params
```

```{r}
params_id <- 107

pipeline_dir <- file.path(pipeline_dir, params_id)

cluster_dir <- file.path(pipeline_dir, "clusters")

cluster_map_dir <- file.path(pipeline_dir, "cluster_maps")

nk_max <- 10

pt_per_in <- 72
```

```{r}
clusters <- "clusters.csv"
clusters <- file.path(cluster_dir, clusters)
clusters <- read_csv(clusters, show_col_types = FALSE)
colnames(clusters) <- c("ID", paste0("nk", 2:nk_max))

clusters_long <- clusters %>% 
  pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         nk = factor(nk),
         k = factor(k))

#Mouse cluster Sankey plot
p_mouse_alluvial <- ggplot(clusters_long,
                           aes(x = nk,
                               stratum = k,
                               alluvium = ID,
                               fill = k, 
                               label = k)) + 
  geom_flow(stat = "alluvium", aes.flow = "forward") + 
  geom_stratum(alpha = 0.5) + 
  labs(x = "Number of clusters",
       y = "Number of models") + 
  theme_bw() + 
  theme(panel.grid.major.x = element_blank())

width_pts <- 1003
height_pts <- 741

width_in <- width_pts/pt_per_in
height_in <- height_pts/pt_per_in

width_in <- unit(width_in, "in")
height_in <- unit(height_in, "in")

#Export plot
outfile <- "mouse_sankey.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile, 
    width = width_in,
    height = height_in)
print(p_mouse_alluvial)
dev.off()
```

```{r}
# Anatomy
anat_file <- "../data/mouse/atlas/DSURQE_CCFv3_average_50um.mnc"
anat <- mincGetVolume(anat_file)
anat_vol <- mincArray(anat)

# Mask
mask_file <- "../data/mouse/atlas/coronal_50um_coverage_bin0.8.mnc"
mask <- mincGetVolume(mask_file)

cs_pipeline_dir <- "../data/cross_species/"
cs_pipeline_dir <- file.path(cs_pipeline_dir, version)

human_params_id <- 700

cs_metadata <- file.path(cs_pipeline_dir, "metadata.csv")
cs_params <- fetch_params_metadata(metadata = cs_metadata,
                                   mouse_id = params_id,
                                   human_id = human_params_id)

cs_params_id <- 405

# Threshold method
threshold <- cs_params %>% 
  filter(id == cs_params_id) %>% 
  pull(threshold)

# Threshold value
threshold_value <- cs_params %>% 
  filter(id == cs_params_id) %>% 
  pull(threshold_value)

# Threshold symmetric option
threshold_symmetric <- cs_params %>% 
  filter(id == cs_params_id) %>% 
  pull(threshold_symmetric)

jacobians <- "relative"

cluster_map_dir <- file.path(cluster_map_dir, paste0("resolution_", resolution))
cluster_map_dir <- file.path(cluster_map_dir, jacobians)

cluster_map_dir_50um <- file.path(pipeline_dir, "cluster_maps")
cluster_map_dir_50um <- file.path(cluster_map_dir_50um, "resolution_0.05")
cluster_map_dir_50um <- file.path(cluster_map_dir_50um, jacobians)
```

```{r}
# Mouse images need to be resampled to 50um
run <- FALSE
if (run) {
  
  indir <- cluster_map_dir
  outdir <- cluster_map_dir_50um
  
  for (nk in 2:nk_max) {
    for (k in 1:nk) {
      
      infile <- paste0("cluster_map_nk_", nk, "_k_", k, ".mnc")
      outfile <- infile
      
      infile <- file.path(indir, infile)
      outfile <- file.path(outdir, outfile)
      
      cmd_mincresample <- paste("mincresample", "-clobber",
                                "-like", anat_file,
                                infile, outfile)
      system(command = cmd_mincresample)
      
    }
  }
  
}
```

```{r}

slc <- 92

for (nk in 2:nk_max) {
  for (k in 1:nk) {
    
    img <- import_cluster_map(imgdir = cluster_map_dir_50um,
                              mask = mask_file,
                              nk = nk, k = k,
                              threshold = threshold,
                              threshold_value = threshold_value,
                              threshold_symmetric = threshold_symmetric)
    
    overlay_threshold <- numeric(2)
    overlay_threshold[1] <- min(abs(img[img != 0]))
    overlay_threshold[2] <- 0.8*max(abs(img[img != 0]))
    overlay_threshold <- round(overlay_threshold, 2)
    
    img <- mincArray(img)
    
    ss <- sliceSeries(nrow = 1, ncol = 1, dimension = 1, slices = slc) %>% 
      anatomy(anat_vol, low = 700, high = 1400) %>% 
      overlay(img, 
              low = overlay_threshold[1], 
              high = overlay_threshold[2], 
              symmetric = TRUE) 
    
    width_px <- dim(anat_vol)[2]
    height_px <- dim(anat_vol)[3]
    
    width_in <- 5
    height_in <- 5*(height_px/width_px)
    
    width_in <- unit(width_in, "in")
    height_in <- unit(height_in, "in")
    
    outfile <- paste("mouse_cluster_centroid_nk", nk, "k", k, sep = "_")
    outfile <- paste0(outfile, ".pdf")
    outfile <- file.path(output_dir, outfile)
    pdf(file = outfile,
        width = width_in,
        height = height_in)
    draw(ss)
    dev.off()
    
  }
}
```
