---
title: "Untitled"
author: "Antoine Beauchamp"
output: html_document
---

# Initialization  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      include = FALSE,
                      cache.lazy = FALSE)
```

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(data.tree))
suppressPackageStartupMessages(library(RMINC))
suppressPackageStartupMessages(library(MRIcrotome))
suppressPackageStartupMessages(library(pheatmap))
# suppressPackageStartupMessages(library(viridis))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(ggplotify))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(gridExtra))
```

```{r functions}
source("../functions/buildSimilarityMatrix.R")
source("../functions/tree_tools.R")
source("analysis_tools.R")
```

```{r parameters}
#Path to data directory
datadir <- "../data/"

#Gene space
gene_space <- "average_latent_space"
# gene_space <- "input_space"
# gene_space<- "latent_space"

#Latent space ID
#Only used if gene_space == "latent_space"
latent_space_id <- 1

#Jacobians
# jacobians <- "absolute"
jacobians <- "relative"

#Thresholding method
# threshold_method <- "intensity"
threshold_method <- "topn"

#Threshold value
threshold <- 0.2
# threshold <- 0.1
# threshold <- 0.05


#Mask type
# mask_type <- "positive"
# mask_type <- "negative"

#Metric
metric <- "correlation"

#Number of clusters
nk_mouse <- 6
nk_human <- 5

#Mouse and human clusters to examine
k_mouse <- c(4, 6)
k_human <- c(1, 4)

#Mouse cluster information
df_mouse_clusters <- tibble(nk = rep(nk_mouse, length(k_mouse)),
                            k  = k_mouse) %>% 
  unite(col = "cluster_id", nk, k, 
        sep = "-", remove = FALSE)


#Human cluster information
df_human_clusters <- tibble(nk = rep(nk_human, length(k_human)),
                            k = k_human) %>% 
  unite(col = "cluster_id", nk, k, 
        sep = "-", remove = FALSE)
```

# Panel A: Cluster correlation heatmap

```{r fig4-panelA-sim-mat}
#Import positive mask similarity matrix
mat_sim_pos <- import_similarity_matrix(gene_space = gene_space,
                                        jacobians = jacobians,
                                        threshold_method = threshold_method,
                                        threshold = threshold,
                                        mask = "positive")

#Import negative mask similarity matrix
mat_sim_neg <- import_similarity_matrix(gene_space = gene_space,
                                        jacobians = jacobians,
                                        threshold_method = threshold_method,
                                        threshold = threshold,
                                        mask = "negative")

#Average the positive and negative similarity matrices
mat_sim <- array(data = 0,
                 dim = c(dim(mat_sim_pos), 2))
mat_sim[,,1] <- mat_sim_pos
mat_sim[,,2] <- mat_sim_neg
mat_sim <- rowMeans(mat_sim, dims = 2, na.rm = TRUE)
colnames(mat_sim) <- colnames(mat_sim_pos)
rownames(mat_sim) <- rownames(mat_sim_pos)

#Select number of mouse and human clusters
col_selection <- str_detect(colnames(mat_sim), str_c("^", nk_mouse, "-"))
row_selection <- str_detect(rownames(mat_sim), str_c("^", nk_human, "-"))

#Subset the similarity matrix for the number of clusters
mat_sim_nk <- mat_sim[row_selection, col_selection]  
mat_sim_nk <- t(mat_sim_nk)
```

```{r fig4-panelA-heatmap-main}
#Heatmap colour range
heatmap_range <- c(min(mat_sim_nk), max(mat_sim_nk))
heatmap_range_dist <- heatmap_range[2] - heatmap_range[1]

#Heatmap palette
heatmap_colours <- rev(brewer.pal(n = 7, name = "RdYlBu"))
palette_length <- 255
heatmap_palette <- colorRampPalette(heatmap_colours)(palette_length)

#Heatmap breaks
heatmap_breaks <- seq(heatmap_range[1], heatmap_range[2], length.out = palette_length)

mat_labels <- matrix("", nrow = nrow(mat_sim_nk), ncol = ncol(mat_sim_nk))
for(j in 1:ncol(mat_sim_nk)) {
  i <- which(mat_sim_nk[,j] == max(mat_sim_nk[,j]))
  mat_labels[i,j] <- as.character(j)
}

#Generate heatmap
fig4_heatmap_ggplot <- as.ggplot(pheatmap(mat = mat_sim_nk,
                                          color = heatmap_palette,
                                          breaks = heatmap_breaks,
                                          display_numbers = mat_labels,
                                          fontsize_number = 10, 
                                          number_color = "black",
                                          cluster_rows = F, 
                                          cluster_cols = F, 
                                          legend = T,
                                          silent = TRUE))

#Extract heatmap grobs and modify some params
fig4_heatmap_main_grob <- grid.force(ggplotGrob(fig4_heatmap_ggplot))
fig4_heatmap_matrix_grob <- getGrob(fig4_heatmap_main_grob, "matrix.4-3-4-3")
fig4_heatmap_colnames_grob <- getGrob(fig4_heatmap_main_grob, "col_names.5-3-5-3")
fig4_heatmap_colnames_grob[["rot"]] <- 0
fig4_heatmap_colnames_grob[["y"]] <- unit(0.5, "npc")
fig4_heatmap_colnames_grob[["hjust"]] <- 0.5
fig4_heatmap_colnames_grob[["vjust"]] <- 0.5
fig4_heatmap_rownames_grob <- getGrob(fig4_heatmap_main_grob, "row_names.4-4-4-4")
fig4_heatmap_rownames_grob[["x"]] <- unit(0.8, "npc")
fig4_heatmap_rownames_grob[["hjust"]] <- 1

#Create column title
fig4_heatmap_coltitle_grob <- textGrob("Human clusters",
                                       x = 0.5, y = 0.5,
                                       just = "centre",
                                       gp = gpar(fontsize = 11))

#Create row title
fig4_heatmap_rowtitle_grob <- textGrob("Mouse clusters",
                                       x = 0.8, y = 0.5,
                                       rot = 90,
                                       just = "bottom",
                                       gp = gpar(fontsize = 11))
```

```{r fig4-panelA-heatmap-legend}
#Create the scale matrix for the legend raster
fig4_heatmap_legend_scale <- matrix(rev(heatmap_palette), nrow = palette_length, ncol = 1)
fig4_heatmap_legend_scale_width <- 0.3
fig4_heatmap_legend_scale_height <- 1
fig4_heatmap_legend_scale_x <- 0.05
fig4_heatmap_legend_scale_y <- 0

#Raster grob for the legend
fig4_heatmap_legend_scale_grob <- rasterGrob(fig4_heatmap_legend_scale,
                                             x = fig4_heatmap_legend_scale_x,
                                             y = fig4_heatmap_legend_scale_y,
                                             width = fig4_heatmap_legend_scale_width,
                                             height = fig4_heatmap_legend_scale_height,
                                             just = c("left", "bottom"))

#Legend scale text
fig4_heatmap_legend_text <- seq(0.4, heatmap_range[2], by = 0.1)
fig4_heatmap_legend_text_x <- fig4_heatmap_legend_scale_x + fig4_heatmap_legend_scale_width + 0.05
fig4_heatmap_legend_text_y <- (fig4_heatmap_legend_text - heatmap_range[1])/heatmap_range_dist
fig4_heatmap_legend_text_grob <- textGrob(fig4_heatmap_legend_text,
                                          x = fig4_heatmap_legend_text_x,
                                          y = fig4_heatmap_legend_text_y,
                                          just = c("left", "center"),
                                          gp = gpar(fontsize = 9))

#Legend title
fig4_heatmap_legend_title <- "Correlation"
fig4_heatmap_legend_title_x <- fig4_heatmap_legend_text_x + 0.3
fig4_heatmap_legend_title_y <- (fig4_heatmap_legend_scale_y + fig4_heatmap_legend_scale_height)/2
fig4_heatmap_legend_title_grob <- textGrob(fig4_heatmap_legend_title,
                                           x = fig4_heatmap_legend_title_x,
                                           y = fig4_heatmap_legend_title_y,
                                           just = c("center", "top"),
                                           rot = 90,
                                           gp = gpar(fontsize = 11))

#Combined legend grob
fig4_heatmap_legend_grob <- gTree(children = gList(fig4_heatmap_legend_scale_grob,
                                                   fig4_heatmap_legend_text_grob,
                                                   fig4_heatmap_legend_title_grob))
```

```{r fig4-panelA-heatmap-legend}
fig4_heatmap_title <- "Mouse-human cluster correlation matrix"
fig4_heatmap_title_grob <- textGrob(label = fig4_heatmap_title,
                                    x = 0, y = 0.5, 
                                    just = c("left", "center"),
                                    gp = gpar(fontsize = 11))
```

# Panel B: Neuroanatomy correlation distributions

```{r fig4-panelB-dist-import}
#Import neuroanatomical similarity distributions
df_sim_hist <- read_csv("../analyses/anatomical_similarity_histogram.csv", 
                        show_col_types = FALSE)

#Get cluster pair correlations
# cluster_correlations <- numeric(nrow(df_mouse_clusters))
# for (i in 1:nrow(df_mouse_clusters)) {
#   cluster_correlations[i] <- mat_sim_nk[df_mouse_clusters[[i, "k"]], 
#                                         df_human_clusters[[i, "k"]]]
# }

#Get cluster pair correlations
df_top_correlations <- tibble(k = 1:5,
                              human_cluster = str_c(5, k, sep = "-"),
                              mouse_cluster = 0,
                              correlation = 0)
for (j in 1:nrow(df_top_correlations)) {
  max_corr <- max(mat_sim_nk[,j])
  df_top_correlations[j, "correlation"] <- max_corr
  df_top_correlations[j, "mouse_cluster"] <- which(mat_sim_nk[,j] == max_corr) 
}

df_top_correlations <- df_top_correlations %>% 
  mutate(mouse_cluster = str_c(6, mouse_cluster, sep = "-"),
         mouse_cluster = str_c("M", mouse_cluster),
         human_cluster = str_c("H", human_cluster),
         human_y = 5.0,
         mouse_y = 4.5) 
```

```{r fig4-panelB-dist-plot}
#Create the distribution KDE plot
fig4_density <- ggplot(df_sim_hist, aes(x = Similarity, 
                                        y = ..density..,
                                        fill = Type,
                                        col = Type)) + 
  geom_density(alpha = 0.1,
               bw = 0.05) + 
  # geom_vline(xintercept = unique(df_top_correlations[["correlation"]]),
  #            linetype = "dashed") +
  annotate(geom = "segment",
           x = df_top_correlations[["correlation"]],
           xend = df_top_correlations[["correlation"]],
           y = 0, yend = c(4.65, 4.4, 4.65, 4.4, 4.65),
           linetype = "dotted",
           size = 0.3) + 
  annotate(geom = "text", 
           x = df_top_correlations[["correlation"]],
           y = c(4.75, 4.5, 4.75, 4.5, 4.75),
           label = df_top_correlations[["k"]], 
           size = 2) +
  coord_cartesian(ylim = c(0, 5)) + 
  scale_x_continuous(breaks = seq(-0.1, 0.9, by = 0.2),
                     expand = expansion(mult = 0)) + 
  scale_fill_discrete(labels = c("Homologous", "Homologous-\n adjacent", "Non-homologous")) + 
  scale_color_discrete(labels = c("Homologous", "Homologous-\n adjacent", "Non-homologous")) + 
  labs(x = "Correlation",
       y = "Density",
       col = NULL,
       fill = NULL) + 
  theme_bw() + 
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8),
        legend.key.size = unit(8, 'pt'),
        plot.margin = margin(t = 0, b = 0, r = 0, l = 0))

#Extract grobs from the plot
fig4_density_grob <- grid.force(ggplotGrob(fig4_density))
fig4_density_panel_grob <- getGrob(fig4_density_grob, "panel.7-5-7-5")
fig4_density_xtitle_grob <- getGrob(fig4_density_grob, "xlab-b.9-5-9-5")
fig4_density_xtext_grob <- getGrob(fig4_density_grob, "axis-b.8-5-8-5")
fig4_density_ytitle_grob <- textGrob("Density",
                                     x = 0.8, y = 0.5, 
                                     rot = 90,
                                     just = "bottom",
                                     gp = gpar(fontsize = 11))
fig4_density_ytext_grob <- getGrob(fig4_density_grob, "axis-l.7-4-7-4")
fig4_density_legend_grob <- getGrob(fig4_density_grob, "guides.3-3-3-3")
```

```{r fig4-panelB-dist-title}
fig4_density_title <- "Similarity of neuroanatomical regions"
fig4_density_title_grob <- textGrob(label = fig4_density_title,
                                    x = 0, y = 0.5, 
                                    just = c("left", "center"),
                                    gp = gpar(fontsize = 11))
```


# Panels C and D: Cluster neuroanatomy

## Top: Representative cluster maps

```{r fig4-panelsCD-ss-import}
#Import mouse anatomy image
mouse_anat_file <- "../data/mouse/atlas/DSURQE_CCFv3_average_200um.mnc"
mouse_anat <- mincGetVolume(mouse_anat_file)

#Import human anatomy image
human_anat_file <- "../data/human/registration/reference_files/model_1.0mm.mnc"
human_anat <- mincGetVolume(human_anat_file)
human_anat_vol <- mincArray(human_anat)

#Cropped human images along sagittal and transverse planes
human_slices_dim_1 <- 25:160
human_slices_dim_3 <- 35:167
human_anat_vol_cropped <- human_anat_vol[human_slices_dim_1,,human_slices_dim_3]

#Import mouse cluster maps
list_mouse_clusters <- vector(mode = "list", length = nrow(df_mouse_clusters))
names(list_mouse_clusters) <- df_mouse_clusters[["cluster_id"]]
for (i in 1:nrow(df_mouse_clusters)) {
  list_mouse_clusters[[i]] <- import_cluster_map(datadir = datadir,
                                                 species = "mouse",
                                                 nk = df_mouse_clusters[[i, "nk"]],
                                                 k = df_mouse_clusters[[i, "k"]],
                                                 jacobians = jacobians,
                                                 mask = "symmetric",
                                                 threshold_method = threshold_method, 
                                                 threshold = threshold)
}

#Import human cluster maps
list_human_clusters <- vector(mode = "list", length = nrow(df_human_clusters))
names(list_human_clusters) <- df_human_clusters[["cluster_id"]]
for (i in 1:nrow(df_human_clusters)) {
  list_human_clusters[[i]] <- import_cluster_map(datadir = datadir,
                                                 species = "human",
                                                 nk = df_human_clusters[[i, "nk"]],
                                                 k = df_human_clusters[[i, "k"]],
                                                 jacobians = jacobians,
                                                 mask = "symmetric",
                                                 threshold_method = threshold_method,
                                                 threshold = threshold)
}
```

```{r fig4-panelsCD-ss-1}
#Create the base slice series without legend
fig4_ss_1_base <- sliceSeries(nrow = 5, ncol = 1, begin = 10, end = 50) %>% 
  anatomy(mincArray(mouse_anat), low = 700, high = 1400) %>% 
  overlay(mincArray(list_mouse_clusters[[1]]), low = 0.3, high = 0.7, symmetric = TRUE) %>% 
  sliceSeries(nrow = 5, ncol = 1, begin = 50, end = 180) %>% 
  anatomy(human_anat_vol_cropped, low = 3, high = 7) %>% 
  overlay(mincArray(list_human_clusters[[1]])[human_slices_dim_1,,human_slices_dim_3],
          low = 0.3, high = 0.7, symmetric = TRUE)

#Base slice series grob
fig4_ss_1_base_grob <- grobify(fig4_ss_1_base)

#Add a legend to the slice series
fig4_ss_1_legend_grob <- fig4_ss_1_base %>% 
  legend("Effect size") %>% 
  grobify()

#Extract the legend only from the slice series
fig4_ss_1_legend_grob <- fig4_ss_1_legend_grob[["children"]][[3]][["children"]][[1]][["children"]][[1]][["children"]][[1]]

#Create labels for the mouse and human slice series
fig4_ss_1_labels <- c(names(list_mouse_clusters)[1],
                      names(list_human_clusters)[1])
fig4_ss_1_labels_grob <- textGrob(label = fig4_ss_1_labels,
                                  x = c(0.25, 0.75),
                                  just = "center",
                                  gp = gpar(fontsize = 10))
```

```{r fig4-panelsCD-ss-2}
#Create the base slice series without legend
fig4_ss_2_base <- sliceSeries(nrow = 5, ncol = 1, begin = 10, end = 50) %>% 
  anatomy(mincArray(mouse_anat), low = 700, high = 1400) %>% 
  overlay(mincArray(list_mouse_clusters[[2]]), low = 0.3, high = 0.7, symmetric = TRUE) %>% 
  sliceSeries(nrow = 5, ncol = 1, begin = 50, end = 180) %>% 
  anatomy(human_anat_vol_cropped, low = 3, high = 7) %>% 
  overlay(mincArray(list_human_clusters[[2]])[human_slices_dim_1,,human_slices_dim_3],
          low = 0.3, high = 0.7, symmetric = TRUE) 

#Base slice series grob
fig4_ss_2_base_grob <- grobify(fig4_ss_2_base)

#Add a legend to the slice series
fig4_ss_2_legend_grob <- fig4_ss_2_base %>% 
  legend() %>% 
  grobify()

#Extract the legend only from the slice series
fig4_ss_2_legend_grob <- fig4_ss_2_legend_grob[["children"]][[3]][["children"]][[1]][["children"]][[1]][["children"]][[1]]

#Create labels for the mouse and human slice series
fig4_ss_2_labels <- c(names(list_mouse_clusters)[2],
                      names(list_human_clusters)[2])
fig4_ss_2_labels_grob <- textGrob(label = fig4_ss_2_labels,
                                  x = c(0.25, 0.75),
                                  just = "center",
                                  gp = gpar(fontsize = 10))
```

```{r fig4-panelsCD-ss-title}
#Slice series title
fig4_ss_title <- "Cluster-averaged relative effect size maps"
fig4_ss_title_grob <- textGrob(label = fig4_ss_title,
                               x = 0, y = 0.5, 
                               just = c("left", "center"),
                               gp = gpar(fontsize = 11))
```

## Bottom: Polar plots

```{r fig4-panelsCD-polar-import}
#Import mouse atlas labels
mouse_labels_file <- "../data/mouse/atlas/DSURQE_CCFv3_labels_200um.mnc"
mouse_labels <- mincGetVolume(mouse_labels_file)

#Import mouse atlas definitions
mouse_defs_file <- "../data/mouse/atlas/DSURQE_40micron_R_mapping_long.csv"
mouse_defs <- read_csv(mouse_defs_file, show_col_types = FALSE) %>% 
  select(name = Structure, label = Label)

#Import mouse neuroanatomical tree
mouse_tree_file <- "../data/mouse/expression/MouseExpressionTree_DSURQE.RData"
load(mouse_tree_file)
mouse_tree <- Clone(treeMouseExpr)
rm(treeMouseExpr)

#Import human microarray atlas labels
human_labels_file <- "../data/human/expression/AHBA_microarray_labels_studyspace_1.0mm.mnc"
human_labels <- mincGetVolume(human_labels_file)

#Import human microarray atlas definitions
human_defs_file <- "../data/human/expression/AHBA_microarray_coordinates_mni_defs.csv"
human_defs <- read_csv(human_defs_file, show_col_types = FALSE)

#Import human neuroanatomical tree
human_tree_file <- "../data/human/expression/HumanExpressionTree.RData"
load(human_tree_file)
human_tree <- Clone(treeHumanExpr)
rm(treeHumanExpr)

#Import mapping for mouse-human neuroanatomical homologues
neuro_file <- "../data/MouseHumanMatches_H10M09.csv"
df_spokes <- read_csv(neuro_file, show_col_types = FALSE)
colnames(df_spokes) <- str_to_lower(colnames(df_spokes))
df_spokes <- df_spokes %>% 
  filter(!(name %in% c("White matter", "Ventricles")))
```

```{r fig4-panelsCD-polar-1-prep}
#Mouse and human numbers of clusters
nk_list <- list("mouse" = nk_mouse,
                "human" = nk_human)

#Mouse and human cluster IDs
k_list <- list("mouse" = df_mouse_clusters[[1,"k"]],
               "human" = df_human_clusters[[1,"k"]])

#Mouse and human labels
labels <- list("mouse" = mouse_labels,
               "human" = human_labels)

#Mouse and human definitions
defs <- list("mouse" = mouse_defs,
             "human" = human_defs)

#Mouse and human trees
trees <- list("mouse" = mouse_tree,
              "human" = human_tree)

#Prepare polar plot data from files
radar_data <- prepare_radar_chart(datadir = "../data/",
                                  spokes = df_spokes,
                                  nk = nk_list, 
                                  k = k_list,
                                  labels = labels,
                                  defs = defs,
                                  trees = trees,
                                  jacobians = jacobians,
                                  threshold_method = threshold_method,
                                  threshold = threshold)
```

```{r fig4-panelsCD-polar-1}
#Data for line at 0
radar_zeroline <- tibble(name = unique(radar_data$name),
                         y = 0)

#Plot parameters
nspokes <- length(unique(radar_data$name))-1
radar_start <- -(2*pi)/nspokes
breaks_start <- -1
breaks_end <- 1
breaks_step <- 0.5
radar_breaks <- seq(breaks_start, breaks_end, by = breaks_step)
radar_labels <- tibble(name = levels(radar_data$name)[6],
                       breaks = radar_breaks)

#Create polar plot
fig4_radar_1 <- ggplot(radar_data, aes(x = name, 
                                       ymin = negative, 
                                       ymax = positive, 
                                       group = species, 
                                       fill = species,
                                       col = species)) + 
  geom_ribbon(alpha = 0.2) +
  geom_line(data = radar_zeroline,
            inherit.aes = FALSE,
            mapping = aes(x = name, y = y, group = 1),
            linetype = "dashed",
            size = 0.5) + 
  geom_text(data = radar_labels,
            inherit.aes = FALSE,
            mapping = aes(x = name,
                          y = breaks,
                          label = breaks),
            size = 2.5,
            nudge_y = 0.1) + 
  coord_radar(start = radar_start) +
  scale_x_discrete(expand = expansion(),
                   labels = c("CbN", "Cx", "CxN", "IB", "MB", "P", "MY", "CbCx", "CbN")) + 
  scale_y_continuous(breaks = seq(-1, 1, by = 0.5), limits = c(-1, 1.2)) + 
  scale_fill_discrete(labels = c("Human", "Mouse")) + 
  scale_color_discrete(labels = c("Human", "Mouse")) + 
  labs(x = NULL,
       fill = NULL, 
       col = NULL) + 
  theme_bw() +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x = element_text(size = 6, face = "bold"),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        plot.margin = margin(t = 0, b = 0, r = 0, l = 0))

#Extract grobs from polar plot
fig4_radar_1_grob <- grid.force(ggplotGrob(fig4_radar_1))
fig4_radar_1_panel_grob <- getGrob(fig4_radar_1_grob, "panel.7-5-7-5")
fig4_radar_legend_grob <- getGrob(fig4_radar_1_grob, "guides.3-3-3-3")

#Plot annotation
fig4_radar_1_annotation_text <- str_c(str_c("Mouse ", str_c(nk_list[["mouse"]], 
                                                            k_list[["mouse"]], sep = "-")), 
                                      "and",
                                      str_c("human ", str_c(nk_list[["human"]], 
                                                            k_list[["human"]], sep = "-")),
                                      sep = " ")
fig4_radar_1_annotation_grob <- textGrob(fig4_radar_1_annotation_text,
                                         gp = gpar(fontsize = 10))
```

```{r fig4-panelsCD-polar-2-prep}
#Mouse and human cluster IDs
k_list <- list("mouse" = df_mouse_clusters[[2,"k"]],
               "human" = df_human_clusters[[2,"k"]])

#Prepare polar plot data from files
radar_data <- prepare_radar_chart(datadir = "../data/",
                                  spokes = df_spokes,
                                  nk = nk_list,
                                  k = k_list,
                                  labels = labels,
                                  defs = defs,
                                  trees = trees,
                                  jacobians = jacobians,
                                  threshold_method = threshold_method,
                                  threshold = threshold)
```

```{r fig4-panelsCD-polar-2}
#Data for line at 0
radar_zeroline <- tibble(name = unique(radar_data$name),
                         y = 0)

#Plot parameters
nspokes <- length(unique(radar_data$name))-1
radar_start <- -(2*pi)/nspokes
breaks_start <- -1
breaks_end <- 1
breaks_step <- 0.5
radar_breaks <- seq(breaks_start, breaks_end, by = breaks_step)
radar_labels <- tibble(name = levels(radar_data$name)[6],
                       breaks = radar_breaks)

#Create polar plot
fig4_radar_2 <- ggplot(radar_data, aes(x = name,
                                       ymin = negative, 
                                       ymax = positive, 
                                       group = species, 
                                       fill = species, 
                                       col = species)) + 
  geom_ribbon(alpha = 0.2) +
  geom_line(data = radar_zeroline,
            inherit.aes = FALSE,
            mapping = aes(x = name, y = y, group = 1),
            linetype = "dashed",
            size = 0.5) + 
  geom_text(data = radar_labels,
            inherit.aes = FALSE,
            mapping = aes(x = name,
                          y = breaks,
                          label = breaks),
            size = 2.5,
            nudge_y = 0.1) + 
  coord_radar(start = radar_start) +
  scale_x_discrete(expand = expansion(),
                   labels = c("CbN", "Cx", "CxN", "IB", "MB", "P", "MY", "CbCx", "CbN")) + 
  scale_y_continuous(breaks = seq(-1, 1, by = 0.5), limits = c(-1, 1.2)) + 
  scale_fill_discrete(labels = c("Human", "Mouse")) + 
  scale_color_discrete(labels = c("Human", "Mouse")) + 
  labs(x = NULL,
       fill = NULL, 
       col = NULL) + 
  theme_bw() +
  theme(legend.position = "none",
        axis.text.x = element_text(size = 6, face = "bold"),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        plot.margin = margin(t = 0, b = 0, r = 0, l = 0))

#Extract grobs from polar plot
fig4_radar_2_grob <- grid.force(ggplotGrob(fig4_radar_2))
fig4_radar_2_panel_grob <- getGrob(fig4_radar_2_grob, "panel.7-5-7-5")

#Plot annotation
fig4_radar_2_annotation_text <- str_c(str_c("Mouse ", str_c(nk_list[["mouse"]], 
                                                            k_list[["mouse"]], sep = "-")), 
                                      "and",
                                      str_c("human ", str_c(nk_list[["human"]], 
                                                            k_list[["human"]], sep = "-")),
                                      sep = " ")
fig4_radar_2_annotation_grob <- textGrob(fig4_radar_2_annotation_text,
                                         gp = gpar(fontsize = 10))
```

```{r fig4-panelsCD-polar-title}
fig4_radar_title <- "Representation of neuroanatomical areas in mouse and human clusters"
fig4_radar_title_grob <- textGrob(label = fig4_radar_title,
                                  x = 0, y = 0.5, 
                                  just = c("left", "center"),
                                  gp = gpar(fontsize = 10))
```

# Panel E: Human cluster diagnosis information

```{r fig4-panelE-dx-prep}
#Import cluster assignment data 
human_cluster_assignments <- "../data/human/clustering/human_clusters_groups10_3.0mm.csv"
human_cluster_assignments <- read_csv(human_cluster_assignments, show_col_types = FALSE)
human_cluster_assignments <- human_cluster_assignments %>% 
  select(ID, k = str_c("Group", nk_human))

#Import human demographics data
human_demographics <- "../data/human/registration/DBM_input_demo_passedqc.csv"
human_demographics <- read_csv(human_demographics, show_col_types = FALSE)
human_demographics <- human_demographics %>% 
  select(Extract_ID, DX) %>% 
  mutate(ID = str_remove(Extract_ID, ".extracted.mnc"))

#Join cluster assignment to demographics data
human_cluster_dx <- inner_join(human_cluster_assignments, 
                               human_demographics,
                               by = "ID")

#Relabel the cluster diagnoses
human_dx_relabel <- tibble(DX = unique(human_cluster_dx$DX),
                           DX_new = c("ASD", 
                                      "OCD", 
                                      "ADHD", 
                                      "OCD", 
                                      "ADHD", 
                                      "ID",
                                      "Anxiety",
                                      "Other", 
                                      "Other"))

#Join new diagnostic labels to cluster assignments
human_cluster_dx <- inner_join(human_cluster_dx, 
                               human_dx_relabel, 
                               by = "DX")

#Create all combinations of DX and cluster assignments
df_cluster_dx_combinations <- expand_grid(k = unique(human_cluster_dx[["k"]]),
                                          DX_new = unique(human_cluster_dx[["DX_new"]]))

#Count number of participants in each cluster-diagnosis bin
human_cluster_dx_summary <- human_cluster_dx %>% 
  group_by(k, DX_new) %>% 
  summarise(num = n()) %>% 
  ungroup() %>% 
  right_join(df_cluster_dx_combinations, by = c("k", "DX_new")) %>% 
  mutate(num = ifelse(is.na(num), 0, num),
         cluster_id = str_c(5, k, sep = "-"),
         cluster_id = factor(cluster_id, levels = str_c(5, 1:5, sep = "-")))
```

```{r fig4-panelE-dx-plot}
fig4_cluster_dx <- ggplot(human_cluster_dx_summary, 
                          aes(x = cluster_id, 
                              y = num, 
                              fill = DX_new,
                              col = DX_new)) + 
  geom_col(position = "dodge", 
           width = 0.8,
           alpha = 0.7) + 
  labs(x = "Cluster ID",
       y = "Number of participants",
       fill = NULL,
       col = NULL) + 
  scale_y_continuous(breaks = seq(0, 100, by = 20)) + 
  theme_bw() + 
  theme(legend.position = "bottom",
        legend.direction = "horizontal") + 
  guides(color = guide_legend(nrow = 1),
         fill = guide_legend(nrow = 1)) 

#Extract grobs
fig4_cluster_dx_grob <- grid.force(ggplotGrob(fig4_cluster_dx))
```

```{r fig4-panelE-dx-title}
fig4_cluster_dx_title <- "Diagnostic breakdown of human clusters"
fig4_cluster_dx_title_grob <- textGrob(label = fig4_cluster_dx_title,
                                       x = 0, y = 0.5, 
                                       just = c("left", "center"),
                                       gp = gpar(fontsize = 11))
```


# Figure 


## Figure layout v1


```{r fig.width = 10, fig.height = 10}
fig4_layout <- rbind(c(NA, 1,  1,  1,  1,  1,  1,  1,  1,  1, NA),
                     c( 2,  3,  4,  4,  4,  5, NA,  6, NA, NA,  7),
                     c( 2,  8,  9, 10, 11, 12, 13, 14, 15, 16,  7),
                     c( 2, NA, NA, 17, NA, NA, 18, NA, 19, NA,  7),
                     c( 2, NA, NA, 20, NA, NA, NA, NA, NA, NA,  7),
                     c( 2, 21, 21, 21, 21, 21, 21, 21, 21, 21,  7),
                     c( 2, 22, 23, 23, 23, NA, 24, 24, 24, NA,  7),
                     c( 2, 25, 26, 27, 27, 28, 29, NA, 30, NA,  7),
                     c( 2, NA, NA, 31, 31, NA, 32, NA, 33, NA,  7),
                     c( 2, NA, NA, 34, 34, NA, 32, NA, 33, NA,  7),
                     c( 2, NA, NA, 35, 35, NA, 36, 36, 36, NA,  7),
                     c( 2, 37, 37, 37, 37, 37, 37, 37, 37, 37,  7),
                     c( 2, 38, 39, 39, 39, 39, 39, 39, 39, 39,  7),
                     c(NA, 40, 40, 40, 40, 40, 40, 40, 40, 40, NA),
                     c(NA, 41, 41, 41, 41, 41, 41, 41, 41, 41, NA))
fig4_widths <- c(0.1, 0.3, 0.3, 1.9, 0.8, 0.3, 1.9, 0.3, 1.9, 0.6, 0.1)
fig4_widths_in <- unit(fig4_widths, "inch")

fig4_heights <- c(0.1, 0.3, 2.5, 0.3, 0.3, 0.1, 0.3, 2.1, 0.2, 0.2, 0.4, 0.1, 0.3, 2.4, 0.1)
fig4_heights_in <- unit(fig4_heights, "inch")

# gTree(children = gList(rectGrob(),
fig4_plots_grob <- arrangeGrob(gTree(children = gList(rectGrob(), zeroGrob())), #1
                               gTree(children = gList(rectGrob(), zeroGrob())), #2
                               textGrob("A.", gp = gpar(fontsize = 14, fontface = "bold")), #3
                               gTree(children = gList(rectGrob(), fig4_heatmap_title_grob)), #4
                               # gTree(children = gList(rectGrob(), fig4_ss_title_grob)), #5
                               textGrob("C.", gp = gpar(fontsize = 14, fontface = "bold")), #5
                               textGrob("D.", gp = gpar(fontsize = 14, fontface = "bold")), #6
                               gTree(children = gList(rectGrob(), zeroGrob())), #7
                               gTree(children = gList(rectGrob(),fig4_heatmap_rowtitle_grob)), #8
                               gTree(children = gList(rectGrob(),fig4_heatmap_rownames_grob)), #9
                               fig4_heatmap_matrix_grob, #10
                               gTree(children = gList(rectGrob(), fig4_heatmap_legend_grob)), #11
                               gTree(children = gList(rectGrob(), zeroGrob())), #12
                               fig4_ss_1_base_grob, #13
                               gTree(children = gList(rectGrob(), zeroGrob())), #14
                               fig4_ss_2_base_grob, #15
                               gTree(children = gList(rectGrob(), fig4_ss_2_legend_grob)), #16
                               gTree(children = gList(rectGrob(),fig4_heatmap_colnames_grob)), #17
                               gTree(children = gList(rectGrob(),fig4_ss_1_labels_grob)), #18
                               gTree(children = gList(rectGrob(),fig4_ss_2_labels_grob)), #19
                               gTree(children = gList(rectGrob(),fig4_heatmap_coltitle_grob)), #20
                               gTree(children = gList(rectGrob(), zeroGrob())), #21
                               textGrob("B.", gp = gpar(fontsize = 14, fontface = "bold")), #22
                               gTree(children = gList(rectGrob(), fig4_density_title_grob)), #23
                               gTree(children = gList(rectGrob(), fig4_radar_title_grob)), #24
                               gTree(children = gList(rectGrob(),fig4_density_ytitle_grob)), #25
                               gTree(children = gList(rectGrob(),fig4_density_ytext_grob)), #26
                               fig4_density_panel_grob, #27
                               gTree(children = gList(rectGrob(), zeroGrob())), #28
                               fig4_radar_1_panel_grob, #29
                               fig4_radar_2_panel_grob, #30
                               gTree(children = gList(rectGrob(), fig4_density_xtext_grob)), #31
                               gTree(children = gList(rectGrob(), fig4_radar_1_annotation_grob)), #32
                               gTree(children = gList(rectGrob(), fig4_radar_2_annotation_grob)), #33
                               gTree(children = gList(rectGrob(), fig4_density_xtitle_grob)), #34
                               gTree(children = gList(rectGrob(), fig4_density_legend_grob)), #35
                               gTree(children = gList(rectGrob(), fig4_radar_legend_grob)), #36
                               gTree(children = gList(rectGrob(), zeroGrob())), #37
                               textGrob("E.", gp = gpar(fontsize = 14, fontface = "bold")), #38
                               gTree(children = gList(rectGrob(), fig4_cluster_dx_title_grob)), #39
                               gTree(children = gList(rectGrob(), fig4_cluster_dx_grob)), #40
                               gTree(children = gList(rectGrob(), zeroGrob())), #41
                               layout_matrix = fig4_layout,
                               widths = fig4_widths_in,
                               heights = fig4_heights_in)

fig4_border_grob <- rectGrob(gp = gpar(fill = NA))

fig4_grob <- gTree(children = gList(fig4_plots_grob,
                                    fig4_border_grob))

fig4_width <- 8.5
fig4_height <- 10

fig4_outfile <- "fig.pdf"
pdf(file = fig4_outfile,
    width = fig4_width,
    height = fig4_height)
grid.draw(fig4_grob)
dev.off()

grid.newpage()
grid.draw(fig4_grob)

```


## Figure layout v2


```{r}
nrows <- 15
ncols <- 11
df_indices <- expand_grid(i = 1:nrows,
                          j = 1:ncols)
list_indices <- vector(mode = "list", length = nrow(df_indices))
for (r in 1:nrow(df_indices)) {
  i <- df_indices[[r, "i"]]
  j <- df_indices[[r, "j"]]
  list_indices[[r]] <- gTree(children = gList(rectGrob(), 
                                              textGrob(label = str_c("(", i, ", ", j, ")"),
                                                       gp = gpar(fontsize = 4))))
}

fig4_guide_layout <- matrix(data = 1:nrow(df_indices), nrow = nrows, ncol = ncols, byrow = TRUE)

fig4_widths <- c(0.1, 0.3, 0.3, 1.9, 0.8, 0.3, 1.9, 0.3, 1.9, 0.6, 0.1)
fig4_widths_in <- unit(fig4_widths, "inch")

fig4_heights <- c(0.1, 0.3, 0.3, 0.3, 2.5, 0.1, 0.3, 2.1, 0.2, 0.2, 0.4, 0.1, 0.3, 2.4, 0.1)
fig4_heights_in <- unit(fig4_heights, "inch")

fig4_guide_plots_grob <- arrangeGrob(grobs = list_indices,
                                     layout_matrix = fig4_guide_layout,
                                     widths = fig4_widths_in,
                                     heights = fig4_heights_in)


fig4_guide_border_grob <- rectGrob(gp = gpar(fill = NA))

fig4_guide_grob <- gTree(children = gList(fig4_guide_plots_grob,
                                          fig4_guide_border_grob))

fig4_width <- 8.5
fig4_height <- 10

fig4_guide_outfile <- "Figure4_guide.pdf"
pdf(file = guide_outfile ,
    width = fig4_width,
    height = fig4_height)
grid.draw(fig4_guide_grob)
dev.off()

fig4_layout <- matrix(data = NA, 
                      nrow = nrow(fig4_guide_layout),
                      ncol = ncol(fig4_guide_layout))

#Row 1
fig4_layout[1, 2:10] <- 1

#Row 2
fig4_layout[2:14, 1] <- 2
fig4_layout[2, 2] <- 3
fig4_layout[2, 3:5] <- 4
fig4_layout[2, 6] <- 5
fig4_layout[2, 7:10] <- 6
fig4_layout[2:14, 11] <- 7

#Row 3
fig4_layout[3, 4] <- 8
fig4_layout[3, 7] <- 9
fig4_layout[3, 9] <- 10

#Row 4
fig4_layout[4, 4] <- 11
fig4_layout[4, 7] <- 12
fig4_layout[4, 9] <- 13

#Row 5
fig4_layout[5, 2] <- 14
fig4_layout[5, 3] <- 15
fig4_layout[5, 4] <- 16
fig4_layout[5, 5] <- 17
fig4_layout[5, 6] <- 18
fig4_layout[5, 7] <- 19
fig4_layout[5, 8] <- 20
fig4_layout[5, 9] <- 21
fig4_layout[5, 10] <- 22

#Row 6
fig4_layout[6, 1:11] <- 23

#Row 7
fig4_layout[7, 2] <-  24
fig4_layout[7, 3:5] <-  25
fig4_layout[7, 6] <-  26
fig4_layout[7, 7:9] <-  27

#Row 8
fig4_layout[8, 2] <- 28
fig4_layout[8, 3] <- 29
fig4_layout[8, 4:5] <- 30
fig4_layout[8, 6] <- 31
fig4_layout[8, 7] <- 32
fig4_layout[8, 9] <- 33

#Row 9
fig4_layout[9, 4:5] <- 34
fig4_layout[9, 7] <- 35
fig4_layout[9, 9] <- 36

#Row 10
fig4_layout[10, 4:5] <- 37
fig4_layout[10, 7] <- 35
fig4_layout[10, 9] <- 36

#Row 11
fig4_layout[11, 4:5] <- 38
fig4_layout[11, 7:9] <- 39

#Row 12
fig4_layout[12, 2:10] <- 40

#Row 13
fig4_layout[13, 2] <- 41
fig4_layout[13, 3:10] <- 42

#Row 14
fig4_layout[14, 2:10] <- 43

#Row 15 
fig4_layout[15, 2:10] <- 44


fig4_plots_grob <- arrangeGrob(gTree(children = gList(rectGrob(), zeroGrob())), #1
                               gTree(children = gList(rectGrob(), zeroGrob())), #2
                               textGrob("A.", gp = gpar(fontsize = 14, fontface = "bold")), #3
                               gTree(children = gList(rectGrob(), fig4_heatmap_title_grob)), #4
                               textGrob("C.", gp = gpar(fontsize = 14, fontface = "bold")), #5
                               gTree(children = gList(rectGrob(), fig4_ss_title_grob)), #6
                               gTree(children = gList(rectGrob(), zeroGrob())), #7
                               gTree(children = gList(rectGrob(),fig4_heatmap_coltitle_grob)), #8
                               gTree(children = gList(rectGrob(),textGrob("Best match"))), #9
                               gTree(children = gList(rectGrob(),textGrob("Second best match"))), #10
                               gTree(children = gList(rectGrob(),fig4_heatmap_colnames_grob)), #11
                               gTree(children = gList(rectGrob(),fig4_ss_1_labels_grob)), #12
                               gTree(children = gList(rectGrob(),fig4_ss_2_labels_grob)), #13
                               gTree(children = gList(rectGrob(),fig4_heatmap_rowtitle_grob)), #14
                               gTree(children = gList(rectGrob(),fig4_heatmap_rownames_grob)), #15
                               fig4_heatmap_matrix_grob, #16
                               gTree(children = gList(rectGrob(), fig4_heatmap_legend_grob)), #17
                               gTree(children = gList(rectGrob(), zeroGrob())), #18
                               fig4_ss_1_base_grob, #19
                               gTree(children = gList(rectGrob(), zeroGrob())), #20
                               fig4_ss_2_base_grob, #21
                               gTree(children = gList(rectGrob(), fig4_ss_2_legend_grob)), #22
                               gTree(children = gList(rectGrob(), zeroGrob())), #23
                               textGrob("B.", gp = gpar(fontsize = 14, fontface = "bold")), #24
                               gTree(children = gList(rectGrob(), fig4_density_title_grob)), #25
                               textGrob("D.", gp = gpar(fontsize = 14, fontface = "bold")), #26
                               gTree(children = gList(rectGrob(), fig4_radar_title_grob)), #27
                               gTree(children = gList(rectGrob(),fig4_density_ytitle_grob)), #28
                               gTree(children = gList(rectGrob(),fig4_density_ytext_grob)), #29
                               fig4_density_panel_grob, #30
                               gTree(children = gList(rectGrob(), zeroGrob())), #31
                               fig4_radar_1_panel_grob, #32
                               fig4_radar_2_panel_grob, #33
                               gTree(children = gList(rectGrob(), fig4_density_xtext_grob)), #34
                               gTree(children = gList(rectGrob(), fig4_radar_1_annotation_grob)), #35
                               gTree(children = gList(rectGrob(), fig4_radar_2_annotation_grob)), #36
                               gTree(children = gList(rectGrob(), fig4_density_xtitle_grob)), #37
                               gTree(children = gList(rectGrob(), fig4_density_legend_grob)), #38
                               gTree(children = gList(rectGrob(), fig4_radar_legend_grob)), #39
                               gTree(children = gList(rectGrob(), zeroGrob())), #40
                               textGrob("E.", gp = gpar(fontsize = 14, fontface = "bold")), #41
                               gTree(children = gList(rectGrob(), fig4_cluster_dx_title_grob)), #42
                               gTree(children = gList(rectGrob(), fig4_cluster_dx_grob)), #43
                               gTree(children = gList(rectGrob(), zeroGrob())), #44
                               layout_matrix = fig4_layout,
                               widths = fig4_widths_in,
                               heights = fig4_heights_in)

fig4_border_grob <- rectGrob(gp = gpar(fill = NA))

fig4_grob <- gTree(children = gList(fig4_plots_grob,
                                    fig4_border_grob))

fig4_outfile <- "Figure4.pdf"
pdf(file = fig4_outfile,
    width = fig4_width,
    height = fig4_height)
grid.draw(fig4_grob)
dev.off()

grid.newpage()
grid.draw(fig4_grob)
```


```{r}
nrows <- 15
ncols <- 11
df_indices <- expand_grid(i = 1:nrows,
                          j = 1:ncols)
list_indices <- vector(mode = "list", length = nrow(df_indices))
for (r in 1:nrow(df_indices)) {
  i <- df_indices[[r, "i"]]
  j <- df_indices[[r, "j"]]
  list_indices[[r]] <- gTree(children = gList(rectGrob(), 
                                              textGrob(label = str_c("(", i, ", ", j, ")"),
                                                       gp = gpar(fontsize = 4))))
}

fig4_guide_layout <- matrix(data = 1:nrow(df_indices), nrow = nrows, ncol = ncols, byrow = TRUE)

fig4_widths <- c(0.1, 0.3, 0.3, 1.9, 0.8, 0.3, 2.0, 0.1, 2.0, 0.6, 0.1)
fig4_widths_in <- unit(fig4_widths, "inch")

fig4_heights <- c(0.1, 0.3, 0.3, 0.3, 2.5, 0.1, 0.3, 2.1, 0.2, 0.2, 0.4, 0.1, 0.3, 2.4, 0.1)
fig4_heights_in <- unit(fig4_heights, "inch")

fig4_guide_plots_grob <- arrangeGrob(grobs = list_indices,
                                     layout_matrix = fig4_guide_layout,
                                     widths = fig4_widths_in,
                                     heights = fig4_heights_in)


fig4_guide_border_grob <- rectGrob(gp = gpar(fill = NA))

fig4_guide_grob <- gTree(children = gList(fig4_guide_plots_grob,
                                          fig4_guide_border_grob))

fig4_width <- 8.5
fig4_height <- 10

fig4_guide_outfile <- "Figure4_guide.pdf"
pdf(file = guide_outfile ,
    width = fig4_width,
    height = fig4_height)
grid.draw(fig4_guide_grob)
dev.off()

fig4_layout <- matrix(data = NA, 
                      nrow = nrow(fig4_guide_layout),
                      ncol = ncol(fig4_guide_layout))

#Row 1
fig4_layout[1, 2:10] <- 1

#Row 2
fig4_layout[2:14, 1] <- 2
fig4_layout[2, 2] <- 3
fig4_layout[2, 3:5] <- 4
fig4_layout[2, 6] <- 5
fig4_layout[2, 7:10] <- 6
fig4_layout[2:14, 11] <- 7

#Row 3
fig4_layout[3, 4] <- 8
fig4_layout[3, 7] <- 9
fig4_layout[3, 9] <- 10

#Row 4
fig4_layout[4, 4] <- 11
fig4_layout[4, 7] <- 12
fig4_layout[4, 9] <- 13

#Row 5
fig4_layout[5, 2] <- 14
fig4_layout[5, 3] <- 15
fig4_layout[5, 4] <- 16
fig4_layout[5, 5] <- 17
fig4_layout[5, 6] <- 18
fig4_layout[5, 7] <- 19
fig4_layout[5, 8] <- 20
fig4_layout[5, 9] <- 21
fig4_layout[5, 10] <- 22

#Row 6
fig4_layout[6, 1:11] <- 23

#Row 7
fig4_layout[7, 2] <-  24
fig4_layout[7, 3:5] <-  25
fig4_layout[7, 6] <-  26
fig4_layout[7, 7:9] <-  27

#Row 8
fig4_layout[8, 2] <- 28
fig4_layout[8, 3] <- 29
fig4_layout[8, 4:5] <- 30
fig4_layout[8, 6] <- 31
fig4_layout[8, 7] <- 32
fig4_layout[8, 9] <- 33

#Row 9
fig4_layout[9, 4:5] <- 34
fig4_layout[9, 7] <- 35
fig4_layout[9, 9] <- 36

#Row 10
fig4_layout[10, 4:5] <- 37
fig4_layout[10, 7] <- 35
fig4_layout[10, 9] <- 36

#Row 11
fig4_layout[11, 2:6] <- 38
fig4_layout[11, 7:9] <- 39

#Row 12
fig4_layout[12, 2:10] <- 40

#Row 13
fig4_layout[13, 2] <- 41
fig4_layout[13, 3:10] <- 42

#Row 14
fig4_layout[14, 2:10] <- 43

#Row 15 
fig4_layout[15, 2:10] <- 44


fig4_plots_grob <- arrangeGrob(zeroGrob(), #1
                               zeroGrob(), #2
                               textGrob("A.", gp = gpar(fontsize = 14, fontface = "bold")), #3
                               fig4_heatmap_title_grob, #4
                               textGrob("C.", gp = gpar(fontsize = 14, fontface = "bold")), #5
                               fig4_ss_title_grob, #6
                               zeroGrob(), #7
                               fig4_heatmap_coltitle_grob, #8
                               textGrob("Best match", gp = gpar(fontsize = 11)), #9
                               textGrob("Second best match", gp = gpar(fontsize = 11)), #10
                               fig4_heatmap_colnames_grob, #11
                               fig4_ss_1_labels_grob, #12
                               fig4_ss_2_labels_grob, #13
                               fig4_heatmap_rowtitle_grob, #14
                               fig4_heatmap_rownames_grob, #15
                               fig4_heatmap_matrix_grob, #16
                               fig4_heatmap_legend_grob, #17
                               zeroGrob(), #18
                               fig4_ss_1_base_grob, #19
                               zeroGrob(), #20
                               fig4_ss_2_base_grob, #21
                               fig4_ss_2_legend_grob, #22
                               zeroGrob(), #23
                               textGrob("B.", gp = gpar(fontsize = 14, fontface = "bold")), #24
                               fig4_density_title_grob, #25
                               textGrob("D.", gp = gpar(fontsize = 14, fontface = "bold")), #26
                               fig4_radar_title_grob, #27
                               fig4_density_ytitle_grob, #28
                               fig4_density_ytext_grob, #29
                               fig4_density_panel_grob, #30
                               zeroGrob(), #31
                               fig4_radar_1_panel_grob, #32
                               fig4_radar_2_panel_grob, #33
                               fig4_density_xtext_grob, #34
                               fig4_radar_1_annotation_grob, #35
                               fig4_radar_2_annotation_grob, #36
                               fig4_density_xtitle_grob, #37
                               fig4_density_legend_grob, #38
                               fig4_radar_legend_grob, #39
                               zeroGrob(), #40
                               textGrob("E.", gp = gpar(fontsize = 14, fontface = "bold")), #41
                               fig4_cluster_dx_title_grob, #42
                               fig4_cluster_dx_grob, #43
                               zeroGrob(), #44
                               layout_matrix = fig4_layout,
                               widths = fig4_widths_in,
                               heights = fig4_heights_in)

fig4_border_grob <- rectGrob(gp = gpar(fill = NA))

fig4_grob <- gTree(children = gList(fig4_plots_grob,
                                    fig4_border_grob))

fig4_outfile <- "Figure4.pdf"
pdf(file = fig4_outfile,
    width = fig4_width,
    height = fig4_height)
grid.draw(fig4_grob)
dev.off()

grid.newpage()
grid.draw(fig4_grob)
```


## Figure layout new

```{r}
fig4_layout <- rbind(c(NA,  1,  1,  1,  1,  1,  1,  1,  1,  1, NA),
                     c( 2, NA,  3,  3,  3, NA,  4,  4,  4, NA,  5),
                     c( 2,  6,  7,  8,  9, 10, 11, 12, 13, 14,  5),
                     c( 2, NA, NA, 15, NA, NA, 16, NA, 17, NA,  5),
                     c( 2, NA, NA, 18, NA, NA, NA, NA, NA, NA,  5),
                     c( 2, 19, 19, 19, 19, 19, 19, 19, 19, 19,  5),
                     c( 2, NA, 20, 20, 20, NA, 21, 21, 21, NA,  5),
                     c( 2, 22, 23, 24, 24, 25, 26, NA, 27, NA,  5),
                     c( 2, NA, NA, 28, 28, NA, 29, NA, 30, NA,  5),
                     c( 2, NA, NA, 31, 31, NA, 29, NA, 30, NA,  5),
                     c( 2, NA, NA, 32, 32, NA, 33, 33, 33, NA,  5),
                     c( 2, 34, 34, 34, 34, 34, 34, 34, 34, 34,  5),
                     c(NA, 35, 35, 35, 35, 35, 35, 35, 35, 35, NA),
                     c(NA, 36, 36, 36, 36, 36, 36, 36, 36, 36, NA))
fig4_widths <- c(0.1, 0.3, 0.3, 1.9, 0.8, 0.1, 2.1, 0.1, 2.1, 0.6, 0.1)
fig4_widths_in <- unit(fig4_widths, "inch")

fig4_heights <- c(0.1, 0.3, 2.5, 0.3, 0.3, 0.1, 0.3, 2.1, 0.2, 0.2, 0.4, 0.1, 2.4, 0.1)
fig4_heights_in <- unit(fig4_heights, "inch")

fig4_plots_grob <- arrangeGrob(zeroGrob(), #1
                               zeroGrob(), #2
                               fig4_heatmap_title_grob, #3
                               fig4_ss_title_grob, #4
                               zeroGrob(), #5
                               fig4_heatmap_rowtitle_grob, #6
                               fig4_heatmap_rownames_grob, #7
                               fig4_heatmap_matrix_grob, #8
                               fig4_heatmap_legend_grob, #9
                               zeroGrob(), #10
                               fig4_ss_1_base_grob, #11
                               zeroGrob(), #12
                               fig4_ss_2_base_grob, #13
                               fig4_ss_2_legend_grob, #14
                               fig4_heatmap_colnames_grob, #15
                               fig4_ss_1_labels_grob, #16
                               fig4_ss_2_labels_grob, #17
                               fig4_heatmap_coltitle_grob, #18
                               zeroGrob(), #19
                               fig4_density_title_grob, #20
                               fig4_radar_title_grob, #21
                               fig4_density_ytitle_grob, #22
                               fig4_density_ytext_grob, #23
                               fig4_density_panel_grob, #24
                               zeroGrob(), #25
                               fig4_radar_1_panel_grob, #26
                               fig4_radar_2_panel_grob, #27
                               fig4_density_xtext_grob, #28
                               fig4_radar_1_annotation_grob, #29
                               fig4_radar_2_annotation_grob, #30
                               fig4_density_xtitle_grob, #31
                               fig4_density_legend_grob, #32
                               fig4_radar_legend_grob, #33
                               zeroGrob(), #34
                               fig4_cluster_dx_grob, #35
                               zeroGrob(), #36
                               layout_matrix = fig4_layout,
                               widths = fig4_widths_in,
                               heights = fig4_heights_in)


fig4_border_grob <- rectGrob(gp = gpar(fill = NA))

fig4_grob <- gTree(children = gList(fig4_plots_grob,
                                    fig4_border_grob))

fig4_width <- 8.5
fig4_height <- 9.5

fig4_outfile <- "fig.pdf"
pdf(file = fig4_outfile,
    width = fig4_width,
    height = fig4_height)
grid.draw(fig4_grob)
dev.off()

grid.newpage()
grid.draw(fig4_grob)
```


