---
title: "Human and mouse cluster similarity permutation analysis"
author: "Antoine Beauchamp"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(patchwork))
```

```{r functions}
source("../../src/utils.R")
# source("../../src/processing.R")
# source("../../src/analysis.R")
# source("../../src/tree_tools.R")
```

```{r directories}
#Output directory
output_dir <- "outputs"

#Similarity pipeline
version <- "v2"
pipeline_dir <- "../../data/cross_species/"
pipeline_dir <- file.path(pipeline_dir, version)

#Human parameters
human_resolution <- 0.8
human_es_method <- "normative-growth"
human_es_df <- 3
human_cluster_map_method <- "mean"

#Mouse parameters
mouse_resolution <- 0.2
mouse_cluster_map_method <- human_cluster_map_method

#Similarity parameters
metric <- "correlation"

metadata <- file.path(pipeline_dir, "metadata.csv")
params <- fetch_params_metadata(metadata = metadata,
                                human_resolution = human_resolution,
                                human_es_method = human_es_method,
                                human_es_df = human_es_df,
                                human_cluster_map_method = human_cluster_map_method,
                                metric = metric)
params
```
```{r}
#Parameter set ID
params_id <- 405

#Human parameter set ID
human_params_id <- params %>% 
  filter(id == params_id) %>% 
  pull(human_id)

#Mouse parameter set ID
mouse_params_id <- params %>% 
  filter(id == params_id) %>% 
  pull(mouse_id)

permutation_dir <- file.path(pipeline_dir, params_id, "permutations", "similarity")
permutation_files <- list.files(permutation_dir, full.names = TRUE)

permutation_ids <- permutation_files %>% 
  basename() %>% 
  str_extract("[0-9]+") %>% 
  as.numeric() %>% 
  unique() %>% 
  sort()
```

```{r}
# jacobians <- c("absolute", "relative")
jacobians <- "relative"

np <- length(permutation_ids)

list_permutations <- vector(mode = "list", length = length(jacobians))
names(list_permutations) <- jacobians
for (j in jacobians) {
  
  df_sim <- tibble()
  for (p in 1:np) {
    
    infile <- permutation_files %>% 
      str_subset(str_c("permutation_", permutation_ids[p], "_", j))
    
    df_sim_tmp <- infile %>% 
      read_csv(show_col_types = FALSE) %>% 
      mutate(human_nk = human_img %>% basename() %>% str_extract("_nk_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric(),
             human_k = human_img %>% basename() %>% str_extract("_k_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric(),
             mouse_nk = mouse_img %>% basename() %>% str_extract("_nk_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric(),
             mouse_k = mouse_img %>% basename() %>% str_extract("_k_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric()) %>% 
      unite(col = "human_cluster_id", human_nk, human_k, sep = "-", remove = FALSE) %>% 
      unite(col = "mouse_cluster_id", mouse_nk, mouse_k, sep = "-", remove = FALSE) %>% 
      mutate(permutation = permutation_ids[p]) 
    
    df_sim <- bind_rows(df_sim, df_sim_tmp)
  }
  
  df_sim <- df_sim %>% 
    mutate(jacobians = j)
  
  list_permutations[[j]] <- df_sim
  
}

df_permutations <- reduce(.x = list_permutations, .f = bind_rows)
```


```{r fig.width = 10, fig.height = 5}
ggplot(df_permutations, 
       aes(x = similarity,
           y = ..density..)) + 
  geom_histogram(fill = "grey70",
                 col = "black",
                 binwidth = 0.02) + 
  facet_grid(~jacobians) + 
  coord_cartesian(xlim = c(0, 1)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) + 
  labs(title = "Null distribution of mouse-human cluster correlations",
       x = "Correlation",
       y = "Density") + 
  theme_bw()
```

```{r fig.width = 10, fig.height = 5}
ggplot(df_permutations, 
       aes(x = similarity,
           y = ..density..,
           fill = jacobians,
           col = jacobians)) + 
  geom_density(alpha = 0.3,
               bw = 0.05) +
  coord_cartesian(xlim = c(0, 1)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) + 
  labs(title = "Null distribution of mouse-human cluster correlations",
       x = "Correlation",
       y = "Density",
       fill = "Jacobians",
       col = "Jacobians") + 
  theme_bw()
```

```{r}
similarity_dir <- file.path(pipeline_dir, params_id, "similarity")
similarity_files <- list.files(similarity_dir, full.names = TRUE)

similarity <- vector(mode = "list", length = length(jacobians))
names(similarity) <- jacobians
for (j in jacobians) {
  similarity[[j]] <- similarity_files %>% 
    str_subset(j) %>% 
    read_csv(show_col_types = FALSE) %>% 
    mutate(human_nk = human_img %>% basename() %>% str_extract("_nk_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric(),
           human_k = human_img %>% basename() %>% str_extract("_k_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric(),
           mouse_nk = mouse_img %>% basename() %>% str_extract("_nk_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric(),
           mouse_k = mouse_img %>% basename() %>% str_extract("_k_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric()) %>% 
    unite(col = "human_cluster_id", human_nk, human_k, sep = "-", remove = FALSE) %>% 
    unite(col = "mouse_cluster_id", mouse_nk, mouse_k, sep = "-", remove = FALSE)
}
```

```{r}
df_similarity <- similarity[["relative"]]
```

```{r}
human_nk_max <- max(df_similarity[["human_nk"]])
mouse_nk_max <- max(df_similarity[["mouse_nk"]])

df_sim_pvals <- tibble()
for (h_nk in 2:human_nk_max) {
  for (m_nk in (h_nk-1):(h_nk+1)){
    
    if ((m_nk > 1) & (m_nk <= mouse_nk_max)) {
      
      df_sim_nk <- df_similarity %>% 
        select(human_cluster_id, human_nk, human_k,
               mouse_cluster_id, mouse_nk, mouse_k,
               similarity) %>% 
        filter(human_nk == h_nk,
               mouse_nk == m_nk) %>% 
        mutate(pval = 0)
      
      sim_perm_nk <- df_permutations %>% 
        filter(human_nk == h_nk,
               mouse_nk == m_nk) %>% 
        pull(similarity) %>% 
        sort()
      
      for (i in 1:nrow(df_sim_nk)) {
        ntail <- sum(sim_perm_nk >= df_sim_nk[[i, "similarity"]])
        df_sim_nk[[i, "pval"]] <- ntail/length(sim_perm_nk)
      }
      
      df_sim_pvals <- bind_rows(df_sim_pvals, df_sim_nk)
      
    }
  }
}

alpha <- 0.05
df_sim_pvals <- df_sim_pvals %>% 
  mutate(significant = ifelse(pval < 0.05, 1, 0))
```

```{r}
df_significant_counts <- df_sim_pvals %>% 
  group_by(human_nk, mouse_nk) %>% 
  summarise(n = sum(significant), 
            .groups = "drop")

ggplot(df_significant_counts, 
       aes(x = factor(human_nk), 
           y = fct_rev(factor(mouse_nk)),
           fill = factor(n))) + 
  geom_tile(col = "grey50") +
  scale_fill_manual(values = brewer.pal(n = 9, name = "OrRd")[c(1, 3, 5, 9)],
                    limits = factor(0:3)) + 
  scale_x_discrete(expand = expansion(mult = 0), position = "top") + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  labs(x = "Human cluster solution (nk)",
       y = "Mouse cluster solution (nk)",
       fill = "Number of significant pairs") + 
  theme_bw() + 
  theme(axis.ticks = element_blank())
```
```{r}
df_similarity_diag <- df_similarity %>% 
  filter(human_nk == mouse_nk)

cluster_lvls <- df_similarity_diag %>% 
  select(human_cluster_id, human_nk, human_k) %>% 
  distinct() %>% 
  arrange(human_nk, human_k) %>% 
  pull(human_cluster_id)

df_similarity_diag <- df_similarity_diag %>% 
  mutate(human_cluster_id = factor(human_cluster_id, levels = cluster_lvls),
         mouse_cluster_id = factor(mouse_cluster_id, levels = cluster_lvls))

#Heatmap colour range
heatmap_range <- c(min(df_similarity_diag[["similarity"]]), max(df_similarity_diag[["similarity"]]))

#Heatmap palette
heatmap_colours <- rev(brewer.pal(n = 7, name = "RdYlBu"))
palette_length <- 255
heatmap_palette <- colorRampPalette(heatmap_colours)(palette_length)

ggplot(df_similarity_diag, 
       aes(x = human_cluster_id, 
           y = fct_rev(mouse_cluster_id),
           fill = similarity)) + 
  geom_tile(col = "grey50") + 
  scale_fill_gradientn(colors = heatmap_palette) + 
  scale_x_discrete(expand = expansion(mult = 0), position = "top") + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  labs(x = "Human clusters",
       y = "Mouse clusters",
       fill = "Similarity") + 
  theme_bw()
```
```{r}
pvals <- c(0.01, 0.05, 0.1)
pvals_log10 <- -log10(pvals)

for (nk in 2:human_nk_max) {
  
  df_similarity_nk <- df_sim_pvals %>% 
    filter(mouse_nk == nk,
           human_nk == nk)  
  
  df_permutations_nk <- df_permutations %>% 
    filter(mouse_nk == nk,
           human_nk == nk)
  
  p_null_dist <- ggplot(df_permutations_nk,
                        aes(x = similarity,
                            y = ..density..)) + 
    geom_histogram(alpha = 1,
                   binwidth = 0.025,
                   fill = "grey90",
                   col = "grey50",
                   size = 0.2) + 
    geom_vline(data = df_similarity_nk,
               mapping = aes(xintercept = similarity,
                             col = similarity),
               linetype = "dotted",
               size = 0.75) +
    coord_cartesian(xlim = c(0, 1)) + 
    scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                       expand = expansion(mult = 0)) +
    scale_y_continuous(expand = expansion(mult = 0)) + 
    scale_color_gradientn(colors = heatmap_palette) + 
    labs(title = "Null distribution of mouse-human cluster correlations",
         x = "Correlation",
         y = "Density",
         color = "Correlation") + 
    theme_bw()
  
  p_pvals <- ggplot(df_similarity_nk,
                    aes(x = similarity,
                        y = -log10(pval))) + 
    geom_line() +
    geom_point(aes(fill = similarity),
               shape = 21,
               size = 2) +
    geom_hline(yintercept = pvals_log10,
               linetype = "dashed") +
    annotate(geom = "text",
             x = 0.01,
             y = pvals_log10+0.15,
             label = str_c("p = ", pvals), hjust = 0,
             size = 2.5) + 
    coord_cartesian(xlim = c(0, 1),
                    ylim = c(0, 3)) +
    scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                       expand = expansion(mult = 0)) + 
    scale_fill_gradientn(colors = heatmap_palette) + 
    labs(title = "Cluster correlation upper-tail probabilities",
         x = "Correlation",
         y = "-log10(p)",
         fill = "Correlation") +
    theme_bw() + 
    theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0))
  
  df_similarity_nk <- df_similarity_nk %>% 
    mutate(label = ifelse(pval <= 0.1, pval, NA),
           label = round(label, 2),
           label = as.character(label))
  
  p_heatmap <- ggplot(df_similarity_nk, 
                      aes(x = factor(human_k),
                          y = fct_rev(factor(mouse_k)),
                          fill = similarity)) +
    geom_tile(col = "grey50") + 
    geom_text(aes(label = label),
              size = 3) + 
    labs(x = "Human clusters",
         y = "Mouse clusters",
         fill = "Correlation",
         title = "Mouse-human cluster correlation matrix",
         caption = "Annotations correspond to tail probabilities") + 
    scale_fill_gradientn(colors = heatmap_palette) + 
    scale_x_discrete(expand = expansion(mult = 0)) + 
    scale_y_discrete(expand = expansion(mult = 0)) + 
    theme_bw()
  
  p_significance <- (((p_null_dist / p_pvals) | plot_spacer() | p_heatmap) + 
                       plot_layout(widths = c(1.5, 0.05, 1),
                                   heights = c(1, 1),
                                   guides = "collect") + 
                       plot_annotation(title = "Statistical significance of relative mouse-human cluster correlations",
                                       tag_levels = "A", tag_suffix = "."))
  
  outfile <- paste0("cluster_significance_nk_", nk, ".pdf")
  pdf(file = outfile,
      width = unit(10, 'inch'),
      height = unit(5.5, 'inch'))
  print(p_significance)
  dev.off()
}
```



```{r}
nk_human <- 8
nk_mouse <- 8

df_similarity_nk <- df_sim_pvals %>% 
  filter(mouse_nk == nk_mouse,
         human_nk == nk_human)  

df_permutations_nk <- df_permutations %>% 
  filter(mouse_nk == nk_mouse,
         human_nk == nk_human)

p_null_dist <- ggplot(df_permutations_nk,
                      aes(x = similarity,
                          y = ..density..)) + 
  geom_histogram(alpha = 1,
                 binwidth = 0.025,
                 fill = "grey90",
                 col = "grey50",
                 size = 0.2) + 
  geom_vline(data = df_similarity_nk,
             mapping = aes(xintercept = similarity,
                           col = similarity),
             linetype = "dotted",
             size = 0.75) +
  coord_cartesian(xlim = c(0, 1)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                     expand = expansion(mult = 0)) +
  scale_y_continuous(expand = expansion(mult = 0)) + 
  scale_color_gradientn(colors = heatmap_palette) + 
  labs(title = "Null distribution of mouse-human cluster correlations",
       x = "Correlation",
       y = "Density",
       color = "Correlation") + 
  theme_bw()

p_null_dist
```


```{r fig.width = 12, fig.height = 6}
pvals <- c(0.01, 0.05, 0.1)
pvals_log10 <- -log10(pvals)
p_pvals <- ggplot(df_similarity_nk,
                  aes(x = similarity,
                      y = -log10(pval))) + 
  geom_line() +
  geom_point(aes(fill = similarity),
             shape = 21,
             size = 2) +
  geom_hline(yintercept = pvals_log10,
             linetype = "dashed") +
  annotate(geom = "text",
           x = 0.01,
           y = pvals_log10+0.15,
           label = str_c("p = ", pvals), hjust = 0,
           size = 2.5) + 
  coord_cartesian(xlim = c(0, 1)) +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                     expand = expansion(mult = 0)) + 
  scale_fill_gradientn(colors = heatmap_palette) + 
  labs(title = "Cluster correlation upper-tail probabilities",
       x = "Correlation",
       y = "-log10(p)",
       fill = "Correlation") +
  theme_bw() + 
  theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0))
p_pvals
```

```{r}
df_similarity_nk <- df_similarity_nk %>% 
  mutate(label = ifelse(pval <= 0.1, pval, NA),
         label = round(label, 2),
         label = as.character(label))

p_heatmap <- ggplot(df_similarity_nk, 
                    aes(x = factor(human_k),
                        y = fct_rev(factor(mouse_k)),
                        fill = similarity)) +
  geom_tile(col = "grey50") + 
  geom_text(aes(label = label),
            size = 3) + 
  labs(x = "Human clusters",
       y = "Mouse clusters",
       fill = "Correlation",
       title = "Mouse-human cluster correlation matrix",
       caption = "Annotations correspond to tail probabilities") + 
  scale_fill_gradientn(colors = heatmap_palette) + 
  scale_x_discrete(expand = expansion(mult = 0)) + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  theme_bw()
p_heatmap
```

```{r fig.width = 12, fig.height = 6}
p_significance <- (((p_null_dist / p_pvals) | plot_spacer() | p_heatmap) + 
                     plot_layout(widths = c(1.5, 0.05, 1),
                                 heights = c(1, 1),
                                 guides = "collect") + 
                     plot_annotation(title = "Statistical significance of relative mouse-human cluster correlations",
                                     tag_levels = "A", tag_suffix = "."))

outfile <- "cluster_significance.pdf"
pdf(file = outfile,
    width = unit(10, 'inch'),
    height = unit(5.5, 'inch'))
print(p_significance)
dev.off()
```

```{r}
df_sim_pvals_all <- df_sim_pvals_all %>% 
  mutate(qval = 0)

nk_range <- 2:10
for (nkm in nk_range) {
  for (nkh in nk_range) {
    ind_human <- str_detect(df_sim_pvals_all[["human_cluster"]], str_c("^", nkh, "-")) 
    ind_mouse <- str_detect(df_sim_pvals_all[["mouse_cluster"]], str_c("^", nkm, "-")) 
    ind_combined <- ind_human & ind_mouse
    pvals <- df_sim_pvals_all[ind_combined, "pval"][[1]]
    qvals <- p.adjust(pvals, method = "fdr")
    df_sim_pvals_all[ind_combined, "qval"] <- qvals
  }
}
```

```{r}
df_qvals <- df_sim_pvals_all %>% 
  mutate(human_nk = as.numeric(str_extract(human_cluster, "[0-9]+")),
         human_nk_label = str_c("H", human_nk),
         mouse_nk = as.numeric(str_extract(mouse_cluster, "[0-9]+")),
         mouse_nk_label = str_c("M", mouse_nk)) %>% 
  unite(col = "meta_id", human_nk_label, mouse_nk_label, sep = "-") %>% 
  select(meta_id, human_nk, mouse_nk, correlation, pval, qval)

qvals <- c(0.01, 0.05, 0.1)
qvals_log10 <- -log10(qvals)
ggplot(df_qvals,
       aes(x = correlation,
           y = -log10(qval),
           group = meta_id)) + 
  geom_line(col = "grey70") +
  geom_point() + 
  # geom_point(aes(fill = correlation),
  #            shape = 21,
  #            size = 2) +
  geom_hline(yintercept = qvals_log10,
             linetype = "dashed") +
  annotate(geom = "text",
           x = 0.01,
           y = qvals_log10+0.15,
           label = str_c("q = ", qvals), hjust = 0,
           size = 2.5) + 
  coord_cartesian(xlim = c(0, 1)) +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                     expand = expansion(mult = 0)) + 
  # scale_fill_gradientn(colors = heatmap_palette) + 
  # labs(title = "Cluster correlation upper-tail probabilities",
  #      x = "Correlation",
  #      y = "-log10(p)",
  #      fill = "Correlation") +
  theme_bw() + 
  theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0))
```

```{r fig.width = 10, fig.height = 5}
df_nk_combinations <- expand_grid(human_nk = nk_range,
                                  mouse_nk = nk_range)
pthresholds <- c(0.05, 0.01)
list_pcounts <- vector(mode = "list", length = length(pthresholds))
for(p in 1:length(pthresholds)) {
  list_pcounts[[p]] <- df_qvals %>% 
    filter(pval <= pthresholds[p]) %>% 
    group_by(human_nk, mouse_nk) %>% 
    count() %>% 
    ungroup() %>% 
    right_join(df_nk_combinations, by = c("human_nk", "mouse_nk")) %>% 
    mutate(n = ifelse(is.na(n), 0, n))
}

list_pplots <- vector(mode = "list", length = length(list_pcounts)) 
for (p in 1:length(pthresholds)) {
  list_pplots[[p]] <- ggplot(list_pcounts[[p]], 
                             aes(x = factor(human_nk),
                                 y = fct_rev(factor(mouse_nk)),
                                 fill = factor(n))) + 
    geom_tile(col = "grey50") +
    scale_fill_manual(values = brewer.pal(n = 9, name = "OrRd")[c(1, 3, 5, 9)],
                      limits = factor(0:3)) + 
    scale_x_discrete(expand = expansion()) + 
    scale_y_discrete(expand = expansion()) + 
    labs(x = "Number of human clusters",
         y = "Number of mouse clusters",
         fill = "n",
         title = str_c("Number of cluster pairs significant at p = ", pthresholds[p])) + 
    theme_bw()
}

p_pplots <- ((list_pplots[[1]] | list_pplots[[2]]) + 
               plot_layout(guides = "collect")) + 
  plot_annotation(title = "Cluster significance without correction")

outfile <- "cluster_significance_n_pvals.pdf"
pdf(file = outfile,
    width = unit(10, 'inch'),
    height = unit(5.5, 'inch'))
print(p_pplots)
dev.off()
```


```{r fig.width = 10, fig.height = 5}
qthresholds <- pthresholds
list_qcounts <- vector(mode = "list", length = length(qthresholds))
for(q in 1:length(qthresholds)) {
  list_qcounts[[q]] <- df_qvals %>% 
    filter(qval <= qthresholds[q]) %>% 
    group_by(human_nk, mouse_nk) %>% 
    count() %>% 
    ungroup() %>% 
    right_join(df_nk_combinations, by = c("human_nk", "mouse_nk")) %>% 
    mutate(n = ifelse(is.na(n), 0, n))
}

list_qplots <- vector(mode = "list", length = length(list_qcounts)) 
for (q in 1:length(qthresholds)) {
  list_qplots[[q]] <- ggplot(list_qcounts[[q]], 
                             aes(x = factor(human_nk),
                                 y = fct_rev(factor(mouse_nk)),
                                 fill = factor(n))) + 
    geom_tile(col = "grey50") +
    scale_fill_manual(values = brewer.pal(n = 9, name = "OrRd")[c(1, 3, 5, 9)],
                      limits = factor(0:3)) + 
    scale_x_discrete(expand = expansion()) + 
    scale_y_discrete(expand = expansion()) + 
    labs(x = "Number of human clusters",
         y = "Number of mouse clusters",
         fill = "n",
         title = str_c("Number of cluster pairs significant at q = ", qthresholds[q])) + 
    theme_bw()
}

p_qplots <- ((list_qplots[[1]] | list_qplots[[2]]) + 
               plot_layout(guides = "collect")) + 
  plot_annotation(title = "Cluster significance after Benjamini-Hochberg correction")

outfile <- "cluster_significance_n.pdf"
pdf(file = outfile,
    width = unit(10, 'inch'),
    height = unit(5.5, 'inch'))
print(p_qplots)
dev.off()
```




