---
title: "Untitled"
author: "Antoine Beauchamp"
date: '2023-02-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(RColorBrewer)
library(patchwork)
```


```{r}
permutation_dir <- "../../data/human/permutation/"
permutation_ids <- list.files(permutation_dir) %>% 
  str_subset("permutation_[0-9]+") %>% 
  str_extract("[0-9]+") %>% 
  as.numeric()

jacobians <- c("absolute", "relative")
jacobians_short <- c("abs", "rel")
signs <- c("positive", "negative")

np <- 190
list_permutations <- vector(mode = "list", length = np)
for (p in 1:np) {
  
  indir <- list.files(permutation_dir, full.names = TRUE) %>% 
    str_subset(str_c("permutation_", p, "$")) %>% 
    file.path("similarity_matrix")
  
  df_sim <- tibble()
  for (j in 1:length(jacobians)) {
    
    infiles <- list.files(indir, full.names = TRUE) %>% 
      str_subset(jacobians_short[j])
    
    for (s in 1:length(signs)) {
      df_sim_tmp <- infiles %>% 
        str_subset(signs[s]) %>% 
        read_csv(show_col_types = FALSE) %>%
        select(human_cluster = cluster_id, contains("6-")) %>% 
        pivot_longer(cols = -human_cluster, 
                     names_to = "mouse_cluster", 
                     values_to = "correlation") %>% 
        mutate(jacobians = jacobians[j],
               sign = signs[s], 
               permutation = p)
      df_sim <- bind_rows(df_sim_tmp, df_sim)
    }
  }
  
  list_permutations[[p]] <- df_sim %>% 
    mutate(correlation = ifelse(is.na(correlation), 0, correlation)) %>% 
    group_by(permutation,
             jacobians,
             human_cluster, 
             mouse_cluster) %>% 
    summarise(correlation = mean(correlation), 
              .groups = "drop")
}

df_permutations <- reduce(.x = list_permutations,
                          .f = bind_rows)
```

```{r fig.width = 10, fig.height = 5}
ggplot(df_permutations, 
       aes(x = correlation,
           y = ..density..)) + 
  geom_histogram(fill = "grey70",
                 col = "black",
                 binwidth = 0.02) + 
  facet_grid(~jacobians) + 
  coord_cartesian(xlim = c(0, 1)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) + 
  labs(title = "Null distribution of mouse-human cluster correlations",
       x = "Correlation",
       y = "Density") + 
  theme_bw()
```

```{r fig.width = 10, fig.height = 5}
ggplot(df_permutations, 
       aes(x = correlation,
           y = ..density..,
           fill = jacobians,
           col = jacobians)) + 
  geom_density(alpha = 0.3,
               bw = 0.05) +
  coord_cartesian(xlim = c(0, 1)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) + 
  labs(title = "Null distribution of mouse-human cluster correlations",
       x = "Correlation",
       y = "Density",
       fill = "Jacobians",
       col = "Jacobians") + 
  theme_bw()
```

```{r}
similarity_dir <- "../../data/similarity_matrix/latent_space_100/"
threshold_method <- "topn"
threshold <- 0.2

similarity_files <- list.files(similarity_dir, full.names = TRUE) %>% 
  str_subset(str_c(threshold_method, threshold, sep = "_")) %>% 
  str_subset(str_flatten(signs, collapse = "|"))

df_sim_true <- tibble()
for (j in 1:length(jacobians)) {
  for (s in 1:length(signs)) {
    
    infile <- similarity_files %>% 
      str_subset(jacobians_short[j]) %>% 
      str_subset(signs[s])
    
    df_sim_true_tmp <- read_csv(infile, show_col_types = FALSE) %>% 
      filter(str_detect(cluster_id, "5-")) %>% 
      select(human_cluster = cluster_id, contains("6-")) %>% 
      pivot_longer(cols = -human_cluster, 
                   names_to = "mouse_cluster", 
                   values_to = "correlation") %>% 
      mutate(jacobians = jacobians[j],
             sign = signs[s])
    
    df_sim_true <- bind_rows(df_sim_true_tmp, df_sim_true)
  }  
}

df_sim_true <- df_sim_true %>% 
  mutate(correlation = ifelse(is.na(correlation), 0, correlation)) %>% 
  group_by(jacobians,
           human_cluster, 
           mouse_cluster) %>% 
  summarise(correlation = mean(correlation), 
            .groups = "drop")
```

```{r}
similarity_dir <- "../../data/similarity_matrix/latent_space_100/"
threshold_method <- "topn"
threshold <- 0.2

similarity_files <- list.files(similarity_dir, full.names = TRUE) %>% 
  str_subset(str_c(threshold_method, threshold, sep = "_")) %>% 
  str_subset(str_flatten(signs, collapse = "|"))

df_sim_all <- tibble()
for (j in 1:length(jacobians)) {
  for (s in 1:length(signs)) {
    
    infile <- similarity_files %>% 
      str_subset(jacobians_short[j]) %>% 
      str_subset(signs[s])
    
    df_sim_all_tmp <- read_csv(infile, show_col_types = FALSE) %>% 
      rename(human_cluster = cluster_id) %>% 
      pivot_longer(cols = -human_cluster, 
                   names_to = "mouse_cluster", 
                   values_to = "correlation") %>% 
      mutate(jacobians = jacobians[j],
             sign = signs[s])
    
    df_sim_all <- bind_rows(df_sim_all_tmp, df_sim_all)
  }  
}

df_sim_all <- df_sim_all %>% 
  mutate(correlation = ifelse(is.na(correlation), 0, correlation)) %>% 
  group_by(jacobians,
           human_cluster, 
           mouse_cluster) %>% 
  summarise(correlation = mean(correlation), 
            .groups = "drop")

df_sim_pvals_all <- df_sim_all %>% 
  filter(jacobians == "relative") %>% 
  mutate(pval = 0)

for (i in 1:nrow(df_sim_pvals_all)) {
  correlation <- df_sim_pvals_all[[i, "correlation"]]
  ntail <- sum(df_permutations_rel[["correlation"]] >= correlation) 
  df_sim_pvals_all[[i, "pval"]] <- ntail/nrow(df_permutations_rel)
}
```



```{r}
nk_human <- 10
nk_mouse <- 3
df_sim_nk <- df_sim_pvals_all %>% 
  filter(str_detect(human_cluster, str_c(nk_human, "-")),
         str_detect(mouse_cluster, str_c(nk_mouse, "-")))

df_permutations_rel <- filter(df_permutations, jacobians == "relative")
```

```{r fig.width = 10, fig.height = 5}
#Heatmap colour range
heatmap_range <- c(min(df_sim_true[["correlation"]]), max(df_sim_true[["correlation"]]))

#Heatmap palette
heatmap_colours <- rev(brewer.pal(n = 7, name = "RdYlBu"))
palette_length <- 255
heatmap_palette <- colorRampPalette(heatmap_colours)(palette_length)

p_null_dist <- ggplot(df_permutations_rel,
                      aes(x = correlation,
                          y = ..density..)) + 
  geom_density(alpha = 0.3,
               bw = 0.05,
               fill = "grey10") +
  geom_vline(data = df_sim_nk,
             mapping = aes(xintercept = correlation,
                           col = correlation),
             linetype = "dotted",
             size = 0.75) +
  coord_cartesian(xlim = c(0, 1),
                  ylim = c(0, 3.5)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                     expand = expansion(mult = 0)) +
  scale_y_continuous(expand = expansion(mult = 0)) + 
  scale_color_gradientn(colors = heatmap_palette) + 
  labs(title = "Null distribution of mouse-human cluster correlations",
       x = "Correlation",
       y = "Density",
       color = "Correlation") + 
  theme_bw()
# theme_gray()

p_null_dist
```

```{r fig.width = 12, fig.height = 6}
pvals <- c(0.01, 0.05, 0.1)
pvals_log10 <- -log10(pvals)
p_pvals <- ggplot(df_sim_nk,
                  aes(x = correlation,
                      y = -log10(pval))) + 
  geom_line() +
  geom_point(aes(fill = correlation),
             shape = 21,
             size = 2) +
  geom_hline(yintercept = pvals_log10,
             linetype = "dashed") +
  annotate(geom = "text",
           x = 0.01,
           y = pvals_log10+0.15,
           label = str_c("p = ", pvals), hjust = 0,
           size = 2.5) + 
  coord_cartesian(xlim = c(0, 1)) +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                     expand = expansion(mult = 0)) + 
  scale_fill_gradientn(colors = heatmap_palette) + 
  labs(title = "Cluster correlation upper-tail probabilities",
       x = "Correlation",
       y = "-log10(p)",
       fill = "Correlation") +
  theme_bw() + 
  theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0))
p_pvals
```

```{r}
p_heatmap <- ggplot(df_sim_nk, 
                    aes(x = human_cluster,
                        y = fct_rev(mouse_cluster),
                        fill = correlation)) +
  geom_tile(col = "grey50") + 
  geom_text(aes(label = round(pval, 3)),
            size = 3) + 
  labs(x = "Human clusters",
       y = "Mouse clusters",
       fill = "Correlation",
       title = "Mouse-human cluster correlation matrix",
       caption = "Annotations correspond to tail probabilities") + 
  scale_fill_gradientn(colors = heatmap_palette) + 
  scale_x_discrete(expand = expansion(mult = 0)) + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  theme_bw()
p_heatmap
```

```{r fig.width = 12, fig.height = 6}
p_significance <- (((p_null_dist / p_pvals) | plot_spacer() | p_heatmap) + 
                     plot_layout(widths = c(1.5, 0.05, 1),
                                 heights = c(1, 1),
                                 guides = "collect") + 
                     plot_annotation(title = "Statistical significance of relative mouse-human cluster correlations",
                                     tag_levels = "A", tag_suffix = "."))

outfile <- "cluster_significance.pdf"
pdf(file = outfile,
    width = unit(10, 'inch'),
    height = unit(5.5, 'inch'))
print(p_significance)
dev.off()
```

```{r}
df_sim_pvals_all <- df_sim_pvals_all %>% 
  mutate(qval = 0)

nk_range <- 2:10
for (nkm in nk_range) {
  for (nkh in nk_range) {
    ind_human <- str_detect(df_sim_pvals_all[["human_cluster"]], str_c("^", nkh, "-")) 
    ind_mouse <- str_detect(df_sim_pvals_all[["mouse_cluster"]], str_c("^", nkm, "-")) 
    ind_combined <- ind_human & ind_mouse
    pvals <- df_sim_pvals_all[ind_combined, "pval"][[1]]
    qvals <- p.adjust(pvals, method = "fdr")
    df_sim_pvals_all[ind_combined, "qval"] <- qvals
  }
}
```

```{r}
df_qvals <- df_sim_pvals_all %>% 
  mutate(human_nk = as.numeric(str_extract(human_cluster, "[0-9]+")),
         human_nk_label = str_c("H", human_nk),
         mouse_nk = as.numeric(str_extract(mouse_cluster, "[0-9]+")),
         mouse_nk_label = str_c("M", mouse_nk)) %>% 
  unite(col = "meta_id", human_nk_label, mouse_nk_label, sep = "-") %>% 
  select(meta_id, human_nk, mouse_nk, correlation, pval, qval)

qvals <- c(0.01, 0.05, 0.1)
qvals_log10 <- -log10(qvals)
ggplot(df_qvals,
       aes(x = correlation,
           y = -log10(qval),
           group = meta_id)) + 
  geom_line(col = "grey70") +
  geom_point() + 
  # geom_point(aes(fill = correlation),
  #            shape = 21,
  #            size = 2) +
  geom_hline(yintercept = qvals_log10,
             linetype = "dashed") +
  annotate(geom = "text",
           x = 0.01,
           y = qvals_log10+0.15,
           label = str_c("q = ", qvals), hjust = 0,
           size = 2.5) + 
  coord_cartesian(xlim = c(0, 1)) +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                     expand = expansion(mult = 0)) + 
  # scale_fill_gradientn(colors = heatmap_palette) + 
  # labs(title = "Cluster correlation upper-tail probabilities",
  #      x = "Correlation",
  #      y = "-log10(p)",
  #      fill = "Correlation") +
  theme_bw() + 
  theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0))
```

```{r fig.width = 10, fig.height = 5}
df_nk_combinations <- expand_grid(human_nk = nk_range,
                                  mouse_nk = nk_range)
pthresholds <- c(0.05, 0.01)
list_pcounts <- vector(mode = "list", length = length(pthresholds))
for(p in 1:length(pthresholds)) {
  list_pcounts[[p]] <- df_qvals %>% 
    filter(pval <= pthresholds[p]) %>% 
    group_by(human_nk, mouse_nk) %>% 
    count() %>% 
    ungroup() %>% 
    right_join(df_nk_combinations, by = c("human_nk", "mouse_nk")) %>% 
    mutate(n = ifelse(is.na(n), 0, n))
}

list_pplots <- vector(mode = "list", length = length(list_pcounts)) 
for (p in 1:length(pthresholds)) {
  list_pplots[[p]] <- ggplot(list_pcounts[[p]], 
                             aes(x = factor(human_nk),
                                 y = fct_rev(factor(mouse_nk)),
                                 fill = factor(n))) + 
    geom_tile(col = "grey50") +
    scale_fill_manual(values = brewer.pal(n = 9, name = "OrRd")[c(1, 3, 5, 9)],
                      limits = factor(0:3)) + 
    scale_x_discrete(expand = expansion()) + 
    scale_y_discrete(expand = expansion()) + 
    labs(x = "Number of human clusters",
         y = "Number of mouse clusters",
         fill = "n",
         title = str_c("Number of cluster pairs significant at p = ", pthresholds[p])) + 
    theme_bw()
}

p_pplots <- ((list_pplots[[1]] | list_pplots[[2]]) + 
               plot_layout(guides = "collect")) + 
  plot_annotation(title = "Cluster significance without correction")

outfile <- "cluster_significance_n_pvals.pdf"
pdf(file = outfile,
    width = unit(10, 'inch'),
    height = unit(5.5, 'inch'))
print(p_pplots)
dev.off()
```


```{r fig.width = 10, fig.height = 5}
qthresholds <- pthresholds
list_qcounts <- vector(mode = "list", length = length(qthresholds))
for(q in 1:length(qthresholds)) {
  list_qcounts[[q]] <- df_qvals %>% 
    filter(qval <= qthresholds[q]) %>% 
    group_by(human_nk, mouse_nk) %>% 
    count() %>% 
    ungroup() %>% 
    right_join(df_nk_combinations, by = c("human_nk", "mouse_nk")) %>% 
    mutate(n = ifelse(is.na(n), 0, n))
}

list_qplots <- vector(mode = "list", length = length(list_qcounts)) 
for (q in 1:length(qthresholds)) {
  list_qplots[[q]] <- ggplot(list_qcounts[[q]], 
                             aes(x = factor(human_nk),
                                 y = fct_rev(factor(mouse_nk)),
                                 fill = factor(n))) + 
    geom_tile(col = "grey50") +
    scale_fill_manual(values = brewer.pal(n = 9, name = "OrRd")[c(1, 3, 5, 9)],
                      limits = factor(0:3)) + 
    scale_x_discrete(expand = expansion()) + 
    scale_y_discrete(expand = expansion()) + 
    labs(x = "Number of human clusters",
         y = "Number of mouse clusters",
         fill = "n",
         title = str_c("Number of cluster pairs significant at q = ", qthresholds[q])) + 
    theme_bw()
}

p_qplots <- ((list_qplots[[1]] | list_qplots[[2]]) + 
               plot_layout(guides = "collect")) + 
  plot_annotation(title = "Cluster significance after Benjamini-Hochberg correction")

outfile <- "cluster_significance_n.pdf"
pdf(file = outfile,
    width = unit(10, 'inch'),
    height = unit(5.5, 'inch'))
print(p_qplots)
dev.off()
```




