---
title: "Human and mouse cluster similarity permutation analysis"
author: "Antoine Beauchamp"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(ggalluvial))
suppressPackageStartupMessages(library(viridis))
suppressPackageStartupMessages(library(viridisLite))
```

```{r environment}
SRCPATH <- Sys.getenv("SRCPATH")
PROJECTPATH <- Sys.getenv("PROJECTPATH")
```

```{r functions}
source(file.path(SRCPATH, "utils.R"))
# source(file.path(SRCPATH, "processing.R"))
# source(file.path(SRCPATH, "analysis.R"))
# source(file.path(SRCPATH, "tree_tools.R"))
```

```{r directories}
# Output directory
output_dir <- "outputs/cluster_permutations/"

# Similarity pipeline
version <- "v3"
pipeline_dir <- file.path(PROJECTPATH, "data/cross_species/")
pipeline_dir <- file.path(pipeline_dir, version)

# input_1_id <- "700"
# input_1_species <- "human"
# input_2_id <- "107"
# input_2_species <- "mouse"
# id <- 375
# id <- 861
id <- 779

# Identify matching parameter sets
metadata <- file.path(pipeline_dir, "metadata.csv")
params <- fetch_params_metadata(metadata = metadata, id = id)
params
```

```{r parameters}
# Parameter set ID
params_id <- id

# Human parameter set ID
# human_params_id <- params %>% 
# filter(id == params_id) %>% 
# pull(human_id)

# Mouse parameter set ID
# mouse_params_id <- params %>% 
# filter(id == params_id) %>% 
# pull(mouse_id)

# Path to similarity directory
similarity_dir <- file.path(pipeline_dir, params_id, "similarity")
similarity_file <- file.path(similarity_dir, "similarity.csv")

# Permutation directory and files
permutation_dir <- file.path(pipeline_dir, params_id, "permutations", "similarity")
permutation_files <- list.files(permutation_dir, full.names = TRUE)

# Permutation IDs
permutation_ids <- permutation_files %>% 
  basename() %>% 
  str_extract("[0-9]+") %>% 
  as.numeric() %>% 
  unique() %>% 
  sort()

# Output directory
output_dir <- file.path(output_dir, version, params_id)
if (!(dir.exists(output_dir))) {dir.create(output_dir, recursive = TRUE)}
```

```{r}
# Import the similarity data and extract cluster information
similarity <- read_csv(similarity_file, show_col_types = FALSE) %>% 
  mutate(img1_nk = img1 %>% 
           basename() %>% 
           str_extract("_nk_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img1_k = img1 %>% 
           basename() %>% 
           str_extract("_k_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img1_jacobians = img1 %>% 
           str_extract("absolute|relative"),
         img2_nk = img2 %>% 
           basename() %>% 
           str_extract("_nk_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img2_k = img2 %>% 
           basename() %>% 
           str_extract("_k_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img2_jacobians = img2 %>% 
           str_extract("absolute|relative"),) %>% 
  unite(col = "img1_cluster_id", img1_nk, img1_k, 
        sep = "-", remove = FALSE) %>% 
  unite(col = "img2_cluster_id", img2_nk, img2_k, 
        sep = "-", remove = FALSE)

# Filter similarity data for desired cluster numbers
# and combine Jacobians
df_similarity <- similarity %>%
  group_by(img1_nk, img2_nk, img1_k, img2_k, img1_cluster_id, img2_cluster_id) %>% 
  summarise(similarity = mean(similarity),
            .groups = "drop")
```


```{r fig4-PONDSK-MICe-heatmap}
# Number of permutations
np <- length(permutation_files)
list_permutations <- vector(mode = "list", length = np)  
for (p in permutation_ids) {
  
  # Permutation data to import
  permutation_file <- permutation_files %>% 
    str_subset(str_c("similarity_permutation_", p, ".csv"))
  
  # Import permutation data
  list_permutations[[p]] <- read_csv(permutation_file, 
                                     show_col_types = FALSE) %>% 
    mutate(img1_nk = img1 %>% 
             basename() %>% 
             str_extract("_nk_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img1_k = img1 %>% 
             basename() %>% 
             str_extract("_k_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img2_nk = img2 %>% 
             basename() %>% 
             str_extract("_nk_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img2_k = img2 %>% 
             basename() %>% 
             str_extract("_k_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric()) %>% 
    unite(col = "img1_cluster_id", img1_nk, img1_k, 
          sep = "-", remove = FALSE) %>% 
    unite(col = "img2_cluster_id", img2_nk, img2_k, 
          sep = "-", remove = FALSE) %>% 
    mutate(permutation = p)
  
}

# Filter permutations data for desired cluster numbers
# and combine Jacobians
df_permutations <- list_permutations %>% 
  bind_rows() %>% 
  group_by(permutation, img1_nk, img2_nk, img1_k, img2_k, img1_cluster_id, img2_cluster_id) %>% 
  summarise(similarity = mean(similarity), .groups = "drop")
```


```{r compute-pvals}
if (params_id == 375) {
  labs <- c("POND-SickKids", "MICe")
} else if (params_id == 861) {
  labs <- c("HBN", "MICe")
} else if (params_id == 799) {
  labs <- c("POND-SickKids", "HBN")
}

similarity_max <- 1.00
similarity_min <- 0.10

heatmap_palette_length <- 255

# Numerical values for the heatmap scale
heatmap_scale_values <- seq(similarity_min, similarity_max, length.out = heatmap_palette_length)
heatmap_scale_values <- (heatmap_scale_values - similarity_min)/(similarity_max - similarity_min)

# Colours for the heatmap palette 
heatmap_scale_colours <- magma(n = heatmap_palette_length, begin = 0.3)

# Heatmap palette vector
heatmap_scale_palette <- colorRampPalette(heatmap_scale_colours)(heatmap_palette_length)

# Mouse and human max nk
nk_max_1 <- max(df_similarity[["img1_nk"]])
nk_max_2 <- max(df_similarity[["img2_nk"]])

# Iterate along nk diagonal +/- 1
df_sim_pvals <- tibble()
for (nk_1 in 2:nk_max_1) {
  for (nk_2 in (nk_1-1):(nk_1+1)){
    
    if ((nk_2 > 1) & (nk_2 <= nk_max_2)) {
      
      df_sim_nk <- df_similarity %>% 
        select(img1_cluster_id, img1_nk, img1_k,
               img2_cluster_id, img2_nk, img2_k,
               similarity) %>% 
        filter(img1_nk == nk_1,
               img2_nk == nk_2) %>% 
        mutate(pval = 0)
      
      sim_perm_nk <- df_permutations %>% 
        filter(img1_nk == nk_1,
               img2_nk == nk_2) %>% 
        pull(similarity) %>% 
        sort()
      
      for (i in 1:nrow(df_sim_nk)) {
        ntail <- sum(sim_perm_nk >= df_sim_nk[[i, "similarity"]])
        df_sim_nk[[i, "pval"]] <- ntail/length(sim_perm_nk)
      }
      
      df_sim_nk <- df_sim_nk %>%
        mutate(significant = ifelse(pval <= 0.10, TRUE, FALSE),
               pval_lab = case_when(pval > 0.10 ~ "",
                                    pval >= 0.001 & pval <= 0.10 ~ paste0("p = ", as.character(round(pval, 3))),
                                    pval < 0.001 ~ "p < 0.001"),
               cor_lab = ifelse(pval_lab == "", "", paste0("r = ", as.character(round(similarity, 3)))),
               stat_lab = ifelse(pval_lab == "", "", paste(pval_lab, cor_lab, sep = "\n")))
      
      # Heatmap plot
      p <- ggplot(df_sim_nk, 
                  aes(x = img2_cluster_id, 
                      y = fct_rev(img1_cluster_id), 
                      fill = similarity)) + 
        geom_tile(col = "grey50") + 
        geom_text(mapping = aes(label = stat_lab),
                  size = 2.2, 
                  hjust = "center", 
                  vjust = "center") + 
        labs(x = labs[2],
             y = labs[1],
             fill = "Correlation") + 
        scale_fill_gradientn(colors = heatmap_scale_palette,
                             values = heatmap_scale_values,
                             limits = c(similarity_min, similarity_max),
                             breaks = seq(0, 1, by = 0.2)) + 
        scale_x_discrete(expand = expansion(mult = 0), position = "top") + 
        scale_y_discrete(expand = expansion(mult = 0)) + 
        theme_bw()
      
      # Export
      outfile <- paste("cluster_similarity", nk_1, nk_2, sep = "_")
      outfile <- paste0(outfile, ".pdf")
      outfile <- file.path(output_dir, outfile)
      pdf(file = outfile,
          width = unit(500/72, "in"),
          height = unit(500/72, "in"))
      print(p)
      dev.off()
      
      df_sim_pvals <- bind_rows(df_sim_pvals, df_sim_nk)
      
    }
  }
}

```




```{r}
knitr::opts_chunk$set(eval = FALSE)
```


```{r plot-num-significant}
# Count number of significant matches per nk pairs
df_significant_counts <- df_sim_pvals %>% 
  group_by(human_nk, mouse_nk) %>% 
  summarise(n = sum(significant), 
            .groups = "drop")

p_significant_counts <- ggplot(df_significant_counts, 
                               aes(x = factor(human_nk), 
                                   y = fct_rev(factor(mouse_nk)),
                                   fill = factor(n))) + 
  geom_tile(col = "grey50") +
  scale_fill_manual(values = brewer.pal(n = 9, name = "OrRd")[c(1, 3, 5, 9)],
                    limits = factor(1:4)) + 
  scale_x_discrete(expand = expansion(mult = 0), position = "top") + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  labs(x = "Human cluster solution (nk)",
       y = "Mouse cluster solution (nk)",
       fill = "Number of significant pairs") + 
  theme_bw() + 
  theme(axis.ticks = element_blank())

outfile <- paste0("significant_cluster_pairs.pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(8, "in"))
print(p_significant_counts)
dev.off()
```

```{r plot-diag-matrices}
# Filter for diagonal nk
df_similarity_diag <- df_similarity %>% 
  filter(human_nk == mouse_nk)

# Cluster ID levels
cluster_lvls <- df_similarity_diag %>% 
  select(human_cluster_id, human_nk, human_k) %>% 
  distinct() %>% 
  arrange(human_nk, human_k) %>% 
  pull(human_cluster_id)

# Convert cluster IDs to factor
df_similarity_diag <- df_similarity_diag %>% 
  mutate(human_cluster_id = factor(human_cluster_id, levels = cluster_lvls),
         mouse_cluster_id = factor(mouse_cluster_id, levels = cluster_lvls))

# Heatmap colour range
heatmap_range <- c(min(df_similarity_diag[["similarity"]]), 
                   max(df_similarity_diag[["similarity"]]))

# Heatmap palette
heatmap_colours <- rev(brewer.pal(n = 7, name = "RdYlBu"))
palette_length <- 255
heatmap_palette <- colorRampPalette(heatmap_colours)(palette_length)

p_diag_matrices <- ggplot(df_similarity_diag, 
                          aes(x = human_cluster_id, 
                              y = fct_rev(mouse_cluster_id),
                              fill = similarity)) + 
  geom_tile(col = "grey50") + 
  scale_fill_gradientn(colors = heatmap_palette) + 
  scale_x_discrete(expand = expansion(mult = 0), position = "top") + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  labs(x = "Human clusters",
       y = "Mouse clusters",
       fill = "Similarity") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 270))

outfile <- paste0("similarity_matrices_diagonal.pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(8, "in"))
print(p_diag_matrices)
dev.off()
```

```{r plot-pairwise-significance}
# Extract diagonal nk values
df_similarity_diag <- df_similarity %>% 
  filter(human_nk == mouse_nk)

# Cluster lvls
cluster_lvls <- df_similarity_diag %>% 
  select(human_cluster_id, human_nk, human_k) %>% 
  distinct() %>% 
  arrange(human_nk, human_k) %>% 
  pull(human_cluster_id)

# Convert cluster IDs to factor
df_similarity_diag <- df_similarity_diag %>% 
  mutate(human_cluster_id = factor(human_cluster_id, levels = cluster_lvls),
         mouse_cluster_id = factor(mouse_cluster_id, levels = cluster_lvls))

#Heatmap colour range
heatmap_range <- c(min(df_similarity_diag[["similarity"]]), 
                   max(df_similarity_diag[["similarity"]]))

#Heatmap palette
heatmap_colours <- rev(brewer.pal(n = 7, name = "RdYlBu"))
palette_length <- 255
heatmap_palette <- colorRampPalette(heatmap_colours)(palette_length)

# p-value markers
pvals <- c(0.01, 0.05, 0.1)
pvals_log10 <- -log10(pvals)

# Iterate over cluster solutions
for (nk_1 in 2:nk_max_1) {
  
  # Filter true values for human nk
  df_similarity_nk_tmp <- df_sim_pvals %>% 
    filter(human_nk == nk_1)  
  
  # Filter permutations for human nk
  df_permutations_nk_tmp <- df_permutations %>% 
    filter(human_nk == nk_1)
  
  m_nk_range <- unique(df_similarity_nk_tmp[["mouse_nk"]])
  for (m_nk in m_nk_range) {
    
    # Filter true values for mouse nk    
    df_similarity_nk <- df_similarity_nk_tmp %>% 
      filter(mouse_nk == m_nk)
    
    # Filter permutations for mouse nk
    df_permutations_nk <- df_permutations_nk_tmp %>% 
      filter(mouse_nk == m_nk)
    
    # Plot of null distribution for nk solution
    p_null_dist <- ggplot(df_permutations_nk,
                          aes(x = similarity,
                              y = ..density..)) + 
      geom_histogram(alpha = 1,
                     binwidth = 0.025,
                     fill = "grey90",
                     col = "grey50",
                     size = 0.2) + 
      geom_vline(data = df_similarity_nk,
                 mapping = aes(xintercept = similarity,
                               col = similarity),
                 linetype = "dotted",
                 size = 0.75) +
      coord_cartesian(xlim = c(0, 1)) + 
      scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                         expand = expansion(mult = 0)) +
      scale_y_continuous(expand = expansion(mult = 0)) + 
      scale_color_gradientn(colors = heatmap_palette) + 
      labs(title = "Null distribution of mouse-human cluster correlations",
           x = "Correlation",
           y = "Density",
           color = "Correlation") + 
      theme_bw()
    
    # Plot of p-values for nk solution
    p_pvals <- ggplot(df_similarity_nk,
                      aes(x = similarity,
                          y = -log10(pval))) + 
      geom_line() +
      geom_point(aes(fill = similarity),
                 shape = 21,
                 size = 2) +
      geom_hline(yintercept = pvals_log10,
                 linetype = "dashed") +
      annotate(geom = "text",
               x = 0.01,
               y = pvals_log10+0.15,
               label = str_c("p = ", pvals), hjust = 0,
               size = 2.5) + 
      coord_cartesian(xlim = c(0, 1),
                      ylim = c(0, 3)) +
      scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                         expand = expansion(mult = 0)) + 
      scale_fill_gradientn(colors = heatmap_palette) + 
      labs(title = "Cluster correlation upper-tail probabilities",
           x = "Correlation",
           y = "-log10(p)",
           fill = "Correlation") +
      theme_bw() + 
      theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0))
    
    # Create labels based on p-values
    df_similarity_nk <- df_similarity_nk %>% 
      mutate(label = ifelse(pval <= 0.1, pval, NA),
             label = round(label, 2),
             label = as.character(label))
    
    # Plot of similarity matrix for nk solution
    p_heatmap <- ggplot(df_similarity_nk, 
                        aes(x = factor(human_k),
                            y = fct_rev(factor(mouse_k)),
                            fill = similarity)) +
      geom_tile(col = "grey50") + 
      geom_text(aes(label = label),
                size = 3) + 
      labs(x = "Human clusters",
           y = "Mouse clusters",
           fill = "Correlation",
           title = "Mouse-human cluster correlation matrix",
           caption = "Annotations correspond to tail probabilities") + 
      scale_fill_gradientn(colors = heatmap_palette) + 
      scale_x_discrete(expand = expansion(mult = 0)) + 
      scale_y_discrete(expand = expansion(mult = 0)) + 
      theme_bw()
    
    # Combine plots into one
    p_significance <- (((p_null_dist / p_pvals) | plot_spacer() | p_heatmap) + 
                         plot_layout(widths = c(1.5, 0.05, 1),
                                     heights = c(1, 1),
                                     guides = "collect") + 
                         plot_annotation(title = "Statistical significance of relative mouse-human cluster correlations",
                                         tag_levels = "A", tag_suffix = "."))
    
    outfile <- paste0("cluster_significance_H", nk_1, "_M", m_nk, ".pdf")
    outfile <- file.path(output_dir, outfile)
    pdf(file = outfile,
        width = unit(10, 'inch'),
        height = unit(5.5, 'inch'))
    print(p_significance)
    dev.off()
    
  }
}
```

```{r plot-human-sankey-sig}
# Human pipeline directory
human_param_id <- params[["human_id"]]
human_pipeline_dir <- "../../data/human/derivatives/v2/"
human_pipeline_dir <- file.path(human_pipeline_dir, human_param_id)

# Human cluster directory
human_cluster_resolution <- params[["human_cluster_resolution"]]
human_cluster_resolution <- sprintf("%.1f", human_cluster_resolution)
human_cluster_dir <- file.path(human_pipeline_dir, "clusters", str_c("resolution_", human_cluster_resolution))

# Human clusters
human_cluster_file <- file.path(human_cluster_dir, "clusters.csv")
df_human_clusters <- read_csv(human_cluster_file, show_col_types = FALSE)

# Convert clusters to long form
df_human_clusters_long <- df_human_clusters %>% 
  pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         nk = factor(nk),
         k = factor(k))

# Count p-values for nk diagonal
df_sim_pvals_human_diag <- df_sim_pvals %>% 
  filter(human_nk == mouse_nk) %>% 
  select(nk = human_nk,
         k = human_k, 
         significant) %>%
  group_by(nk, k) %>% 
  summarise(significant = sum(significant), 
            .groups = "drop") %>% 
  mutate(nk = factor(nk),
         k = factor(k),
         significant = ifelse(significant > 0, 1, 0))

# Combine significance information with cluster assignment
df_human_clusters_sig <- df_human_clusters_long %>% 
  left_join(df_sim_pvals_human_diag,
            by = c("nk", "k")) %>% 
  mutate(significant = factor(significant))

p_human_sig_sankey <- ggplot(df_human_clusters_sig,
                             aes(x = nk,
                                 stratum = k,
                                 fill = significant,
                                 alluvium = ID)) + 
  geom_flow(stat = "alluvium", aes.flow = "forward") + 
  geom_stratum() + 
  scale_fill_manual(values = c("grey50", brewer.pal(n = 9, name = "OrRd")[9]),
                    limits = factor(0:1), labels = c("No", "Yes")) + 
  labs(x = "Number of clusters",
       y = "Number of patients",
       fill = "Has a significant match",
       title = "Human clusters with significant matches") + 
  theme_bw() + 
  theme(panel.grid.major.x = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal")

outfile <- "human_sankey_significant.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_human_sig_sankey)
dev.off()
```

```{r plot-human-sankey-pvals}
# Compute minimum human p-values for nk diagonal
df_sim_pvals_human_diag <- df_sim_pvals %>% 
  filter(human_nk == mouse_nk) %>% 
  select(nk = human_nk,
         k = human_k, 
         pval) %>% 
  group_by(nk, k) %>% 
  summarise(pval = min(pval), .groups = "drop") %>% 
  mutate(nk = factor(nk),
         k = factor(k),
         pval = -log10(pval),
         pval = ifelse(is.infinite(pval), NA, pval),
         pval = ifelse(is.na(pval), max(pval, na.rm = TRUE), pval),
         pval = ifelse(pval > 3, 3, pval))

# Join human cluster information with p-values
df_human_clusters_pval <- df_human_clusters_long %>% 
  left_join(df_sim_pvals_human_diag,
            by = c("nk", "k")) 

p_human_pval_sankey <- ggplot(df_human_clusters_pval,
                              aes(x = nk,
                                  stratum = k,
                                  fill = pval,
                                  alluvium = ID)) + 
  geom_flow(stat = "alluvium", aes.flow = "forward") + 
  geom_stratum() + 
  scale_fill_gradientn(colors = brewer.pal(n = 9, name = "OrRd")[2:9],
                       limits = c(0.3, 3),
                       breaks = seq(0, 3, by = 0.5)) +
  labs(x = "Number of clusters",
       y = "Number of patients",
       fill = "-log10(p)",
       title = "Human cluster minimal p-values") + 
  theme_bw() + 
  theme(panel.grid.major.x = element_blank())

outfile <- "human_sankey_pvals.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_human_pval_sankey)
dev.off()
```

```{r plot-mouse-sankey-sig}
# Mouse pipeline parameter set ID
mouse_param_id <- params[["mouse_id"]]

# Mouse pipeline directory
mouse_pipeline_dir <- "../../data/mouse/derivatives/v2/"
mouse_pipeline_dir <- file.path(mouse_pipeline_dir, mouse_param_id)

# Mouse cluster directory
mouse_cluster_dir <- file.path(mouse_pipeline_dir, "clusters")

# Import mouse clusters
mouse_cluster_file <- file.path(mouse_cluster_dir, "clusters.csv")
df_mouse_clusters <- read_csv(mouse_cluster_file, show_col_types = FALSE)
colnames(df_mouse_clusters) <- c("ID", str_c("nk", 2:10))

# Convert mouse clusters to long format
df_mouse_clusters_long <- df_mouse_clusters %>% 
  pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         nk = factor(nk),
         k = factor(k))

# Count p-values for nk diagonal
df_sim_pvals_mouse_diag <- df_sim_pvals %>% 
  filter(human_nk == mouse_nk) %>% 
  select(nk = mouse_nk,
         k = mouse_k, 
         significant) %>%
  group_by(nk, k) %>% 
  summarise(significant = sum(significant), 
            .groups = "drop") %>% 
  mutate(nk = factor(nk),
         k = factor(k),
         significant = ifelse(significant > 0, 1, 0))

# Combine clusters with significance information
df_mouse_clusters_sig <- df_mouse_clusters_long %>% 
  left_join(df_sim_pvals_mouse_diag,
            by = c("nk", "k")) %>% 
  mutate(significant = factor(significant))

p_mouse_sig_sankey <- ggplot(df_mouse_clusters_sig,
                             aes(x = nk,
                                 stratum = k,
                                 fill = significant,
                                 alluvium = ID)) + 
  geom_flow(stat = "alluvium", aes.flow = "forward") + 
  geom_stratum() + 
  scale_fill_manual(values = c("grey50", brewer.pal(n = 9, name = "OrRd")[9]),
                    limits = factor(0:1), labels = c("No", "Yes")) + 
  labs(x = "Number of clusters",
       y = "Number of patients",
       fill = "Has a significant match",
       title = "Mouse clusters with significant matches") + 
  theme_bw() + 
  theme(panel.grid.major.x = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal")

outfile <- "mouse_sankey_significant.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_mouse_sig_sankey)
dev.off()
```

```{r plot-mouse-sankey-pvals}
# Compute minimum mouse p-values for nk diagonal
df_sim_pvals_mouse_diag <- df_sim_pvals %>% 
  filter(mouse_nk == human_nk) %>% 
  select(nk = mouse_nk,
         k = mouse_k, 
         pval) %>% 
  group_by(nk, k) %>% 
  summarise(pval = min(pval), .groups = "drop") %>% 
  mutate(nk = factor(nk),
         k = factor(k),
         pval = -log10(pval),
         pval = ifelse(is.infinite(pval), NA, pval),
         pval = ifelse(is.na(pval), max(pval, na.rm = TRUE), pval),
         pval = ifelse(pval > 3, 3, pval),
         pval = ifelse(pval < 0.3, 0.3, pval))

# Combine clusters with p-value information
df_mouse_clusters_pval <- df_mouse_clusters_long %>% 
  left_join(df_sim_pvals_mouse_diag,
            by = c("nk", "k")) 

p_mouse_pval_sankey <- ggplot(df_mouse_clusters_pval,
                              aes(x = nk,
                                  stratum = k,
                                  fill = pval,
                                  alluvium = ID)) + 
  geom_flow(stat = "alluvium", aes.flow = "forward") + 
  geom_stratum() + 
  scale_fill_gradientn(colors = brewer.pal(n = 9, name = "OrRd")[3:9],
                       limits = c(0.3, 3),
                       breaks = seq(0, 3, by = 0.5)) +
  labs(x = "Number of clusters",
       y = "Number of models",
       fill = "-log10(p)",
       title = "Mouse cluster minimal p-values") + 
  theme_bw() + 
  theme(panel.grid.major.x = element_blank())

outfile <- "mouse_sankey_pvals.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_mouse_pval_sankey)
dev.off()
```

# H2-M4 permutations

```{r}
# Permutation directory and files
permutation_dir <- file.path(pipeline_dir, params_id, "permutations", "similarity_H2M4")
permutation_files <- list.files(permutation_dir, full.names = TRUE)

# Permutation IDs
permutation_ids <- permutation_files %>% 
  basename() %>% 
  str_extract("[0-9]+") %>% 
  as.numeric() %>% 
  unique() %>% 
  sort()

```

```{r import-perms-H2M4}
# Jacobians to use
jacobians <- c("absolute", "relative")
#  jacobians <- "relative"

# Number of permutations
np <- length(permutation_ids)

# Iterate over jacobians
list_permutations <- vector(mode = "list", length = length(jacobians))
names(list_permutations) <- jacobians
for (j in jacobians) {
  
  # Iterate over permutations
  df_sim <- tibble()
  for (p in 1:np) {
    
    # Permutation similarity data
    infile <- permutation_files %>% 
      str_subset(str_c("permutation_", permutation_ids[p], "_", j))
    
    # Import permutation similarity data
    df_sim_tmp <- infile %>% 
      read_csv(show_col_types = FALSE) %>% 
      mutate(human_nk = human_img %>% basename() %>% str_extract("_nk_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric(),
             human_k = human_img %>% basename() %>% str_extract("_k_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric(),
             mouse_nk = mouse_img %>% basename() %>% str_extract("_nk_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric(),
             mouse_k = mouse_img %>% basename() %>% str_extract("_k_[0-9]+") %>% str_extract("[0-9]+") %>% as.numeric()) %>% 
      unite(col = "human_cluster_id", human_nk, human_k, sep = "-", remove = FALSE) %>% 
      unite(col = "mouse_cluster_id", mouse_nk, mouse_k, sep = "-", remove = FALSE) %>% 
      mutate(permutation = permutation_ids[p]) 
    
    # Collate permutation data
    df_sim <- bind_rows(df_sim, df_sim_tmp)
  }
  
  # Include jacobians information
  df_sim <- df_sim %>% 
    mutate(jacobians = j)
  
  list_permutations[[j]] <- df_sim
  
}

# Reduce permutations data frames into one
df_permutations <- reduce(.x = list_permutations, .f = bind_rows)

# Average similarity values for both jacobians
df_permutations <- df_permutations %>% 
  group_by(permutation, 
           human_cluster_id, human_nk, human_k, 
           mouse_cluster_id, mouse_nk, mouse_k) %>% 
  summarise(similarity = mean(similarity), .groups = "drop")
```

```{r compute-pvals-H2M4}
nk_1 <- unique(df_permutations[["human_nk"]])
m_nk <- unique(df_permutations[["mouse_nk"]])

df_sim_pvals <- df_similarity %>% 
  select(human_cluster_id, human_nk, human_k,
         mouse_cluster_id, mouse_nk, mouse_k,
         similarity) %>% 
  filter(human_nk == nk_1,
         mouse_nk == m_nk) %>% 
  mutate(pval = 0)

for (i in 1:nrow(df_sim_pvals)) {
  ntail <- sum(sim_perm_nk >= df_sim_pvals[[i, "similarity"]])
  df_sim_pvals[[i, "pval"]] <- ntail/length(sim_perm_nk)
}

# Evaluate significance
alpha <- 0.05
df_sim_pvals <- df_sim_pvals %>% 
  mutate(significant = ifelse(pval < 0.05, 1, 0))
```

```{r plot-significance-H2M4}
# Filter true values for mouse nk    
df_similarity_nk <- df_sim_pvals %>% 
  filter(human_nk == nk_1,
         mouse_nk == m_nk)

# Filter permutations for mouse nk
df_permutations_nk <- df_permutations %>% 
  filter(human_nk == nk_1,
         mouse_nk == m_nk)

# Plot of null distribution for nk solution
p_null_dist <- ggplot(df_permutations_nk,
                      aes(x = similarity,
                          y = ..density..)) + 
  geom_histogram(alpha = 1,
                 binwidth = 0.025,
                 fill = "grey90",
                 col = "grey50",
                 size = 0.2) + 
  geom_vline(data = df_similarity_nk,
             mapping = aes(xintercept = similarity,
                           col = similarity),
             linetype = "dotted",
             size = 0.75) +
  coord_cartesian(xlim = c(0, 1)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                     expand = expansion(mult = 0)) +
  scale_y_continuous(expand = expansion(mult = 0)) + 
  scale_color_gradientn(colors = heatmap_palette) + 
  labs(title = "Null distribution of mouse-human cluster correlations",
       x = "Correlation",
       y = "Density",
       color = "Correlation") + 
  theme_bw()

# Plot of p-values for nk solution
p_pvals <- ggplot(df_similarity_nk,
                  aes(x = similarity,
                      y = -log10(pval))) + 
  geom_line() +
  geom_point(aes(fill = similarity),
             shape = 21,
             size = 2) +
  geom_hline(yintercept = pvals_log10,
             linetype = "dashed") +
  annotate(geom = "text",
           x = 0.01,
           y = pvals_log10+0.15,
           label = str_c("p = ", pvals), hjust = 0,
           size = 2.5) + 
  coord_cartesian(xlim = c(0, 1),
                  ylim = c(0, 3)) +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1),
                     expand = expansion(mult = 0)) + 
  scale_fill_gradientn(colors = heatmap_palette) + 
  labs(title = "Cluster correlation upper-tail probabilities",
       x = "Correlation",
       y = "-log10(p)",
       fill = "Correlation") +
  theme_bw() + 
  theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0))

# Create labels based on p-values
df_similarity_nk <- df_similarity_nk %>% 
  mutate(label = ifelse(pval <= 0.1, pval, NA),
         label = round(label, 2),
         label = as.character(label))

# Plot of similarity matrix for nk solution
p_heatmap <- ggplot(df_similarity_nk, 
                    aes(x = factor(human_k),
                        y = fct_rev(factor(mouse_k)),
                        fill = similarity)) +
  geom_tile(col = "grey50") + 
  geom_text(aes(label = label),
            size = 3) + 
  labs(x = "Human clusters",
       y = "Mouse clusters",
       fill = "Correlation",
       title = "Mouse-human cluster correlation matrix",
       caption = "Annotations correspond to tail probabilities") + 
  scale_fill_gradientn(colors = heatmap_palette) + 
  scale_x_discrete(expand = expansion(mult = 0)) + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  theme_bw()

# Combine plots into one
p_significance <- (((p_null_dist / p_pvals) | plot_spacer() | p_heatmap) + 
                     plot_layout(widths = c(1.5, 0.05, 1),
                                 heights = c(1, 1),
                                 guides = "collect") + 
                     plot_annotation(title = "Statistical significance of relative mouse-human cluster correlations",
                                     tag_levels = "A", tag_suffix = "."))

outfile <- paste0("cluster_significance_H", nk_1, "_M", m_nk, ".pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, 'inch'),
    height = unit(5.5, 'inch'))
print(p_significance)
dev.off()
```


