---
title: "Human and mouse cluster similarity"
author: "Antoine Beauchamp"
date: '`r Sys.Date()`'
output: pdf_document
---

# Description

# Initialization

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(data.tree))
suppressPackageStartupMessages(library(RMINC))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(RColorBrewer))
```

```{r functions}
SRCPATH <- Sys.getenv("SRCPATH")
if (SRCPATH == "") {
  SRCPATH <- "../../src/"
  Sys.setenv(SRCPATH=SRCPATH)
}

source(file.path(SRCPATH, "utils.R"))
source(file.path(SRCPATH, "processing.R"))
source(file.path(SRCPATH, "analysis.R"))
source(file.path(SRCPATH, "tree_tools.R"))
```

```{r parameters}
# Output directory
output_dir <- "outputs/cluster_similarity/"

# Similarity pipeline
version <- "v3"
pipeline_dir <- "../../data/cross_species/"
pipeline_dir <- file.path(pipeline_dir, version)

# Identify matching parameter sets
metadata <- file.path(pipeline_dir, "metadata.csv")
params <- fetch_params_metadata(metadata = metadata)
params
```

```{r directories}
# Parameter set ID
# params_id <- 984 #PONDSK-MICe
# params_id <- 394 #HBN-MICe
params_id <- 278 #PONDSK-HBN

# Extract parameter set
params_subset <- params %>% 
  filter(id == params_id)

# Similarity metric
metric <- params %>% 
  filter(id == params_id) %>% 
  pull(metric)

# Jacobians
jacobians <- c("absolute", "relative")

param_ids <- numeric(2)
species <- character(2)
datasets <- character(2)
resolutions <- numeric(2)
for (i in 1:2) {
  param_ids[i] <- params_subset[[paste("input", i, "id", sep = "_")]]
  species[i] <- params_subset[[paste("input", i, "species", sep = "_")]]
  datasets[i] <- params_subset[[paste("input", i, "dataset", sep = "_")]]
  resolutions[i] <- params_subset[[paste("input", i, "resolution", sep = "_")]]
}

# Pipeline directory
pipeline_dir <- file.path(pipeline_dir, params_id, "similarity")

# Output directory
output_dir <- file.path(output_dir, version, params_id)
if (!(dir.exists(output_dir))) {dir.create(output_dir, recursive = TRUE)}
```

```{r import}
# Import absolute and relative similarity data
similarity_file <- file.path(pipeline_dir, "similarity.csv")
similarity <- read_csv(similarity_file, show_col_types = FALSE)
for (i in 1:2) {
  
  # Get files for input i
  files_i <- similarity[[paste0("img", i)]]
  
  # Get Jacobian IDs
  similarity[[paste("img", i, "jacobians", sep = "_")]] <- str_extract(files_i, "absolute|relative")
  
  # Extract nk values
  similarity[[paste("img", i, "nk", sep = "_")]] <- files_i %>% 
    basename() %>% 
    str_extract("_nk_[0-9]+") %>% 
    str_extract("[0-9]+") %>% 
    as.numeric()
  
  # Extract k values  
  similarity[[paste("img", i, "k", sep = "_")]] <- files_i %>% 
    basename() %>% 
    str_extract("_k_[0-9]+") %>% 
    str_extract("[0-9]+") %>% 
    as.numeric()
  
  # Construct cluster ID
  similarity[[paste("img", i, "cluster_id", sep = "_")]] <- str_c(similarity[[paste("img", i, "nk", sep = "_")]],
                                                                  similarity[[paste("img", i, "k", sep = "_")]], 
                                                                  sep = "-")
  
}
```


# Similarity matrices

```{r similarity-matrices}
# Highest number of clusters
nk_max <- max(c(max(similarity[["img_1_nk"]]), max(similarity[["img_2_nk"]])))
n_off_diag <- 2

# Generate heatmap colour palette
heatmap_colours <- rev(brewer.pal(n = 7, name = "RdYlBu"))
palette_length <- 255
heatmap_palette <- colorRampPalette(heatmap_colours)(palette_length)

# Iterate over cluster solutions
for (nk1 in 2:nk_max) {
  
  # Iterate over off-diagonal terms
  nk2_range <- seq(nk1-n_off_diag, nk1+n_off_diag)
  nk2_range <- nk2_range[nk2_range >= 2 & nk2_range <= nk_max]
  for (nk2 in nk2_range) {
    
    # Filter similarity for given cluster solutions
    similarity_nk <- similarity %>% 
      filter(img_1_nk == nk1,
             img_2_nk == nk2) %>% 
      mutate(img_1_cluster_id = factor(img_1_cluster_id, levels = sort(unique(img_1_cluster_id))),
             img_2_cluster_id = factor(img_2_cluster_id, levels = sort(unique(img_2_cluster_id))))
    
    # Iterate over jacobians
    for (j in jacobians) {
      
      # Filter similarity for specific jacobians
      similarity_nk_j <- similarity_nk %>% 
        filter(img_1_jacobians == j,
               img_2_jacobians == j) %>% 
        select(img_1_cluster_id, img_2_cluster_id, similarity)
      
      # Plot similarity matrix for specific jacobians
      p_sim_j <- ggplot(similarity_nk_j, 
                        aes(x = img_1_cluster_id, 
                            y = fct_rev(img_2_cluster_id), 
                            fill = similarity)) + 
        geom_tile(col = "grey50") + 
        labs(x = paste(datasets[1], "clusters"),
             y = paste(datasets[2], "clusters"),
             fill = metric,
             title = paste(str_to_title(j), "similarity matrix")) + 
        scale_fill_gradientn(colors = heatmap_palette) +
        scale_x_discrete(expand = expansion(mult = 0), position = "top") + 
        scale_y_discrete(expand = expansion(mult = 0)) + 
        theme_bw() + 
        theme(axis.ticks = element_blank())
      
      # Export plot
      outfile <- paste("similarity_matrix", datasets[1], nk1, datasets[2], nk2, j, sep = "_")
      outfile <- paste0(outfile, ".pdf")
      outfile <- file.path(output_dir, outfile)
      pdf(file = outfile, 
          width = unit(10, "in"),
          height = unit(8, "in"))
      print(p_sim_j)
      dev.off()
      
    }
    
    # Aggregate similarity values over Jacobians
    similarity_nk <- similarity_nk %>% 
      group_by(img_1_cluster_id, img_2_cluster_id) %>% 
      summarise(similarity = mean(similarity), .groups = "drop") 
    
    # Plot combined similarity matrix
    p_sim <- ggplot(similarity_nk, 
                    aes(x = img_1_cluster_id, 
                        y = fct_rev(img_2_cluster_id), 
                        fill = similarity)) + 
      geom_tile(col = "grey50") + 
      labs(x = paste(datasets[1], "clusters"),
           y = paste(datasets[2], "clusters"),
           fill = metric,
           title = "Final similarity matrix") + 
      scale_fill_gradientn(colors = heatmap_palette) +
      scale_x_discrete(expand = expansion(mult = 0), position = "top") + 
      scale_y_discrete(expand = expansion(mult = 0)) + 
      theme_bw() + 
      theme(axis.ticks = element_blank())
    
    # Export plot
    outfile <- paste("similarity_matrix", datasets[1], nk1, datasets[2], nk2, sep = "_")
    outfile <- paste0(outfile, ".pdf")
    outfile <- file.path(output_dir, outfile)
    pdf(file = outfile, 
        width = unit(10, "in"),
        height = unit(8, "in"))
    print(p_sim)
    dev.off()
    
  }
}
```

# Where do the similarity values come from?


```{r, eval = FALSE}
# Input pipeline directories
input_pipeline_dirs <- file.path("../../data/", species)

# Expression directories
expr_dirs <- file.path(input_pipeline_dirs, "expression")

# Import files for both pipeline inputs
masks <- character(2)
anats <- vector(mode = "list", length = 2)
labels <- vector(mode = "list", length = 2)
defs <- vector(mode = "list", length = 2)
trees <- vector(mode = "list", length = 2)
for (i in 1:2) {
  if (species[i] == "human") {
    
    # Human imaging directory
    imgdir <- file.path(input_pipeline_dirs[i], "registration", version, "reference_files")  
    
    # Human mask file
    masks[i] <- file.path(imgdir, paste0("mask_", resolutions[i], "mm.mnc"))
    
    # Human anatomy template
    anat <- file.path(imgdir, paste0("model_", resolutions[i], "mm.mnc"))
    anats[[i]] <- mincGetVolume(anat)
    
    # Human microarray labels
    label <- str_c("AHBA_microarray_labels_study_", resolutions[i], "mm.mnc")
    label <- file.path(expr_dirs[i], version, label)
    labels[[i]] <- round(mincGetVolume(label))
    
    # Human microarray label definitions
    def <- file.path(expr_dirs[i], "AHBA_microarray_coordinates_mni_defs.csv")
    defs[[i]] <- read_csv(def, show_col_types = FALSE)
    
    # Human expression tree
    load(file.path(expr_dirs[i], "HumanExpressionTree.RData"))
    trees[[i]] <- Clone(treeHumanExpr)
    rm(treeHumanExpr)
    
    
  } else if (species[i] == "mouse") {
    
    # Mouse atlas directory
    imgdir <- file.path(input_pipeline_dirs[i], "atlas")
    
    # Mouse mask file
    masks[i] <- file.path(imgdir, "coronal_200um_coverage_bin0.8.mnc")
    
    # Mouse anatomy template
    anat <- file.path(imgdir, "DSURQE_CCFv3_average_200um.mnc")
    anats[[i]] <- mincGetVolume(anat)
    
    # Mouse atlas labels
    label <- file.path(imgdir, "DSURQE_CCFv3_labels_200um.mnc")
    labels[[i]] <- mincGetVolume(label)
    
    # Mouse atlas label definitions
    def <- file.path(imgdir, "DSURQE_40micron_R_mapping_long.csv")
    defs[[i]] <- read_csv(def, show_col_types = FALSE) %>% 
      select(name = Structure, label = Label)
    
    # Mouse expression tree
    load(file.path(expr_dirs[i], "MouseExpressionTree_DSURQE.RData"))
    trees[[i]] <- Clone(treeMouseExpr)
    rm(treeMouseExpr)
    
  }
}

# Update pipeline directories with parameter IDs
input_pipeline_dirs <- file.path(input_pipeline_dirs, "derivatives", version, param_ids)

# Centroid directories
centroid_dirs <- vector(mode = "list", length = 2)
names(centroid_dirs) <- jacobians
for (j in jacobians) {
  centroid_dirs[[j]] <- file.path(input_pipeline_dirs, "centroids", paste0("resolution_", resolutions), j)
}

# Import mapping for mouse-human neuroanatomical homologues
neuro_file <- "../../data/cross_species/MouseHumanMatches_H10M09.csv"
df_neuro <- read_csv(neuro_file, show_col_types = FALSE)
colnames(df_neuro) <- str_to_lower(colnames(df_neuro))
df_neuro <- df_neuro %>% 
  filter(!(name %in% c("White matter", "Ventricles")))

# Get image thresholding parameters
# Threshold method
threshold <- params %>% 
  filter(id == params_id) %>% 
  pull(threshold)

# Threshold value
threshold_value <- params %>% 
  filter(id == params_id) %>% 
  pull(threshold_value)

# Threshold symmetric option
threshold_symmetric <- params %>% 
  filter(id == params_id) %>% 
  pull(threshold_symmetric)
```


```{r, eval = FALSE}
run <- FALSE
nproc <- 8
if (run) {
  
  df_iter <- tibble()
  for (nk1 in 2:nk_max) {
    if (nk1 == 2) {
      nk2_range <- seq(nk1, nk1+n_off_diag)
    } else if (nk1 == nk_max) {
      nk2_range <- seq(nk1-n_off_diag, nk1)
    } else {
      nk2_range <- seq(nk1-n_off_diag, nk1+n_off_diag)
    } 
    for (nk2 in nk2_range) {
      df_iter <- df_iter %>%
        bind_rows(expand_grid(k1 = 1:nk1,
                              k2 = 1:nk2) %>% 
                    mutate(nk1 = nk1, nk2 = nk2))
    }
  }
  
  pb <- txtProgressBar(max = nrow(df_iter), style = 3)
  progress <- function(n) {setTxtProgressBar(pb = pb, value = n)}
  cl <- makeSOCKcluster(nproc)
  registerDoSNOW(cl)
  opts <- list(progress=progress)
  results <- foreach(i = 1:nrow(df_iter), 
                     .combine = "c",
                     .packages = c("tidyverse" ,"RMINC", "data.tree"), 
                     .options.snow = opts) %dopar% {
                       
                       nk <- c(df_iter[[i, "nk1"]], df_iter[[i, "nk2"]])
                       k <- c(df_iter[[i, "k1"]], df_iter[[i, "k2"]])
                       
                       centroid_anat <- vector(mode = "list", length = length(jacobians))
                       names(centroid_anat) <- jacobians
                       for (j in jacobians) {
                         centroid_anat[[j]] <- compare_centroid_anatomy(centroid_dirs = centroid_dirs[[j]],
                                                                        species = species,
                                                                        nk = nk, k = k,
                                                                        nodes = df_neuro,
                                                                        masks = masks, trees = trees, labels = labels,
                                                                        defs = defs, threshold = threshold, 
                                                                        threshold_value = threshold_value,
                                                                        threshold_symmetric = threshold_symmetric)
                         names(centroid_anat[[j]]) <- datasets
                         centroid_anat[[j]] <- bind_rows(centroid_anat[[j]], .id = "dataset")
                         
                       }
                       
                       centroid_anat <- bind_rows(centroid_anat, .id = "jacobians")
                       
                       cluster_ids <- str_c(nk, k, sep = "-")
                       outfile <- paste0("centroid_anatomy_", str_flatten(str_c(datasets, cluster_ids, sep = "_"), collapse = "_"))
                       outfile <- paste0(outfile, ".csv")
                       outfile <- file.path(output_dir, outfile)
                       write_csv(x = centroid_anat, file = outfile)
                       
                       outfile
                     }
  close(pb)
  stopCluster(cl)
  
} 
```


```{r, eval = FALSE}
centroid_anat <- vector(mode = "list", length = length(jacobians))
names(centroid_anat) <- jacobians
for (j in jacobians) {
  centroid_anat[[j]] <- compare_centroid_anatomy(centroid_dirs = centroid_dirs[[j]],
                                                 species = species,
                                                 nk = c(2,2), k = c(1,1),
                                                 nodes = df_neuro,
                                                 masks = masks, trees = trees, labels = labels,
                                                 defs = defs, threshold = threshold, 
                                                 threshold_value = threshold_value,
                                                 threshold_symmetric = threshold_symmetric)
  names(centroid_anat[[j]]) <- datasets
  centroid_anat[[j]] <- bind_rows(centroid_anat[[j]], .id = "dataset")
}
centroid_anat <- bind_rows(centroid_anat, .id = "jacobians")
```


```{r, eval = FALSE}
neuro_acronyms <- c("Cx", "CxN", "IB", "MB", "P", "M", "CbCx", "CbN")
df_neuro_acronyms <- df_neuro %>% 
  select(name) %>% 
  mutate(name = factor(name, levels = name),
         acronym = factor(neuro_acronyms, levels = neuro_acronyms))

centroid_anat_plot <- centroid_anat %>% 
  left_join(df_neuro_acronyms, by = "name") %>% 
  mutate(sign = str_to_title(sign), 
         sign = factor(sign, levels = c("Positive", "Negative")),
         jacobians = str_to_title(jacobians))

ggplot(centroid_anat_plot, 
       aes(x = acronym, y = f_per_label, fill = dataset, col = dataset, group = dataset)) + 
  geom_col(position = "dodge") +
  facet_grid(sign~jacobians) + 
  labs(x = "Brain region",
       y = "Fraction of expressing voxels",
       col = "Dataset", fill = "Dataset") +
  theme_bw()
```



# Mouse-human neuroanatomical radar plots


```{r radar-import, eval = FALSE}
# Mouse anatomy
mouse_anat_file <- "../../data/mouse/atlas/DSURQE_CCFv3_average_200um.mnc"
mouse_anat <- mincGetVolume(mouse_anat_file)
mouse_anat_vol <- mincArray(mouse_anat)

# Human anatomy
human_anat_file <- "../../data/human/registration/v2/reference_files/model_0.8mm.mnc"
human_anat <- mincGetVolume(human_anat_file)
human_anat_vol <- mincArray(human_anat)

# Cropped human images along sagittal and transverse planes
human_slices_dim_1 <- 25:200
human_slices_dim_3 <- 25:220
human_anat_vol_cropped <- human_anat_vol[human_slices_dim_1,,human_slices_dim_3]

# Human mask
human_mask <- "../../data/human/registration/v3/reference_files/mask_0.8mm.mnc"

# Mouse mask
mouse_mask <- "../../data/mouse/atlas/coronal_200um_coverage_bin0.8.mnc"

# Human cluster map directories
human_centroid_dirs <- file.path(human_pipeline_dir, "centroids")
human_centroid_dirs <- file.path(human_centroid_dirs, str_c("resolution_", human_resolution))
human_centroid_dirs <- file.path(human_centroid_dirs, jacobians)
names(human_centroid_dirs) <- jacobians

# Mouse cluster map directories
mouse_centroid_dirs <- file.path(mouse_pipeline_dir, "centroids")
mouse_centroid_dirs <- file.path(mouse_centroid_dirs, str_c("resolution_", mouse_resolution))
mouse_centroid_dirs <- file.path(mouse_centroid_dirs, jacobians)
names(mouse_centroid_dirs) <- jacobians  

# Import mouse atlas labels
mouse_labels_file <- "../../data/mouse/atlas/DSURQE_CCFv3_labels_200um.mnc"
mouse_labels <- mincGetVolume(mouse_labels_file)

# Import mouse atlas definitions
mouse_defs_file <- "../../data/mouse/atlas/DSURQE_40micron_R_mapping_long.csv"
mouse_defs <- read_csv(mouse_defs_file, show_col_types = FALSE) %>% 
  select(name = Structure, label = Label)

# Import mouse neuroanatomical tree
mouse_tree_file <- "../../data/mouse/expression/MouseExpressionTree_DSURQE.RData"
load(mouse_tree_file)
mouse_tree <- Clone(treeMouseExpr)
rm(treeMouseExpr)

# Import human microarray atlas labels
human_labels_file <- str_c("AHBA_microarray_labels_study_", human_resolution, "mm.mnc")
human_labels_file <- file.path("../../data/human/expression/", version, human_labels_file)
human_labels <- mincGetVolume(human_labels_file)
human_labels <- round(human_labels)

# Import human microarray atlas definitions
human_defs_file <- "../../data/human/expression/AHBA_microarray_coordinates_mni_defs.csv"
human_defs <- read_csv(human_defs_file, show_col_types = FALSE)

# Import human neuroanatomical tree
human_tree_file <- "../../data/human/expression/HumanExpressionTree.RData"
load(human_tree_file)
human_tree <- Clone(treeHumanExpr)
rm(treeHumanExpr)

# Import mapping for mouse-human neuroanatomical homologues
neuro_file <- "../../data/cross_species/MouseHumanMatches_H10M09.csv"
df_spokes <- read_csv(neuro_file, show_col_types = FALSE)
colnames(df_spokes) <- str_to_lower(colnames(df_spokes))
df_spokes <- df_spokes %>% 
  filter(!(name %in% c("White matter", "Ventricles")))

# Threshold method
threshold <- params %>% 
  filter(id == params_id) %>% 
  pull(threshold)

# Threshold value
threshold_value <- params %>% 
  filter(id == params_id) %>% 
  pull(threshold_value)

# Threshold symmetric option
threshold_symmetric <- params %>% 
  filter(id == params_id) %>% 
  pull(threshold_symmetric)
```

```{r radar-args, eval = FALSE}
# Centroid directories
centroid_dirs_abs <- c("human" = human_centroid_dirs[[1]], 
                       "mouse" = mouse_centroid_dirs[[1]])

centroid_dirs_rel <- c("human" = human_centroid_dirs[[2]], 
                       "mouse" = mouse_centroid_dirs[[2]])

# Combine cluster map directories
centroid_dirs <- list(centroid_dirs_abs, centroid_dirs_rel)
names(centroid_dirs) <- jacobians

# Human and mouse trees
trees <- list("human" = human_tree,
              "mouse" = mouse_tree)

# Human and mouse labels
labels <- list("human" = human_labels,
               "mouse" = mouse_labels)

# Human and mouse definitions
defs <- list("human" = human_defs,
             "mouse" = mouse_defs)

# Human and mouse masks
masks <- list("human" = human_mask,
              "mouse" = mouse_mask)
```


```{r, eval = FALSE}
# Human and mouse nk
nk_list <- list("human" = 2,
                "mouse" = 2)

# Human and mouse k
k <- list("human" = 1,
          "mouse" = 1)

df_abs_1_1 <- prepare_radar_chart(cluster_dirs = centroid_dirs[["absolute"]],
                                  nk = nk_list, k = k,
                                  trees = trees,
                                  spokes = df_spokes,
                                  labels = labels,
                                  defs = defs,
                                  masks = masks,
                                  threshold = threshold,
                                  threshold_value = threshold_value,
                                  threshold_symmetric = threshold_symmetric)

df_abs_1_1
```


```{r radar-plot, eval = FALSE}
# Maximum nk
nk_max <- params[["human_cluster_nk_max"]]

# Iterate over diagonal nk similarity values
for (nk in 2:nk_max) {
  for (hk in 1:nk) {
    for (mk in 1:nk) {
      
      print(paste0("H", nk, "-", hk, "; M", nk, "-", mk))
      
      # Human and mouse nk
      nk_list <- list("human" = nk,
                      "mouse" = nk)
      
      # Human and mouse k
      k <- list("human" = hk,
                "mouse" = mk)
      
      # Iterate over jacobians
      list_radar <- vector(mode = "list", length = length(jacobians))
      names(list_radar) <- jacobians
      for (j in jacobians) {
        
        # Prepare radar chart data frame
        df_radar <- prepare_radar_chart(cluster_dirs = cluster_dirs[[j]],
                                        nk = nk_list, k = k,
                                        trees = trees,
                                        spokes = df_spokes,
                                        labels = labels,
                                        defs = defs,
                                        masks = masks,
                                        threshold = threshold,
                                        threshold_value = threshold_value,
                                        threshold_symmetric = threshold_symmetric)
        
        # Replace NANs with 0
        df_radar <- df_radar %>% 
          mutate(positive = ifelse(is.nan(positive), 0, positive))
        
        # Data for line at 0
        radar_zeroline <- tibble(name = unique(df_radar[["name"]]),
                                 y = 0)
        
        # Plot parameters
        nspokes <- length(unique(df_radar[["name"]]))-1
        radar_start <- -(2*pi)/nspokes
        breaks_start <- -1
        breaks_end <- 1
        breaks_step <- 0.5
        radar_breaks <- seq(breaks_start, breaks_end, by = breaks_step)
        radar_labels <- tibble(name = levels(df_radar[["name"]])[6],
                               breaks = radar_breaks)
        
        # Radar plot for given jacobians
        list_radar[[j]] <- ggplot(df_radar,
                                  aes(x = name, 
                                      ymin = negative, 
                                      ymax = positive, 
                                      group = species, 
                                      fill = species,
                                      col = species)) + 
          geom_ribbon(alpha = 0.2) +
          geom_line(data = radar_zeroline,
                    inherit.aes = FALSE,
                    mapping = aes(x = name, y = y, group = 1),
                    linetype = "dashed",
                    size = 0.5) + 
          geom_text(data = radar_labels,
                    inherit.aes = FALSE,
                    mapping = aes(x = name,
                                  y = breaks,
                                  label = breaks),
                    size = 2.5,
                    nudge_y = 0.1) + 
          coord_radar(start = radar_start) +
          scale_x_discrete(expand = expansion(),
                           labels = c("CbN", "Cx", "CxN", "IB", "MB", "P", "MY", "CbCx", "CbN")) + 
          scale_y_continuous(breaks = seq(-1, 1, by = 0.5), limits = c(-1, 1.2)) +
          scale_fill_discrete(labels = c("Human", "Mouse")) + 
          scale_color_discrete(labels = c("Human", "Mouse")) + 
          labs(x = NULL,
               fill = NULL, 
               col = NULL,
               title = str_to_title(j)) + 
          theme_bw() +
          theme(legend.position = "bottom",
                legend.direction = "horizontal",
                axis.text.x = element_text(size = 6, face = "bold"),
                axis.ticks.x = element_blank(),
                axis.line.x = element_blank(),
                axis.text.y = element_blank(),
                axis.ticks.y = element_blank(),
                axis.title.y = element_blank(),
                plot.margin = margin(t = 0, b = 0, r = 0, l = 0))
        
      }
      
      # Combine plots for absolute and relative jacobians
      p_radar <- (list_radar[[1]] | list_radar[[2]]) +
        plot_annotation(title = paste0("Human ", nk, "-", hk, " and mouse ", nk, "-", mk))
      
      # Export plot
      outfile <- paste0("radar_plot_H", nk, "-", hk, "_M", nk, "-", mk, ".pdf")
      outfile <- file.path(output_dir, outfile)
      pdf(file = outfile,
          width = unit(8, "in"),
          height = unit(5, "in"))
      print(p_radar)
      dev.off()
      
    }
  }
}
```
