---
title: "Human and mouse cluster diagnostics and optimization"
author: "Antoine Beauchamp"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(SNFtool))
suppressPackageStartupMessages(library(umap))
suppressPackageStartupMessages(library(cluster))
suppressPackageStartupMessages(library(ggalluvial))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(RColorBrewer))
```

```{r functions}
SRCPATH <- Sys.getenv("SRCPATH")

source(file.path(SRCPATH, "utils.R"))

# Function to estimate cluster metrics over a range of solutions
estimate_cluster_metrics <- function (W, NUMC = 2:5){
  if (min(NUMC) == 1) {
    warning("Note that we always assume there are more than one cluster.")
    NUMC <- NUMC[NUMC > 1]
  }
  W <- (W + t(W))/2
  diag(W) <- 0
  if (length(NUMC) <= 0) {
    warning(paste("Invalid NUMC provided, must be an integer vector", 
                  "with atleast one other number than 1.", "Using default NUMC=c(2,3,4,5)", 
                  sep = ""))
    NUMC <- 2:5
  }
  degs <- rowSums(W)
  degs[degs == 0] <- .Machine$double.eps
  D <- diag(degs)
  L <- D - W
  Di <- diag(1/sqrt(degs))
  L <- Di %*% L %*% Di
  eigs <- eigen(L)
  eigs_order <- sort(eigs$values, index.return = T)$ix
  eigs$values <- eigs$values[eigs_order]
  eigs$vectors <- eigs$vectors[, eigs_order]
  eigengap <- abs(diff(eigs$values))
  quality <- list()
  for (c_index in 1:length(NUMC)) {
    ck <- NUMC[c_index]
    UU <- eigs$vectors[, 1:ck]
    EigenvectorsDiscrete <- SNFtool:::.discretisation(UU)[[1]]
    EigenVectors <- EigenvectorsDiscrete^2
    temp1 <- EigenVectors[do.call(order, lapply(1:ncol(EigenVectors), 
                                                function(i) EigenVectors[, i])), ]
    temp1 <- t(apply(temp1, 1, sort, TRUE))
    quality[[c_index]] <- (1 - eigs$values[ck + 1])/(1 - 
                                                       eigs$values[ck]) * sum(sum(diag(1/(temp1[, 1] + .Machine$double.eps)) %*% 
                                                                                    temp1[, 1:max(2, ck - 1)]))
  }
  
  out <- tibble(nk = NUMC,
                eigengap = eigengap[NUMC],
                rotation = unlist(quality))
  
  return(out)
}
```

```{r directories}
# Output directory
output_dir <- "outputs/cluster_diagnostics/"

# Human pipeline
human_version <- "v3"
human_pipeline_dir <- "../../data/human/derivatives/"
human_pipeline_dir <- file.path(human_pipeline_dir, human_version)

# Mouse pipeline
mouse_version <- "v3"
mouse_pipeline_dir <- "../../data/mouse/derivatives/"
mouse_pipeline_dir <- file.path(mouse_pipeline_dir, mouse_version)
```

```{r mouse-params}
mouse_resolution <- 0.2
mouse_centroid_method <- "mean"

# Identify mouse parameter set ID
mouse_metadata <- file.path(mouse_pipeline_dir, "metadata.csv")
mouse_params <- fetch_params_metadata(mouse_metadata, 
                                      resolution = mouse_resolution,
                                      centroid_method = mouse_centroid_method)
mouse_params
```

```{r human-params}
dataset <- "POND-SickKids"
# dataset <- "HBN"
human_resolution <- 3.0
human_es_method <- "normative-growth"
human_es_group <- "controls"
human_es_df <- 3
human_es_ncontrols <- NA
human_centroid_method <- mouse_centroid_method

# human_es_method <- "propensity-matching"
# human_es_df <- NA
# human_es_ncontrols <- 10

#Identify human parameter set ID
human_metadata <- file.path(human_pipeline_dir, "metadata.csv")
human_params <- fetch_params_metadata(metadata = human_metadata,
                                      resolution = human_resolution,
                                      es_method = human_es_method,
                                      es_group = human_es_group,
                                      es_df = human_es_df,
                                      es_ncontrols = human_es_ncontrols,
                                      centroid_method = human_centroid_method)
human_params
```

```{r directories-2}
# Mouse parameter set ID
mouse_params_id <- 107

# Human parameter set ID
human_params_id <- "577"
# human_params_id <- "013"
# human_params_id <- 256
# human_params_id <- "547"
# human_params_id <- "664"

# Human cluster resolution
human_cluster_resolution <- human_params %>% 
  filter(id == human_params_id) %>% 
  pull(cluster_resolution)
human_cluster_resolution <- sprintf("%.1f", human_cluster_resolution)

# Mouse cluster resolution
mouse_cluster_resolution <- mouse_params %>% 
  filter(id == mouse_params_id) %>% 
  pull(cluster_resolution)
mouse_cluster_resolution <- sprintf("%.1f", mouse_cluster_resolution)

# Cluster directories
mouse_cluster_dir <- file.path(mouse_pipeline_dir, mouse_params_id, "clusters", str_c("resolution_", mouse_cluster_resolution))
human_cluster_dir <- file.path(human_pipeline_dir, human_params_id, "clusters", str_c("resolution_", human_cluster_resolution))

# Human effect size directory
human_es_dir <- file.path(human_pipeline_dir, human_params_id, "effect_sizes")
human_es_dir <- file.path(human_es_dir, str_c("resolution_", human_cluster_resolution))

# Output directory
params_id <- str_c(str_c("H", human_params_id), 
                   str_c("M", mouse_params_id), 
                   sep = "-")
output_dir <- file.path(output_dir, human_version, params_id)
if (!(dir.exists(output_dir))) {dir.create(output_dir, recursive = TRUE)}
```

```{r import}
# Human clusters
human_cluster_file <- file.path(human_cluster_dir, "clusters.csv")
df_human_clusters <- read_csv(human_cluster_file, show_col_types = FALSE)

# Mouse clusters
mouse_cluster_file <- file.path(mouse_cluster_dir, "clusters.csv")
df_mouse_clusters <- read_csv(mouse_cluster_file, show_col_types = FALSE)
colnames(df_mouse_clusters) <- c("ID", str_c("nk", 2:10))

# Human affinity matrix
human_affinity_file <- file.path(human_cluster_dir, "affinity.csv")
df_human_affinity <- read_csv(human_affinity_file, show_col_types = FALSE)
mat_human_affinity <- as.matrix(df_human_affinity)
rownames(mat_human_affinity) <- colnames(mat_human_affinity)

# Mouse affinity matrix
mouse_affinity_file <- file.path(mouse_cluster_dir, "affinity.RData")
load(mouse_affinity_file)
mat_mouse_affinity <- W
df_mouse_affinity <- as_tibble(mat_mouse_affinity)
```

# Mouse and human affinity distributions

```{r affinity-distributions, fig.width = 10, fig.height = 3}
# Human affinity df long form
df_human_affinity_long <- df_human_affinity %>% 
  mutate(patient_1 = colnames(df_human_affinity)) %>% 
  pivot_longer(cols = -patient_1, names_to = "patient_2", values_to = "affinity")

# Mouse affinity df long form
df_mouse_affinity_long <- df_mouse_affinity %>% 
  mutate(model_1 = colnames(df_mouse_affinity)) %>% 
  pivot_longer(cols = -model_1, names_to = "model_2", values_to = "affinity")

# Combine mouse and human affinity
df_affinity_compare <- bind_rows(df_human_affinity_long %>% 
                                   select(affinity) %>% 
                                   mutate(species = "human"),
                                 df_mouse_affinity_long %>% 
                                   select(affinity) %>% 
                                   mutate(species = "mouse"))

# Plot distributions of affinity values
p_affinity_dist <- ggplot(df_affinity_compare, 
                          aes(x = affinity, fill = species, y = ..density..)) + 
  geom_histogram(binwidth = 0.0001, position = "dodge") + 
  coord_cartesian(xlim = c(0, 0.01)) + 
  labs(fill = "Species",
       x = "Affinity",
       y = "Density",
       title = "Distribution of affinity values",
       caption = "Note: Maximal affinity is 0.5") + 
  theme_bw()

# Export plot
outfile <- "affinity_distributions.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile, 
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_affinity_dist)
dev.off()

p_affinity_dist
```

# Human clusters

## Human cluster dispersion

```{r human-sankey}
# Convert cluster information to long format
df_human_clusters_long <- df_human_clusters %>% 
  pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         nk = factor(nk),
         k = factor(k))

# Human cluster Sankey plot
p_human_alluvial <- ggplot(df_human_clusters_long,
                           aes(x = nk,
                               stratum = k,
                               alluvium = ID,
                               fill = k, 
                               label = k)) + 
  geom_flow(stat = "alluvium", aes.flow = "forward") + 
  geom_stratum(alpha = 0.5) + 
  labs(x = "Number of clusters",
       y = "Number of patients",
       title = "Human cluster dispersion") + 
  theme_bw() + 
  theme(panel.grid.major.x = element_blank())

# Export plot
outfile <- "human_sankey.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile, 
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_human_alluvial)
dev.off()
```

```{r human-cluster-n}
# Human cluster counts
df_human_clusters_n <- df_human_clusters_long %>% 
  group_by(nk, k) %>% 
  count() %>% 
  ungroup()

# Plot of human cluster counts
p_human_counts <- ggplot(df_human_clusters_n, 
                         aes(x = nk, y = fct_rev(k), fill = n)) + 
  geom_tile(col = "black") +
  geom_text(aes(label = n)) + 
  scale_x_discrete(expand = expansion()) + 
  scale_y_discrete(expand = expansion()) + 
  scale_fill_distiller(na.value = "white", palette = "Reds", direction = 1) +
  labs(x = "nk",
       y = "k",
       title = "Human clusters numbers") + 
  theme_bw()

# Export plot
outfile <- "human_cluster_counts.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile, 
    width = unit(10, "in"),
    height = unit(8, "in"))
print(p_human_counts)
dev.off()

p_human_counts
```

```{r human-umap, eval = FALSE}
# UMAP random seed
umap_seed <- 2

# Jacobians
jacobians <- c("absolute", "relative")

# Create UMAP plots for absolute and relative Jacobians
list_human_umap <- vector(mode = "list", length = length(jacobians))
names(list_human_umap) <- jacobians
for (j in jacobians) {
  
  # Import effect size matrix
  human_es_file <- file.path(human_es_dir, j, "effect_sizes.csv")
  df_human_es <- as_tibble(data.table::fread(human_es_file, header = TRUE))
  
  # Extract labels and data from matrix 
  df_human_es_data <- df_human_es[,colnames(df_human_es) != "file"]
  df_human_es_labels <- df_human_es[,colnames(df_human_es) == "file"]
  
  # Create the UMAP projection
  human_umap <- umap(df_human_es_data, n_components = 2, 
                     random_state = umap_seed)
  
  # Create data frame from UMAP data
  df_human_umap <- human_umap[["layout"]]
  colnames(df_human_umap) <- c("x1", "x2")
  df_human_umap <- as_tibble(df_human_umap)
  df_human_umap[["ID"]] <- df_human_es_labels[["file"]]
  
  # Add cluster assignment information
  df_human_umap <- df_human_umap %>% 
    inner_join(df_human_clusters, by = "ID")
  
  # Convert data frame to long format
  df_human_umap_long <- df_human_umap %>% 
    column_to_rownames("ID") %>% 
    pivot_longer(cols = c(-x1, -x2), 
                 names_to = "nk", 
                 values_to = "k") %>% 
    mutate(nk = str_remove(nk, "nk"),
           nk = as.numeric(nk),
           nk = factor(nk),
           k = factor(k))
  
  # Plot of UMAP projection
  p_human_umap <- ggplot(df_human_umap_long,
                         aes(x = x1, y = x2, col = k)) +
    geom_point() + 
    facet_wrap(~nk, nrow = 3) + 
    labs(title = paste("Human", j, "effect size UMAP projection")) + 
    theme_bw()
  
  # Export plot
  outfile <- paste0("human_umap_", umap_seed, "_", j, ".pdf")
  outfile <- file.path(output_dir, outfile)
  pdf(file = outfile, 
      width = 12,
      height = 10)
  print(p_human_umap)
  dev.off()
  
}
```


## Optimal number of human clusters

```{r human-cluster-optimal}
# Max nk to examine
nk_max <- 100

# Human optimal nk
estimateNumberOfClustersGivenGraph(W = mat_human_affinity, NUMC = 2:nk_max)
```

```{r human-cluster-metrics, fig.width = 10, fig.height = 5}
# Get human cluster metrics
df_human_cluster_metrics <- estimate_cluster_metrics(W = mat_human_affinity, NUMC = 2:nk_max)

# Plot x-axis breaks
xbreaks <- seq(0, nk_max, by = 4)
# xbreaks <- seq(0, nk_max, by = 1)

# Plot of eigengap distribution
p_human_eigengap <- ggplot(df_human_cluster_metrics,
                           aes(x = nk, y = eigengap)) + 
  geom_hline(yintercept = 0,
             linetype = "dashed",
             col = "grey50") + 
  geom_line() + 
  geom_point() +
  scale_x_continuous(breaks = xbreaks) + 
  labs(y = "Eigengap") +
  theme_bw()

# Plot of rotation cost distribution
p_human_rotation <- ggplot(df_human_cluster_metrics,
                           aes(x = nk, y = rotation)) + 
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = xbreaks) + 
  labs(y = "Rotation best") +
  theme_bw()

# Combined metric plot
p_human_metrics <- (p_human_eigengap / p_human_rotation) +
  plot_annotation(title = "Human cluster metric distribution")

# Export plot
outfile <- "human_cluster_metrics.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_human_metrics)
dev.off()
```

```{r human-affinity-mat, fig.width = 6, fig.height = 5}
#Get max number of clusters identified
human_nk_max <- human_params %>% 
  filter(id == human_params_id) %>% 
  pull(cluster_nk_max)

# Iterate over all cluster solutions
for (nk in 2:human_nk_max) {
  
  # Get human cluster labels for given nk
  df_human_labels_nk <- tibble(patient = colnames(df_human_affinity),
                               k = spectralClustering(affinity = mat_human_affinity,
                                                      K = nk))
  
  # Arrange patients by cluster assignment
  patient_lvls <- df_human_labels_nk %>% 
    arrange(k) %>% 
    pull(patient)
  
  # Clamp affinity values
  threshold <- 0.005
  df_human_affinity_long_clamped <- df_human_affinity_long %>% 
    mutate(affinity = ifelse(affinity >= threshold, threshold, affinity),
           patient_1 = factor(patient_1, levels = patient_lvls),
           patient_2 = factor(patient_2, levels = patient_lvls))
  
  # Plot human affinity matrix at nk
  p_human_affinity_matrix <- ggplot(df_human_affinity_long_clamped, 
                                    aes(x = patient_1,
                                        y = fct_rev(patient_2),
                                        fill = affinity)) + 
    geom_tile() + 
    scale_x_discrete(expand = expansion()) +
    scale_y_discrete(expand = expansion()) +
    scale_fill_gradientn(colours = c("white", brewer.pal(n = 9, name = "Reds")), na.value = "white") + 
    labs(fill = "Affinity",
         x = "Patient",
         y = "Patient",
         title = paste("Human affinity matrix for nk =", nk),
         caption = paste("Affinity values clamped at", threshold)) + 
    theme_bw() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank())
  
  # Export plot
  outfile <- paste0("human_affinity_matrix_nk_", nk, ".pdf")
  outfile <- file.path(output_dir, outfile)
  pdf(file = outfile, 
      width = unit(10, "in"),
      height = unit(8, "in"))
  print(p_human_affinity_matrix)
  dev.off()
  
}
```


## Human silhouette analysis

```{r}
# Convert affinity matrix to distance matrix
mat_human_distance <- 2/(mat_human_affinity) - 2/max(mat_human_affinity)
# mat_human_distance <- 1/(mat_human_affinity) - 1/max(mat_human_affinity)
# mat_human_distance <- -1*log10(mat_human_affinity/max(mat_human_affinity))

nk_max <- 10
list_human_silhouette <- vector(mode = "list", length = nk_max - 1)
for (nk in 2:nk_max) {
  
  nk_col <- paste0("nk", nk)
  
  # Calculate silhouette coefficients
  silhouette_out <- silhouette(x = df_human_clusters[[nk_col]], 
                               dmatrix = mat_human_distance)
  
  list_human_silhouette[[nk-1]] <- df_human_clusters %>% 
    select(ID, k = all_of(nk_col)) %>% 
    mutate(nk = nk,
           neighbour = silhouette_out[,2],
           coeff = silhouette_out[,3]) 
  
}

df_human_silhouette <- reduce(.x = list_human_silhouette,
                              .f = bind_rows)

df_human_silhouette_cluster_avg <- df_human_silhouette %>% 
  group_by(nk, k) %>% 
  summarise(coeff = mean(coeff),
            .groups = "drop")

df_human_silhouette_total_avg <- df_human_silhouette %>% 
  group_by(nk) %>% 
  summarise(coeff = mean(coeff),
            .groups = "drop")

p_human_silhouette <- ggplot(df_human_silhouette,
                             aes(x = factor(nk), y = coeff)) + 
  geom_jitter(width = 0.25, height = 0,
              shape = 21, fill = "grey50",
              alpha = 0.3, size = 0.5) +
  geom_point(data = df_human_silhouette_total_avg,
             size = 2,
             col = "red") + 
  geom_line(data = df_human_silhouette_total_avg,
            mapping = aes(group = 1),
            col = "red",
            size = 0.75) + 
  geom_hline(yintercept = 0,
             linetype = "dashed") + 
  coord_cartesian(ylim = c(-1,1)) +
  scale_y_continuous(breaks = seq(-1, 1, by = 0.2)) + 
  labs(x = "Number of clusters",
       y = "Silhouette coefficient",
       title = "Silhouette analysis for human clusters") + 
  theme_bw()

# Export plot
outfile <- paste0("human_silhouette.pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile, 
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_human_silhouette)
dev.off()
```



# Mouse clusters

## Mouse cluster dispersion

```{r mouse-sankey}
# Convert cluster information to long format
df_mouse_clusters_long <- df_mouse_clusters %>% 
  pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         nk = factor(nk),
         k = factor(k))

# Mouse cluster Sankey plot
p_mouse_alluvial <- ggplot(df_mouse_clusters_long,
                           aes(x = nk,
                               stratum = k,
                               alluvium = ID,
                               fill = k, 
                               label = k)) + 
  geom_flow(stat = "alluvium", aes.flow = "forward") + 
  geom_stratum(alpha = 0.5) + 
  labs(x = 'Number of clusters',
       y = 'Number of models',
       title = "Mouse cluster dispersion") + 
  theme_bw() + 
  theme(panel.grid.major.x = element_blank())

# Export plot
outfile <- "mouse_sankey.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile, 
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_mouse_alluvial)
dev.off()
```

## Optimal number of mouse clusters

```{r mouse-cluster-optimal}
# Max nk to examine
nk_max <- 100

# Mouse optimal nk
estimateNumberOfClustersGivenGraph(W = mat_mouse_affinity, NUMC = 2:nk_max)
```


```{r mouse-cluster-metrics, fig.width = 10, fig.height = 5}
# Get cluster metric distributions
df_mouse_cluster_metrics <- estimate_cluster_metrics(W = mat_mouse_affinity, NUMC = 2:nk_max)

# Plot x-axis breaks
xbreaks <- seq(0, nk_max, by = 4)
# xbreaks <- seq(0, nk_max, by = 1)

# Plot eigengap distribution
p_mouse_eigengap <- ggplot(df_mouse_cluster_metrics,
                           aes(x = nk, y = eigengap)) + 
  geom_hline(yintercept = 0,
             linetype = "dashed",
             col = "grey50") + 
  geom_line() + 
  geom_point() +
  scale_x_continuous(breaks = xbreaks) + 
  labs(y = "Eigengap") +
  theme_bw()

# Plot rotation cost distribution
p_mouse_rotation <- ggplot(df_mouse_cluster_metrics,
                           aes(x = nk, y = rotation)) + 
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = xbreaks) + 
  labs(y = "Rotation best") +
  theme_bw()

# Combine metric plots
p_mouse_metrics <- (p_mouse_eigengap / p_mouse_rotation) +
  plot_annotation(title = "Mouse cluster metric distribution")

# Export plot
outfile <- "mouse_cluster_metrics.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_mouse_metrics)
dev.off()
```

```{r mouse-affinity-mat, fig.width = 6, fig.height = 5}
# Specify max nk
mouse_nk_max <- human_nk_max

# Iterate over cluster solution
for (nk in 2:mouse_nk_max) {
  
  # Get mouse cluster labels for given nk
  df_mouse_labels_nk <- tibble(model = colnames(df_mouse_affinity),
                               k = spectralClustering(affinity = mat_mouse_affinity,
                                                      K = nk))
  
  # Arrange models by cluster assignment
  model_lvls <- df_mouse_labels_nk %>% 
    arrange(k) %>% 
    pull(model)
  
  # Clamp affinity values
  threshold <- 0.01
  df_mouse_affinity_long_clamped <- df_mouse_affinity_long %>% 
    mutate(affinity = ifelse(affinity >= threshold, threshold, affinity),
           model_1 = factor(model_1, levels = model_lvls),
           model_2 = factor(model_2, levels = model_lvls))
  
  # Plot mouse affinity matrix
  p_mouse_affinity_matrix <- ggplot(df_mouse_affinity_long_clamped, 
                                    aes(x = model_1,
                                        y = fct_rev(model_2),
                                        fill = affinity)) + 
    geom_tile() + 
    scale_x_discrete(expand = expansion()) +
    scale_y_discrete(expand = expansion()) +
    scale_fill_gradientn(colours = c("white", brewer.pal(n = 9, name = "Reds")), na.value = "white") + 
    labs(fill = "Affinity",
         x = "Model",
         y = "Model",
         title = paste("Mouse model affinity matrix for nk =", nk),
         caption = paste("Affinity values clamped at", threshold)) + 
    theme_bw() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank())
  
  # Export plot
  outfile <- paste0("mouse_affinity_matrix_nk_", nk, ".pdf")
  outfile <- file.path(output_dir, outfile)
  pdf(file = outfile, 
      width = 10,
      height = 8)
  print(p_mouse_affinity_matrix)
  dev.off()
}
```

## Mouse silhouette analysis

```{r}
# Convert affinity matrix to distance matrix
mat_mouse_distance <- 2/(mat_mouse_affinity) - 2/max(mat_mouse_affinity)
# mat_mouse_distance <- -1*log10(mat_mouse_affinity/max(mat_mouse_affinity))

nk_max <- 10
list_mouse_silhouette <- vector(mode = "list", length = nk_max - 1)
for (nk in 2:nk_max) {
  
  nk_col <- paste0("nk", nk)
  
  # Calculate silhouette coefficients
  silhouette_out <- silhouette(x = df_mouse_clusters[[nk_col]], 
                               dmatrix = mat_mouse_distance)
  
  list_mouse_silhouette[[nk-1]] <- df_mouse_clusters %>% 
    select(ID, k = all_of(nk_col)) %>% 
    mutate(nk = nk,
           neighbour = silhouette_out[,2],
           coeff = silhouette_out[,3]) 
  
}

df_mouse_silhouette <- reduce(.x = list_mouse_silhouette,
                              .f = bind_rows)

df_mouse_silhouette_cluster_avg <- df_mouse_silhouette %>% 
  group_by(nk, k) %>% 
  summarise(coeff = mean(coeff),
            .groups = "drop")

df_mouse_silhouette_total_avg <- df_mouse_silhouette %>% 
  group_by(nk) %>% 
  summarise(coeff = mean(coeff),
            .groups = "drop")

p_mouse_silhouette <- ggplot(df_mouse_silhouette,
                             aes(x = factor(nk), y = coeff)) + 
  geom_jitter(width = 0.25, height = 0,
              shape = 21, fill = "grey50",
              alpha = 0.3, size = 0.5) +
  geom_point(data = df_mouse_silhouette_total_avg,
             size = 2,
             col = "red") + 
  geom_line(data = df_mouse_silhouette_total_avg,
            mapping = aes(group = 1),
            col = "red",
            size = 0.75) + 
  geom_hline(yintercept = 0,
             linetype = "dashed") + 
  coord_cartesian(ylim = c(-1,1)) +
  scale_y_continuous(breaks = seq(-1, 1, by = 0.2)) + 
  labs(x = "Number of clusters",
       y = "Silhouette coefficient",
       title = "Silhouette analysis for mouse clusters") + 
  theme_bw()

# Export plot
outfile <- paste0("mouse_silhouette.pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile, 
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_mouse_silhouette)
dev.off()
```


# In development

## Network analysis


```{r}
mat_human_adjacency <- mat_human_affinity
mat_human_adjacency[mat_human_affinity >= threshold] <- 1
mat_human_adjacency[mat_human_affinity < threshold] <- 0
```


```{r, fig.width = 10, fig.height = 10}
library(igraph)

# n <- 50
n <- nrow(mat_human_affinity)
threshold <- 0.01
mat_human_adjacency <- mat_human_affinity
mat_human_adjacency[mat_human_affinity >= threshold] <- 1
mat_human_adjacency[mat_human_affinity < threshold] <- 0
colnames(mat_human_adjacency) <- NULL
rownames(mat_human_adjacency) <- NULL
mat_human_adjacency <- mat_human_adjacency[1:n, 1:n]
set.seed(1)
g <- graph_from_adjacency_matrix(mat_human_adjacency, mode = "undirected")
```

```{r, fig.width = 5, fig.height = 4}
degree(g) %>% 
  table() %>% 
  enframe() %>% 
  mutate(name = factor(as.numeric(name)), 
         value = as.numeric(value)) %>% 
  ggplot(aes(x = name, y = value)) + 
  geom_col()
```


```{r, fig.width = 10, fig.height = 10}
V(g)$k <- df_human_clusters$nk2
g <- simplify(g)
g <- delete.vertices(g, degree(g) < 6)
# layout <- layout_with_drl(g)
layout <- layout_nicely(g)
plot(g, layout = layout, vertex.size = 3, vertex.label = NA, vertex.color = ifelse(V(g)$k == 1, "yellow", "red"))
```

```{r fig.width = 8, fig.height = 8}

# n <- 100
n <- nrow(mat_human_affinity)
mat_human_adjacency <- mat_human_affinity
colnames(mat_human_adjacency) <- NULL
rownames(mat_human_adjacency) <- NULL
mat_human_adjacency <- mat_human_adjacency[1:n, 1:n]
g <- graph_from_adjacency_matrix(mat_human_adjacency, mode = "undirected", weighted = TRUE)
V(g)$k <- df_human_clusters$nk2[1:n]
g <- simplify(g)
# g <- delete.vertices(g, degree(g) < 6)
# layout <- layout_with_drl(g)
layout <- layout_nicely(g)
plot(g, layout = layout, vertex.size = 3, vertex.label = NA, vertex.color = ifelse(V(g)$k == 1, "yellow", "red"), edge.width = 3*edge.betweenness(g)/max(edge.betweenness(g)))

```

```{r}
length(E(g))
```



```{r}
g <- graph_from_adjacency_matrix(mat_human_affinity_test[1:10, 1:10], mode = "upper", diag = FALSE)
plot(g)
```

