---
title: "Human cluster characteristics"
author: "Antoine Beauchamp"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(RMINC))
```

```{r functions}
source("../../src/utils.R")
source("../../src/processing.R")
# source("../../src/analysis.R")
```


```{r parameters}
#Output directory
output_dir <- "outputs/human_cluster_characteristics/"

#Human directories
version <- "v2"

registration_dir <- "../../data/human/registration/"
registration_dir <- file.path(registration_dir, version)

pipeline_dir <- "../../data/human/derivatives/"
pipeline_dir <- file.path(pipeline_dir, version)

#Human parameters
resolution <- 0.8
es_method <- "normative-growth"
es_df <- 3
cluster_map_method <- "mean"

metadata <- file.path(pipeline_dir, "metadata.csv")
params <- fetch_params_metadata(metadata = metadata,
                                resolution = resolution,
                                es_method = es_method,
                                es_df = es_df,
                                cluster_map_method = cluster_map_method)
params
```



```{r}
#Parameter set ID
params_id <- 700

#Pipeline directory
pipeline_dir <- file.path(pipeline_dir, params_id)

#Cluster resolution
cluster_resolution <- params[["cluster_resolution"]]
cluster_resolution <- sprintf("%.1f", cluster_resolution)

#Cluster directory
cluster_dir <- file.path(pipeline_dir, "clusters", paste0("resolution_", cluster_resolution))

#Output directory
output_dir <- file.path(output_dir, version, params_id)
if (!(dir.exists(output_dir))) {dir.create(output_dir, recursive = TRUE)}
```

```{r}
demographics <- file.path(registration_dir, "subject_info", "demographics.csv")
demographics <- read_csv(demographics, show_col_types = FALSE)
```

```{r}
clusters <- file.path(cluster_dir, "clusters.csv")
clusters <- read_csv(clusters, show_col_types = FALSE)
```

# 2-cluster total volume


```{r}
clusters_vol <- clusters %>% 
  mutate(absolute = 0,
         relative = 0)
```

```{r eval = FALSE}
# res <- params[["resolution"]]
res <- 3.0

# mask <- file.path(registration_dir, "reference_files", "mask_0.8mm.mnc")
mask <- file.path(registration_dir, "reference_files", "mask_3.0mm.mnc")

jacobians <- c("absolute", "relative")
jacobians_dir <- file.path(registration_dir, "jacobians_resampled", "resolution_3.0", jacobians)
names(jacobians_dir) <- jacobians

for (j in jacobians) {
  
  imgfiles <- clusters_vol[["ID"]]
  imgfiles <- file.path(jacobians_dir[[j]], imgfiles)
  voxels <- import_images(imgfiles, mask = mask, output_format = "matrix", 
                          inparallel = TRUE, nproc = 4)
  voxels <- (res^3)*exp(voxels)
  volumes <- rowSums(voxels)
  clusters_vol[[j]] <- volumes*(0.1^3)
}
```

```{r eval = FALSE}
p_cluster_vol <- ggplot(clusters_vol, aes(x = factor(nk2), y = absolute)) + 
  geom_jitter(col = "grey70") + 
  geom_boxplot(alpha = 0.5) + 
  labs(x = "Cluster ID", 
       y = "Total absolute volume (cm^3)",
       title = "Total brain volume comparison for human 2-cluster solution") + 
  theme_bw()

outfile <- "cluster_volumes_nk2.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(10, "in"))
print(p_cluster_vol)
dev.off()
```

```{r eval = FALSE}
df_model <- clusters_vol %>% 
  select(cluster = nk2, volume = absolute) %>% 
  mutate(cluster = factor(cluster))

summary(lm(volume ~ cluster, data = df_model))
```

# Cluster diagnoses


```{r}
demographics <- demographics %>% 
  filter(!is.na(DX),
         !is.na(Age),
         !is.na(Sex),
         !is.na(Site),
         !is.na(Scanner))

cluster_demographics <- clusters %>% 
  left_join(demographics, by = c("ID" = "file"))

df_diagnoses <- tibble(DX = c("ASD", "OCD", "ADHD", "Sub-threshold OCD", "Anxiety", "Sub-threshold ADHD", "Intellectual Disability only", "Tourette Syndrome", "Other", "Fragile X"),
                       DX_new = c("ASD", "OCD", "ADHD", "OCD", "Other", "ADHD", "Other", "Other", "Other", "Other"))

cluster_demographics <- cluster_demographics %>% 
  left_join(df_diagnoses, by = "DX")
```


```{r}
dx_lvls <- c("ASD", "ADHD", "OCD", "Other")

nk_max <- 10
chi2_pvals <- numeric(nk_max-1)
for (nk in 2:nk_max) {
  
  df_tmp <- cluster_demographics %>% 
    select(k = paste0("nk", nk), DX_new) %>% 
    mutate(k = factor(k),
           DX_new = factor(DX_new, levels = dx_lvls))
  
  chi2 <- chisq.test(x = df_tmp$k, y = df_tmp$DX_new, simulate.p.value = TRUE, B = 1e5)
  
  diagnoses_grid <- expand_grid(DX_new = df_diagnoses$DX_new,
                                k = 1:nk)
  
  
  df_prop_nk <- cluster_demographics %>% 
    select(k = paste0("nk", nk), DX_new) %>% 
    group_by(k) %>% 
    mutate(n_per_k = n()) %>% 
    group_by(k, DX_new) %>% 
    mutate(n_per_k_per_dx = n(),
           prop_per_k_per_dx = n_per_k_per_dx/n_per_k) %>% 
    ungroup() %>% 
    distinct() %>% 
    right_join(diagnoses_grid, by = c("k", "DX_new")) %>% 
    mutate(prop_per_k_per_dx = ifelse(is.na(prop_per_k_per_dx), 0, prop_per_k_per_dx),
           k = factor(k),
           DX_new = factor(DX_new, levels = dx_lvls))
  
  p_dx_nk <- ggplot(df_prop_nk, 
                    aes(x = k, y = prop_per_k_per_dx, fill = DX_new)) +
    geom_col(position = "dodge") +
    labs(x = "k",
         y = "Proportion per cluster",
         fill = "Diagnosis",
         caption = paste("Chi-squared test p-value:", round(chi2$p.value, 4))) + 
    theme_bw() 
  
  outfile <- paste0("dx_proportions_nk_", nk, ".pdf")
  outfile <- file.path(output_dir, outfile)
  pdf(file = outfile,
      width = unit(10, "inch"),
      height = unit(5, "inch"))
  print(p_dx_nk)
  dev.off()
  
  
}
```


## Fragile X

```{r}
df_fxs <- cluster_demographics %>% 
  filter(DX == "Fragile X")

df_fxs
```

```{r}
mouse_clusters <- "../../data/mouse/derivatives/v2/107/clusters/clusters.csv"
mouse_clusters <- read_csv(mouse_clusters, show_col_types = FALSE)
colnames(mouse_clusters) <- c("ID", str_c("nk", 2:10))

ind_fmr1 <- str_detect(mouse_clusters[["ID"]], "Fmr1")
mouse_clusters[ind_fmr1,]
```

Human FXS patient and mouse models are in matching clusters in nk = 2, 3, 4, 5. Then we have H6-1 to M6-6, which is not significant. After that the two mouse models aren't even in the same cluster. H7-1 and M7-5 have p = 0.09. No significant match at nk = 8, 9, or 10.


```{r}
pond_genetics <- file.path(registration_dir, "subject_info", "POND_variants.xlsx")
pond_genetics <- read_excel(pond_genetics)

fxs_id <- df_fxs[["Subject_ID"]] %>% 
  str_remove("POND_")

pond_genetics %>% 
  filter(POND_ID == fxs_id)
```

No identified variant for the FXS patient.


# POND clinical scores

```{r}
pond_clinical <- "../../data/human/registration/v2/subject_info/POND_clinical_scores.csv"
pond_clinical <- read_csv(pond_clinical, show_col_types = FALSE)

View(pond_clinical)
```



```{r}
colnames(pond_clinical) %>% 
  str_subset("CB68.*TOT")
```

What's the best way to look at this?

```{r}
clinical_scales <- c("CB68IPPER",
                     "CB68EPPER",
                     "CB68TPPER",
                     "FULL_IQ_SUMMARY",
                     "VERBAL_IQ_SUMMARY",
                     "PREFORM_IQ_SUMMARY",
                     "SBFULLIQ",
                     "SCQTOT",
                     "SCQTOT_C",
                     "ADHD_I_SUB",
                     "ADHD_HI_SUB",
                     "TPOCS_TOT")

pond_clinical_subset <- pond_clinical[, c("SUBJECT", clinical_scales)]

head(pond_clinical_subset)
```

```{r}
clusters_clinical <- clusters %>% 
  left_join(demographics, by = c("ID" = "file")) %>% 
  mutate(Subject_ID = str_remove(Subject_ID, "POND_")) %>% 
  filter(Dataset == "POND") %>% 
  mutate(Subject_ID = as.numeric(Subject_ID)) %>% 
  left_join(pond_clinical_subset, by = c("Subject_ID" = "SUBJECT"))

# Convert cluster data to long format
clusters_long <- clusters %>% 
  pivot_longer(cols = -ID, names_to = "nk", values_to = "k") %>% 
  mutate(nk = str_remove(nk, "nk"),
         nk = as.numeric(nk),
         k = as.numeric(k)) %>% 
  unite(col = "cluster_id", nk, k, sep = "-", remove = FALSE)

# Number of participants per cluster
cluster_counts <- clusters_long %>% 
  group_by(cluster_id, nk, k) %>% 
  count() %>% 
  ungroup() %>% 
  arrange(nk, k)
```

```{r}
nk_max <- max(cluster_counts["nk"])

df_anova <- expand_grid(nk = 2:nk_max,
                        scale = clinical_scales) %>% 
  mutate(Fval = 0, pval = 0, npatients = 0)
for (i in 1:nrow(df_anova)) {
  
  nk <- df_anova[[i, "nk"]]
  s <- df_anova[[i, "scale"]]
  
  labels <- clusters_clinical[[paste0("nk", nk)]]
  scores <- clusters_clinical[[s]]
  
  missing <- is.na(scores)
  labels <- labels[!missing]
  scores <- scores[!missing]
  
  anova <- summary(aov(scores ~ factor(labels)))
  df_anova[[i, "Fval"]] = anova[[1]][[1,"F value"]]
  df_anova[[i, "pval"]] = anova[[1]][[1,"Pr(>F)"]]
  df_anova[[i, "npatients"]] = length(labels)
  
}


min_groupsize <- 50
df_anova_large <- expand_grid(nk = 2:nk_max,
                              scale = clinical_scales) %>% 
  mutate(Fval = 0, pval = 0, npatients = 0)
for (i in 1:nrow(df_anova_large)) {

    nk <- df_anova_large[[i, "nk"]]
  s <- df_anova_large[[i, "scale"]]
  
  ind_nk <- cluster_counts[["nk"]] == nk
  cluster_counts_nk <- cluster_counts[ind_nk,]
  ind_groupsize <- cluster_counts_nk[["n"]] > min_groupsize
  labels_pass <- cluster_counts_nk[ind_groupsize, "k"][[1]]
  
  labels <- clusters_clinical[[paste0("nk", nk)]]
  scores <- clusters_clinical[[s]]
  
  missing <- is.na(scores)
  labels <- labels[!missing]
  scores <- scores[!missing]
  
  labels_filter <- labels %in% labels_pass
  labels <- labels[labels_filter]
  scores <- scores[labels_filter]
  
  anova <- summary(aov(scores ~ factor(labels)))
  df_anova_large[[i, "Fval"]] = anova[[1]][[1,"F value"]]
  df_anova_large[[i, "pval"]] = anova[[1]][[1,"Pr(>F)"]]
  df_anova_large[[i, "npatients"]] = length(labels)
  
}
```

```{r}
df_anova_p <- df_anova %>% 
  mutate(nk = factor(nk), 
         scale = factor(scale, levels = clinical_scales),
         pval_log = -log10(pval),
         significant = ifelse(pval < 0.05, "*", NA))

df_anova_large_p <- df_anova_large %>% 
  mutate(nk = factor(nk), 
         scale = factor(scale, levels = clinical_scales),
         pval_log = -log10(pval),
         significant = ifelse(pval < 0.05, "*", NA))
  
library(RColorBrewer)

ggplot(df_anova_p,
       aes(x = nk, y = scale, fill = pval_log)) + 
  geom_tile(col = "black") +
  geom_text(mapping = aes(label = significant)) + 
  scale_fill_gradientn(colours = brewer.pal(n = 9, name = "Reds")) +
  labs(x = "nk",
       y = "Clinical scale",
       fill = "-log10(p)")
```
```{r}
ggplot(df_anova_large_p,
       aes(x = nk, y = scale, fill = pval_log)) + 
  geom_tile(col = "black") +
  geom_text(mapping = aes(label = significant)) + 
  scale_fill_gradientn(colours = brewer.pal(n = 9, name = "Reds")) +
  labs(x = "nk",
       y = "Clinical scale",
       fill = "-log10(p)")
```
```{r}
npatients_tot <- nrow(clusters_clinical)

df_scale_completion <- df_anova_p %>% 
  select(scale, completed = npatients) %>% 
  distinct() %>% 
  mutate(missing = npatients_tot - completed) %>% 
  pivot_longer(cols = -scale, names_to = "classification", values_to = "n") %>% 
  mutate(completed = ifelse(classification == "completed", TRUE, FALSE))

ggplot(df_scale_completion,
       aes(x = n, y = scale, fill = completed)) + 
  geom_col(col = "black") +
  scale_fill_manual(values = c("grey70", brewer.pal(n = 9, name = "Reds")[8])) +
  scale_x_continuous(expand = expansion(),
                     breaks = seq(0, 600, by = 50)) +
  scale_y_discrete(expand = expansion()) +
  labs(x = "Number of patients",
       y = "Clinical scale",
       fill = "Completed")
```
```{r}
library(ggbeeswarm)
```


```{r}
clusters_clinical %>% 
  select(k = nk2, y = SCQTOT_C) %>% 
  ggplot(aes(x = factor(k), y = y)) + 
  geom_beeswarm(col = "grey50") + 
  geom_boxplot(outlier.shape = NA,
               alpha = 0.3) +
  theme_bw()
```

```{r}
clusters_clinical %>% 
  select(k = nk6, y = SCQTOT_C) %>% 
  ggplot(aes(x = factor(k), y = y)) + 
  geom_beeswarm(col = "grey50") + 
  geom_boxplot(outlier.shape = NA,
               alpha = 0.3) +
  theme_bw()
```


```{r}
clusters_clinical %>% 
  select(k = nk2, y = PREFORM_IQ_SUMMARY) %>% 
  ggplot(aes(x = factor(k), y = y)) + 
  geom_beeswarm(col = "grey50") + 
  geom_boxplot(outlier.shape = NA,
               alpha = 0.3) +
  theme_bw()
```

```{r}
clusters_clinical %>% 
  select(k = nk2, y = VERBAL_IQ_SUMMARY) %>% 
  ggplot(aes(x = factor(k), y = y)) + 
  geom_beeswarm(col = "grey50") + 
  geom_boxplot(outlier.shape = NA,
               alpha = 0.3) +
  theme_bw()
```

```{r}
clusters_clinical %>% 
  select(k = nk2, y = FULL_IQ_SUMMARY) %>% 
  ggplot(aes(x = factor(k), y = y)) + 
  geom_beeswarm(col = "grey50") + 
  geom_boxplot(outlier.shape = NA,
               alpha = 0.3) +
  theme_bw()
```



```{r}
tmp1 <- clusters_clinical %>% 
  select(Subject_ID,
         CB68IPPER,
         CB68EPPER,
         CB68TPPER,
         FULL_IQ_SUMMARY,
         SBFULLIQ,
         WISC_IV_FSIQ_PERCENT,
         WISC_V_FSIQ_PERCENT,
         WPPSI_IV47_FSIQ_PR,
         SCQTOT,
         SCQTOT_C,
         ADHD_I_SUB,
         ADHD_HI_SUB,
         TPOCS_TOT)

scales <-  c("FULL_IQ_SUMMARY","SBFULLIQ", "WISC_IV_FSIQ_PERCENT", "WISC_V_FSIQ_PERCENT", "WPPSI_IV47_FSIQ_PR",
             "CB68IPPER", "CB68EPPER", "CB68TPPER",
             "SCQTOT", "SCQTOT_C",
             "ADHD_I_SUB",
             "ADHD_HI_SUB",
             "TPOCS_TOT")

tmp1 <- tmp1 %>% 
  pivot_longer(cols = -Subject_ID, names_to = "Scale", values_to = "Score") %>% 
  mutate(Exists = ifelse(is.na(Score), 0, 1),
         Subject_ID = factor(Subject_ID),
         Scale = factor(Scale, levels = scales),
         Exists = factor(Exists))
```


```{r fig.width = 20, fig.height = 4}
ggplot(tmp1, aes(x = Subject_ID, y = fct_rev(Scale), fill = Exists)) + 
  geom_tile(show.legend = FALSE, col = "grey30") +
  labs(x = "Participants",
       y = "Clinical Assessments",
       title = "POND participant clinical assessment completion") + 
  scale_fill_manual(values = c("white", "red")) + 
  scale_x_discrete(expand = expansion()) + 
  scale_y_discrete(expand = expansion()) + 
  theme_bw() + 
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```



```{r}
tmp2 <- clusters_clinical %>% 
  select(nk2, nk5, nk9,         
         CB68IPPER,
         CB68EPPER,
         CB68TPPER,
         SCQTOT,
         SCQTOT_C,
         ADHD_I_SUB,
         ADHD_HI_SUB,
         TPOCS_TOT,
         FULL_IQ_SUMMARY,
         SBFULLIQ,
         WISC_IV_FSIQ_PERCENT,
         WISC_V_FSIQ_PERCENT)
```


```{r}
tmp2_long <- tmp2 %>% 
  pivot_longer(cols = c(nk2, nk5, nk9), names_to = "nk", values_to = "k") %>% 
  mutate(nk = str_remove(nk, "nk"),
         k = factor(k, levels = 1:9))
```

```{r}
cols <- colnames(tmp2_long)[!(colnames(tmp2_long) %in% c("nk", "k"))]

outfile <- "cluster_clinical_scores.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(8, "in"),
    height = unit(8, "in"))

for (col in cols) {
  
  p <- tmp2_long %>% 
    mutate(k = fct_rev(k)) %>% 
    ggplot(aes_string(x = col, y = "k")) + 
    geom_jitter(width = 0.3, col = "grey70") + 
    geom_boxplot(alpha = 0.5, outlier.shape = NA) + 
    facet_wrap(~nk, ncol = 3) + 
    labs(x = "Score",
         y = "k",
         title = col) + 
    theme_bw()
  
  print(p)
}

dev.off()
```


```{r}
p1 <- tmp2_long %>% 
  ggplot(aes(x = CB68TPPER, y = fct_rev(k))) + 
  geom_jitter(width = 0.3, col = "grey70") + 
  geom_boxplot(alpha = 0.5, outlier.shape = NA) + 
  facet_wrap(~nk, ncol = 3) + 
  coord_cartesian(xlim = c(0, 100)) +
  labs(x = "Percentile rank",
       y = "k",
       title = "CB68 Total Problems") + 
  theme_bw()

outfile <- "test.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(8, "in"),
    height = unit(8, "in"))
print(p1)
print(p2)
dev.off()
```

```{r}
p2 <- tmp2_long %>% 
  ggplot(aes(x = CB68TPPER, y = fct_rev(k))) + 
  geom_jitter(width = 0.3, col = "grey70") + 
  geom_boxplot(alpha = 0.5, outlier.shape = NA) + 
  facet_wrap(~nk, ncol = 3) + 
  coord_cartesian(xlim = c(0, 100)) +
  labs(x = "Percentile rank",
       y = "k",
       title = "CB68 Total Problems") + 
  theme_bw()
```


```{r}
tmp2_long %>% 
  ggplot(aes(x = CB68IPPER, y = fct_rev(k))) + 
  geom_jitter(width = 0.3, col = "grey70") + 
  geom_boxplot(alpha = 0.5, outlier.shape = NA) + 
  facet_wrap(~nk, ncol = 3) + 
  coord_cartesian(xlim = c(0, 100)) +
  labs(x = "Percentile rank",
       y = "k",
       title = "CB68 Internalizing Problems") + 
  theme_bw()
```


```{r}
tmp2_long %>% 
  ggplot(aes(x = CB68EPPER, y = fct_rev(k))) + 
  geom_jitter(width = 0.3, col = "grey70") + 
  geom_boxplot(alpha = 0.5, outlier.shape = NA) + 
  facet_wrap(~nk, ncol = 3) + 
  coord_cartesian(xlim = c(0, 100)) +
  labs(x = "Percentile rank",
       y = "k",
       title = "CB68 Externalizing Problems") + 
  theme_bw()
```

```{r}
tmp2_long %>% 
  ggplot(aes(x = FULL_IQ_SUMMARY, y = fct_rev(k))) + 
  geom_jitter(width = 0.3, col = "grey70") + 
  geom_boxplot(alpha = 0.5, outlier.shape = NA) + 
  facet_wrap(~nk, ncol = 3) + 
  labs(x = "Score",
       y = "k",
       title = "Full IQ summary") + 
  theme_bw()
```

```{r}
tmp2_long %>% 
  ggplot(aes(x = SCQTOT, y = fct_rev(k))) + 
  geom_jitter(width = 0.3, col = "grey70") + 
  geom_boxplot(alpha = 0.5, outlier.shape = NA) + 
  facet_wrap(~nk, ncol = 3) + 
  labs(x = "Score",
       y = "k",
       title = "SCQ total score") + 
  theme_bw()
```

```{r}
tmp2_long %>% 
  ggplot(aes(x = ADHD_I_SUB, y = fct_rev(k))) + 
  geom_jitter(width = 0.3, col = "grey70") + 
  geom_boxplot(alpha = 0.5, outlier.shape = NA) + 
  facet_wrap(~nk, ncol = 3) + 
  labs(x = "Score",
       y = "k",
       title = "SWAN 'ADHD_I") + 
  theme_bw()
```


```{r}
tmp2_long %>% 
  ggplot(aes(x = ADHD_HI_SUB, y = fct_rev(k))) + 
  geom_jitter(width = 0.3, col = "grey70") + 
  geom_boxplot(alpha = 0.5, outlier.shape = NA) + 
  facet_wrap(~nk, ncol = 3) + 
  labs(x = "Score",
       y = "k",
       title = "SWAN 'ADHD_HI") + 
  theme_bw()
```

```{r}
tmp2_long %>% 
  ggplot(aes(x = TPOCS_TOT, y = fct_rev(k))) + 
  geom_jitter(width = 0.3, col = "grey70") + 
  geom_boxplot(alpha = 0.5, outlier.shape = NA) + 
  facet_wrap(~nk, ncol = 3) + 
  labs(x = "Score",
       y = "k",
       title = "TOCS total score") + 
  theme_bw()
```


