---
title: "Human cluster genetics"
author: "Antoine Beauchamp"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(ggalluvial))
```

```{r functions}
source("../../src/utils.R")
# source("../../src/processing.R")
# source("../../src/analysis.R")
```

```{r parameters}
#Output directory
output_dir <- "outputs/human_cluster_genetics/"

#Human directories
version <- "v3"

registration_dir <- "../../data/human/registration/"
registration_dir <- file.path(registration_dir, version)

pipeline_dir <- "../../data/human/derivatives/"
pipeline_dir <- file.path(pipeline_dir, version)

#Human parameters
resolution <- 0.8
es_method <- "normative-growth"
es_df <- 3
centroid_method <- "mean"

metadata <- file.path(pipeline_dir, "metadata.csv")
params <- fetch_params_metadata(metadata = metadata,
                                resolution = resolution,
                                es_method = es_method,
                                es_df = es_df,
                                centroid_method = centroid_method)
params
```

```{r}
#Parameter set ID
params_id <- "700"

#Pipeline directory
pipeline_dir <- file.path(pipeline_dir, params_id)

#Cluster resolution
cluster_resolution <- params %>% 
  filter(id == params_id) %>% 
  pull(cluster_resolution)
cluster_resolution <- sprintf("%.1f", cluster_resolution)

#Cluster directory
cluster_dir <- file.path(pipeline_dir, "clusters", paste0("resolution_", cluster_resolution))

#Output directory
output_dir <- file.path(output_dir, version, params_id)
if (!(dir.exists(output_dir))) {dir.create(output_dir, recursive = TRUE)}
```

```{r}
genetics <- file.path(registration_dir, "subject_info", "POND_variants.xlsx")
genetics <- read_excel(genetics)
genetics <- genetics %>% 
  filter(!(SUBJECT_ID_INT %in% c("SK0664-003", "SK1016-003", "QAM-22961A2"))) %>% 
  select(POND_ID, 
         `SIGNIFICANT VARIANT TYPE`,
         `SIGNIFICANT VARIANT`,
         `CLASSIFICATION`) %>%
  filter(str_detect(POND_ID, "POND-[a-zA-Z]+.*", negate = TRUE),
         str_detect(POND_ID, ";", negate = TRUE)) %>% 
  mutate(POND_ID = str_remove(POND_ID, "-")) %>% 
  distinct()

ids_multiple <- genetics %>% 
  group_by(POND_ID) %>% 
  count() %>% 
  filter(n > 1) %>% 
  pull(POND_ID)

genetics_repeats <- genetics %>% 
  filter(POND_ID %in% ids_multiple) %>% 
  arrange(POND_ID)

genetics_unique <- genetics %>% 
  filter(!(POND_ID %in% ids_multiple)) %>% 
  arrange(POND_ID)

genetics_repeats_unique <- genetics_repeats %>% 
  filter(!is.na(CLASSIFICATION))

genetics <- bind_rows(genetics_unique, 
                      genetics_repeats_unique)

demographics <- file.path(registration_dir, "subject_info", "demographics.csv")
demographics <- read_csv(demographics, show_col_types = FALSE)

clusters <- file.path(cluster_dir, "clusters.csv")
clusters <- read_csv(clusters, show_col_types = FALSE)
clusters <- clusters %>% 
  left_join(demographics %>% 
              select(Subject_ID, file),
            by = c("ID" = "file")) %>% 
  mutate(Subject_ID = str_remove(Subject_ID, "POND_"),
         Subject_ID = str_remove(Subject_ID, "sub-"))

clusters_genetics <- clusters %>% 
  left_join(genetics, by = c("Subject_ID" = "POND_ID")) %>% 
  mutate(gene_identified = !is.na(CLASSIFICATION)) %>% 
  distinct()
```

```{r}
sum(clusters_genetics$gene_identified)
```


```{r eval = FALSE}
df_clusters_long <- clusters_genetics %>% 
  select(ID, contains("nk"), gene_identified) %>% 
  pivot_longer(cols = c(-ID, -gene_identified),names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         nk = factor(nk),
         k = factor(k))

df_clusters_gene_counts <- df_clusters_long %>% 
  group_by(nk, k) %>% 
  summarise(ngenes = sum(gene_identified), .groups = "drop")

df_clusters_long <- df_clusters_long %>% 
  left_join(df_clusters_gene_counts, by = c("nk", "k"))

df_clusters_long <- df_clusters_long %>% 
  mutate(ngenes = ifelse(ngenes == 0, NA, ngenes))

clusters_w_matches <- c("2-1", "2-2", 
                        "3-1", "3-3", 
                        "4-1", "4-2", "4-3", 
                        "5-2", "5-5", 
                        "6-2", "6-6",
                        "7-1", "7-2", "7-4",
                        "8-1", "8-2", "8-4", "8-6", "8-7",
                        "9-4", "9-5", "9-7",
                        "10-10")

p_sankey_genes <- ggplot(df_clusters_long,
                         aes(x = nk, stratum = k,
                             alluvium = ID,
                             fill = ngenes)) +
  geom_flow(stat = "alluvium", aes.flow = "forward") +
  geom_stratum() +
  scale_fill_gradientn(colors = brewer.pal(n = 9, name = "OrRd")[2:9],
                       breaks = seq(0, 12, 2)) +
  labs(x = "Number of clusters",
       y = "Number of patients",
       fill = "Identified variants",
       title = "Human clusters with identified genetic variants") +
  theme_bw() +
  theme(panel.grid.major.x = element_blank())

outfile <- "sankey_gene_variants.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_sankey_genes)
dev.off()
```


```{r}
df_variants_long <- df_clusters_long %>% 
  select(ID, nk, k) %>% 
  left_join(clusters_genetics %>% 
              select(ID, Subject_ID, 
                     gene_identified,
                     `SIGNIFICANT VARIANT`, 
                     `SIGNIFICANT VARIANT TYPE`,
                     CLASSIFICATION),
            by = "ID") %>% 
  filter(gene_identified > 0) %>% 
  select(-ID, -gene_identified) %>% 
  arrange(nk, k) %>% 
  unite("cluster", nk, k, sep = "-")

outfile <- "cluster_variants_long.csv"
outfile <- file.path(output_dir, outfile)
write_csv(df_variants_long, outfile)
```

```{r}
fxs_file <- demographics %>% 
  filter(DX == "Fragile X") %>% 
  pull(file)

df_variants <- clusters_genetics %>% 
  filter(gene_identified > 0 | ID == fxs_file) %>% 
  select(Subject_ID, ID, contains("nk"),
         significant_variant = `SIGNIFICANT VARIANT`, 
         significant_variant_type = `SIGNIFICANT VARIANT TYPE`,
         classification = CLASSIFICATION) %>% 
  mutate(significant_variant = ifelse(ID == fxs_file, "FMR1", significant_variant),
         classification = ifelse(significant_variant == "FMR1", "Diagnosis", classification)) %>% 
  select(-ID) %>% 
  arrange(nk2, nk3)

outfile <- "cluster_variants.csv"
outfile <- file.path(output_dir, outfile)
write_csv(df_variants, outfile)
```


```{r}
library(ggbeeswarm)

clusters_w_matches <- c("2-1", "2-2", 
                        "3-1", "3-3", 
                        "4-1", "4-2", "4-3", 
                        "5-2", "5-5", 
                        "6-2", "6-6",
                        "7-1", "7-2", "7-4",
                        "8-1", "8-2", "8-4", "8-6", "8-7",
                        "9-4", "9-5", "9-7",
                        "10-10")

df_gene_counts_matches <- df_clusters_gene_counts %>% 
  mutate(nk = as.numeric(as.character(nk)),
         k = as.numeric(as.character(k))) %>% 
  unite(col = "cluster_id", nk, k, sep = "-", remove = FALSE) %>% 
  mutate(has_match = cluster_id %in% clusters_w_matches)

p_genes_and_matches <- ggplot(df_gene_counts_matches, 
       aes(x = has_match, y = ngenes, col = factor(nk))) + 
  geom_beeswarm(cex = 2.0) +
  coord_cartesian(ylim = c(0, 15)) + 
  scale_x_discrete(labels = c("No", "Yes")) + 
  scale_y_continuous(breaks = seq(0, 20, 2)) + 
  labs(x = "Mouse match",
       y = "Patients with identified variants",
       col = "Number of clusters") + 
  theme_bw()

outfile <- "gene_variants_and_matches.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(6, "in"),
    height = unit(5, "in"))
print(p_genes_and_matches)
dev.off()
```

```{r}
p_genes_and_matches_bar <- df_gene_counts_matches %>% 
  ggplot(aes(x = factor(k), y = ngenes, fill = has_match)) + 
  geom_col() + 
  facet_wrap(~nk, ncol = 3) + 
  scale_fill_discrete(labels = c("No", "Yes")) + 
  labs(x = "Cluster",
       y = "Patients with identified variants",
       fill = "Mouse match") + 
  theme_bw() 

outfile <- "gene_variants_and_matches_bar.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_genes_and_matches_bar)
dev.off()
```

```{r}
p_genes_and_matches_bar_agg <- df_gene_counts_matches %>% 
  group_by(nk, has_match) %>% 
  summarise(ngenes = sum(ngenes), 
            .groups = "drop") %>% 
  ggplot(aes(x = factor(nk), y = ngenes, fill = has_match)) +
  geom_col(position = "dodge") +
  scale_fill_discrete(labels = c("No", "Yes")) + 
  labs(x = "Number of clusters",
       y = "Patients with identified variants",
       fill = "Cluster matches mouse") + 
  theme_bw()

outfile <- "gene_variants_and_matches_bar_agg.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_genes_and_matches_bar_agg)
dev.off()
```


```{r}
p_genes_and_matches_bar <- df_gene_counts_matches %>% 
  ggplot(aes(x = factor(k), y = ngenes, fill = has_match)) + 
  geom_col() + 
  facet_wrap(~nk, ncol = 3) + 
  scale_fill_discrete(labels = c("No", "Yes")) + 
  labs(x = "Cluster",
       y = "Patients with identified variants",
       fill = "Mouse match") + 
  theme_bw() 

outfile <- "gene_variants_and_matches_bar.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(5, "in"))
print(p_genes_and_matches_bar)
dev.off()
```


# Comparison with mouse models

```{r}
mouse_clusters <- "../../data/mouse/derivatives/v2/107/clusters/clusters.csv"
mouse_clusters <- read_csv(mouse_clusters, show_col_types = FALSE)
colnames(mouse_clusters) <- c("ID", str_c("nk", 2:10))


```

## 22q11

```{r}
df_variants <- df_variants %>% 
  rename(variant = `SIGNIFICANT VARIANT`)
```

```{r}
gene_str <- "22q11"

df_variants %>% 
  filter(str_detect(variant, gene_str)) %>% 
  select(contains("nk")) %>% 
  pivot_longer(cols = everything(), names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         k = as.numeric(k)) %>% 
  unite(col = "cluster_id", nk, k, sep = "-",
        remove = FALSE) %>% 
  arrange(nk) %>% 
  pull(cluster_id)
```

```{r}
mouse_clusters %>% 
  filter(str_detect(ID, gene_str)) %>% 
  select(contains("nk")) %>% 
  pivot_longer(cols = everything(), names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         k = as.numeric(k)) %>% 
  unite(col = "cluster_id", nk, k, sep = "-",
        remove = FALSE) %>% 
  arrange(nk) %>% 
  pull(cluster_id)
```
Matches: 2, 3, 4, 5
No match 6-10

## PTEN

```{r}
gene_str <- "PTEN"

df_variants %>% 
  filter(str_detect(variant, gene_str)) %>% 
  select(contains("nk")) %>% 
  pivot_longer(cols = everything(), names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         k = as.numeric(k)) %>% 
  unite(col = "cluster_id", nk, k, sep = "-",
        remove = FALSE) %>% 
  arrange(nk) %>% 
  pull(cluster_id)
```


```{r}
gene_str <- "Pten"

mouse_clusters %>% 
  filter(str_detect(ID, gene_str)) %>% 
  select(contains("nk")) %>% 
  pivot_longer(cols = everything(), names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         k = as.numeric(k)) %>% 
  unite(col = "cluster_id", nk, k, sep = "-",
        remove = FALSE) %>% 
  arrange(nk) %>% 
  pull(cluster_id)
```

Matches: 2
Non-matches: 3-10

## TSC1

```{r}
gene_str <- "TSC1"

df_variants %>% 
  filter(str_detect(variant, gene_str)) %>% 
  select(contains("nk")) %>% 
  pivot_longer(cols = everything(), names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         k = as.numeric(k)) %>% 
  unite(col = "cluster_id", nk, k, sep = "-",
        remove = FALSE) %>% 
  arrange(nk) %>% 
  pull(cluster_id)
```

```{r}
gene_str <- "Tsc1"

mouse_clusters %>% 
  filter(str_detect(ID, gene_str)) %>% 
  select(contains("nk")) %>% 
  pivot_longer(cols = everything(), names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         k = as.numeric(k)) %>% 
  unite(col = "cluster_id", nk, k, sep = "-",
        remove = FALSE) %>% 
  arrange(nk) %>% 
  pull(cluster_id)
```
Matches: None
Non-matches: 2-10

## NRXN1

```{r}
gene_str <- "NRXN1"

df_variants %>% 
  filter(str_detect(variant, gene_str)) %>% 
  select(contains("nk")) %>% 
  pivot_longer(cols = everything(), names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         k = as.numeric(k)) %>% 
  unite(col = "cluster_id", nk, k, sep = "-",
        remove = FALSE) %>% 
  arrange(nk) %>% 
  pull(cluster_id)
```

```{r}
gene_str <- "Nrxn1"

mouse_clusters %>% 
  filter(str_detect(ID, gene_str)) %>% 
  select(contains("nk")) %>% 
  pivot_longer(cols = everything(), names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         k = as.numeric(k)) %>% 
  unite(col = "cluster_id", nk, k, sep = "-",
        remove = FALSE) %>% 
  arrange(nk) %>% 
  pull(cluster_id)
```
Matches: None
Non-matches: All


## NLGN1

```{r}
gene_str <- "NLGN1"

df_variants %>% 
  filter(str_detect(variant, gene_str)) %>% 
  select(contains("nk")) %>% 
  pivot_longer(cols = everything(), names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         k = as.numeric(k)) %>% 
  unite(col = "cluster_id", nk, k, sep = "-",
        remove = FALSE) %>% 
  arrange(nk) %>% 
  pull(cluster_id)
```

```{r}
gene_str <- "Nl1"

mouse_clusters %>% 
  filter(str_detect(ID, gene_str)) %>% 
  select(contains("nk")) %>% 
  pivot_longer(cols = everything(), names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk),
         k = as.numeric(k)) %>% 
  unite(col = "cluster_id", nk, k, sep = "-",
        remove = FALSE) %>% 
  arrange(nk) %>% 
  pull(cluster_id)
```
Matches: 3, 6 (0.09), 7 (0.08), 8 (0.1)
Non-matches:  2, 4, 5, 9, 10



# Some old stuff

```{r}
genetics %>% 
  mutate(gene_identified = ifelse(is.na(CLASSIFICATION), 0, 1)) %>% 
  select(POND_ID, gene_identified) %>% 
  distinct() %>% 
  group_by(gene_identified) %>% 
  summarise(count = n(),
            frac = n()/nrow(.))
```


```{r}
genetics_tmp <- genetics %>% 
  mutate(has_genetics = TRUE,
         gene_identified = ifelse(is.na(CLASSIFICATION), FALSE, TRUE))

demographics_tmp <- demographics %>% 
  mutate(Subject_ID = str_remove(Subject_ID, "POND_"),
         has_imaging = TRUE) %>% 
  filter(DX != "Control")

data_full <- full_join(demographics_tmp, genetics_tmp, by = c("Subject_ID" = "POND_ID")) %>% 
  mutate(has_genetics = ifelse(is.na(has_genetics), FALSE, TRUE),
         has_imaging = ifelse(is.na(has_imaging), FALSE, TRUE),
         Dataset = ifelse(is.na(Dataset), "POND", Dataset)) 

data_full %>% 
  filter(has_imaging) %>% 
  group_by(has_genetics) %>% 
  count()
```

```{r}
data_full_pond <- filter(data_full, Dataset == "POND") %>% 
  mutate(category = case_when(has_imaging & !has_genetics ~ "imaging only",
                              !has_imaging & has_genetics ~ "genetics only",
                              has_imaging & has_genetics ~ "both"),
         category = factor(category, levels = c("imaging only", "genetics only", "both")))

data_full_pond %>% 
  group_by(category) %>% 
  count()
```


```{r}
pond_metadata <- file.path(registration_dir, "subject_info", "pond-metadata-20230111.xlsx")
pond_metadata <- read_excel(pond_metadata)
```

```{r}
tmp <- data_full_pond %>% 
  left_join(pond_metadata, by = c("Subject_ID" = "Subject")) %>% 
  select(Subject_ID, POND_DATE, category) %>% 
  mutate(POND_DATE = as.Date(POND_DATE)) %>% 
  filter(!is.na(POND_DATE))

ggplot(tmp, aes(x = factor(year(POND_DATE)), fill = fct_rev(category))) + 
  geom_bar() + 
  labs(x = "Year",
       y = "Number of patients",
       title = "POND imaging and genetics over time",
       fill = "Available data") + 
  theme_bw()
```

Clearly seems like the discrepancy isn't due to date. 

```{r}
data_imaging_pond <- data_full_pond %>% 
  filter(has_imaging)

ggplot(data_imaging_pond, aes(x = Site, fill = has_genetics)) + 
  geom_bar()
```


```{r}
tmp <- data_full_pond %>% 
  left_join(pond_metadata, by = c("Subject_ID" = "Subject")) %>% 
  filter(!is.na(PRIMARY_DIAGNOSIS))

p <- ggplot(tmp, aes(x = category, fill = PRIMARY_DIAGNOSIS)) + 
  geom_bar() + 
  theme_bw()

outfile <- "/projects/abeauchamp/POND_genetics_imaging.pdf"
pdf(file = outfile,
    width = unit(10, "in"),
    height = unit(8, "in"))
print(p)
dev.off()
```
```{r}
tmp %>% 
  group_by(category, PRIMARY_DIAGNOSIS) %>% 
  count() %>% 
  arrange(category)
```

```{r}
tmp %>% 
  filter(category == "genetics only") %>% 
  group_by(PRIMARY_DIAGNOSIS) %>% 
  summarise(n(), n()/nrow(.))
```

```{r}
tmp %>% 
  filter(category == "both") %>% 
  group_by(PRIMARY_DIAGNOSIS) %>% 
  summarise(n(), n()/nrow(.))
```

```{r}
tmp %>% 
  filter(category == "imaging only") %>% 
  group_by(PRIMARY_DIAGNOSIS) %>% 
  summarise(n(), n()/nrow(.))
```




```{r}
tmp_long <- tmp %>% 
  select(-POND_YEAR) %>% 
  rename(imaging = has_imaging, 
         genetics = has_genetics) %>% 
  pivot_longer(cols = c(imaging, genetics), 
               names_to = "feature", 
               values_to = "measured")

ggplot(tmp_long, aes(x = POND_DATE, y = measured, col = feature)) + 
  geom_jitter()
```



```{r}
intersect(demographics_tmp$Subject_ID, genetics_tmp$POND_ID)
```




# -------------

```{r}
library(RMINC)
library(MRIcrotome)

anat <- file.path(registration_dir, "reference_files", "model_0.8mm.mnc")
anat <- mincGetVolume(anat)

mask <- file.path(registration_dir, "reference_files", "mask_0.8mm.mnc")
mask <- mincGetVolume(mask)

demo_lt_5 <- demographics %>% 
  filter(Age <= 5, Sex == "Male") %>% 
  sample_n(size = 5)

files_lt_5 <- demo_lt_5[["file"]]

demo_gt_20 <- demographics %>% 
  filter(Age >= 20, Sex == "Male") %>% 
  sample_n(size = 5)

demo_gt_20[["file"]]

jacobians <- c("absolute", "relative")
jacobians_dir <- file.path(registration_dir, "jacobians_resampled", "resolution_0.8", jacobians)
names(jacobians_dir) <- jacobians


imgs_lt_5 <- vector(mode = "list", length = length(jacobians))
imgs_gt_20 <- vector(mode = "list", length = length(jacobians))
names(imgs_lt_5) <- jacobians
names(imgs_gt_20) <- jacobians
for (j in jacobians) {
  
  infiles_lt_5 <- file.path(jacobians_dir[[j]], files_lt_5)
  infiles_gt_20 <- file.path(jacobians_dir[[j]], files_gt_20)
  
  imgs_lt_5[[j]] <- vector(mode = "list", length = 5)
  imgs_gt_20[[j]] <- vector(mode = "list", length = 5)
  for (i in 1:5) {
    img_lt_5 <- mincGetVolume(infiles_lt_5[[i]])
    img_lt_5[mask < 0.5] <- 0
    imgs_lt_5[[j]][[i]] <- mincArray(img_lt_5)
    
    img_gt_20 <- mincGetVolume(infiles_gt_20[[i]])
    img_gt_20[mask < 0.5] <- 0
    imgs_gt_20[[j]][[i]] <- mincArray(img_gt_20)
  }
  
}


```

```{r fig.width = 5, fig.height = 10}
sliceSeries(nrow = 10, ncol = 1, begin = 50, end = 200) %>% 
  anatomy(mincArray(anat), low = 3, high = 7) %>% 
  overlay(imgs_lt_5[["absolute"]][[1]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_lt_5[["absolute"]][[2]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_lt_5[["absolute"]][[3]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_lt_5[["absolute"]][[4]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_lt_5[["absolute"]][[5]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  draw()
```

```{r fig.width = 5, fig.height = 10}
sliceSeries(nrow = 10, ncol = 1, begin = 50, end = 200) %>% 
  anatomy(mincArray(anat), low = 3, high = 7) %>% 
  overlay(imgs_lt_5[["relative"]][[1]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_lt_5[["relative"]][[2]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_lt_5[["relative"]][[3]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_lt_5[["relative"]][[4]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_lt_5[["relative"]][[5]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  draw()
```

```{r fig.width = 5, fig.height = 10}
sliceSeries(nrow = 10, ncol = 1, begin = 50, end = 200) %>% 
  anatomy(mincArray(anat), low = 3, high = 7) %>% 
  overlay(imgs_gt_20[["absolute"]][[1]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_gt_20[["absolute"]][[2]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_gt_20[["absolute"]][[3]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_gt_20[["absolute"]][[4]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_gt_20[["absolute"]][[5]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  draw()
```


```{r fig.width = 5, fig.height = 10}
sliceSeries(nrow = 10, ncol = 1, begin = 50, end = 200) %>% 
  anatomy(mincArray(anat), low = 3, high = 7) %>% 
  overlay(imgs_gt_20[["relative"]][[1]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_gt_20[["relative"]][[2]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_gt_20[["relative"]][[3]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_gt_20[["relative"]][[4]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(imgs_gt_20[["relative"]][[5]], low = 0.1, high = 0.5, symmetric = TRUE) %>% 
  draw()
```
