---
title: "Examining normative growth models"
author: "Antoine Beauchamp"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(RMINC))
suppressPackageStartupMessages(library(MRIcrotome))
```

```{r env}
SRCPATH <- Sys.getenv("SRCPATH")
PROJECTPATH <- Sys.getenv("PROJECTPATH")
# SRCPATH <- "/projects/abeauchamp/Projects/MouseHumanMapping/Paper_ClusteringAutism/main/src"
```

```{r functions}
source(file.path(SRCPATH, "utils.R"))
source(file.path(SRCPATH, "processing.R"))

plot_normative_splines <- function(voxels, nv = 1000, seed = 123, 
                                   age_range = c(5, 30), subtitle = NULL, 
                                   outfile = "normative_splines.jpeg") {
  
  demo <- voxels %>% 
    select(!starts_with("V"))
  
  voxels <- voxels %>% 
    select(starts_with("V"))
  
  set.seed(seed)
  vsample <- sample(x = 1:ncol(voxels), size = nv, replace = FALSE)
  
  voxel_sample <- voxels[,vsample]
  
  voxel_sample <- demo %>% 
    bind_cols(voxel_sample) %>% 
    pivot_longer(cols = c(-Age, -Sex), names_to = "Voxel", values_to = "Intensity")
  
  
  title <- paste("Normative models for", nv, "voxels")
  pvoxels <- ggplot(voxel_sample, aes(x = Age, y = Intensity, group = Voxel)) +
    geom_line(size = 0.1,
              alpha = 0.05) +
    coord_cartesian(xlim = age_range,
                    ylim = c(-0.4, 0.4)) +
    scale_x_continuous(breaks = seq(age_range[1], age_range[2], by = 2)) +
    scale_y_continuous(breaks = seq(-0.4, 0.4, by = 0.1)) +
    labs(x = "Age",
         y = "Intensity",
         title = title,
         subtitle = subtitle) +
    theme_bw()
  
  jpeg(file = outfile,
       width = 10,
       height = 5,
       units= "in",
       res = 200)
  print(pvoxels)
  dev.off()
  
}
```

```{r directories-1}
# Output directory
output_dir <- file.path(PROJECTPATH, "analyses", "primary", "outputs", "human_normative_models/")

# Pipeline directory
version <- "v3"
pipeline_dir <- file.path(PROJECTPATH, "data/human/derivatives/")
pipeline_dir <- file.path(pipeline_dir, version)

# Registration directory
registration_dir <- file.path(PROJECTPATH, "data/human/registration/v3/")
```

```{r params}
params_id <- "547"
# params_id <- "664"

# Identify parameter set ID
metadata <- file.path(pipeline_dir, "metadata.csv")
params <- fetch_params_metadata(metadata,
                                id = params_id)
params
```

```{r directories-2}
# Parameter set ID
params_id <- "547"
# params_id <- "664"

# Update output directory
output_dir <- file.path(output_dir, params_id)

# Image resolution
resolution <- params %>% 
  filter(id == params_id) %>% 
  pull(resolution)
resolution <- sprintf("%.1f", resolution)

# Mask
maskfile <- paste0("mask_", resolution, "mm.mnc")
maskfile <- file.path(registration_dir, "reference_files", maskfile)
mask <- mincGetVolume(maskfile)

# Template
template <- paste0("model_", resolution, "mm.mnc")
template <- file.path(registration_dir, "reference_files", template)
template <- mincGetVolume(template)

# List of input files
input_files <- list.files(output_dir, full.names = TRUE)
```

```{r}
jacobians_dir <- file.path(registration_dir, "jacobians_resampled", paste("resolution", resolution, sep = "_"))

demographics <- file.path(pipeline_dir, params_id, "demographics.csv")
demographics <- read_csv(demographics, show_col_types = FALSE) %>% 
  filter(!is.na(DX),
         !is.na(Age),
         !is.na(Sex))
```


```{r}
jacobians <- c("absolute", "relative")
sex <- c("Male", "Female")

j <- 1; s <- 1

# Image files
imgdir <- file.path(jacobians_dir, jacobians[j])
imgfiles <- list.files(imgdir, full.names = TRUE)

imgs_in_demographics <- basename(imgfiles) %in% demographics[["file"]]
imgfiles <- imgfiles[imgs_in_demographics]
row_match <- match(basename(imgfiles), demographics[["file"]])
demographics <- demographics[row_match,]

voxels <- import_images(imgfiles = imgfiles, mask = maskfile, output_format = "matrix", nproc = 4)
```


```{r}
v <- sample(1:ncol(voxels), size = 1)

y <- voxels[,v]

batch <- demographics %>% 
  select(Site, Scanner) %>% 
  unite(col = batch) %>% 
  pull(batch)

y <- residuals(lm(y ~ batch))
 
df_voxel <- demographics %>% 
  select(Age, Sex, DX) %>% 
  mutate(y = y,
         IsControl = ifelse(DX == "Control", TRUE, FALSE))

ggplot(df_voxel, aes(x = Age, y = y)) + 
  geom_point() + 
  facet_grid(IsControl~.)
```

```{r}
df_fit <- df_voxel %>% 
  filter(IsControl)

model_fit <- lm(y ~ Sex + ns(Age, df = 3), data = df_fit)

newdata <- tibble(Age = seq(5, 60, by = 1),
                      Sex = sex[s])

df_model  <- predict(model_fit, 
                             newdata = newdata,                         
                             interval = "prediction",
                             level = pnorm(q = 1) - pnorm(q = -1))
df_model <- as_tibble(df_model)
df_model <- bind_cols(newdata, df_model)

ggplot(df_fit, aes(x = Age, y = y)) + 
  geom_point() + 
  geom_ribbon(data = df_model,
            mapping = aes(y = fit, ymin = lwr, ymax = upr),
            alpha = 0.3) + 
  geom_line(data = df_model,
            mapping = aes(y = fit),
            col = "red") 
```



```{r directories-2}
nsample <- 10000

df_inputs <- expand_grid(jacobians = c("absolute", "relative"),
                         sex = c("male", "female"),
                         batch = c(TRUE, FALSE))
for (i in 1:nrow(df_inputs)) {
  
  print(paste(i, "of", nrow(df_inputs)))
  
  j <- df_inputs[[i, "jacobians"]]
  s <- df_inputs[[i, "sex"]]
  b <- df_inputs[[i, "batch"]]
  
  input_file <- input_files %>% 
    str_subset(".csv") %>% 
    str_subset(paste0("_", j)) %>% 
    str_subset(paste0("_", s)) %>% 
    str_subset("_wbatch", negate = !b)
  
  df_voxels <- as_tibble(data.table::fread(input_file, header = TRUE))
  
  subtitle <- paste("Jacobians:", j, "; Sex:", s, "; Batch-normalized:", b)
  outfile <- "normative_model_splines"
  outfile <- paste(outfile, j, s, "batch", b, sep = "_")
  outfile <- paste0(outfile, ".jpeg")
  outfile <- file.path(output_dir, outfile)
  
  plot_normative_splines(voxels = df_voxels, nv = nsample,
                         subtitle = subtitle, outfile = outfile)
  
  ages_ss <- seq(5, 30, by = 5)
  
  df_voxels_ss <- df_voxels %>% 
    filter(Age %in% ages_ss) %>% 
    select(-Age, -Sex)
  
  mat_voxels_ss <- df_voxels_ss %>%
    as.matrix() %>% 
    t() 
  
  ss <- sliceSeries(nrow = 10, ncol = 1, begin = 14, end = 66) %>% 
    anatomy(mincArray(template), low = 40, high = 110)
  
  for (c in 1:ncol(mat_voxels_ss)) {
    
    img <- numeric(length(template))
    img[mask > 0.5] <- mat_voxels_ss[,c]
    attributes(img) <- attributes(template)
    
    
    if (c == 1) {
      ss <- ss %>% 
        overlay(mincArray(img), low = 0.1, high = 0.3, symmetric = TRUE) %>% 
        addtitle(paste0("Age = ", ages_ss[c]))
    } else {
      ss <- ss %>% 
        sliceSeries() %>% anatomy() %>% 
        overlay(mincArray(img), low = 0.1, high = 0.3, symmetric = TRUE) %>% 
        addtitle(paste0("Age = ", ages_ss[c]))
    }
  }
  
  ss <- ss %>% 
    legend("")
  
  outfile <- "normative_model_ss"
  outfile <- paste(outfile, j, s, "batch", b, sep = "_")
  outfile <- paste0(outfile, ".jpeg")
  outfile <- file.path(output_dir, outfile)
  jpeg(file = outfile,
       width = 10,
       height = 10,
       units= "in",
       res = 200)
  draw(ss)
  dev.off()
  
}
```


```{r}
demographics <- file.path(registration_dir, "subject_info", "demographics.csv")
demographics <- read_csv(demographics, show_col_types = FALSE)

demographics <- demographics %>% 
  filter(!is.na(Age), 
         !is.na(Sex),
         !is.na(DX))

ggplot(demographics, 
       aes(x = Age, fill = Dataset)) + 
  geom_histogram(position = "dodge")
```

```{r}
controls <- demographics %>% 
  filter(DX == "Control")
```


```{r}
controls %>% 
  filter(Dataset %in% c("POND", "SickKids")) %>% 
  pull(Age) %>% 
  quantile(c(0.025, 0.975))
```

```{r}
controls %>% 
  filter(Dataset %in% c("POND", "SickKids")) %>% 
  pull(Age) %>% 
  range()
```

```{r}
controls %>% 
  filter(Dataset == "POND") %>% 
  pull(Age) %>% 
  quantile(c(0.025, 0.975))
```

```{r}
controls %>% 
  filter(Dataset == "SickKids") %>% 
  pull(Age) %>% 
  quantile(c(0.025, 0.975))
```
```{r}
controls %>% 
  filter(Dataset == "HBN") %>% 
  pull(Age) %>% 
  quantile(c(0.025, 0.975))
```

```{r}
controls %>% 
  filter(Dataset == "HBN") %>% 
  pull(Age) %>% 
  range()
```

