---
title: "Untitled"
format: html
editor: visual
---

```{r}
# library(tidyverse)
# library(RMINC)
# library(ggalluvial)
# library(patchwork)
# library(MRIcrotome)
library(grid)
library(gridExtra)
# library(RColorBrewer)
# library(ggnewscale)
```

```{r}
PROJECTPATH <- Sys.getenv("PROJECTPATH")
SRCPATH <- Sys.getenv("SRCPATH")
```

```{r}
source(file.path(SRCPATH, "utils.R"))
source(file.path(SRCPATH, "processing.R"))
source(file.path(SRCPATH, "analysis.R"))
```

```{r}
fig_theme <-   theme_bw() +
  theme(panel.grid.minor.x = element_blank(),
        plot.title = element_text(size = 10),
        axis.title = element_text(size = 9),
        axis.text = element_text(size = 8))
```

# MICe clusters

```{r}
file <- "resources/cluster_metrics_uncertainty_MICe.csv"
df_metrics_MICe <- read_csv(file, show_col_types = FALSE)

df_metrics_MICe_summary <- df_metrics_MICe %>% 
  group_by(nk) %>% 
  summarise(eigengap_mean = mean(eigengap), 
            eigengap_min = quantile(eigengap, prob = 0.025),
            eigengap_max = quantile(eigengap, prob = 0.975),
            ARI_mean = mean(ARI),
            ARI_min = quantile(ARI, prob = 0.025),
            ARI_max = quantile(ARI, prob = 0.975)) %>% 
  ungroup() 
```

```{r}
plt_MICe_eigengap <- ggplot(df_metrics_MICe, aes(x = nk, y = eigengap)) + 
  geom_line(mapping = aes(group = factor(seed)),
            alpha = 0.03) + 
  geom_pointrange(data = df_metrics_MICe_summary,
                  mapping = aes(y = eigengap_mean, ymin = eigengap_min, ymax = eigengap_max),
                  col = "red", linewidth = 0.65) + 
  coord_cartesian(ylim = c(0, 0.22)) + 
  scale_x_continuous(breaks = seq(0, 100, by = 1)) + 
  scale_y_continuous(breaks = seq(0, 1, by = 0.02)) + 
  labs(x = "Cluster solution (K)",
       y = "Spectral Clustering Eigengap",
       title = "MICe Eigengap Distributions") + 
  fig_theme

plt_MICe_ARI <- ggplot(df_metrics_MICe, aes(x = nk, y = ARI)) + 
  geom_line(mapping = aes(group = factor(seed)),
            alpha = 0.04) + 
  geom_pointrange(data = df_metrics_MICe_summary,
                  mapping = aes(y = ARI_mean, ymin = ARI_min, ymax = ARI_max),
                  col = "red", linewidth = 0.65) + 
  coord_cartesian(ylim = c(0, 1)) + 
  scale_x_continuous(breaks = seq(0, 100, by = 1)) + 
  scale_y_continuous(breaks = seq(-1, 1, by = 0.1)) +
  labs(x = "Cluster solution (K)",
       y = "Adjusted Rand Index",
       title = "MICe Rand Index Distributions") + 
  fig_theme
```

```{r}
df_metrics_MICe %>% 
  group_by(seed) %>% 
  filter(eigengap == max(eigengap)) %>% 
  ungroup() %>% 
  group_by(nk) %>% 
  count() %>% 
  mutate(prop = n/500)
```

```{r}
df_metrics_MICe_summary %>% 
  select(nk, contains("ARI")) 
```

```{r}
ggplot(df_metrics_MICe_summary, aes(x = nk, y = eigengap_mean)) + 
  geom_ribbon(mapping = aes(ymin = eigengap_min, ymax = eigengap_max),
                            alpha = 0.2) +
  geom_line() + 
  scale_x_continuous(breaks = c(2, 5, 10, 20, 30, 40, 50, 75, 100)) + 
  scale_y_continuous(breaks = seq(0, 1, by = 0.02)) +
  labs(x = "K",
       y = "Eigengap") + 
  theme_bw() +
  theme(panel.grid.minor.x = element_blank())
```

```{r}
ggplot(df_metrics_MICe_summary, aes(x = nk, y = eigengap_mean)) + 
  geom_ribbon(mapping = aes(ymin = eigengap_min, ymax = eigengap_max),
                            alpha = 0.2) +
  geom_line() + 
  coord_cartesian(xlim = c(2, 20)) + 
  scale_x_continuous(breaks = c(2:10, 15, 20)) + 
  scale_y_continuous(breaks = seq(0, 1, by = 0.02)) +
  labs(x = "K",
       y = "Eigengap") + 
  theme_bw() +
  theme(panel.grid.minor.x = element_blank())
```

```{r}
df_metrics_MICe_summary <- df_metrics_MICe_summary %>% 
  mutate(eigengap_diff = eigengap_max - eigengap_min)

ggplot(df_metrics_MICe_summary, aes(x = nk, y = eigengap_diff)) + 
  geom_line() + 
  scale_x_continuous(breaks = c(2, 5, 10, 20, 30, 40, 50, 75, 100)) + 
  scale_y_continuous(breaks = seq(0, 1, by = 0.02)) +
  labs(x = "K",
       y = "Eigengap") + 
  theme_bw() +
  theme(panel.grid.minor.x = element_blank())
```


```{r}
ggplot(df_metrics_MICe_summary, aes(x = nk, y = ARI_mean)) + 
  geom_ribbon(mapping = aes(ymin = ARI_min, ymax = ARI_max),
                            alpha = 0.2) +
  geom_line() + 
  scale_x_continuous(breaks = c(2, 5, 10, 20, 30, 40, 50, 75, 100)) + 
  scale_y_continuous(breaks = seq(0, 1, by = 0.2)) +
  labs(x = "K",
       y = "ARI") + 
  theme_bw() +
  theme(panel.grid.minor.x = element_blank())
```

# POND+ clusters

```{r}
combine_files <- FALSE
if (combine_files) {
  dataset <- "POND"
  file_prefix <- "cluster_metrics_uncertainty"
  file_rgx <- paste0(file_prefix, "_", dataset, "_[0-9]+.csv")
  files <- str_subset(list.files("resources/"), file_rgx)
  files <- file.path("resources", files)
  
  df_metrics_POND <- map_dfr(files, read_csv, show_col_types = FALSE)
  
  outfile <- paste(file_prefix, dataset, sep = "_")
  outfile <- paste0(outfile, ".csv")
  outfile <- file.path("resources", outfile)
  write_csv(df_metrics_POND, outfile)
}

file <- "resources/cluster_metrics_uncertainty_POND.csv"
df_metrics_POND <- read_csv(file, show_col_types = FALSE)


df_metrics_POND_summary <- df_metrics_POND %>% 
  group_by(nk) %>% 
  summarise(eigengap_mean = mean(eigengap), 
            eigengap_min = quantile(eigengap, prob = 0.025),
            eigengap_max = quantile(eigengap, prob = 0.975),
            ARI_mean = mean(ARI),
            ARI_min = quantile(ARI, prob = 0.025),
            ARI_max = quantile(ARI, prob = 0.975)) %>% 
  ungroup() 

plt_POND_eigengap <- ggplot(df_metrics_POND, aes(x = nk, y = eigengap)) + 
  geom_line(mapping = aes(group = factor(seed)),
            alpha = 0.025) + 
  geom_pointrange(data = df_metrics_POND_summary,
                  mapping = aes(y = eigengap_mean, ymin = eigengap_min, ymax = eigengap_max),
                  col = "red") + 
  coord_cartesian(ylim = c(0, 0.08)) + 
  scale_x_continuous(breaks = seq(0, 20, by = 1)) + 
  scale_y_continuous(breaks = seq(0, 1, by = 0.02)) + 
  labs(x = "Cluster solution (K)",
       y = "Spectral Clustering Eigengap",
       title = "POND+ Eigengap Distributions") + 
  fig_theme

plt_POND_ARI <- ggplot(df_metrics_POND, aes(x = nk, y = ARI)) + 
  geom_line(mapping = aes(group = factor(seed)),
            alpha = 0.03) + 
  geom_pointrange(data = df_metrics_POND_summary,
                  mapping = aes(y = ARI_mean, ymin = ARI_min, ymax = ARI_max),
                  col = "red") + 
  coord_cartesian(ylim = c(0, 1)) + 
  scale_x_continuous(breaks = seq(0, 20, by = 1)) + 
  scale_y_continuous(breaks = seq(-1, 1, by = 0.1)) +
  labs(x = "Cluster solution (K)",
       y = "Adjusted Rand Index",
       title = "POND+ Rand Index Distributions") + 
  fig_theme
```

```{r}
df_metrics_POND %>% 
  group_by(seed) %>% 
  filter(eigengap == max(eigengap)) %>% 
  ungroup() %>% 
  group_by(nk) %>% 
  count() %>% 
  mutate(prop = n/length(unique(df_metrics_POND$seed)))
```

# HBN clusters

```{r}
combine_files <- FALSE
if (combine_files) {
  dataset <- "HBN"
  file_prefix <- "cluster_metrics_uncertainty"
  file_rgx <- paste0(file_prefix, "_", dataset, "_[0-9]+.csv")
  files <- str_subset(list.files("resources/"), file_rgx)
  files <- file.path("resources", files)
  
  df_metrics_HBN <- map_dfr(files, read_csv, show_col_types = FALSE)
  
  outfile <- paste(file_prefix, dataset, sep = "_")
  outfile <- paste0(outfile, ".csv")
  outfile <- file.path("resources", outfile)
  write_csv(df_metrics_HBN, outfile)
}


file <- "resources/cluster_metrics_uncertainty_HBN.csv"
df_metrics_HBN <- read_csv(file, show_col_types = FALSE)


df_metrics_HBN_summary <- df_metrics_HBN %>% 
  group_by(nk) %>% 
  summarise(eigengap_mean = mean(eigengap), 
            eigengap_min = quantile(eigengap, prob = 0.025),
            eigengap_max = quantile(eigengap, prob = 0.975),
            ARI_mean = mean(ARI),
            ARI_min = quantile(ARI, prob = 0.025),
            ARI_max = quantile(ARI, prob = 0.975)) %>% 
  ungroup() 

plt_HBN_eigengap <- ggplot(df_metrics_HBN, aes(x = nk, y = eigengap)) + 
  geom_line(mapping = aes(group = factor(seed)),
            alpha = 0.03) + 
  geom_pointrange(data = df_metrics_HBN_summary,
                  mapping = aes(y = eigengap_mean, ymin = eigengap_min, ymax = eigengap_max),
                  col = "red") + 
  coord_cartesian(ylim = c(0, 0.08)) + 
  scale_x_continuous(breaks = seq(0, 20, by = 1)) + 
  scale_y_continuous(breaks = seq(0, 1, by = 0.02)) + 
  labs(x = "Cluster solution (K)",
       y = "Spectral Clustering Eigengap",
       title = "HBN Eigengap Distributions") + 
  fig_theme

plt_HBN_ARI <- ggplot(df_metrics_HBN, aes(x = nk, y = ARI)) + 
  geom_line(mapping = aes(group = factor(seed)),
            alpha = 0.04) + 
  geom_pointrange(data = df_metrics_HBN_summary,
                  mapping = aes(y = ARI_mean, ymin = ARI_min, ymax = ARI_max),
                  col = "red") + 
  coord_cartesian(ylim = c(0, 1)) + 
  scale_x_continuous(breaks = seq(0, 20, by = 1)) + 
  scale_y_continuous(breaks = seq(-1, 1, by = 0.1)) +
  labs(x = "Cluster solution (K)",
       y = "Adjusted Rand Index",
       title = "HBN Rand Index Distributions") + 
  fig_theme
```

```{r}
df_metrics_HBN %>% 
  group_by(seed) %>% 
  filter(eigengap == max(eigengap)) %>% 
  ungroup() %>% 
  group_by(nk) %>% 
  count() %>% 
  mutate(prop = n/length(unique(df_metrics_HBN$seed)))
```

# Figures

```{r}
heights <- rep(1, 3)/3
widths <- rep(1, 2)/2
layout <- matrix(1:6, ncol = 2, nrow = 3, byrow = TRUE)

fig <- arrangeGrob(ggplotGrob(plt_MICe_eigengap),
                   ggplotGrob(plt_MICe_ARI),
                   ggplotGrob(plt_POND_eigengap),
                   ggplotGrob(plt_POND_ARI),
                   ggplotGrob(plt_HBN_eigengap),
                   ggplotGrob(plt_HBN_ARI),
                   layout_matrix = layout,
                   heights = unit(heights, "npc"),
                   widths = unit(widths, "npc"))

outfile <- "cluster_metric_uncertainty.pdf"
outfile <- file.path("resources", outfile)
pdf(file = outfile,
    width = unit(9, "in"),
    height = unit(8, "in"))
grid.draw(fig)
dev.off()
```

```{r}
df_metrics_summary_combined <- bind_rows(
  df_metrics_MICe_summary %>% 
    mutate(dataset = "MICe"),
  df_metrics_POND_summary %>% 
    mutate(dataset = "POND"),
  df_metrics_HBN_summary %>% 
    mutate(dataset = "HBN")
)

df_metrics_summary_combined <- df_metrics_summary_combined %>% 
  mutate(dataset = factor(dataset, levels = c("MICe", "POND", "HBN")))

df_metrics_summary_combined <- bind_rows(
  df_metrics_summary_combined %>% 
    select(nk, dataset, contains("eigengap")) %>% 
    rename(y = eigengap_mean, ymin = eigengap_min, ymax = eigengap_max) %>% 
    mutate(metric = "Eigengap"),
  df_metrics_summary_combined %>% 
    select(nk, dataset, contains("ARI")) %>% 
    rename(y = ARI_mean, ymin = ARI_min, ymax = ARI_max) %>% 
    mutate(metric = "ARI")
)

df_metrics_summary_combined <- df_metrics_summary_combined %>% 
  mutate(metric = factor(metric, levels = c("Eigengap", "ARI")))


plt <- ggplot(df_metrics_summary_combined, 
       aes(x = nk, y = y, ymin = ymin, ymax = ymax)) +
  
  # geom_ribbon(alpha = 0.2) +
  geom_pointrange(size = 0.2) +
  facet_grid(metric~dataset, scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 20, by = 1)) + 
  labs(x = "Cluster solution (K)",
       y = "Score") + 
  fig_theme

outfile <- "cluster_metric_uncertainty_2.pdf"
outfile <- file.path("resources", outfile)
pdf(file = outfile,
    width = unit(6, "in"),
    height = unit(4, "in"))
grid.draw(plt)
dev.off()
```
