---
title: "Untitled"
output: html_document
date: "2025-10-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Initialization

```{r}
library(tidyverse)
library(RMINC)
library(ggalluvial)
library(patchwork)
library(MRIcrotome)
library(grid)
library(gridExtra)
library(RColorBrewer)
library(ggnewscale)
```

```{r}
PROJECTPATH <- Sys.getenv("PROJECTPATH")
SRCPATH <- Sys.getenv("SRCPATH")
```

```{r}
source(file.path(SRCPATH, "utils.R"))
source(file.path(SRCPATH, "processing.R"))
source(file.path(SRCPATH, "analysis.R"))
```

```{r}
output_dir <- file.path("outputs", "figure2_draft_3_new")
if (!(dir.exists(output_dir))) {dir.create(path = output_dir, recursive = TRUE)}
outfile_prefix <- "figure2_draft_3_new"
```

```{r}
pipeline_dir <- file.path(PROJECTPATH, "data/cross_species/v3")

human_datasets <- c("POND", "HBN")

params_ids <- c("POND" = "375", "HBN" = "861")
# params_ids <- c("POND" = "852", "HBN" = "021")
metadata <- file.path(pipeline_dir, "metadata.csv")
human_params_ids <- character(2)
for (i in 1:length(params_ids)) {
  pipeline_params <- fetch_params_metadata(metadata = metadata,
                                           params = list(id = params_ids[i]))
  
  human_params_ids[i] <- pipeline_params[["input_1_id"]]
}
mouse_params_id <- pipeline_params[["input_2_id"]]
```

```{r}
human_pipeline_dirs <- file.path(PROJECTPATH, "data/human/derivatives/v3/", human_params_ids)

human_cluster_dirs <- file.path(human_pipeline_dirs, "clusters", "resolution_3.0")
human_centroid_dirs <- file.path(human_pipeline_dirs, "centroids", "resolution_0.8")
```

```{r}
mouse_pipeline_dir <- file.path(PROJECTPATH, "data/mouse/derivatives/v3/", mouse_params_id)

mouse_cluster_dir <- file.path(mouse_pipeline_dir, "clusters", "resolution_0.2")
mouse_centroid_dir <- file.path(mouse_pipeline_dir, "centroids", "resolution_0.05")
```


```{r}
# Total figure dimensions in pts
fig_width <- 612
fig_height <- 792

# Figure border dimensions in pts
border_padding_width <- 4
border_padding_height <- border_padding_width

# Vertical padding between panels
# panel_padding_height <- 50
panel_padding_height <- border_padding_height

# Total width and height of all panels, excluding padding
panel_tot_width <- fig_width - 2*border_padding_width
panel_tot_height <- fig_height - 2*border_padding_height - 2*panel_padding_height

# Individual panel height
panel_height <- panel_tot_height/3
```

```{r}
nk_subset <- c(2, 4, 6, 8)
```


# Cluster similarity

```{r eval = TRUE}
mouse_cluster_file <- file.path(mouse_cluster_dir, "clusters.csv")
df_mouse_clusters <- read_csv(mouse_cluster_file, show_col_types = FALSE)

df_mouse_cluster_counts <- df_mouse_clusters %>% 
  pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = as.numeric(str_remove(nk_name, "nk"))) %>% 
  select(-nk_name) %>% 
  unite(col = "cluster_id", "nk", "k", sep = "-", remove = FALSE) %>% 
  group_by(cluster_id) %>% 
  count() %>% 
  ungroup()
```

```{r eval = TRUE}
human_cluster_files <- file.path(human_cluster_dirs, "clusters.csv")
list_human_clusters <- map(human_cluster_files, read_csv, show_col_types = FALSE)
names(list_human_clusters) <- human_datasets

list_human_clusters_long <- map(.x = list_human_clusters, 
    .f = function(x) {
      x %>% 
        pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>%
        mutate(nk = as.numeric(str_remove(nk_name, "nk"))) %>%
        select(-nk_name) %>%
        unite(col = "cluster_id", "nk", "k", sep = "-", remove = FALSE)
    })

# df_human_cluster_counts <- human_clusters %>%
#   pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
#   mutate(nk = as.numeric(str_remove(nk_name, "nk"))) %>% 
#   select(-nk_name) %>% 
#   unite(col = "cluster_id", "nk", "k", sep = "-", remove = FALSE) %>% 
#   group_by(cluster_id) %>% 
#   count() %>% 
#   ungroup()
```

```{r eval = TRUE}
list_similarity <- vector(mode = "list", length = length(human_datasets))
names(list_similarity) <- human_datasets
for (i in 1:length(list_similarity)) {
  
  df_similarity <- compute_similarity_significance(
    similarity = import_similarity(param_id = params_ids[i], 
                                   pipeline_dir = pipeline_dir), 
    permutations = import_similarity_permutations(param_id = params_ids[i], 
                                                  pipeline_dir = pipeline_dir)
  )
  
  colnames(df_similarity) <- colnames(df_similarity) %>% 
    str_replace("img1", "human") %>% 
    str_replace("img2", "mouse")
  
  cluster_ids <- df_similarity %>% 
    select(human_cluster_id, human_nk, human_k) %>% 
    arrange(human_nk, human_k) %>% 
    distinct() %>% 
    pull(human_cluster_id)
  
  df_cluster_grid <- expand_grid(human_cluster_id = cluster_ids,
                                 mouse_cluster_id = cluster_ids) 
  
  df_matches <- df_similarity %>% 
    mutate(match = pval < 0.05) %>% 
    right_join(df_cluster_grid) %>% 
    mutate(match = ifelse(is.na(match), FALSE, match))
  
  list_similarity[[i]] <- df_matches
  
}
```


```{r}
list_cluster_groups <- list("A" = c("5-1", "6-1", "7-1", "8-1", "9-1", "10-1"),
                            "B" = c("5-3", "6-3", "7-3", "8-5", "9-4", "10-3"),
                            "C" = c("5-5", "6-4", "7-4", "8-2", "9-5", "10-5"),
                            "D" = c("5-4", "6-5", "7-7", "8-6", "9-2", "10-4"))
                            # "E" = c("5-1", "6-6", "7-6", "8-7", "9-9", "10-9"),
                            # "F" = c("5-2", "6-2", "7-2", "8-8", "9-6", "10-2"))


df_cluster_groups <- as_tibble(list_cluster_groups) %>% 
  pivot_longer(cols = everything(), names_to = "group", values_to = "mouse_cluster_id")

df_cluster_groups <- bind_rows(tibble(group = c("A", "D"), 
                                      mouse_cluster_id = c("2-1", "2-2")),
                               tibble(group = c("D", "B", "A"),
                                      mouse_cluster_id = c("4-1", "4-3", "4-4")),
                               df_cluster_groups) %>% 
  separate(col = "mouse_cluster_id", into = c("nk", "k"), sep = "-", remove = FALSE) %>% 
  mutate(nk = as.numeric(nk), k = as.numeric(k))

list_similarity_groups <- vector(mode = "list", length = length(human_datasets))
names(list_similarity_groups) <- human_datasets
for (i in 1:length(list_similarity_groups)) {
  list_similarity_groups[[i]] <- df_cluster_groups %>% 
    semi_join(filter(list_similarity[[i]], match),
              by = "mouse_cluster_id")
}
```

```{r}
col2hex <- function(x, alpha = FALSE) {
  args <- as.data.frame(t(col2rgb(x, alpha = alpha)))
  args <- c(args, list(names = x, maxColorValue = 255))
  do.call(rgb, args)
}

col2hex("springgreen4")
col2hex("darkorchid1")
col2hex("seagreen2")
```


# MICe-POND Sankey

```{r}
# Convert cluster information to long format
df_mouse_clusters_long <- df_mouse_clusters %>% 
  pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = str_remove(nk_name, "nk"),
         nk = as.numeric(nk))

df_mouse_sankey_pond <- df_mouse_clusters_long %>%
  filter(nk %in% nk_subset) %>% 
  left_join(list_similarity_groups[["POND"]], by = c("nk", "k"))

df_mouse_sankey_pond <- df_mouse_sankey_pond %>% 
  mutate(nk = factor(nk), k = factor(k))

stratum_width <- 0.75

palette <- c("A" = "springgreen4",
             "B" = "sienna2",
             "C" = "seagreen2",
             "D" = "darkorchid1")

# palette <- c("A" = "springgreen4",
#              "B" = "seagreen2",
#              "C" = "#446F87",
#              "D" = "darkorchid1")

# Mouse cluster Sankey plot
plt_mouse_sankey_pond <- ggplot(df_mouse_sankey_pond,
                           aes(x = nk,
                               stratum = k,
                               alluvium = ID,
                               fill = group,
                               label = k)) + 
  geom_flow(stat = "alluvium", aes.flow = "forward", width = stratum_width) + 
  geom_stratum(alpha = 1, width = stratum_width) +
  # geom_stratum(mapping = aes(col = group), alpha = 1, width = stratum_width) +
  # scale_x_discrete(position = "top") + 
  scale_x_discrete(position = "top", 
                   expand = expansion(add = c(stratum_width/2+0.020, stratum_width/2+0.005))) +
  # scale_x_discrete(position = "top", expand = expansion(mult = c(0.0, 0.0))) +
  scale_y_continuous(breaks = c(seq(0, 130, by = 20), nrow(df_mouse_clusters))) + 
  scale_fill_manual(values = palette, na.value = "grey80") + 
  scale_colour_manual(values = palette) + 
  labs(x = "K",
       y = "Number of models") + 
  # theme_void() + 
  theme_bw() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid = element_blank(),
        legend.position = "none",
        panel.border = element_blank(),
        axis.line.y.left = element_line(colour = "grey50"),
        panel.ontop = FALSE)

mouse_sankey_pond_grob <- ggplotGrob(plt_mouse_sankey_pond)

# plt_mouse_sankey_pond
```





# MICe-HBN Sankey

```{r}
df_mouse_sankey_hbn <- df_mouse_clusters_long %>%
  filter(nk %in% nk_subset) %>% 
  left_join(list_similarity_groups[["HBN"]], by = c("nk", "k"))

df_mouse_sankey_hbn <- df_mouse_sankey_hbn %>% 
  mutate(nk = factor(nk), k = factor(k))

stratum_width <- 0.75

palette <- c("A" = "springgreen4",
             "B" = "sienna2",
             "C" = "seagreen2",
             "D" = "darkorchid1")

# palette <- c("A" = "springgreen4",
#              "B" = "seagreen2",
#              "C" = "#446F87",
#              "D" = "darkorchid1")

# Mouse cluster Sankey plot
plt_mouse_sankey_hbn <- ggplot(df_mouse_sankey_hbn,
                           aes(x = nk,
                               stratum = k,
                               alluvium = ID,
                               fill = group,
                               label = k)) + 
  geom_flow(stat = "alluvium", aes.flow = "forward", width = stratum_width) + 
  geom_stratum(alpha = 1, width = stratum_width) +
  # geom_stratum(mapping = aes(col = group), alpha = 1, width = stratum_width) +
  # scale_x_discrete(position = "top") + 
  scale_x_discrete(position = "top", 
                   expand = expansion(add = c(stratum_width/2+0.020, stratum_width/2+0.005))) +
  # scale_x_discrete(position = "top", expand = expansion(mult = c(0.0, 0.0))) +
  scale_y_continuous(breaks = c(seq(0, 130, by = 20), nrow(df_mouse_clusters))) + 
  scale_fill_manual(values = palette, na.value = "grey80") + 
  scale_colour_manual(values = palette) + 
  labs(x = "K",
       y = "Number of models") + 
  # theme_void() + 
  theme_bw() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid = element_blank(),
        legend.position = "none",
        panel.border = element_blank(),
        axis.line.y.left = element_line(colour = "grey50"),
        panel.ontop = FALSE)

mouse_sankey_hbn_grob <- ggplotGrob(plt_mouse_sankey_hbn)

plt_mouse_sankey_hbn
```


# POND demographics

```{r}
# Human registration directory
human_registration_dir <- file.path(PROJECTPATH, "data/human/registration/v3")

# Import human demographics data
demographics <- file.path(human_registration_dir, "subject_info", "demographics.csv")
demographics <- read_csv(demographics, show_col_types = FALSE)

# Filter for participants 
# demographics <- demographics %>%
#   filter(!is.na(DX),
#          !is.na(Age),
#          !is.na(Sex),
#          !is.na(Site),
#          !is.na(Scanner))

# Redefine diagnostic categories
list_diagnoses <- list(
  "POND" = tibble(DX = c("ASD", "OCD", "ADHD", "Sub-threshold OCD",
                         "Anxiety", "Sub-threshold ADHD",
                         "Intellectual Disability only", 
                         "Tourette Syndrome", "Other", "Fragile X"),
                  DX_new = c("ASD", "OCD", "ADHD", "OCD", "Other", 
                             "ADHD", "Other", "Other", "Other", "Other")),
  "HBN" = tibble(DX = c("ASD", "OCD", "ADHD", "Tourette Syndrome", "ID"),
                 DX_new = c("ASD", "OCD", "ADHD", "Other", "Other"))
)

cluster_ids <- list_human_clusters_long[[1]] %>% 
  filter(nk %in% nk_subset) %>% 
  arrange(nk, k) %>% 
  pull(cluster_id) %>% 
  unique()

# Diagnostic category levels
dx_lvls <- c("ASD", "ADHD", "OCD", "Other")

# Full grid of cluster and DX
dx_grid <- expand_grid(DX_new = dx_lvls,
                       cluster_id = cluster_ids)  %>% 
  separate(col = "cluster_id", into = c("nk", "k"), 
           sep = "-", remove = FALSE) %>% 
  mutate(nk = as.numeric(nk), k = as.numeric(k))

rect_w <- 0.5

list_cluster_dx <- vector(mode = "list", length = length(list_human_clusters))
list_human_groups <- vector(mode = "list", length = length(list_human_clusters))
list_rect <- vector(mode = "list", length = length(list_human_clusters))
names(list_cluster_dx) <- names(list_human_clusters)
names(list_human_groups) <- names(list_human_clusters)
names(list_rect) <- names(list_human_clusters)
for (i in 1:length(list_human_clusters)) {
  list_cluster_dx[[i]]  <- list_human_clusters_long[[i]] %>%
    left_join(select(demographics, ID = file, DX), by = "ID") %>% 
    left_join(list_diagnoses[[i]], by = "DX") %>% 
    filter(nk %in% nk_subset) %>% 
    group_by(nk, k) %>% 
    mutate(n_cluster = n()) %>% 
    ungroup() %>% 
    group_by(nk, k, DX_new) %>% 
    mutate(n_cluster_dx = n()) %>% 
    ungroup() %>% 
    mutate(prop_cluster_dx = n_cluster_dx/n_cluster) %>% 
    select(cluster_id, nk, k, DX_new, prop_cluster_dx) %>% 
    distinct() %>% 
    right_join(dx_grid, by = c("cluster_id", "nk", "k", "DX_new")) %>% 
    mutate(prop_cluster_dx = ifelse(is.na(prop_cluster_dx), 0, prop_cluster_dx))
  
  list_human_groups[[i]] <- list_similarity[[i]] %>% 
    filter(match, human_nk == mouse_nk) %>% 
    filter((human_nk %in% nk_subset) | (mouse_nk %in% nk_subset)) %>% 
    group_by(mouse_cluster_id) %>% 
    filter(pval == min(pval)) %>% 
    ungroup() %>% 
    select(human_cluster_id, mouse_cluster_id, human_nk, human_k) %>% 
    left_join(df_cluster_groups, by = "mouse_cluster_id") %>% 
    select(human_cluster_id, nk = human_nk, k = human_k, group) %>% 
    mutate(group = factor(group, levels = c("A", "B", "C", "D")))
  
  list_rect[[i]] <- list_human_groups[[i]]  %>% 
  mutate(xmin = k - rect_w, xmax = k + rect_w, 
         ymin = 0, ymax = 1) 
}


df_cluster_coords <- tibble(cluster_id = cluster_ids) %>% 
  separate(col = "cluster_id", into = c("nk", "k"), sep = "-", remove = FALSE) %>% 
  mutate(nk = as.numeric(nk), k = as.numeric(k),
         x = 1:nrow(.))

x_gap <- 1

df_cluster_coords <- tibble(nk = 2:10, 
                            gap = x_gap*0:8) %>% 
  right_join(df_cluster_coords, by = "nk") %>% 
  mutate(x = x + gap)



library(ggnewscale)

palette <- c("A" = "springgreen4",
             "B" = "sienna2",
             "C" = "seagreen2",
             "D" = "darkorchid1")

dx_palette <- paste0("seashell", 1:4)


plt_pond_dx <- ggplot(list_rect[["POND"]], aes(x = k)) + 
  geom_rect(mapping = aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = group, col = group),
            alpha = 0.6) +
  scale_color_manual(values = palette) + 
  scale_fill_manual(values = palette) + 
  new_scale_fill() + 
  geom_col(data = list_cluster_dx[["POND"]], mapping = aes(x = k, y = prop_cluster_dx, fill = DX_new),
           position = "dodge", col = "grey45", width = 0.8) + 
    scale_fill_manual(values = dx_palette) +
  scale_x_continuous(breaks = seq(1, 20, by = 1)) + 
    facet_grid(.~nk, scales = "free_x") +
  labs(x = "POND+ cluster", y = "Proportion per cluster") + 
  theme_bw() +
  theme(legend.position = "none")

plt_hbn_dx <- ggplot(list_rect[["HBN"]], aes(x = k)) + 
  geom_rect(mapping = aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = group, col = group),
            alpha = 0.6) +
  scale_color_manual(values = palette) + 
  scale_fill_manual(values = palette) + 
  new_scale_fill() + 
  geom_col(data = list_cluster_dx[["HBN"]], mapping = aes(x = k, y = prop_cluster_dx, fill = DX_new),
           position = "dodge", col = "grey45", width = 0.8) + 
    scale_fill_manual(values = dx_palette) +
  scale_x_continuous(breaks = seq(1, 20, by = 1)) + 
    facet_grid(.~nk, scales = "free_x") +
  labs(x = "HBN cluster", y = "Proportion per cluster") + 
  theme_bw() +
  theme(legend.position = "none")

# dx_palette <- paste0("seashell", 1:4)
# 
# plt_pond_dx <- ggplot(list_cluster_dx[["POND"]], aes(x = factor(k), y = prop_cluster_dx, fill = DX_new)) + 
#   geom_col(position = "dodge", col = "grey45") +
#   facet_grid(~nk, scales = "free_x", space = "free") + 
#   coord_cartesian(ylim = c(0, 1.0)) + 
#   scale_y_continuous(breaks = seq(0, 1, by = 0.2)) + 
#   scale_fill_manual(values = dx_palette) +
#   theme_bw() +
#   theme(legend.position = "none")
# 
# plt_hbn_dx <- ggplot(list_cluster_dx[["HBN"]], aes(x = factor(k), y = prop_cluster_dx, fill = DX_new)) + 
#   geom_col(position = "dodge", col = "grey45") +
#   facet_grid(~nk, scales = "free_x", space = "free") +
#   coord_cartesian(ylim = c(0, 1.0)) + 
#   scale_y_continuous(breaks = seq(0, 1, by = 0.2)) + 
#   scale_fill_manual(values = dx_palette) +
#   theme_bw() +
#   theme(legend.position = "none")


fig_patchwork <- plt_mouse_sankey_pond / plt_pond_dx / plt_mouse_sankey_hbn / plt_hbn_dx 

sankey_height_npc <- 0.40
dx_height_npc <- 0.10
# padding_height_npc <- 0.025
# padding_height_npc <- (1 - mouse_sankey_height_npc - human_sankey_height_npc - matches_height_npc)/2

fig_patchwork <- fig_patchwork + 
  plot_layout(heights = c(sankey_height_npc, dx_height_npc, 
                          sankey_height_npc, dx_height_npc))

fig_patchwork_grob <- patchworkGrob(fig_patchwork)

# grobs_list <- c(list(fig_patchwork_grob), reduce(list_mouse_slices, c))
# grobs <- do.call(grobTree, grobs_list)
grobs <- fig_patchwork_grob

fig_width_in <- fig_width/72
fig_height_in <- fig_height/72

outfile <- paste0(outfile_prefix, ".pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(fig_width_in, "in"),
    height = unit(fig_height_in, "in"))
grid.draw(grobs)
dev.off()
```



# Mouse slices

```{r}
# Jacobians to display
jacobians <- "relative"

# # Threshold method
# threshold <- pipeline_params %>% 
#   filter(id == params_ids[["POND"]]) %>% 
#   pull(threshold)
# 
# # Threshold value
# threshold_value <- pipeline_params %>% 
#   filter(id == params_ids[["POND"]]) %>% 
#   pull(threshold_value)
# 
# # Threshold symmetric option
# threshold_symmetric <- pipeline_params %>% 
#   filter(id == params_ids[["POND"]]) %>% 
#   pull(threshold_symmetric)

threshold <- "top_n"
threshold_value <- 0.2
threshold_symmetric <- TRUE

# Mouse centroid map directory
mouse_centroid_dir <- file.path(mouse_centroid_dir, jacobians)

# Mouse anatomy
mouse_anat_file <- file.path(PROJECTPATH, "data/mouse/atlas/DSURQE_CCFv3_average_50um.mnc")
mouse_anat <- mincGetVolume(mouse_anat_file)
mouse_anat_vol <- mincArray(mouse_anat)

# Mouse mask
mouse_mask_file <- file.path(PROJECTPATH, "data/mouse/atlas/coronal_50um_coverage_bin0.8.mnc")
mouse_mask <- mincGetVolume(mouse_mask_file)

overlay_low <- 0.19
overlay_high <- 1.0

# Mouse anatomy thresholds
mouse_anat_low <- 700
mouse_anat_high <- 1400

mouse_slc_dim <- 1
mouse_slc <- 92
```

```{r}
list_mouse_slices_POND <- vector(mode = "list", length = length(nk_subset))
names(list_mouse_slices_POND) <- nk_subset
list_mouse_slices_HBN <- list_mouse_slices_POND
for (i in 1:length(list_mouse_slices_POND)) {
  
  nki <- nk_subset[i]
  list_mouse_slices_POND[[i]] <- vector(mode = "list", length = nki)
  for (k in 1:nki) {
    
    img <- import_cluster_map(imgdir = mouse_centroid_dir,
                              mask = mouse_mask_file,
                              nk = nki, k = k, 
                              threshold = threshold,
                              threshold_value = threshold_value,
                              threshold_symmetric = threshold_symmetric)
    
    # Compute overlay thresholds
    overlay_threshold <- numeric(2)
    overlay_threshold[1] <- min(abs(img[img != 0]))
    overlay_threshold[2] <- 0.8*max(abs(img[img != 0]))
    overlay_threshold <- round(overlay_threshold, 2)
    
    img <- mincArray(img)
    
    img_grob_POND <- sliceSeries(nrow = 1, ncol = 1, 
                            dimension = mouse_slc_dim, 
                            slices = mouse_slc) %>% 
      anatomy(mouse_anat_vol, low = mouse_anat_low, high = mouse_anat_high) %>% 
      overlay(img, 
              low = overlay_threshold[1], high = overlay_threshold[2], 
              symmetric = TRUE) %>% 
      grobify()
    
    img_grob_HBN <- sliceSeries(nrow = 1, ncol = 1, 
                            dimension = mouse_slc_dim, 
                            slices = mouse_slc) %>% 
      anatomy(mouse_anat_vol, low = mouse_anat_low, high = mouse_anat_high) %>% 
      overlay(img, 
              low = overlay_threshold[1], high = overlay_threshold[2], 
              symmetric = TRUE) %>% 
      grobify()
    
    # img_grob$vp <- viewport(x = list_mouse_slc_vps[[i]][["x"]][[k]], 
    #                         y = list_mouse_slc_vps[[i]][["y"]][[k]], 
    #                         width = list_mouse_slc_vps[[i]][["w"]][[k]], 
    #                         height = list_mouse_slc_vps[[i]][["h"]][[k]])
    
    list_mouse_slices_POND[[i]][[k]] <- img_grob_POND
    list_mouse_slices_HBN[[i]][[k]] <- img_grob_HBN
    
  }
}

```


# Human slices

```{r}
# Jacobians to display
jacobians <- "relative"

# # Threshold method
# threshold <- pipeline_params %>% 
#   filter(id == params_id) %>% 
#   pull(threshold)
# 
# # Threshold value
# threshold_value <- pipeline_params %>% 
#   filter(id == params_id) %>% 
#   pull(threshold_value)
# 
# # Threshold symmetric option
# threshold_symmetric <- pipeline_params %>% 
#   filter(id == params_id) %>% 
#   pull(threshold_symmetric)

# Mouse centroid map directory
human_centroid_dirs <- file.path(human_centroid_dirs, jacobians)

# Mouse mask
human_mask_file <- file.path(PROJECTPATH, "data/human/registration/v3/reference_files/mask_0.8mm.mnc")
human_mask <- mincGetVolume(human_mask_file)

# human anatomy
human_anat_file <- file.path(PROJECTPATH, "data/human/registration/v3/reference_files/model_0.8mm.mnc")
human_anat <- mincGetVolume(human_anat_file)
human_anat[human_mask < 0.5] <- 0
human_anat_vol <- mincArray(human_anat)

slices_dim_1 <- 27:220
slices_dim_2 <- 10:280
slices_dim_3 <- 1:220
human_anat_vol_cropped <- human_anat_vol[slices_dim_1, slices_dim_2, slices_dim_3]

overlay_low <- 0.19
overlay_high <- 1.0

# Human anatomy thresholds
human_anat_low <- 40
human_anat_high <- 110

human_slc_dim <- 1
human_slc <- 82
```

```{r}
df_matches_POND <- tibble(mouse_cluster_id = c("2-1", "2-2", "4-1", "4-4", "6-1", "6-4", "6-5", "8-1", "8-2", "8-5", "8-6"),
                          human_cluster_id = c("3-3", "2-1", "4-1", "4-2", "7-2", "6-2", "7-1", "9-5", "8-7", "8-4", "8-2"))


list_human_slices_POND <- vector(mode = "list", length = length(nk_subset))
names(list_human_slices_POND) <- nk_subset
for (i in 1:length(list_human_slices_POND)) {
  
  nki <- nk_subset[i]
  list_human_slices_POND[[i]] <- vector(mode = "list", length = nki)
  for (k in 1:nki) {
    
    cluster_id <- paste0(nki, "-", k)
    
    if (cluster_id %in% df_matches_POND$mouse_cluster_id) {
      
      human_cluster_id <- df_matches_POND %>% 
        filter(mouse_cluster_id == cluster_id) %>% 
        pull(human_cluster_id)
      
      human_nk <- str_split(human_cluster_id, pattern = "-")[[1]][1]
      human_k <- str_split(human_cluster_id, pattern = "-")[[1]][2]
      
      img <- import_cluster_map(imgdir = human_centroid_dirs[1],
                                mask = human_mask_file,
                                nk = human_nk, k = human_k, 
                                threshold = threshold,
                                threshold_value = threshold_value,
                                threshold_symmetric = threshold_symmetric)
      
      # Compute overlay thresholds
      overlay_threshold <- numeric(2)
      overlay_threshold[1] <- min(abs(img[img != 0]))
      overlay_threshold[2] <- 0.8*max(abs(img[img != 0]))
      overlay_threshold <- round(overlay_threshold, 2)
      
      img <- mincArray(img)
      img <- img[slices_dim_1, slices_dim_2, slices_dim_3]
      
      img_grob <- sliceSeries(nrow = 1, ncol = 1, 
                              dimension = human_slc_dim, 
                              slices = human_slc) %>% 
        anatomy(human_anat_vol_cropped, low = human_anat_low, high = human_anat_high) %>% 
        overlay(img, 
                low = overlay_threshold[1], high = overlay_threshold[2], 
                symmetric = TRUE) %>% 
        grobify()
      
      list_human_slices_POND[[i]][[k]] <- img_grob
      
    } else {
      
      list_human_slices_POND[[i]][[k]] <- rectGrob(gp = gpar(fill = "grey90"))
    
    }
  }
}

```


```{r}
df_matches_HBN <- tibble(mouse_cluster_id = c("2-1", "2-2", "4-1", "4-3", "4-4", "6-1", "6-4", "6-5", "8-1", "8-2", "8-3", "8-4", "8-5", "8-6"),
                          human_cluster_id = c("3-3", "2-2", "4-3", "4-4", "4-2", "6-3", "6-1", "5-3", "8-4", "8-8", "9-8", "7-2", "7-3", "8-2"))


list_human_slices_HBN <- vector(mode = "list", length = length(nk_subset))
names(list_human_slices_HBN) <- nk_subset
for (i in 1:length(list_human_slices_HBN)) {
  
  nki <- nk_subset[i]
  list_human_slices_HBN[[i]] <- vector(mode = "list", length = nki)
  for (k in 1:nki) {
    
    cluster_id <- paste0(nki, "-", k)
    
    if (cluster_id %in% df_matches_HBN$mouse_cluster_id) {
      
      human_cluster_id <- df_matches_HBN %>% 
        filter(mouse_cluster_id == cluster_id) %>% 
        pull(human_cluster_id)
      
      human_nk <- str_split(human_cluster_id, pattern = "-")[[1]][1]
      human_k <- str_split(human_cluster_id, pattern = "-")[[1]][2]
      
      img <- import_cluster_map(imgdir = human_centroid_dirs[2],
                                mask = human_mask_file,
                                nk = human_nk, k = human_k, 
                                threshold = threshold,
                                threshold_value = threshold_value,
                                threshold_symmetric = threshold_symmetric)
      
      # Compute overlay thresholds
      overlay_threshold <- numeric(2)
      overlay_threshold[1] <- min(abs(img[img != 0]))
      overlay_threshold[2] <- 0.8*max(abs(img[img != 0]))
      overlay_threshold <- round(overlay_threshold, 2)
      
      img <- mincArray(img)
      img <- img[slices_dim_1, slices_dim_2, slices_dim_3]
      
      img_grob <- sliceSeries(nrow = 1, ncol = 1, 
                              dimension = human_slc_dim, 
                              slices = human_slc) %>% 
        anatomy(human_anat_vol_cropped, low = human_anat_low, high = human_anat_high) %>% 
        overlay(img, 
                low = overlay_threshold[1], high = overlay_threshold[2], 
                symmetric = TRUE) %>% 
        grobify()
      
      list_human_slices_HBN[[i]][[k]] <- img_grob
      
    } else {
      
      list_human_slices_HBN[[i]][[k]] <- rectGrob(gp = gpar(fill = "grey90"))
    
    }
  }
}

```


# Figure

```{r}
list_mouse_slc_vps_POND <- list(
  # K = 2
  list(x = rep(58, 2),
       y = fig_height - c(60, 168),
       w = c(92, 92),
       h = c(40, 40)),
  # K = 4
  list(x = 200 + c(0, 10, 10, 0),
       y = fig_height - c(65, 118, 147, 205),
       w = c(60, 49, 49, 60),
       h = c(60, 49, 49, 60)/2),
  # K = 6
  list(x = 348 + c(6, 12, 12, 12, 0, 0),
       y = fig_height - c(52, 85, 110, 136, 166, 218),
       w = c(50, 45, 45, 45, 60, 60),
       h = c(50, 45, 45, 45, 60, 60)/2),
  # K = 8
  list(x = 500 + c(0, 5, 4, 4, 5, 5, 4, 4),
       y = fig_height - c(52, 80, 105, 132, 158, 183, 210, 239),
       w = c(50, 45, 47, 45, 45, 45, 47, 47),
       h = c(50, 45, 47, 45, 45, 45, 47, 47)/2)
)
names(list_mouse_slc_vps_POND) <- nk_subset

list_human_slc_vps_POND <- vector(mode = "list", length = length(nk_subset))
names(list_human_slc_vps_POND) <- nk_subset
for (i in 1:length(list_human_slc_vps_POND)) {
  list_human_slc_vps_POND[[i]] <- list(x = numeric(nk_subset[i]),
                                  y = numeric(nk_subset[i]),
                                  w = numeric(nk_subset[i]),
                                  h = numeric(nk_subset[i]))
}

for (i in 2:length(list_human_slc_vps_POND)) {
  list_human_slc_vps_POND[[i]][["x"]] <- list_mouse_slc_vps_POND[[i]][["x"]] + list_mouse_slc_vps_POND[[i]][["w"]] + 5 
  list_human_slc_vps_POND[[i]][["y"]] <- list_mouse_slc_vps_POND[[i]][["y"]]
  list_human_slc_vps_POND[[i]][["w"]] <- 0.6*list_mouse_slc_vps_POND[[i]][["w"]]
  list_human_slc_vps_POND[[i]][["h"]] <- list_mouse_slc_vps_POND[[i]][["h"]]
}

list_human_slc_vps_POND[["2"]] <- list_mouse_slc_vps_POND[["2"]]
list_human_slc_vps_POND[["2"]][["y"]] <- list_mouse_slc_vps_POND[["2"]][["y"]] - list_mouse_slc_vps_POND[["2"]][["h"]] - 5
list_human_slc_vps_POND[["2"]][["h"]] <- list_mouse_slc_vps_POND[["2"]][["h"]] + c(10, 8)

list_mouse_slc_vps_HBN <- list_mouse_slc_vps_POND
list_human_slc_vps_HBN <- list_human_slc_vps_POND
```


```{r}
for (i in 1:length(list_mouse_slc_vps_HBN)) {
  list_mouse_slc_vps_HBN[[i]][["y"]] <- list_mouse_slc_vps_POND[[i]][["y"]] - 390
  list_human_slc_vps_HBN[[i]][["y"]] <- list_human_slc_vps_POND[[i]][["y"]] - 390
}

for (i in 1:length(list_human_slices_POND)) {
  nki <- nk_subset[i]
  for (k in 1:nki) {
    
    list_mouse_slices_POND[[i]][[k]]$vp <- viewport(
      x = unit(list_mouse_slc_vps_POND[[i]][["x"]][[k]], "bigpts"), 
      y = unit(list_mouse_slc_vps_POND[[i]][["y"]][[k]], "bigpts"), 
      width = unit(list_mouse_slc_vps_POND[[i]][["w"]][[k]], "bigpts"), 
      height = unit(list_mouse_slc_vps_POND[[i]][["h"]][[k]], "bigpts"),
      just = c("left", "top")
    )
    
    list_human_slices_POND[[i]][[k]]$vp <- viewport(
      x = unit(list_human_slc_vps_POND[[i]][["x"]][[k]], "bigpts"), 
      y = unit(list_human_slc_vps_POND[[i]][["y"]][[k]], "bigpts"), 
      width = unit(list_human_slc_vps_POND[[i]][["w"]][[k]], "bigpts"), 
      height = unit(list_human_slc_vps_POND[[i]][["h"]][[k]], "bigpts"),
      just = c("left", "top")
    )
    
    list_mouse_slices_HBN[[i]][[k]]$vp <- viewport(
      x = unit(list_mouse_slc_vps_HBN[[i]][["x"]][[k]], "bigpts"), 
      y = unit(list_mouse_slc_vps_HBN[[i]][["y"]][[k]], "bigpts"), 
      width = unit(list_mouse_slc_vps_HBN[[i]][["w"]][[k]], "bigpts"), 
      height = unit(list_mouse_slc_vps_HBN[[i]][["h"]][[k]], "bigpts"),
      just = c("left", "top")
    )
    
    list_human_slices_HBN[[i]][[k]]$vp <- viewport(
      x = unit(list_human_slc_vps_HBN[[i]][["x"]][[k]], "bigpts"), 
      y = unit(list_human_slc_vps_HBN[[i]][["y"]][[k]], "bigpts"), 
      width = unit(list_human_slc_vps_HBN[[i]][["w"]][[k]], "bigpts"), 
      height = unit(list_human_slc_vps_HBN[[i]][["h"]][[k]], "bigpts"),
      just = c("left", "top")
    )
    
  }
}


fig_patchwork <- plt_mouse_sankey_pond / plt_pond_dx / plt_mouse_sankey_hbn / plt_hbn_dx 

sankey_height_npc <- 0.40
dx_height_npc <- 0.10
# padding_height_npc <- 0.025
# padding_height_npc <- (1 - mouse_sankey_height_npc - human_sankey_height_npc - matches_height_npc)/2

fig_patchwork <- fig_patchwork + 
  plot_layout(heights = c(sankey_height_npc, dx_height_npc, 
                          sankey_height_npc, dx_height_npc))

fig_patchwork_grob <- patchworkGrob(fig_patchwork)

grobs_list <- c(list(fig_patchwork_grob), 
                reduce(list_mouse_slices_POND, c),
                reduce(list_human_slices_POND, c),
                reduce(list_mouse_slices_HBN, c),
                reduce(list_human_slices_HBN, c))
grobs <- do.call(grobTree, grobs_list)
# grobs <- fig_patchwork_grob

fig_width_in <- fig_width/72
fig_height_in <- fig_height/72

outfile <- paste0(outfile_prefix, ".pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(fig_width_in, "in"),
    height = unit(fig_height_in, "in"))
grid.draw(grobs)
# grid.segments(x0 = 0, x1 = 1, y0 = seq(0, 1, by = 0.1), y1 = seq(0, 1, by = 0.1))
# grid.segments(x0 = 0, x1 = 1, y0 = seq(0.05, 0.95, by = 0.1), y1 = seq(0.05, 0.95, by = 0.1), gp = gpar(lty = "dashed"))
dev.off()

outfile <- paste0(outfile_prefix, "no_slices.pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(fig_width_in, "in"),
    height = unit(fig_height_in, "in"))
grid.draw(fig_patchwork_grob)
# grid.segments(x0 = 0, x1 = 1, y0 = seq(0, 1, by = 0.1), y1 = seq(0, 1, by = 0.1))
# grid.segments(x0 = 0, x1 = 1, y0 = seq(0.05, 0.95, by = 0.1), y1 = seq(0.05, 0.95, by = 0.1), gp = gpar(lty = "dashed"))
dev.off()
```

```{r}
mouse_grobs_list <- c(list(mouse_sankey_grob), reduce(list_mouse_slices, c))
human_grobs_list <- c(list(human_sankey_grob), reduce(list_human_slices, c))

mouse_grobs <- do.call(grobTree, mouse_grobs_list)
human_grobs <- do.call(grobTree, human_grobs_list)

panel_left_width <- 40
panel_width <- panel_tot_width - panel_left_width

fig_widths <- c(border_padding_width, panel_left_width, panel_width, border_padding_width)
fig_heights <- c(border_padding_height, panel_height, panel_padding_height, panel_height, panel_padding_height, panel_height, border_padding_height)

fig_layout <- rbind(c(NA, NA, NA, NA),
                    c(NA, 01, 01, NA),
                    c(NA, NA, NA, NA),
                    c(NA, NA, 02, NA),
                    c(NA, NA, NA, NA),
                    c(NA, 03, 03, NA),
                    c(NA, NA, NA, NA))

fig_grob <- arrangeGrob(
  mouse_grobs,
  matches_grob,
  human_grobs, #
  layout_matrix = fig_layout,
  widths = unit(fig_widths, "bigpts"),
  heights = unit(fig_heights, "bigpts")
)

fig_width_pt <- sum(fig_widths)
fig_height_pt <- sum(fig_heights)

fig_width_in <- fig_width_pt/72
fig_height_in <- fig_height_pt/72

outfile <- paste0(outfile_prefix, "_old.pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(fig_width_in, "in"),
    height = unit(fig_height_in, "in"))
grid.draw(fig_grob)
dev.off()
```

