---
title: "Figure 3"
subtitle: "Clustering Autism"
author: "Antoine Beauchamp"
date: "2024-09-04"
output: html_document
---

# Initialization

```{r fig3-knitr-setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r fig3-packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(RMINC))
suppressPackageStartupMessages(library(MRIcrotome))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(viridis))
suppressPackageStartupMessages(library(viridisLite))
```

```{r fig3-environment}
SRCPATH <- Sys.getenv("SRCPATH")
PROJECTPATH <- Sys.getenv("PROJECTPATH")
```

```{r fig3-functions}
source(file.path(SRCPATH, "utils.R"))
source(file.path(SRCPATH, "processing.R"))
source(file.path(SRCPATH, "analysis.R"))
```

```{r fig3-pipeline-params}
# Output directory
output_dir <- "figure3_dev/"
if (!dir.exists(output_dir)) {
  dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
}

# Plot file prefix
output_plot_prefix <- "figure3"

# Similarity pipeline
version <- "v3"
pipeline_dir <- file.path(PROJECTPATH, "data/cross_species")
pipeline_dir <- file.path(pipeline_dir, version)

# Similarity parameters
metric <- "correlation"

# Fetch parameter set
metadata <- file.path(pipeline_dir, "metadata.csv")
params <- fetch_params_metadata(metadata = metadata,
                                input_1_species = "human",
                                input_1_id = "700",
                                input_2_species = "mouse",
                                input_2_id = "107",
                                n_latent_spaces = 50,
                                metric = metric)

# Extract thresholding parameters
threshold <- params$threshold
threshold_value <- params$threshold_value
threshold_symmetric <- params$threshold_symmetric

params
```

```{r fig3-graphical-params}
# Number of bigpts in an inch
pt_per_in <- 72

# Font family
font_family <- "Helvetica"

# Nature suggested font size: 5-7 pt
font_size <- 6

# Empty rectangle grob
empty_rect_grob <- rectGrob(gp = gpar(fill = NA))

# Black rectangle grob
black_rect_grob <- rectGrob(gp = gpar(fill = "black"))
```


# Heatmaps

```{r fig3-heatmap-palette}
# Max and min similarity values
similarity_max <- 1.00
similarity_min <- 0.10

# Length of the heatmap palette
heatmap_palette_length <- 255

# Numerical values for the heatmap scale
heatmap_scale_values <- seq(similarity_min, similarity_max, length.out = heatmap_palette_length)
heatmap_scale_values <- (heatmap_scale_values - similarity_min)/(similarity_max - similarity_min)

# Colours for the heatmap palette 
heatmap_scale_colours <- magma(n = heatmap_palette_length, begin = 0.3)

# Heatmap palette vector
heatmap_scale_palette <- colorRampPalette(heatmap_scale_colours)(heatmap_palette_length)
```


## PONDSK-MICe 

```{r fig3-PONDSK-MICe-path}
# Pipeline ID
params_id <- "375"

#Pipeline directory
pipeline_dir <- file.path(PROJECTPATH, "data/cross_species/", version, params_id)
```

```{r fig3-PONDSK-MICe-heatmap-similarity}
# Cluster solutions to visualize
nk_1 <- 2
nk_2 <- 4

# Path to mouse-human similarity directory
similarity_dir <- file.path(pipeline_dir, "similarity")
similarity_file <- file.path(similarity_dir, "similarity.csv")

# Import the similarity data and extract cluster information
similarity <- read_csv(similarity_file, show_col_types = FALSE) %>% 
  mutate(img1_nk = img1 %>% 
           basename() %>% 
           str_extract("_nk_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img1_k = img1 %>% 
           basename() %>% 
           str_extract("_k_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img1_jacobians = img1 %>% 
           str_extract("absolute|relative"),
         img2_nk = img2 %>% 
           basename() %>% 
           str_extract("_nk_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img2_k = img2 %>% 
           basename() %>% 
           str_extract("_k_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img2_jacobians = img2 %>% 
           str_extract("absolute|relative"),) %>% 
  unite(col = "img1_cluster_id", img1_nk, img1_k, 
        sep = "-", remove = FALSE) %>% 
  unite(col = "img2_cluster_id", img2_nk, img2_k, 
        sep = "-", remove = FALSE)

# Filter similarity data for desired cluster numbers
# and combine Jacobians
df_similarity_nk <- similarity %>% 
  filter(img1_nk == nk_1,
         img2_nk == nk_2) %>% 
  group_by(img1_cluster_id, img2_cluster_id) %>% 
  summarise(similarity = mean(similarity),
            .groups = "drop")
```

```{r fig3-PONDSK-MICe-heatmap-permutations}
# Path to permutations directory
permutation_dir <- file.path(pipeline_dir, "permutations", "similarity")

# Permutation file names
permutation_files <- list.files(permutation_dir)

# Number of permutations
np <- length(permutation_files)
list_permutations <- vector(mode = "list", length = np)  
for (p in 1:np) {
  
  # Permutation data to import
  permutation_file <- permutation_files %>% 
    str_subset(str_c("similarity_permutation_", p, ".csv"))
  permutation_file <- file.path(permutation_dir, permutation_file)
  
  # Import permutation data
  list_permutations[[p]] <- read_csv(permutation_file, 
                                     show_col_types = FALSE) %>% 
    mutate(img1_nk = img1 %>% 
             basename() %>% 
             str_extract("_nk_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img1_k = img1 %>% 
             basename() %>% 
             str_extract("_k_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img2_nk = img2 %>% 
             basename() %>% 
             str_extract("_nk_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img2_k = img2 %>% 
             basename() %>% 
             str_extract("_k_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric()) %>% 
    unite(col = "img1_cluster_id", img1_nk, img1_k, 
          sep = "-", remove = FALSE) %>% 
    unite(col = "img2_cluster_id", img2_nk, img2_k, 
          sep = "-", remove = FALSE) %>% 
    mutate(permutation = p)
  
}

# Filter permutations data for desired cluster numbers
# and combine Jacobians
df_permutations_nk <- list_permutations %>% 
  bind_rows() %>% 
  filter(img1_nk == nk_1,
         img2_nk == nk_2) %>% 
  group_by(permutation, img1_nk, img2_nk, img1_cluster_id, img2_cluster_id) %>% 
  summarise(similarity = mean(similarity), .groups = "drop")
```

```{r fig3-PONDSK-MICe-heatmap-pvals}
# Compute p-values for cluster correlations
df_similarity_nk[["pval"]] <- 0
for (i in 1:nrow(df_similarity_nk)) {
  df_similarity_nk[[i, "pval"]] <- sum(df_permutations_nk[["similarity"]] >= df_similarity_nk[[i, "similarity"]])/nrow(df_permutations_nk)
}

# Compute q-values and -log10 transforms
df_similarity_nk <- df_similarity_nk %>% 
  mutate(qval = p.adjust(pval, method = "fdr"),
         pval_log = -log10(pval),
         qval_log = -log10(qval),
         significant = ifelse(pval <= 0.10, TRUE, FALSE),
         pval_lab = case_when(pval > 0.10 ~ "",
                              pval >= 0.001 & pval <= 0.10 ~ paste0("p = ", as.character(round(pval, 3))),
                              pval < 0.001 ~ "p < 0.001"),
         cor_lab = ifelse(pval_lab == "", "", paste0("r = ", as.character(round(similarity, 3)))),
         stat_lab = ifelse(pval_lab == "", "", paste(pval_lab, cor_lab, sep = "\n")))
```

```{r fig3-PONDSK-MICe-heatmap-plot}
# Clamp log p-values when infinite
df_similarity_nk <- df_similarity_nk %>% 
  mutate(pval_log = ifelse(is.infinite(pval_log), 3, pval_log))

# Heatmap plot
fig3_heatmap_PONDSK_MICe <- ggplot(df_similarity_nk, 
                                   aes(x = img2_cluster_id, 
                                       y = fct_rev(img1_cluster_id), 
                                       fill = similarity)) + 
  geom_tile(col = "grey50") + 
  geom_text(mapping = aes(label = stat_lab),
            size = 1.6, 
            hjust = "center", 
            vjust = "center") + 
  labs(x = "Mouse clusters",
       y = "POND-SickKids clusters",
       fill = "Correlation") + 
  scale_fill_gradientn(colors = heatmap_scale_palette,
                       values = heatmap_scale_values,
                       limits = c(similarity_min, similarity_max),
                       breaks = seq(0, 1, by = 0.2)) + 
  # ,
  # guide = guide_colourbar(title.position = "top",
  #                         title.hjust = 0.5)) + 
  scale_x_discrete(expand = expansion(mult = 0), position = "top") + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  theme_bw() +
  theme(plot.margin = margin(t = 3, r = 3, b = 8, l = 3))

# Export plot without legend
outfile <- paste0("figure3_PONDSK_MICe_heatmap.pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(500/72, "in"),
    height = unit(500/72, "in"))
print(fig3_heatmap_PONDSK_MICe)
dev.off()
```

```{r fig3-PONDSK-MICe-matches}
df_matches_PONDSK_MICe_opt <- df_similarity_nk %>% 
  filter(pval_lab != "") %>% 
  select(POND = img1_cluster_id, MICe = img2_cluster_id)
```

```{r fig3-PONDSK-MICe-export}
outfile <- "PONDSK_MICe_opt.csv"
outfile <- file.path(output_dir, outfile)
df_similarity_nk %>% 
  select(img1_cluster_id, img2_cluster_id, similarity, pval) %>% 
  write_csv(file = outfile)
```


## HBN-MICe

```{r fig3-HBN-MICe-path}
# Pipeline ID
params_id <- "861"

#Pipeline directory
pipeline_dir <- file.path(PROJECTPATH, "data/cross_species/", version, params_id)
```


```{r fig3-HBN-MICe-heatmap-similarity}
# Cluster solutions to visualize
nk_1 <- 3
nk_2 <- 4

# Path to mouse-human similarity directory
similarity_dir <- file.path(pipeline_dir, "similarity")
similarity_file <- file.path(similarity_dir, "similarity.csv")

# Import the similarity data and extract cluster information
similarity <- read_csv(similarity_file, show_col_types = FALSE) %>% 
  mutate(img1_nk = img1 %>% 
           basename() %>% 
           str_extract("_nk_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img1_k = img1 %>% 
           basename() %>% 
           str_extract("_k_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img1_jacobians = img1 %>% 
           str_extract("absolute|relative"),
         img2_nk = img2 %>% 
           basename() %>% 
           str_extract("_nk_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img2_k = img2 %>% 
           basename() %>% 
           str_extract("_k_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img2_jacobians = img2 %>% 
           str_extract("absolute|relative"),) %>% 
  unite(col = "img1_cluster_id", img1_nk, img1_k, 
        sep = "-", remove = FALSE) %>% 
  unite(col = "img2_cluster_id", img2_nk, img2_k, 
        sep = "-", remove = FALSE)

# Filter similarity data for desired cluster numbers
# and combine Jacobians
df_similarity_nk <- similarity %>% 
  filter(img1_nk == nk_1,
         img2_nk == nk_2) %>% 
  group_by(img1_cluster_id, img2_cluster_id) %>% 
  summarise(similarity = mean(similarity),
            .groups = "drop")
```

```{r fig3-HBN-MICe-heatmap-permutations}
# Path to permutations directory
permutation_dir <- file.path(pipeline_dir, "permutations", "similarity")

# Permutation file names
permutation_files <- list.files(permutation_dir)

# Number of permutations
np <- length(permutation_files)
list_permutations <- vector(mode = "list", length = np)  
for (p in 1:np) {
  
  # Permutation data to import
  permutation_file <- permutation_files %>% 
    str_subset(str_c("similarity_permutation_", p, ".csv"))
  permutation_file <- file.path(permutation_dir, permutation_file)
  
  # Import permutation data
  list_permutations[[p]] <- read_csv(permutation_file, 
                                     show_col_types = FALSE) %>% 
    mutate(img1_nk = img1 %>% 
             basename() %>% 
             str_extract("_nk_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img1_k = img1 %>% 
             basename() %>% 
             str_extract("_k_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img2_nk = img2 %>% 
             basename() %>% 
             str_extract("_nk_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img2_k = img2 %>% 
             basename() %>% 
             str_extract("_k_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric()) %>% 
    unite(col = "img1_cluster_id", img1_nk, img1_k, 
          sep = "-", remove = FALSE) %>% 
    unite(col = "img2_cluster_id", img2_nk, img2_k, 
          sep = "-", remove = FALSE) %>% 
    mutate(permutation = p)
  
}

# Filter permutations data for desired cluster numbers
# and combine Jacobians
df_permutations_nk <- list_permutations %>% 
  bind_rows() %>% 
  filter(img1_nk == nk_1,
         img2_nk == nk_2) %>% 
  group_by(permutation, img1_nk, img2_nk, img1_cluster_id, img2_cluster_id) %>% 
  summarise(similarity = mean(similarity), .groups = "drop")
```

```{r fig3-HBN-MICe-heatmap-pvals}
# Compute p-values for cluster correlations
df_similarity_nk[["pval"]] <- 0
for (i in 1:nrow(df_similarity_nk)) {
  df_similarity_nk[[i, "pval"]] <- sum(df_permutations_nk[["similarity"]] >= df_similarity_nk[[i, "similarity"]])/nrow(df_permutations_nk)
}

# Compute q-values and -log10 transforms
df_similarity_nk <- df_similarity_nk %>% 
  mutate(qval = p.adjust(pval, method = "fdr"),
         pval_log = -log10(pval),
         qval_log = -log10(qval),
         significant = ifelse(pval <= 0.10, TRUE, FALSE),
         pval_lab = case_when(pval > 0.10 ~ "",
                              pval >= 0.001 & pval <= 0.10 ~ paste0("p = ", as.character(round(pval, 3))),
                              pval < 0.001 ~ "p < 0.001"),
         cor_lab = ifelse(pval_lab == "", "", paste0("r = ", as.character(round(similarity, 3)))),
         stat_lab = ifelse(pval_lab == "", "", paste(pval_lab, cor_lab, sep = "\n")))
```

```{r fig3-HBN-MICe-heatmap-plot}
# Clamp log p-values when infinite
df_similarity_nk <- df_similarity_nk %>% 
  mutate(pval_log = ifelse(is.infinite(pval_log), 3, pval_log))

# Heatmap plot
fig3_heatmap_HBN_MICe <- ggplot(df_similarity_nk, 
                                aes(x = img2_cluster_id, 
                                    y = fct_rev(img1_cluster_id), 
                                    fill = similarity)) + 
  geom_tile(col = "grey50") + 
  geom_text(mapping = aes(label = stat_lab),
            size = 1.6, 
            hjust = "center", 
            vjust = "center") + 
  labs(x = "Mouse clusters",
       y = "HBN clusters",
       fill = "Correlation") + 
  scale_fill_gradientn(colors = heatmap_scale_palette,
                       values = heatmap_scale_values,
                       limits = c(similarity_min, similarity_max),
                       breaks = seq(0, 1, by = 0.2)) + 
  scale_x_discrete(expand = expansion(mult = 0), position = "top") + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  theme_bw() +
  theme(legend.position = "none",
        plot.margin = margin(t = 3, r = 3, b = 8, l = 3))

# Export
outfile <- paste0("figure3_HBN_MICe_heatmap.pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(500/72, "in"),
    height = unit(500/72, "in"))
print(fig3_heatmap_HBN_MICe)
dev.off()
```

```{r fig3-HBN-MICe-matches}
df_matches_HBN_MICe_opt <- df_similarity_nk %>% 
  filter(pval_lab != "") %>% 
  select(HBN = img1_cluster_id, MICe = img2_cluster_id)
```

```{r fig3-HBN-MICe-export}
outfile <- "HBN_MICe_opt.csv"
outfile <- file.path(output_dir, outfile)
df_similarity_nk %>% 
  select(img1_cluster_id, img2_cluster_id, similarity, pval) %>% 
  write_csv(file = outfile)
```


## PONDSK-HBN

```{r fig3-PONDSK-HBN-path}
# Pipeline ID
params_id <- "779"

#Pipeline directory
pipeline_dir <- file.path(PROJECTPATH, "data/cross_species/", version, params_id)
```

```{r fig3-PONDSK-HBN-heatmap-similarity}
# Cluster solutions to visualize
nk_1 <- 2
nk_2 <- 3

# Path to mouse-human similarity directory
similarity_dir <- file.path(pipeline_dir, "similarity")
similarity_file <- file.path(similarity_dir, "similarity.csv")

# Import the similarity data and extract cluster information
similarity <- read_csv(similarity_file, show_col_types = FALSE) %>% 
  mutate(img1_nk = img1 %>% 
           basename() %>% 
           str_extract("_nk_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img1_k = img1 %>% 
           basename() %>% 
           str_extract("_k_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img1_jacobians = img1 %>% 
           str_extract("absolute|relative"),
         img2_nk = img2 %>% 
           basename() %>% 
           str_extract("_nk_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img2_k = img2 %>% 
           basename() %>% 
           str_extract("_k_[0-9]+") %>% 
           str_extract("[0-9]+") %>% 
           as.numeric(),
         img2_jacobians = img2 %>% 
           str_extract("absolute|relative"),) %>% 
  unite(col = "img1_cluster_id", img1_nk, img1_k, 
        sep = "-", remove = FALSE) %>% 
  unite(col = "img2_cluster_id", img2_nk, img2_k, 
        sep = "-", remove = FALSE)

# Filter similarity data for desired cluster numbers
# and combine Jacobians
df_similarity_nk <- similarity %>% 
  filter(img1_nk == nk_1,
         img2_nk == nk_2) %>% 
  group_by(img1_cluster_id, img2_cluster_id) %>% 
  summarise(similarity = mean(similarity),
            .groups = "drop")
```

```{r fig3-PONDSK-HBN-heatmap-permutations}
# Path to permutations directory
permutation_dir <- file.path(pipeline_dir, "permutations", "similarity")

# Permutation file names
permutation_files <- list.files(permutation_dir)

# Number of permutations
np <- length(permutation_files)
list_permutations <- vector(mode = "list", length = np)  
for (p in 1:np) {
  
  # Permutation data to import
  permutation_file <- permutation_files %>% 
    str_subset(str_c("similarity_permutation_", p, ".csv"))
  permutation_file <- file.path(permutation_dir, permutation_file)
  
  # Import permutation data
  list_permutations[[p]] <- read_csv(permutation_file, 
                                     show_col_types = FALSE) %>% 
    mutate(img1_nk = img1 %>% 
             basename() %>% 
             str_extract("_nk_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img1_k = img1 %>% 
             basename() %>% 
             str_extract("_k_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img2_nk = img2 %>% 
             basename() %>% 
             str_extract("_nk_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric(),
           img2_k = img2 %>% 
             basename() %>% 
             str_extract("_k_[0-9]+") %>% 
             str_extract("[0-9]+") %>% 
             as.numeric()) %>% 
    unite(col = "img1_cluster_id", img1_nk, img1_k, 
          sep = "-", remove = FALSE) %>% 
    unite(col = "img2_cluster_id", img2_nk, img2_k, 
          sep = "-", remove = FALSE) %>% 
    mutate(permutation = p)
  
}

# Filter permutations data for desired cluster numbers
# and combine Jacobians
df_permutations_nk <- list_permutations %>% 
  bind_rows() %>% 
  filter(img1_nk == nk_1,
         img2_nk == nk_2) %>% 
  group_by(permutation, img1_nk, img2_nk, img1_cluster_id, img2_cluster_id) %>% 
  summarise(similarity = mean(similarity), .groups = "drop")
```

```{r fig3-PONDSK-HBN-heatmap-pvals}
# Compute p-values for cluster correlations
df_similarity_nk[["pval"]] <- 0
for (i in 1:nrow(df_similarity_nk)) {
  df_similarity_nk[[i, "pval"]] <- sum(df_permutations_nk[["similarity"]] >= df_similarity_nk[[i, "similarity"]])/nrow(df_permutations_nk)
}

# Compute q-values and -log10 transforms
df_similarity_nk <- df_similarity_nk %>% 
  mutate(qval = p.adjust(pval, method = "fdr"),
         pval_log = -log10(pval),
         qval_log = -log10(qval),
         significant = ifelse(pval <= 0.10, TRUE, FALSE),
         pval_lab = case_when(pval > 0.10 ~ "",
                              pval >= 0.001 & pval <= 0.10 ~ paste0("p = ", as.character(round(pval, 3))),
                              pval < 0.001 ~ "p < 0.001"),
         pval_lab = ifelse(img1_cluster_id == "2-2" & img2_cluster_id == "3-3", paste0("p = ", as.character(round(pval, 3))), pval_lab),
         cor_lab = ifelse(pval_lab == "", "", paste0("r = ", as.character(round(similarity, 3)))),
         stat_lab = ifelse(pval_lab == "", "", paste(pval_lab, cor_lab, sep = "\n")))
```

```{r fig3-PONDSK-HBN-heatmap-plot}
# Clamp log p-values when infinite
df_similarity_nk <- df_similarity_nk %>% 
  mutate(pval_log = ifelse(is.infinite(pval_log), 3, pval_log))

# Heatmap plot
fig3_heatmap_PONDSK_HBN <- ggplot(df_similarity_nk, 
                                  aes(x = img2_cluster_id, 
                                      y = fct_rev(img1_cluster_id), 
                                      fill = similarity)) + 
  geom_tile(col = "grey50") + 
  geom_text(mapping = aes(label = stat_lab),
            size = 1.6, 
            hjust = "center", 
            vjust = "center") + 
  labs(x = "HBN clusters",
       y = "POND-SickKids clusters",
       fill = "Correlation") + 
  scale_fill_gradientn(colors = heatmap_scale_palette,
                       values = heatmap_scale_values,
                       limits = c(similarity_min, similarity_max),
                       breaks = seq(0, 1, by = 0.2)) + 
  scale_x_discrete(expand = expansion(mult = 0), position = "top") + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  theme_bw() +
  theme(legend.position = "none",
        plot.margin = margin(t = 3, r = 3, b = 8, l = 3))

# Export
outfile <- paste0("figure3_PONDSK_HBN_heatmap.pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(500/72, "in"),
    height = unit(500/72, "in"))
print(fig3_heatmap_PONDSK_HBN)
dev.off()
```

```{r fig3-PONDSK-HBN-matches}
df_matches_PONDSK_HBN_opt <- df_similarity_nk %>% 
  filter(pval_lab != "") %>% 
  select(POND = img1_cluster_id, HBN = img2_cluster_id)
```

```{r fig3-PONDSK-HBN-export}
outfile <- "PONDSK_HBN_opt.csv"
outfile <- file.path(output_dir, outfile)
df_similarity_nk %>% 
  select(img1_cluster_id, img2_cluster_id, similarity, pval) %>% 
  write_csv(file = outfile)
```


## Heatmap patchwork

```{r fig3-heatmap-patchwork}
# Create heatmap patchwork
fig3_heatmap <- (fig3_heatmap_PONDSK_MICe | fig3_heatmap_HBN_MICe | fig3_heatmap_PONDSK_HBN) +
  plot_layout(guides = 'collect') &
  theme(axis.text = element_text(size = font_size-1, family = font_family),
        axis.title = element_text(size = font_size, family = font_family))

# Export
outfile <- paste0("figure3_heatmap.pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(510/72, "in"),
    height = unit(236/72, "in"))
print(fig3_heatmap)
dev.off()
```


# Neuroanatomical slices


```{r fig3-ss-matches}
# Combine data set matches for optimal solutions
df_matches <- df_matches_PONDSK_MICe_opt %>% 
  inner_join(df_matches_HBN_MICe_opt, by = "MICe")
```

```{r fig3-ss-paths}
# Mouse mask
mouse_mask_file <- file.path(PROJECTPATH, "data/mouse/atlas/DSURQE_CCFv3_mask_50um.mnc")
mouse_mask <- mincGetVolume(mouse_mask_file)

# Mouse anatomy
mouse_anat_file <- file.path(PROJECTPATH, "data/mouse/atlas/DSURQE_CCFv3_average_50um.mnc")
mouse_anat <- mincGetVolume(mouse_anat_file)
mouse_anat[mouse_mask < 0.4] <- 0
mouse_anat_vol <- mincArray(mouse_anat)

# Human mask
human_mask_file <- file.path(PROJECTPATH, "data/human/registration/v3/reference_files/mask_0.8mm.mnc")
human_mask <- mincGetVolume(human_mask_file)

# Human anatomy
human_anat_file <- file.path(PROJECTPATH, "data/human/registration/v3/reference_files/model_0.8mm.mnc")
human_anat <- mincGetVolume(human_anat_file)
human_anat[human_mask != 1] <- 0
human_anat_vol <- mincArray(human_anat)

# Cropped human human images
# slices_dim_1 <- 27:220
# slices_dim_1 <- 36:212
slices_dim_1 <- 1:248
slices_dim_3 <- 10:220
human_anat_vol_cropped <- human_anat_vol[slices_dim_1,, slices_dim_3]
```

```{r fig3-ss-dims}
# Mouse slice dimensions in pixels
mouse_width_px <- dim(mouse_anat_vol)[2]
mouse_height_px <- dim(mouse_anat_vol)[3]

# Human slice dimensions in pixels
human_width_px <- dim(human_anat_vol_cropped)[2]
human_height_px <- dim(human_anat_vol_cropped)[3]

human_slc_height_pt <- 30.23
human_slc_width_pt <- human_slc_height_pt*(human_width_px/human_height_px)

mouse_slc_height_pt <- human_slc_height_pt
mouse_slc_width_pt <- mouse_slc_height_pt*(mouse_width_px/mouse_height_px)
```


```{r}
datasets <- colnames(df_matches)
param_ids <- c("700", "107", "013")
species <- c("human", "mouse", "human")
resolutions <- c("resolution_0.8", "resolution_0.05", "resolution_0.8")
centroid_dirs <- file.path(PROJECTPATH, "data", species, "derivatives", version, param_ids, "centroids", resolutions, "relative")

slc_dim <- 2

nslices <- 5

# Human slices
human_slices <- floor(seq(60, 230, length.out = nslices))

# Mouse slices
mouse_slices <- floor(seq(20, 200, length.out = nslices))

slices <- list(human_slices, mouse_slices, human_slices)

threshold_anat <- list(c(40, 110), c(800, 2000), c(40, 110))
threshold_overlay <- c(0.19, 1.0)

maskfiles <- c(human_mask_file, mouse_mask_file, human_mask_file)

templates <- list(human_anat_vol_cropped, mouse_anat_vol, human_anat_vol_cropped)

# Iterate over matches
for (i in 1:nrow(df_matches)) {
  
  outfile <- ""
  list_slice_grobs <- vector(mode = "list", length = ncol(df_matches))
  names(list_slice_grobs) <- datasets
  for (j in 1:ncol(df_matches)) {
    # j <- 1
    
    # Extract cluster information
    cluster_id <- df_matches[[i, j]]
    nk <- str_split(cluster_id, pattern = "-", simplify = TRUE)[1]
    k <- str_split(cluster_id, pattern = "-", simplify = TRUE)[2]
    
    # Import centroid image and threshold
    img <- import_cluster_map(imgdir = centroid_dirs[j],
                              mask = maskfiles[j],
                              nk = nk, k = k,
                              threshold = threshold,
                              threshold_value = threshold_value,
                              threshold_symmetric = threshold_symmetric)
    
    # Convert mincSingleDim to mincArray and crop
    img <- mincArray(img)
    if (datasets[j] %in% c("POND", "HBN")) {
      img <- img[slices_dim_1, , slices_dim_3]
    }
    
    # Iterate over slices
    list_slice_grobs[[j]] <- vector(mode = "list", length = nslices)
    for (s in 1:nslices) {
      # s <- 1
      
      # Generate slice series
      list_slice_grobs[[j]][[s]] <- sliceSeries(nrow = 1, ncol = 1, 
                                                dimension = slc_dim, 
                                                slices = slices[[j]][s]) %>% 
        anatomy(templates[[j]], low = threshold_anat[[j]][1], high = threshold_anat[[j]][2]) %>% 
        overlay(img, 
                low = threshold_overlay[1], 
                high = threshold_overlay[2], 
                symmetric = TRUE) %>% 
        grobify()
      
    }
    
    if (j == 1) {
      outfile <- paste(datasets[j], cluster_id, sep = "_")    
    } else {
      outfile <- paste(outfile, datasets[j], cluster_id, sep = "_")
    }
    
  }
  
  ss_nrow <- nslices
  ss_ncol <- length(datasets)
  
  ss_grobs_list <- reduce(.x = list_slice_grobs, .f = c)
  
  ss_layout <- matrix(1:length(ss_grobs_list),
                      nrow = ss_nrow, ncol = ss_ncol,
                      byrow = FALSE)
  
  ss_grob <- arrangeGrob(grobs = ss_grobs_list,
                         layout_matrix = ss_layout)
  
  ss_height_pt <- 195
  ss_width_pt <- ss_height_pt*(ss_ncol/ss_nrow)
  
  # Export human ss plot
  outfile <- paste("ss", outfile, sep = "_")
  outfile <- paste0(outfile, ".pdf")
  outfile <- file.path(output_dir, outfile)
  export_pdf(x = ss_grob,
             width = ss_width_pt,
             height = ss_height_pt,
             units = "bigpts",
             file = outfile)
  
}
```
