---
title: "Untitled"
format: html
editor: visual
---

- Demographics for multiple clusters in POND+ and HBN
- Univariate behaviour for POND+ and HBN

```{r packages}
library(tidyverse)
library(ggalluvial)
library(ggnewscale)
library(patchwork)
library(grid)
library(gridExtra)
library(viridis)
library(rcartocolor)
```

```{r env}
PROJECTPATH <- Sys.getenv("PROJECTPATH")
SRCPATH <- Sys.getenv("SRCPATH")
```

```{r functions}
consolidate_visits <- function(df, cols) {
  
  subject_ids <- df %>% 
    pull(subject_id) %>% 
    unique()
  
  df_init <- df %>% 
    select(subject_id, visit_instance, all_of(cols)) %>% 
    mutate(n_missing = rowSums(!is.na(across(all_of(cols)))))
  
  df_complete <- df_init %>% 
    filter(n_missing > 0) %>% 
    group_by(subject_id) %>% 
    filter(visit_instance == max(visit_instance)) %>% 
    ungroup() %>% 
    select(subject_id, all_of(cols))
  
  # Participants with completed ABAS
  ids_complete <- df_complete %>% 
    pull(subject_id) %>% 
    unique()
  
  # Participants with no ABAS scores
  ids_missing <- setdiff(subject_ids, ids_complete)
  
  # Create a data frame of NAs for particpants with no scores
  df_missing <- matrix(nrow = length(ids_missing), ncol = length(cols))
  rownames(df_missing) <- ids_missing
  colnames(df_missing) <- cols
  df_missing <- as_tibble(df_missing, rownames = "subject_id")
  
  df_out <- bind_rows(df_complete, df_missing)
  
  return(df_out)
  
}
```

```{r outputs}
outfile_prefix <- "figure_S7_dev"
output_dir <- file.path("outputs", outfile_prefix)
if (!(dir.exists(output_dir))) {dir.create(path = output_dir, recursive = TRUE)}
```

```{r}
# Human registration directory
human_registration_dir <- file.path(PROJECTPATH, "data/human/registration/v3")

# Import human demographics data
demographics <- file.path(human_registration_dir, "subject_info", "demographics.csv")
demographics <- read_csv(demographics, show_col_types = FALSE)

demographics
```


# Human diagnoses

```{r}
list_diagnoses <- list(
  "POND" = tibble(DX = c("ASD", "OCD", "ADHD", "Sub-threshold OCD",
                         "Anxiety", "Sub-threshold ADHD",
                         "Intellectual Disability only", 
                         "Tourette Syndrome", "Other", "Fragile X"),
                  DX_new = c("ASD", "OCD", "ADHD", "OCD", "Other", 
                             "ADHD", "Other", "Other", "Other", "Other")),
  "HBN" = tibble(DX = c("ASD", "OCD", "ADHD", "Tourette Syndrome", "ID"),
                 DX_new = c("ASD", "OCD", "ADHD", "Other", "Other"))
)

```

## POND+

```{r}
df_pond_cluster_labels <- readxl::read_excel("resources/POND_cluster_labels_colours.xlsx") %>% 
  separate(col = "cluster_id", into = c("nk_old", "k_old"), remove = FALSE) %>% 
  separate(col = "cluster_id_new", into = c("nk_new", "k_new"), remove = FALSE) %>%
  mutate(nk_old = as.numeric(nk_old),
         k_old = as.numeric(k_old),
         nk_new = as.numeric(nk_new),
         k_new = as.numeric(k_new))
```


```{r}
file <- "data/human/derivatives/v3/700/clusters/resolution_3.0/clusters.csv"
file <- file.path(PROJECTPATH, file)
df_clusters_pond <- read_csv(file, show_col_types = FALSE)

df_clusters_pond_long <- df_clusters_pond %>% 
  pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = as.numeric(str_remove(nk_name, "nk"))) %>% 
  unite("cluster_id", nk, k, sep = "-", remove = FALSE) %>% 
  select(-nk_name)

df_clusters_pond_long <- df_clusters_pond_long %>% 
  left_join(df_pond_cluster_labels, 
            by = c("cluster_id", "nk" = "nk_old", "k" = "k_old")) %>% 
  select(ID, cluster_id = cluster_id_new, nk = nk_new, k = k_new)

df_clusters_pond_dx <- df_clusters_pond_long %>% 
  left_join(select(demographics, file, DX), by = c("ID" = "file")) %>% 
  left_join(list_diagnoses$POND, by = "DX") %>% 
  select(-DX, DX = DX_new) 
```

```{r}
nk_subset <- seq(2, 10, by = 2)

dx_lvls <- c("ASD", "ADHD", "OCD", "Other")

list_pond_dx_plots <- vector(mode = "list", length = length(nk_subset))
for (i in 1:length(nk_subset)) {
  
  nki <- nk_subset[i]
  
  df_clusters_pond_dx_K <- df_clusters_pond_dx %>% 
    filter(nk == nki)   
  
  df_grid <- expand_grid(k = 1:nki, DX = dx_lvls)
  
  df_cluster_dx_summary <- df_clusters_pond_dx_K %>% 
    group_by(cluster_id) %>% 
    mutate(n_in_cluster = n()) %>% 
    ungroup() %>% 
    group_by(cluster_id, DX) %>% 
    mutate(n_dx_in_cluster = n()) %>%
    ungroup() %>% 
    select(cluster_id, k, DX, n_in_cluster, n_dx_in_cluster)  %>% 
    distinct() %>% 
    mutate(prop_dx = n_dx_in_cluster/n_in_cluster) %>% 
    right_join(df_grid, by = c("DX", "k")) %>% 
    mutate(prop_dx = ifelse(is.na(prop_dx), 0, prop_dx),
           k = factor(k),
           label = paste0("K = ", nki))
  
  plt <- ggplot(df_cluster_dx_summary, aes(x = k, y = prop_dx, fill = DX)) + 
    geom_col(position = "dodge") +
    facet_grid(.~label) + 
    labs(x = "POND+ cluster (k)",
         fill = "Diagnosis") + 
    theme_bw() +
    theme(plot.margin = margin(l = 2, t = 2),
          axis.title = element_text(size = 6),
          axis.text = element_text(size = 6),
          strip.text = element_text(size = 6, margin = margin(t = 2, b = 2)))
  
  if (i == 1) {
    plt <- plt + 
      coord_cartesian(ylim = c(0, 1.0)) + 
      labs(y = "") +
      theme(axis.title.x = element_blank(),
            legend.text = element_text(size = 6, margin = margin(l = 2)),
            legend.title = element_text(size = 6, margin = margin(b = 2)),
            legend.key.size = unit(10, "bigpts"),
            legend.margin = margin(),
            legend.box.margin = margin())
    
    diagnoses_legend_grob <- plt %>% 
      ggplotGrob() %>% 
      grid.force() %>% 
      getGrob("guide-box-right.10-11-10-11")

  }
  
  
  if (i %in% 2:3) {
    plt <- plt + 
      coord_cartesian(ylim = c(0, 0.7)) + 
      theme(axis.title.y = element_blank(),
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank(),
            axis.title.x = element_blank(),
            plot.margin = margin(l = 2, t = 2))
  }
  
  if (i == 4) {
    plt <- plt + 
      coord_cartesian(ylim = c(0, 1.0)) + 
      labs(y = "Proportion per cluster") +
      theme(axis.title.x = element_blank())
  }
  
  if (i == 5) {
    plt <- plt +
      labs(y = "")
  }
  
  plt <- plt + theme(legend.position = "none")
  
  list_pond_dx_plots[[i]] <- plt
  
}



pond_dx_widths <- c(0.2461, 0.2930, 0.4609) 
pond_dx_heights <- c(0.3125, 0.3125, 0.3750)
pond_dx_layout <- rbind(c(01, 02, 03),
                        c(05, 05, 05),
                        c(04, 04, 04))

pond_dx_grob <- arrangeGrob(list_pond_dx_plots[[1]],
                            list_pond_dx_plots[[2]],
                            list_pond_dx_plots[[3]],
                            list_pond_dx_plots[[5]],
                            list_pond_dx_plots[[4]],
                            layout_matrix = pond_dx_layout,
                            widths = unit(pond_dx_widths, "npc"),
                            heights = unit(pond_dx_heights, "npc"))
```

## HBN

```{r}
df_hbn_cluster_labels <- readxl::read_excel("resources/HBN_cluster_labels_colours.xlsx") %>% 
  separate(col = "cluster_id", into = c("nk_old", "k_old"), remove = FALSE) %>% 
  separate(col = "cluster_id_new", into = c("nk_new", "k_new"), remove = FALSE) %>%
  mutate(nk_old = as.numeric(nk_old),
         k_old = as.numeric(k_old),
         nk_new = as.numeric(nk_new),
         k_new = as.numeric(k_new))
```

```{r}
file <- "data/human/derivatives/v3/013/clusters/resolution_3.0/clusters.csv"
file <- file.path(PROJECTPATH, file)
df_clusters_hbn <- read_csv(file, show_col_types = FALSE)

df_clusters_hbn_long <- df_clusters_hbn %>% 
  pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = as.numeric(str_remove(nk_name, "nk"))) %>% 
  unite("cluster_id", nk, k, sep = "-", remove = FALSE) %>% 
  select(-nk_name)

df_clusters_hbn_long <- df_clusters_hbn_long %>% 
  left_join(df_hbn_cluster_labels, 
            by = c("cluster_id", "nk" = "nk_old", "k" = "k_old")) %>% 
  select(ID, cluster_id = cluster_id_new, nk = nk_new, k = k_new)

df_clusters_hbn_dx <- df_clusters_hbn_long %>% 
  left_join(select(demographics, file, DX), by = c("ID" = "file")) %>% 
  left_join(list_diagnoses$HBN, by = "DX") %>% 
  select(-DX, DX = DX_new) 
```

```{r}
nk_subset <- seq(2, 10, by = 2)

dx_lvls <- c("ASD", "ADHD", "OCD", "Other")

list_hbn_dx_plots <- vector(mode = "list", length = length(nk_subset))
for (i in 1:length(nk_subset)) {
  
  nki <- nk_subset[i]
  
  df_clusters_hbn_dx_K <- df_clusters_hbn_dx %>% 
    filter(nk == nki)   
  
  df_grid <- expand_grid(k = 1:nki,
                         DX = dx_lvls)
  
  df_cluster_dx_summary <- df_clusters_hbn_dx_K %>% 
    group_by(cluster_id) %>% 
    mutate(n_in_cluster = n()) %>% 
    ungroup() %>% 
    group_by(cluster_id, DX) %>% 
    mutate(n_dx_in_cluster = n()) %>%
    ungroup() %>% 
    select(cluster_id, k, DX, n_in_cluster, n_dx_in_cluster)  %>% 
    distinct() %>% 
    mutate(prop_dx = n_dx_in_cluster/n_in_cluster) %>% 
    right_join(df_grid, by = c("DX", "k")) %>% 
    mutate(prop_dx = ifelse(is.na(prop_dx), 0, prop_dx),
           k = factor(k),
           label = paste0("K = ", nki))
  
  plt <- ggplot(df_cluster_dx_summary, aes(x = k, y = prop_dx, fill = DX)) + 
    geom_col(position = "dodge") +
    facet_grid(.~label) + 
    coord_cartesian(ylim = c(0, 1.0)) + 
    labs(x = "HBN cluster (k)") + 
    theme_bw() +
    theme(legend.position = "none",
          plot.margin = margin(l = 2, t = 2),
          axis.title = element_text(size = 6),
          axis.text = element_text(size = 6),
          strip.text = element_text(size = 6, margin = margin(t = 2, b = 2)))
  
  if (i == 1) {
    plt <- plt + 
      labs(y = "") +
      theme(axis.title.x = element_blank())
  }
  
  
  if (i %in% 2:3) {
    plt <- plt + 
      theme(axis.title.y = element_blank(),
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank(),
            axis.title.x = element_blank(),
            plot.margin = margin(l = 2, t = 2))
  }
  
  if (i == 4) {
    plt <- plt + 
      labs(y = "Proportion per cluster") +
      theme(axis.title.x = element_blank())
  }
  
  if (i == 5) {
    plt <- plt +
      labs(y = "")
  }
  
  
  list_hbn_dx_plots[[i]] <- plt
  
}



hbn_dx_widths <- c(0.2461, 0.2930, 0.4609) 
hbn_dx_heights <- c(0.3125, 0.3125, 0.3750)
hbn_dx_layout <- rbind(c(01, 02, 03),
                        c(05, 05, 05),
                       c(04, 04, 04))

hbn_dx_grob <- arrangeGrob(list_hbn_dx_plots[[1]],
                            list_hbn_dx_plots[[2]],
                            list_hbn_dx_plots[[3]],
                            list_hbn_dx_plots[[5]],
                            list_hbn_dx_plots[[4]],
                            layout_matrix = hbn_dx_layout,
                            widths = unit(hbn_dx_widths, "npc"),
                            heights = unit(hbn_dx_heights, "npc"))
```


# Mouse gene scores

```{r}
df_mouse_cluster_labels <- readxl::read_excel("resources/MICe_cluster_labels_colours.xlsx") %>% 
  separate(col = "cluster_id", into = c("nk_old", "k_old"), remove = FALSE) %>% 
  separate(col = "cluster_id_new", into = c("nk_new", "k_new"), remove = FALSE) %>%
  mutate(nk_old = as.numeric(nk_old),
         k_old = as.numeric(k_old),
         nk_new = as.numeric(nk_new),
         k_new = as.numeric(k_new))
```



```{r}
file_model_names <- "../../data/mouse/derivatives/v3/107/model_names.csv"
df_model_names <- read_csv(file_model_names, show_col_types = FALSE)
df_model_names
```

```{r}
file_mouse_clusters <- "../../data/mouse/derivatives/v3/107/clusters/resolution_0.2/clusters.csv"
df_mouse_clusters <- read_csv(file_mouse_clusters, show_col_types = FALSE)

df_mouse_clusters_long <- df_mouse_clusters %>% 
  rename(file = ID) %>% 
  pivot_longer(cols = -file, names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = as.numeric(str_remove(nk_name, "nk"))) %>% 
  select(-nk_name) %>% 
  unite(col = "cluster_id", "nk", "k", sep = "-", remove = FALSE)

df_mouse_clusters_long 
```

```{r}
file <- "resources/Eagle_Data.csv"
df_mouse_gene_scores <- read_csv(file, show_col_types = FALSE)

df_mouse_gene_scores <- df_mouse_gene_scores %>% 
  select(model = Model, gene = Gene, 
         sfari_score = gene.score, sfari_syndromic = syndromic, 
         eagle, eagle_binary) %>% 
  distinct()

df_mouse_gene_scores <- df_mouse_gene_scores %>% 
  left_join(df_model_names, by = c("model" = "ID"))
```

```{r}
df_mouse_cluster_scores <- df_mouse_clusters_long %>%
  left_join(df_mouse_gene_scores, by = "file")

df_mouse_cluster_scores <- df_mouse_cluster_scores %>% 
  left_join(df_mouse_cluster_labels, by = c("cluster_id", "nk" = "nk_old", "k" = "k_old")) %>% 
  select(-cluster_id, -nk, -k) %>% 
 rename(cluster_id = cluster_id_new, nk = nk_new, k = k_new)

df_mouse_cluster_scores
```


```{r}
df_mouse_cluster_eagle <- df_mouse_cluster_scores %>% 
  select(ID = file, cluster_id, nk, k, eagle, eagle_binary)

df_mouse_eagle_sankey <- df_mouse_cluster_eagle %>% 
  group_by(cluster_id, nk, k) %>% 
  mutate(eagle_binary_mean = mean(eagle_binary)) %>%
  ungroup() 

# mouse_eagle_palette <- c("white", carto_pal(n = 7, name = "Teal"))
mouse_eagle_palette <- c("white", RColorBrewer::brewer.pal(n = 9, name = "Reds"))
mouse_eagle_palette_bin <- c(mouse_eagle_palette[1],
                             mouse_eagle_palette[length(mouse_eagle_palette)])

alluvium_col <- "grey50"
alluvium_lw <- 0.1
alluvium_alpha <- 1.0


plt_mouse_eagle_sankey <- ggplot(df_mouse_eagle_sankey, 
       aes(x = factor(nk), stratum = factor(k), alluvium = ID)) + 
  geom_flow(mapping = aes(fill = factor(eagle_binary)),
            col = alluvium_col, alpha = alluvium_alpha, linewidth = alluvium_lw,
            stat = "alluvium", aes.flow = "forward") +
  scale_fill_manual(values = mouse_eagle_palette_bin, guide = "none") + 
  new_scale_fill() + 
  geom_stratum(mapping = aes(fill = eagle_binary_mean)) +
  scale_fill_gradientn(colours = mouse_eagle_palette, limits = c(0, 1)) + 
  scale_x_discrete(expand = expansion(add = 0.4)) + 
  scale_y_continuous(breaks = c(seq(0, 130, by = 20), nrow(df_mouse_clusters)),
                     expand = expansion(add = c(3, 3))) + 
  labs(x = "MICe clusters (K)",
       y = "Number of mouse models",
       fill = "EAGLE proportion") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title = element_text(size = 6),
        axis.text = element_text(size = 6),
        legend.title = element_text(size = 6),
        legend.text = element_text(size = 6))

# plt_mouse_eagle_sankey

# BREAK

df_mouse_cluster_sfari <- df_mouse_cluster_scores %>% 
  select(ID = file, cluster_id, nk, k, sfari_score, sfari_syndromic)

df_mouse_sfari_sankey <- df_mouse_cluster_sfari %>% 
  group_by(cluster_id, nk, k) %>% 
  mutate(sfari_syndromic_count = sum(sfari_syndromic),
         sfari_score_mean = mean(sfari_score)) %>%
  ungroup()


# mouse_sfari_palette <- rev(c("white", RColorBrewer::brewer.pal(n = 9, name = "Blues")))
mouse_sfari_palette <- rev(c("white", carto_pal(n = 7, name = "Teal")))
mouse_sfari_palette_bin <- c(mouse_eagle_palette[1],
                             mouse_eagle_palette[length(mouse_eagle_palette)])

plt_mouse_sfari_sankey <- ggplot(df_mouse_sfari_sankey, 
       aes(x = factor(nk), stratum = factor(k), alluvium = ID)) + 
  geom_flow(mapping = aes(fill = sfari_score),
            col = alluvium_col, alpha = alluvium_alpha, linewidth = alluvium_lw,
            stat = "alluvium", aes.flow = "forward") +
  scale_fill_gradientn(colours = mouse_sfari_palette, limits = c(1, 4), guide = "none") +
  new_scale_fill() + 
  geom_stratum(mapping = aes(fill = sfari_score_mean)) +
  scale_fill_gradientn(colours = mouse_sfari_palette, limits = c(1, 4), 
                       guide = guide_colorbar(reverse = TRUE)) +
  scale_x_discrete(expand = expansion(add = 0.4)) + 
  scale_y_continuous(breaks = c(seq(0, 130, by = 20), nrow(df_mouse_clusters)),
                     expand = expansion(add = c(3, 3))) + 
  labs(x = "MICe clusters (K)",
       y = "Number of mouse models",
       fill = "SFARI score") +
  theme_bw() +
theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.y = element_text(size = 6),
        axis.text.y = element_text(size = 6),
      axis.title.x = element_blank(),
        axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
        legend.title = element_text(size = 6),
        legend.text = element_text(size = 6))

# plt_mouse_sfari_sankey


plt_mouse_sankey <- plt_mouse_sfari_sankey / plt_mouse_eagle_sankey + plot_layout(guides = "collect") &
  theme(plot.margin = margin(t = 6, l = 1))
```




# Figure

```{r}
panel_label_pond <- gTree(children = gList(textGrob("POND+", x = 0.53, gp = gpar(fontsize = 8)),
                                           segmentsGrob(x0 = 0.10, x1 = 1, y0 = 0.07, y1 = 0.07)))
panel_label_hbn <- gTree(children = gList(textGrob("HBN", x = 0.53, gp = gpar(fontsize = 8)),
                                          segmentsGrob(x0 = 0.08, x1 = 1, y0 = 0.07, y1 = 0.07)))


# Science two-col figure dimensions
fig_width <- 7.25*72

legend_width <- 35
padding_width <- 10
plotting_area <- fig_width - legend_width - padding_width
panel_width <- plotting_area/2
panel_dx_height <- 160
padding_height <- 10
panel_sankey_height <- 350
panel_label_height <- 15

fig_widths <- c(panel_width, padding_width, panel_width, legend_width)
fig_heights <- c(panel_label_height, panel_dx_height, panel_sankey_height)


fig_layout <- rbind(c(01, 02, 03, 04),
                    c(05, 06, 07, 08),
                    c(09, 09, 09, 09))

fig_grob <- arrangeGrob(panel_label_pond,
                        zeroGrob(),
                        panel_label_hbn,
                        zeroGrob(),
                        pond_dx_grob, 
                        zeroGrob(), #padding
                        hbn_dx_grob, # HBN dx
                        diagnoses_legend_grob, # dx legend
                        patchworkGrob(plt_mouse_sankey),
                        layout_matrix = fig_layout,
                        widths = unit(fig_widths, "bigpts"),
                        heights = unit(fig_heights, "bigpts"))


fig_height_pt <- sum(fig_heights)
fig_width_pt <- sum(fig_widths)

fig_height_in <- fig_height_pt/72
fig_width_in <- fig_width_pt/72

outfile <- paste0(outfile_prefix, ".pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(fig_width_in, "in"),
    height = unit(fig_height_in, "in"))
grid.draw(fig_grob)
grid.text(label = c("A", "B"), 
          x = unit(c(7, 7), "bigpts"),
          y = unit(c(fig_height_pt - 9, fig_height_pt - panel_label_height - panel_dx_height), "bigpts"),
          gp = gpar(fontsize = 10, fontface = "bold"))
invisible(dev.off())
```

```{r}
outfile <- paste0(outfile_prefix, ".png")
outfile <- file.path(output_dir, outfile)
png(file = outfile,
    width = fig_width_in,
    height = fig_height_in,
    units = "in",
    res = 600)

grid.draw(fig_grob)
grid.text(label = c("A", "B"), 
          x = unit(c(7, 7), "bigpts"),
          y = unit(c(fig_height_pt - 9, fig_height_pt - panel_label_height - panel_dx_height), "bigpts"),
          gp = gpar(fontsize = 10, fontface = "bold"))

invisible(dev.off())
```
