---
title: "Untitled"
format: html
editor: visual
---

# Initialization

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(ggbeeswarm))
suppressPackageStartupMessages(library(patchwork))
# suppressPackageStartupMessages(library(viridis))
suppressPackageStartupMessages(library(rcartocolor))
```

```{r env}
PROJECTPATH <- Sys.getenv("PROJECTPATH")
SRCPATH <- Sys.getenv("SRCPATH")

source(file.path(SRCPATH, "utils.R"))
source(file.path(SRCPATH, "processing.R"))
source(file.path(SRCPATH, "analysis.R"))
source(file.path(SRCPATH, "enrichment.R"))
```

```{r functions}
consolidate_visits <- function(df, cols) {
  
  subject_ids <- df %>% 
    pull(subject_id) %>% 
    unique()
  
  df_init <- df %>% 
    select(subject_id, visit_instance, all_of(cols)) %>% 
    mutate(n_missing = rowSums(!is.na(across(all_of(cols)))))
  
  df_complete <- df_init %>% 
    filter(n_missing > 0) %>% 
    group_by(subject_id) %>% 
    filter(visit_instance == max(visit_instance)) %>% 
    ungroup() %>% 
    select(subject_id, all_of(cols))
  
  # Participants with completed ABAS
  ids_complete <- df_complete %>% 
    pull(subject_id) %>% 
    unique()
  
  # Participants with no ABAS scores
  ids_missing <- setdiff(subject_ids, ids_complete)
  
  # Create a data frame of NAs for particpants with no scores
  df_missing <- matrix(nrow = length(ids_missing), ncol = length(cols))
  rownames(df_missing) <- ids_missing
  colnames(df_missing) <- cols
  df_missing <- as_tibble(df_missing, rownames = "subject_id")
  
  df_out <- bind_rows(df_complete, df_missing)
  
  return(df_out)
  
}


bootstrap_sample_estimate <- function(x, groups = NULL, estimate = "mean", 
                                      B = 1000, set_seed = TRUE) {
  
  if (estimate == "mean") {
    estimator <- mean
  } else if (estimate == "median") {
    estimator <- median
  } else if (estimate == "sd") {
    estimator <- sd
  } else {
    stop()
  }
  
  n_groups <- ifelse(is.null(groups), 1, length(unique(groups)))
  if (n_groups > 1) {
    if (!is.factor(groups)) {
      stop("groups must be factor")
    }
  }
  groups_lvls <- levels(groups)
  
  bootstrap_samples <- matrix(data = 0, nrow = B, ncol = n_groups)
  colnames(bootstrap_samples) <- groups_lvls
  for (i in 1:nrow(bootstrap_samples)) {
    if (n_groups == 1) {
      if (set_seed) {set.seed(i)}
      bootstrap_samples[[i]] <- estimator(sample(x = x, size = length(x), 
                                                 replace = TRUE))
    } else {
      x_split <- split(x = x, f = groups)
      n_split <- lapply(x_split, length)
      if (set_seed) {set.seed(i)}
      x_split_sample <- mapply(FUN = sample, x = x_split, size = n_split, 
                               MoreArgs = list(replace = TRUE))
      bootstrap_samples[i,] <- sapply(X = x_split_sample, FUN = estimator)
    }
  }
  
  return(bootstrap_samples)
  
}

bootstrap_sample_estimate_ci <- function(x, groups = NULL, estimate = "mean", 
                                         interval = c(0.025, 0.975), B = 1000, 
                                         set_seed = TRUE) {
  bootstrap_samples <- bootstrap_sample_estimate(x = x, groups = groups, 
                                                 estimate = estimate,
                                                 B = B, set_seed = set_seed)
  bootstrap_ci <- apply(bootstrap_samples, MARGIN = 2, quantile, interval)
  bootstrap_ci <- t(bootstrap_ci)
  colnames(bootstrap_ci) <- c("lower", "upper")
  return(bootstrap_ci)
}

group_summary <- function(x, groups, B = 1000) {
  
  means <- split(x = x, f = groups) %>% 
    sapply(mean) %>% 
    matrix(ncol = 1, nrow = length(levels(groups)))
  colnames(means) <- "mu"
  
  ci <- bootstrap_sample_estimate_ci(x = x, groups = groups, B = B)
  
  out <- cbind(means, ci)
  rownames(out) <- levels(groups)
  
  return(out)
  
}
```

```{r outputs}
outfile_prefix <- "figure4"
output_dir <- file.path("outputs", outfile_prefix)
if (!(dir.exists(output_dir))) {dir.create(path = output_dir, recursive = TRUE)}
```

```{r pipeline-paths}
pipeline_dir <- file.path(PROJECTPATH, "data/cross_species/v3")

human_datasets <- c("POND", "HBN")

params_ids <- c("POND" = "375", "HBN" = "861")
# params_ids <- c("POND" = "852", "HBN" = "021")
metadata <- file.path(pipeline_dir, "metadata.csv")
human_params_ids <- character(2)
for (i in 1:length(params_ids)) {
  pipeline_params <- fetch_params_metadata(metadata = metadata,
                                           params = list(id = params_ids[i]))
  
  human_params_ids[i] <- pipeline_params[["input_1_id"]]
}
mouse_params_id <- pipeline_params[["input_2_id"]]

# Human pipeline directory
human_pipeline_dirs <- file.path(PROJECTPATH, "data/human/derivatives/v3/", human_params_ids)

# Human cluster and centroid directories
human_cluster_dirs <- file.path(human_pipeline_dirs, "clusters", "resolution_3.0")
human_centroid_dirs <- file.path(human_pipeline_dirs, "centroids", "resolution_0.8")

# Human registration directory
human_registration_dir <- file.path(PROJECTPATH, "data/human/registration/v3/")
```

```{r fig-params}
# Total figure dimensions in pts
fig_width <- 7.25*72
fig_height <- 792
```

# Transcriptomic cluster similarity

```{r}
params_ids <- c(params_ids, "POND_HBN" = "779")
list_similarity <- vector(mode = "list", length = length(params_ids))
names(list_similarity) <- names(params_ids)
for (i in 1:length(list_similarity)) {
  
  df_similarity <- compute_similarity_significance(
    similarity = import_similarity(param_id = params_ids[i], 
                                   pipeline_dir = pipeline_dir), 
    permutations = import_similarity_permutations(param_id = params_ids[i], 
                                                  pipeline_dir = pipeline_dir)
  )
  
  cluster_ids <- df_similarity %>% 
    select(img1_cluster_id, img1_nk, img1_k) %>% 
    arrange(img1_nk, img1_k) %>% 
    distinct() %>% 
    pull(img1_cluster_id)
  
  df_cluster_grid <- expand_grid(img1_cluster_id = cluster_ids,
                                 img2_cluster_id = cluster_ids) 
  
  
  df_matches <- df_similarity %>% 
    mutate(match = pval < 0.05) %>% 
    right_join(df_cluster_grid,
               by = c("img1_cluster_id", "img2_cluster_id")) %>% 
    mutate(match = ifelse(is.na(match), FALSE, match))
  
  list_similarity[[i]] <- df_matches
  
}  

```

# Import cluster information

```{r}
list_clusters <- vector(mode = "list", length = length(human_datasets))
names(list_clusters) <- human_datasets
for (i in 1:length(human_datasets)) {
  clusters_file <- file.path(human_cluster_dirs[i], "clusters.csv")
  list_clusters[[i]] <- read_csv(clusters_file, show_col_types = FALSE)
}

sankey_palette_files <- c("POND_cluster_labels_colours.xlsx",
                          "HBN_cluster_labels_colours.xlsx")


```

```{r}
df_pond_cluster_labels <- readxl::read_excel(file.path("resources", sankey_palette_files[1])) %>% 
  separate(col = "cluster_id", into = c("nk_old", "k_old"), remove = FALSE) %>% 
  separate(col = "cluster_id_new", into = c("nk_new", "k_new"), remove = FALSE) %>%
  mutate(nk_old = as.numeric(nk_old),
         k_old = as.numeric(k_old),
         nk_new = as.numeric(nk_new),
         k_new = as.numeric(k_new))

df_hbn_cluster_labels <- readxl::read_excel(file.path("resources", sankey_palette_files[2])) %>% 
  separate(col = "cluster_id", into = c("nk_old", "k_old"), remove = FALSE) %>% 
  separate(col = "cluster_id_new", into = c("nk_new", "k_new"), remove = FALSE) %>%
  mutate(nk_old = as.numeric(nk_old),
         k_old = as.numeric(k_old),
         nk_new = as.numeric(nk_new),
         k_new = as.numeric(k_new))
```

```{r}
# Import demographics
demographics_file <- file.path(human_registration_dir, "subject_info",
                               "demographics.csv")
df_demographics <- read_csv(demographics_file, show_col_types = FALSE)

for (i in 1:length(list_clusters)) {
  
  # Subset demographics variables
  df_demographics_subset <- df_demographics %>% 
    filter(Dataset == human_datasets[i]) %>% 
    select(file, subject_id = Subject_ID, 
           age = Age, sex = Sex, dx = DX)
  
  # Join demographics information
  list_clusters[[i]] <- list_clusters[[i]] %>% 
    inner_join(df_demographics_subset, by = c("ID" = "file"))
  
}
```

# Process clinical data

## Process POND data

```{r import-pond-db}
# Import full POND database
pond_db_file <- "POND_database_export_20251210.csv"
pond_db_file <- file.path(human_registration_dir, "subject_info/POND", pond_db_file)
df_pond_db <- read_csv(pond_db_file, show_col_types = FALSE)
```

```{r clean-pond-db}
# List of database data columns
list_data_cols <- list(
  CBCL = c("cb68ipts", "cb68epts", "cbipts", "cbepts"),
  ABAS = c("ab05gccs", "ab21gccs", "ab89gccs"),
  BOT2 = c("bot2_bltc_ss", "bot2_bal_ss", "bot2_bdyc_stds"),
  KINDL = c("kkid_tot", "kkdo_tot", "kkdy_tot"),
  NEPSY = c("nepsyii_a516_ar_ss", "nepsyii_a516_mf_ss", "nepsyii_a516_mfd_ss", 
            "nepsyii_a516_mf_mfd_ccs", "nepsyii_a516_tm_ss",
            "nepsyii_a716_as_tcssc", "nepsyii_a716_as_css"),
  OWL = c("owllcss", "owloess", "owlocss"),
  OWL2 = c("owl2lcss", "owl2oess", "owl2olcss"),
  RBS = "rbsallt",
  SCQ = "scqtot",
  SSP = c("ssp_tactile_rs", "ssp_taste_smell_rs", "ssp_movement_rs", "ssp_underresp_seeks_rs",
          "ssp_aud_filter_rs", "ssp_low_enrgy_weak_rs", "ssp_vis_aud_rs", "ssp_total_rs"),
  SpatialNBack = c("s0b_tgt_accuracy", "s0b_nontgt_accuracy", "s1b_tgt_accuracy", "s1b_nontgt_accuracy",
                   "s2b_tgt_accuracy", "s2b_nontgt_accuracy"),
  StopTask = c("mt_st_pcrt", "mt_st_mcrtt", "mt_st_crtsdt", "mt_st_psit", "mt_st_ssrtt",
               "mt_st_itssrt", "mt_st_psrrt"),
  SWAN = c("adhd_i_sub", "adhd_hi_sub"),
  TOCS = "tpocs_tot",
  IQ = c("wasi_ii_fsiq_4", "wasi_fsiq_4", "wisc_v_fsiq", "wisc_iv_fsiq",
         "sbfulliq", "wppsi47_full", "wppsi_iv47_fsiq_cs", "wasi_ii_fsiq_2",
         "wasi_fsiq_2")
)

# Reduce data columns into a vector
pond_db_data_cols <- reduce(list_data_cols, c)

# Database columns to include
pond_db_cols <- c("subject_id", "sub_id", "redcap_event_name", "redcap_repeat_instance",
                  "site", "dob", "primary_diagnosis", "research_confirm_diag", 
                  pond_db_data_cols)

# Subset for desired columns
df_pond_db_subset <- df_pond_db[,pond_db_cols]

# Remove deprecated and cross-visit arms
events_exclude <- c("deprecated_arm_1", "cross_visit_arm_1")
df_pond_db_subset <- df_pond_db_subset %>% 
  filter(!(redcap_event_name %in% events_exclude)) %>% 
  filter(str_detect(subject_id, "deprecated", negate = TRUE))

# Dictionary for site codes
df_site_codes <- tibble(site_acronym = c("HBK", "HSC", "LHR", "MCU", "QNS"),
                        site_code = c("105", "088", "113", "114", "394"))

# Redefine site codes based on subject site acronym
df_pond_db_subset <- df_pond_db_subset %>% 
  mutate(site_acronym = subject_id %>% 
           str_trunc(9, ellipsis = "") %>% 
           str_trunc(3, side = "left", ellipsis = "")) %>% 
  left_join(df_site_codes, by = "site_acronym") 

# Clean up IDs
df_pond_db_subset <- df_pond_db_subset %>% 
  mutate(subject_id_test = str_trunc(subject_id, 4, side = "left", ellipsis = "")) %>% 
  mutate(pond_id = paste0(site_code, subject_id_test)) %>% 
  select(-subject_id_test, -sub_id, -site) %>% 
  rename(site = site_code,
         redcap_id = subject_id,
         subject_id = pond_id)  

# Clean up visits information
df_pond_db_subset <- df_pond_db_subset %>% 
  mutate(redcap_repeat_instance = ifelse(is.na(redcap_repeat_instance), 0, redcap_repeat_instance)) %>% 
  mutate(visit_type = ifelse(redcap_event_name == "baseline_arm_1", "baseline", "longitudinal")) %>% 
  rename(visit_instance = redcap_repeat_instance) %>% 
  select(-redcap_event_name)

# Correct ABAS values 
df_pond_db_subset <- df_pond_db_subset %>% 
  mutate(ab21gccs = ifelse(ab21gccs == "<40", NA, ab21gccs),
         ab21gccs = as.numeric(ab21gccs))  

# Consolidate missing values
df_pond_db_subset <- df_pond_db_subset %>% 
  mutate(across(all_of(pond_db_data_cols), ~ ifelse(.x %in% c(-9999, 999), NA, .x)))
```

```{r consolidate-clinical-scores}
# Initialize data frame for POND clinical scores
df_clinical_scores_pond <- df_pond_db_subset %>% 
  select(redcap_id, subject_id) %>% 
  distinct()


# Consolidate CBCL scores -----------------------------------------------------

# If cb68 scores present, use those. If not, use cb scores
df_cbcl_init <- df_pond_db_subset %>% 
  select(subject_id, visit_instance, starts_with("cb")) %>% 
  mutate(cbcl_ep_ts = ifelse(!is.na(cb68epts), cb68epts, cbepts),
         cbcl_ip_ts = ifelse(!is.na(cb68ipts), cb68ipts, cbipts)) %>% 
  select(subject_id, visit_instance, cbcl_ep_ts, cbcl_ip_ts)

df_cbcl <- consolidate_visits(df = df_cbcl_init, cols = c("cbcl_ep_ts", "cbcl_ip_ts"))

df_clinical_scores_pond <- df_clinical_scores_pond %>% 
  left_join(df_cbcl, by = "subject_id")


# Consolidate ABAS scores -----------------------------------------------------
# Unsure of the order to use scales here, when they have multiple in the same visit

df_abas_init <- df_pond_db_subset %>%
  select(subject_id, visit_instance, starts_with("ab")) %>% 
  mutate(abas_gccs = ifelse(!is.na(ab89gccs), ab89gccs,
                            ifelse(!is.na(ab21gccs), ab21gccs, ab05gccs))) %>% 
  select(subject_id, visit_instance, abas_gccs)

df_abas <- consolidate_visits(df = df_abas_init, cols = "abas_gccs")

df_clinical_scores_pond <- df_clinical_scores_pond %>% 
  left_join(df_abas, by = "subject_id")


# Consolidate KINDL scores ----------------------------------------------------
# Not sure if I can compare scores here?
# Some scores are 0. What is the range? Scores above 100.

df_kindl_init <- df_pond_db_subset %>%
  select(subject_id, visit_instance, kkid_tot, kkdo_tot, kkdy_tot) %>% 
  mutate(kindl_tot = ifelse(!is.na(kkdo_tot), kkdo_tot, 
                            ifelse(!is.na(kkid_tot), kkid_tot, kkdy_tot))) %>% 
  select(subject_id, visit_instance, kindl_tot)

df_kindl <- consolidate_visits(df = df_kindl_init, cols = "kindl_tot")

df_clinical_scores_pond <- df_clinical_scores_pond %>% 
  left_join(df_kindl, by = "subject_id")


# Consolidate OWL scores ------------------------------------------------------

df_owl_init <- df_pond_db_subset %>%
  select(subject_id, visit_instance, starts_with("owl")) %>% 
  mutate(owl_lc_ss = ifelse(!is.na(owl2lcss), owl2lcss, owllcss),
         owl_oe_ss = ifelse(!is.na(owl2oess), owl2oess, owloess),
         owl_olc_ss = ifelse(!is.na(owl2olcss), owl2olcss, owllcss)) %>% 
  select(subject_id, visit_instance, starts_with("owl"))  

df_owl <- consolidate_visits(df = df_owl_init, cols = c("owl_lc_ss", "owl_oe_ss", "owl_olc_ss"))

df_clinical_scores_pond <- df_clinical_scores_pond %>% 
  left_join(df_owl, by = "subject_id")


# Consolidate IQ scores ------------------------------------------------------

df_fsiq_init <- df_pond_db_subset %>% 
  select(subject_id, visit_instance, all_of(list_data_cols[["IQ"]])) %>% 
  mutate(fsiq = ifelse(!is.na(wasi_ii_fsiq_4), wasi_ii_fsiq_4,
                       ifelse(!is.na(wasi_fsiq_4), wasi_fsiq_4,
                              ifelse(!is.na(wisc_v_fsiq), wisc_v_fsiq,
                                     ifelse(!is.na(wisc_iv_fsiq), wisc_iv_fsiq,
                                            ifelse(!is.na(sbfulliq), sbfulliq,
                                                   ifelse(!is.na(wppsi47_full), wppsi47_full,
                                                          ifelse(!is.na(wppsi_iv47_fsiq_cs), wppsi_iv47_fsiq_cs,
                                                                 ifelse(!is.na(wasi_ii_fsiq_2), wasi_ii_fsiq_2,
                                                                        ifelse(!is.na(wasi_fsiq_2), wasi_fsiq_2, NA)))))))))) %>% 
  select(subject_id, visit_instance, fsiq)


df_fsiq <- consolidate_visits(df = df_fsiq_init, cols = "fsiq")

df_clinical_scores_pond <- df_clinical_scores_pond %>% 
  left_join(df_fsiq, by = "subject_id")


# Consolidate remaining variables ---------------------------------------------

idx_vars <- !(names(list_data_cols) %in% c("CBCL", "ABAS", "KINDL", "OWL", "OWL2", "IQ"))
list_data_cols_sub <- list_data_cols[idx_vars]
for (cols in list_data_cols[idx_vars]) {
  df_clinical_scores_pond <- df_clinical_scores_pond %>% 
    left_join(consolidate_visits(df = df_pond_db_subset, cols = cols),
              by = "subject_id")
}

# Update subject IDs to match clusters and demographics
df_clinical_scores_pond <- df_clinical_scores_pond %>% 
  mutate(subject_id = paste0("sub-", subject_id))
```

```{r}
# Join clinical scores and cluster information
df_clusters_clinical_POND <- list_clusters$POND %>% 
  left_join(df_clinical_scores_pond, by = "subject_id") %>% 
  select(-redcap_id)
```

## Process HBN data

```{r}
list_HBN_assessments <- list(
  ACE = list(code = "ACE", skip = TRUE, vars = c("ACE_Score")),
  ARI_P = list(code = "ARI_P",
               skip = TRUE,
               vars = c("ARI_P_Total_Score")),
  ARI_S = list(code = "ARI_S",
               skip = TRUE,
               vars = c("ARI_S_Total_Score")),
  ASSQ = list(code = "ASSQ",
              skip = TRUE,
              vars = c("ASSQ_Total")),
  CDI_P = list(code = "CDI2_P",
               skip = TRUE,
               vars = c("CDI2P_Total_T")),
  CDI_S = list(code = "CDI2_SR",
               skip = TRUE,
               vars = c("CDI2_Total_T")),
  CGAS = list(code = "CGAS",
              skip = TRUE,
              vars = c("CGAS_Score")),
  CIS_P = list(code = "CIS_P",
               skip = TRUE,
               vars = c("CIS_P_Score")),
  CIS_SR = list(code = "CIS_SR",
                skip = TRUE,
                vars = c("CIS_SR_Total")),
  EVT = list(code = "EVT",
             skip = TRUE,
             vars = c("EVT2_StandardScore")),
  GFTA = list(code = "GFTA",
              skip = TRUE,
              vars = c("GFTA_SIW_Stnd", "GFTA_SIS_Stnd")),
  ICU_P = list(code =  "ICU_P",
               skip = TRUE,
               vars = c("ICU_P_Callous", "ICU_P_Uncaring", 
                        "ICU_P_Unemotional", "ICU_P_Total")),
  ICU_SR = list(code = "ICU_SR",
                skip = TRUE,
                vars = c("ICU_SR_Callous", "ICU_SR_Uncaring",
                         "ICU_SR_Unemotional", "ICU_SR_Total")),
  KBIT = list(code = "KBIT",
              skip = TRUE,
              vars = c("KBIT_IQ_Comp")),
  MFQ_P = list(code = "MFQ_P",
               skip = TRUE,
               vars = c("MFQ_P_Total")),
  MFQ_SR = list(code = "MFQ_SR",
                skip = TRUE,
                vars = c("MFQ_SR_Total #1")),
  NIH_Scores = list(code = "NIH_Scores",
                    skip = TRUE,
                    vars = c("NIH7_Card", "NIH7_Cog", "NIH7_Flanker", 
                             "NIH7_List", "NIH7_Pattern", "NIH7_Picture")),
  PPVT = list(code = "PPVT",
              skip = TRUE,
              vars = c("PPVT4_StandardScore")),
  Quotient = list(code = "Quotient",
                  skip = TRUE,
                  vars = c("quotient_global_scaled")),
  RANRAS = list(code = "RANRAS",
                skip = TRUE,
                vars = c("RR_Let_Stnd", "RR_Obj_Stnd", "RR_Two_Stnd", "RR_Col_Stnd",
                         "RR_Num_Stnd", "RR_Three_Stnd")),
  RBS = list(code = "RBS",
             skip = TRUE,
             vars = c("Score_Total")),
  SCARED_P = list(code = "SCARED_P",
                  skip = TRUE,
                  vars = c("SCARED_P_Total")),
  SCARED_SR = list(code = "SCARED_SR",
                   skip = TRUE,
                   vars = c("SCARED_SR_Total")),
  SCQ = list(code = "SCQ",
             skip = TRUE,
             vars = c("SCQ_Total")),
  SDQ = list(code = "SDQ",
             skip = TRUE,
             vars = c("SDQ_Difficulties_Total")),
  SDS = list(code = "SDS",
             skip = TRUE,
             vars = c("SDS_Total_T")),
  STAI = list(code = "STAI",
              skip = TRUE,
              vars = c("STAI_SA", "STAI_TA")),
  SWAN = list(code = "SWAN",
              skip = TRUE,
              vars = c("ADHD_HI", "ADHD_I")),
  TOWRE = list(code = "TOWRE",
               skip = TRUE,
               vars = c("TOWRE_PDE_Scaled", "TOWRE_SWE_Scaled", "TOWRE_Total_Scaled")),
  Vineland = list(code = "Vineland",
                  skip = TRUE,
                  vars = c("VL_Comm_Scale", "VL_DLS_Scale", "VL_Social_Scale")),
  WHODAS_P = list(code = "WHODAS_P",
                  skip = TRUE,
                  vars = c("WHODAS_P_Score")),
  WHODAS_SR = list(code = "WHODAS_SR",
                   skip = TRUE,
                   vars = c("WHODAS_SR_Score")),
  YSR = list(code = "YSR",
             skip = TRUE,
             vars = c("YSR_Total_T"))
)
```

```{r}
path_HBN_assessments <- file.path(human_registration_dir, "subject_info", 
                                  "HBN", "assessment_data")

df_clusters_clinical_HBN <- list_clusters$HBN

for (x in list_HBN_assessments) {
  
  file <- paste0("9994_", x$code, "_20220728.csv")
  file <- file.path(path_HBN_assessments, file)
  df <- read_csv(file, show_col_types = FALSE)
  if (x$skip) {df <- df[2:nrow(df),]}
  
  df <- df[,c("EID", x$vars)]
  colnames(df) <- c("subject_id", x$vars)
  df <- df %>% 
    mutate(across(x$vars, as.numeric)) %>% 
    distinct()
  
  n_multiple <- df %>% 
    group_by(subject_id) %>% 
    count() %>% 
    filter(n > 1) %>% 
    nrow()
  
  if (n_multiple > 0) {
    df <- df %>% 
      group_by(subject_id) %>% 
      sample_n(size = 1) %>% 
      ungroup() 
  }
  
  df_clusters_clinical_HBN <- df_clusters_clinical_HBN %>% 
    left_join(df, by = "subject_id")
}


## CBCL

file <- file.path(path_HBN_assessments, "9994_CBCL_20220728.csv")
df <- read_csv(file, show_col_types = FALSE)

df_cbcl <- df %>% 
  select(subject_id = EID, CBCL_IP_T = CBCL_Int_T, CBCL_EP_T = CBCL_Ext_T)

file <- file.path(path_HBN_assessments, "9994_CBCL_Pre_20220728.csv")
df <- read_csv(file, show_col_types = FALSE)

df <- df[2:nrow(df),]

df_cbcl_pre <- df %>% 
  select(subject_id = EID, CBCL_IP_T = CBCL_Pre_Int_T, CBCL_EP_T = CBCL_Pre_Ext_T) %>% 
  mutate(CBCL_IP_T = as.numeric(CBCL_IP_T),
         CBCL_EP_T = as.numeric(CBCL_EP_T))

df_cbcl <- bind_rows(df_cbcl, df_cbcl_pre)

df_clusters_clinical_HBN <- df_clusters_clinical_HBN %>% 
  left_join(df_cbcl, by = "subject_id")


## IQ

file <- file.path(path_HBN_assessments, "9994_WISC_20220728.csv")
df_wisc <- read_csv(file, show_col_types = FALSE)

df_wisc <- df_wisc[2:nrow(df_wisc),]

df_wisc <- df_wisc %>% 
  select(subject_id = EID, WISC_FSIQ) %>% 
  mutate(WISC_FSIQ = as.numeric(WISC_FSIQ)) %>% 
  group_by(subject_id) %>% 
  mutate(WISC_FSIQ_MEAN = mean(WISC_FSIQ)) %>% 
  ungroup() %>% 
  select(subject_id, WISC_FSIQ = WISC_FSIQ_MEAN) %>% 
  distinct()

file <- file.path(path_HBN_assessments, "9994_WASI_20220728.csv")
df_wasi <- read_csv(file, show_col_types = FALSE)

df_wasi <- df_wasi[2:nrow(df_wasi),]

df_wasi <- df_wasi %>% 
  select(subject_id = EID, WASI_FSIQ) %>% 
  mutate(WASI_FSIQ = as.numeric(WASI_FSIQ))

df_fsiq <- full_join(df_wisc, df_wasi, by = "subject_id")

df_fsiq <- df_fsiq %>% 
  mutate(FSIQ = ifelse(!is.na(WASI_FSIQ), WASI_FSIQ, WISC_FSIQ)) %>% 
  select(subject_id, FSIQ)

df_clusters_clinical_HBN <- df_clusters_clinical_HBN %>% 
  left_join(df_fsiq, by = "subject_id")



## CELF

file <- file.path(path_HBN_assessments, "9994_CELF_Full_5to8_20220728.csv")
df_celf_5to8 <- read_csv(file, show_col_types = FALSE)

df_celf_5to8 <- df_celf_5to8[2:nrow(df_celf_5to8),]

df_celf_5to8 <- df_celf_5to8 %>% 
  select(subject_id = EID, CELF_CLS_Stnd, CELF_RLI_Stnd, CELF_ELI_Stnd, CELF_LCI_Stnd) %>% 
  mutate(CELF_CLS_Stnd = as.numeric(CELF_CLS_Stnd),
         CELF_RLI_Stnd = as.numeric(CELF_RLI_Stnd),
         CELF_ELI_Stnd = as.numeric(CELF_ELI_Stnd),
         CELF_LCI_Stnd = as.numeric(CELF_LCI_Stnd))


file <- file.path(path_HBN_assessments, "9994_CELF_Full_9to21_20220728.csv")
df_celf_9to21 <- read_csv(file, show_col_types = FALSE)

df_celf_9to21 <- df_celf_9to21[2:nrow(df_celf_9to21),]

df_celf_9to21 <- df_celf_9to21 %>% 
  select(subject_id = EID, CELF_CLS_Stnd, CELF_RLI_Stnd, CELF_ELI_Stnd, CELF_LCI_Stnd) %>% 
  mutate(CELF_CLS_Stnd = as.numeric(CELF_CLS_Stnd),
         CELF_RLI_Stnd = as.numeric(CELF_RLI_Stnd),
         CELF_ELI_Stnd = as.numeric(CELF_ELI_Stnd),
         CELF_LCI_Stnd = as.numeric(CELF_LCI_Stnd))


df_celf <- bind_rows(df_celf_5to8, df_celf_9to21)

df_clusters_clinical_HBN <- df_clusters_clinical_HBN %>% 
  left_join(df_celf, by = "subject_id")

df_clusters_clinical_HBN <- df_clusters_clinical_HBN %>% 
  select(-contains("_SR_"), -ARI_S_Total_Score, -CDI2_Total_T)

```

```{r}
list_clusters_clinical <- list(POND = df_clusters_clinical_POND,
                               HBN = df_clusters_clinical_HBN)
```

# Clinical scores analysis

## Complete case analysis

```{r}
list_complete_cases <- vector(mode = "list", length = length(list_clusters_clinical))
names(list_complete_cases) <- names(list_clusters_clinical)
for (l in 1:length(list_clusters_clinical)) {
  
  df_completion <- list_clusters_clinical[[l]] %>% 
    select(-contains("nk"), -ID, -age, -sex, -dx) %>% 
    pivot_longer(cols = -subject_id, names_to = "variable", values_to = "score") %>% 
    mutate(complete = !is.na(score)) %>% 
    group_by(variable) %>% 
    summarise(n_completed = sum(complete)) %>% 
    ungroup() %>% 
    arrange(desc(n_completed))
  
  df_complete_cases <- df_completion %>% 
    mutate(n_complete = 0, n_included = 0)
  
  for (i in 1:nrow(df_complete_cases)) {
    
    variables <- df_completion %>% 
      slice_max(order_by = n_completed, n = i) %>% 
      pull(variable)
    
    df_clinical_subset <- list_clusters_clinical[[l]][, variables]
    
    df_complete_cases[[i, "n_complete"]]  <- sum(complete.cases(df_clinical_subset))
    df_complete_cases[[i, "n_included"]] <- i
    
  }
  
  list_complete_cases[[l]] <- df_complete_cases
  
  plt_complete_cases <- ggplot(df_complete_cases, aes(x = n_included, y = n_complete)) + 
    geom_line() + 
    geom_point() +
    scale_x_continuous(breaks = seq(0, 100, by = 4)) +
    scale_y_continuous(breaks = seq (0, 1000, by = 50)) + 
    labs(x = "Number of variables included",
         y = "Number of complete cases") +
    theme_bw()
  
  outfile <- paste0("questionnaire_completion_", human_datasets[l], ".pdf")
  outfile <- file.path(output_dir, outfile)
  pdf(file = outfile,
      width = unit(10, "in"),
      height = unit(6, "in"))
  print(plt_complete_cases)
  dev.off()
  
}
```

## Pairwise LDA

```{r}
clinical_acronyms_POND <- c("scqtot" = "SCQ",
                            "rbsallt" = "RBS-R",
                            "tpocs_tot" = "TOCS",
                            "adhd_i_sub" = "SWAN I",
                            "adhd_hi_sub" = "SWAN HI",
                            "fsiq" = "FSIQ",
                            "abas_gccs" = "ABAS GAC",
                            "cbcl_ep_ts" = "CBCL EP",
                            "cbcl_ip_ts" = "CBCL IP",
                            "ssp_total_rs" = "SSP TOT",
                            "ssp_aud_filter_rs" = "SSP AF",
                            "ssp_low_enrgy_weak_rs" = "SSP LEW",
                            "ssp_movement_rs" = "SSP MS",
                            "ssp_tactile_rs" = "SSP TAC",
                            "ssp_taste_smell_rs" = "SSP TSS",
                            "ssp_underresp_seeks_rs" = "SSP URSS",
                            "ssp_vis_aud_rs" =  "SSP VAS",
                            "owl_lc_ss" = "OWLS LC",
                            "owl_oe_ss" = "OWLS OE",
                            "owl_olc_ss" = "OWLS OLC",
                            "nepsyii_a516_ar_ss" = "NEPSY AR",
                            "nepsyii_a516_mf_ss" = "NEPSY MF",
                            "nepsyii_a516_mfd_ss" = "NEPSY MFD",
                            "nepsyii_a516_mf_mfd_ccs" = "NEPSY MF vs. MFD",
                            "bot2_bal_ss" = "BOT 2 Bal.",
                            "bot2_bltc_ss" = "BOT 2 Bil. Coord.",
                            "bot2_bdyc_stds" = "BOT 2 Body Coord.")

clinical_acronyms_HBN <- c("ACE_Score" = "ACE",
                           "ARI_P_Total_Score" = "ARI PR",
                           "ARI_S_Total_Score" = "ARI SR",
                           "ASSQ_Total" = "ASSQ",
                           "CDI2P_Total_T" = "CDI2 PR",
                           "CDI2_Total_T" = "CDI2 SR",
                           "CGAS_Score" = "CGAS",
                           "CIS_P_Score" = "CIS PR",
                           "CIS_SR_Total" = "CIS SR",
                           "EVT2_StandardScore" = "EVT2",
                           "GFTA_SIW_Stnd" =  "GFTA SIW",
                           "GFTA_SIS_Stnd" = "GFTA SIS",
                           "ICU_P_Callous" = "ICU PR Call.",
                           "ICU_P_Uncaring" = "ICU PR Uncar.",
                           "ICU_P_Unemotional" = "ICU PR Unemot.",
                           "ICU_P_Total" = "ICU PR TOT",
                           "ICU_SR_Callous" = "ICU SR Call.",
                           "ICU_SR_Uncaring" = "ICU SR Uncar.",
                           "ICU_SR_Unemotional" = "ICU SR Unemot.",
                           "ICU_SR_Total" = "ICU SR TOT",
                           "KBIT_IQ_Comp" = "KBIT IQ",
                           "MFQ_P_Total" = "MFQ PR TOT",
                           "MFQ_SR_Total #1" = "MFQ SR TOT",
                           "NIH7_Card" = "NIH Card",
                           "NIH7_Cog" =  "NIH Cog.",
                           "NIH7_Flanker" =  "NIH Flank.",
                           "NIH7_List" = "NIH List",
                           "NIH7_Pattern" = "NIH Patt.",
                           "NIH7_Picture" = "NIH Pic.",
                           "PPVT4_StandardScore" = "PPVT4",
                           "quotient_global_scaled" = "Quotient",
                           "RR_Let_Stnd" = "RR Let.",
                           "RR_Obj_Stnd" =  "RR Obj.",
                           "RR_Two_Stnd" = "RR Two.",
                           "RR_Col_Stnd" = "RR Col.",
                           "RR_Num_Stnd" =  "RR Num.",
                           "RR_Three_Stnd" = "RR Three",
                           "Score_Total" = "RBS-R",
                           "SCARED_P_Total" = "SCARED PR",
                           "SCARED_SR_Total" = "SCARED SR",
                           "SCQ_Total" = "SCQ",
                           "SDQ_Difficulties_Total" = "SDQ",
                           "SDS_Total_T" = "SDS",
                           "STAI_SA" = "STAI SA", 
                           "STAI_TA" = "STAI TA",
                           "ADHD_HI" = "SWAN HI", 
                           "ADHD_I" = "SWAN I",
                           "TOWRE_PDE_Scaled" = "TOWRE PDE",
                           "TOWRE_SWE_Scaled" = "TOWRE SWE",
                           "TOWRE_Total_Scaled" = "TOWRE TOT",
                           "VL_Comm_Scale" = "VL Comm.",
                           "VL_DLS_Scale" = "VL DLS", 
                           "VL_Social_Scale" = "VL Soc.",
                           "WHODAS_P_Score" = "WHODAS PR",
                           "WHODAS_SR_Score" = "WHODAS SR",
                           "YSR_Total_T" = "YSR",
                           "CBCL_IP_T" = "CBCL IP", 
                           "CBCL_EP_T" = "CBCL EP",
                           "FSIQ" =  "FSIQ",
                           "CELF_CLS_Stnd" = "CELF CLS",
                           "CELF_RLI_Stnd" = "CELF RLI",
                           "CELF_ELI_Stnd" = "CELF ELI",
                           "CELF_LCI_Stnd" = "CELF LCI")

clinical_acronyms <- list(POND = clinical_acronyms_POND,
                          HBN = clinical_acronyms_HBN)

list_clinical_acronyms <- map(.x = clinical_acronyms, 
                              .f = function(x){enframe(x, name = "variable", value = "acronym")})
```

```{r}
df_common <- list_clinical_acronyms$POND %>% 
  rename(POND_variable = variable) %>% 
  inner_join(list_clinical_acronyms$HBN, by = "acronym") %>% 
  rename(HBN_variable = variable)
```

```{r}
# New cluster labels
list_cluster_pathways <- list(
  POND = list(synaptic = c("6-2", "7-2", "8-2", "9-2"),
              chromatin = c("6-6", "7-7", "8-8", "9-9"),
              mapkwnt = c("6-1", "7-1", "8-1", "9-1")),
  HBN = list(synaptic = c("6-2", "7-2", "8-2", "9-2"),
             chromatin = c("6-6", "7-7", "8-8", "9-9"),
             mapkwnt = c("6-1", "7-1", "8-1", "9-1"))
)


list_cluster_groups <- vector(mode = "list", length = length(list_cluster_pathways))
names(list_cluster_groups) <- human_datasets
for (i in 1:length(list_cluster_pathways)) {
  
  df_synaptic <- tibble(cluster_id = list_cluster_pathways[[i]]$synaptic) %>% 
    separate(col = cluster_id, into = c("nk", "k"), sep = "-", remove = FALSE) %>% 
    mutate(nk = as.numeric(nk),
           k = as.numeric(k),
           group = "synaptic")
  
  df_chromatin <- tibble(cluster_id = list_cluster_pathways[[i]]$chromatin) %>% 
    separate(col = cluster_id, into = c("nk", "k"), sep = "-", remove = FALSE) %>% 
    mutate(nk = as.numeric(nk),
           k = as.numeric(k),
           group = "chromatin")
  
  df_mapkwnt <- tibble(cluster_id = list_cluster_pathways[[i]]$mapkwnt) %>% 
    separate(col = cluster_id, into = c("nk", "k"), sep = "-", remove = FALSE) %>% 
    mutate(nk = as.numeric(nk),
           k = as.numeric(k),
           group = "mapkwnt")
  
  list_cluster_groups[[i]] <- bind_rows(df_synaptic, df_chromatin, df_mapkwnt)
  
}

list_cluster_groups$POND <- list_cluster_groups$POND %>% 
  select(cluster_id_new = cluster_id, group) %>% 
  left_join(df_pond_cluster_labels, by = "cluster_id_new") %>% 
  select(cluster_id, nk = nk_old, k = k_old, group)

list_cluster_groups$HBN <- list_cluster_groups$HBN %>% 
  select(cluster_id_new = cluster_id, group) %>% 
  left_join(df_hbn_cluster_labels, by = "cluster_id_new") %>% 
  select(cluster_id, nk = nk_old, k = k_old, group)
```

```{r}
n_variables <- c("POND" = 20, "HBN" = 27)

list_vars_flip <- list(
  POND = c("scqtot", "tpocs_tot", "rbsallt", "cbcl_ep_ts", "cbcl_ip_ts"),
  HBN = c("ARI_P_Total_Score", "ASSQ_Total", "CBCL_IP_T", "CBCL_EP_T", "CIS_P_Score",
          "ICU_P_Callous", "ICU_P_Total", "ICU_P_Uncaring", "ICU_P_Unemotional",
          "MFQ_P_Total", "SCARED_P_Total", "SCQ_Total", "SDQ_Difficulties_Total",
          "SDS_Total_T", "Score_Total", "WHODAS_P_Score")
)

comparisons <- c("chromatin_synaptic", "mapkwnt_synaptic", "chromatin_mapkwnt")
nk_range <- 6:9

df_lda_grid <- expand_grid(dataset = human_datasets,
                           nk = nk_range,
                           comparison = comparisons) %>% 
  mutate(idx = 1:nrow(.))

list_lda <- vector(mode = "list", length = nrow(df_lda_grid))

for (i in 1:length(list_lda)) {
  # for (i in 1:2) {
  
  dataset_i <- df_lda_grid[[i, "dataset"]]
  nk_i <- df_lda_grid[[i,"nk"]]
  comparison_i <- df_lda_grid[[i,"comparison"]]
  comparison_i_splt <- str_split(comparison_i, pattern = "_")[[1]]
  
  df_cluster_compare <- list_cluster_groups[[dataset_i]] %>% 
    filter(nk == nk_i) %>% 
    filter(group %in% comparison_i_splt)
  
  # Fetch variables with the desired completion level
  variables <- list_complete_cases[[dataset_i]] %>% 
    slice_max(order_by = n_complete, n = n_variables[dataset_i]) %>% 
    pull(variable)
  
  # Extract variable scores
  cols <- c("ID", paste0("nk", nk_i), variables)
  df_multivariate <- list_clusters_clinical[[dataset_i]][,cols]
  colnames(df_multivariate) <- c("ID", "k", variables)
  
  # Filter for complete cases
  df_multivariate <- df_multivariate[complete.cases(df_multivariate),]
  
  # Include information about pathway
  df_multivariate <- df_multivariate %>% 
    inner_join(df_cluster_compare %>% 
                 filter(nk == nk_i) %>% 
                 select(k, group), by = "k") %>% 
    mutate(group = factor(group)) %>% 
    select(-k)
  
  # Extract feature matrix and labels
  X <- as.matrix(df_multivariate[,variables])
  X <- scale(X)
  y <- df_multivariate$group
  
  # Fit LDA
  lda_fit <- MASS::lda(x = X, grouping = y, prior = c(0.5, 0.5))
  
  # Extract class probabilities
  lda_pred <- predict(lda_fit, X)
  lda_pred_y <- lda_pred[["class"]]
  lda_pred_prob <- lda_pred[["posterior"]][,2]
  
  # LDA scores
  df_lda_scores <- lda_pred[["x"]] %>% 
    as_tibble() %>% 
    mutate(y = y,
           y_pred = lda_pred_y,
           y_pred_prob = lda_pred_prob) %>% 
    mutate(dataset = dataset_i,
           comparison = comparison_i,
           nk = nk_i)
  
  # LDA loadings
  
  df_lda_loadings <- cor(x = X, y = df_lda_scores$LD1) %>% 
    as_tibble(rownames = "variable") %>% 
    rename(LD1 = V1) %>% 
    mutate(LD1 = ifelse(variable %in% list_vars_flip[[dataset_i]], -1*LD1, LD1))
  
  df_lda_loadings <- df_lda_loadings %>% 
    left_join(list_clinical_acronyms[[dataset_i]], by = "variable") 
  
  df_lda_loadings <- df_lda_loadings %>% 
    mutate(group = ifelse(LD1 >= 0, comparison_i_splt[2], comparison_i_splt[1]))
  
  df_lda_loadings <- df_lda_loadings %>% 
    mutate(dataset = dataset_i,
           comparison = comparison_i,
           nk = nk_i)
  
  df_lda_loadings_common <- df_lda_loadings %>% 
    semi_join(df_common, by = "acronym") %>% 
    mutate(dataset = dataset_i,
           comparison = comparison_i,
           nk = nk_i)
  
  
  # Run LDA ROC analysis
  lda_roc <- pROC::roc(response = y,
                       predictor = lda_pred_prob,
                       direction = "<", 
                       quiet = TRUE)
  
  df_lda_roc <- tibble(tpr = lda_roc$sensitivities,
                       fpr = 1-lda_roc$specificities,
                       thresholds = lda_roc$thresholds,
                       AUC = lda_roc$auc[1]) %>% 
    arrange(tpr) %>% 
    mutate(dataset = dataset_i,
           comparison = comparison_i,
           nk = nk_i)
  
  list_lda[[i]] <- list(data = df_multivariate,
                        scores = df_lda_scores,
                        loadings = df_lda_loadings,
                        loadings_common = df_lda_loadings_common,
                        ROC = df_lda_roc)
  
}
```

# Panel: ROC AUC

```{r}
nk_palette <- carto_pal(name = "PinkYl", n = 4)

df_comparison_labels <- tibble(comparison = c("chromatin_synaptic", "mapkwnt_synaptic", "chromatin_mapkwnt"),
                               label = c("Transcription vs.\n Synaptic-Immune",
                                         "MAPK-WNT vs.\n Synaptic-Immune", 
                                         "Transcription vs.\n MAPK-WNT"),
                               label_loadings = c("Transcription vs.\n Synaptic-Immune\n (K = 7)",
                                                  "MAPK-WNT vs.\n Synaptic-Immune\n (K = 7)", 
                                                  "Transcription vs.\n MAPK-WNT\n (K = 7)")) 

df_auc_comparisons <- list_lda %>% 
  map_dfr(function(x){x[["ROC"]]}) %>% 
  select(-tpr, -fpr, -thresholds) %>% 
  distinct()

list_auc_plts <- vector(mode = "list", length = length(human_datasets))
for (i in 1:length(human_datasets)) {
  
  df_auc_plt <- df_auc_comparisons %>% 
    filter(dataset == human_datasets[i]) %>% 
    mutate(comparison = factor(comparison, levels = df_comparison_labels$comparison))
  
  
  plt_auc <- ggplot(df_auc_plt, aes(x = comparison, y = AUC, fill = factor(nk))) + 
    geom_col(position = "dodge", col = "grey50", linewidth = 0.2) +
    coord_cartesian(ylim = c(0.5, 1.0)) +
    scale_x_discrete(labels = df_comparison_labels$label) + 
    scale_fill_manual(values = nk_palette) + 
    labs(x = "Molecular group comparison",
         y = "ROC AUC",
         fill = NULL) +
    theme_bw() +
    theme(axis.text.x = element_text(size = 6, color = "black"),
          # axis.text.x = element_text(angle = 20, hjust = 1, vjust = 1, size = 6),
          axis.text.y = element_text(size = 6),
          axis.title = element_text(size = 7),
          legend.position = "none")
  
  if (i == 1) {
    plt_auc <- plt_auc + 
      theme(legend.position = "bottom",
            legend.direction = "horizontal",
            legend.text = element_text(size = 6),
            legend.key.size = unit(10, "bigpts"),
            legend.margin = margin())
    
    auc_legend <- plt_auc %>% ggplotGrob() %>% grid.force() %>% getGrob("guides.3-3-3-3")
  }
  
  plt_auc <- plt_auc + 
    theme(legend.position = "none")
  
  list_auc_plts[[i]] <- ggplotGrob(plt_auc)
  
}
```

# Panel: LDA Loadings

```{r}
df_group_labels <- tibble(group = c("chromatin", "mapkwnt", "synaptic"),
                          label = c("Transcription", "MAPK-WNT", "Synaptic-Immune"))

nk_panel <- 7

list_loading_plts <- vector(mode = "list", length = length(human_datasets)) 
for (i in 1:length(list_loading_plts)) {
  
  idx_panel <- df_lda_grid %>% 
    filter(dataset == human_datasets[i], 
           nk == nk_panel) %>% 
    pull(idx)
  
  df_loadings_i <- map_dfr(list_lda[idx_panel], .f = function(x){x[["loadings"]]})
  
  df_loadings_common_i <- map_dfr(list_lda[idx_panel], .f = function(x){x[["loadings_common"]]})
  
  lvls_i <- df_loadings_i %>% 
    filter(comparison == "chromatin_synaptic") %>% 
    arrange(LD1) %>% 
    pull(acronym)
  
  df_loadings_i <- df_loadings_i %>% 
    left_join(df_comparison_labels, by = "comparison")
  
  df_loadings_i <- df_loadings_i %>% 
    mutate(acronym = factor(acronym, levels = lvls_i)) %>% 
    mutate(comparison = factor(comparison, levels = df_comparison_labels$comparison)) %>% 
    mutate(label_loadings = factor(label_loadings, levels = df_comparison_labels$label_loadings))
  
  plt_loadings_i <- ggplot(df_loadings_i, aes(x = LD1, y = acronym, col = group)) + 
    geom_vline(xintercept = 0) + 
    geom_segment(aes(xend = 0, yend = acronym)) + 
    geom_point() +
    facet_grid(.~label_loadings) +
    coord_cartesian(xlim = c(-0.5, 0.5)) + 
    scale_x_continuous(breaks = c(-0.5, 0, 0.5)) + 
    scale_colour_manual(values = c("darkorchid1", "springgreen4", "seagreen2"),
                        labels = c("Transcription", "MAPK-WNT", "Synaptic-Immune")) + 
    labs(x = "LD loadings",
         y = "Clinical variable",
         col = NULL) + 
    theme_bw() +
    theme(strip.text = element_blank(),
          axis.title = element_text(size = 6),
          axis.text = element_text(size = 6),
          legend.title = element_text(size = 6),
          legend.text = element_text(size = 6),
          legend.position = "bottom",
          legend.direction = "horizontal",
          # legend.background = element_rect(color = "black"),
          legend.margin = margin())
  
  if (i == 1) {
    loadings_legend_grob <- plt_loadings_i %>% ggplotGrob() %>% grid.force() %>% getGrob("guides.3-3-3-3")
  }
  
  plt_loadings_i <- plt_loadings_i +
    theme(legend.position = "none")


if (i == 1) {
    lvls_common_i <- df_loadings_common_i %>% 
      filter(comparison == "chromatin_synaptic") %>% 
      arrange(LD1) %>% 
      pull(acronym)
  }
  
  df_loadings_common_i <- df_loadings_common_i %>% 
        left_join(df_comparison_labels, by = "comparison") %>% 
    mutate(acronym = factor(acronym, levels = lvls_common_i)) %>% 
    mutate(comparison = factor(comparison, levels = df_comparison_labels$comparison)) %>% 
    mutate(label_loadings = factor(label_loadings, levels = df_comparison_labels$label_loadings))
  
  plt_loadings_common_i <- ggplot(df_loadings_common_i, aes(x = LD1, y = acronym, col = group)) + 
    geom_vline(xintercept = 0) + 
    geom_segment(aes(xend = 0, yend = acronym)) + 
    geom_point() +
    facet_grid(.~label_loadings) +
    coord_cartesian(xlim = c(-0.5, 0.5)) + 
    scale_x_continuous(breaks = c(-0.5, 0, 0.5)) + 
    scale_colour_manual(values = c("darkorchid1", "springgreen4", "seagreen2"),
                        labels = c("Transcription", "MAPK-WNT", "Synaptic-Immune")) + 
    theme_bw() +
    theme(axis.title.x = element_blank(),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_text(size = 6),
          strip.text.x = element_text(size = 6),
          strip.background = element_rect(fill = "#A9A9A9"),
          legend.position = "none")
  
  
  plt_loadings_patchwork_i <- (plt_loadings_common_i / plt_loadings_i) + plot_layout(heights = c(0.2, 0.8)) &
    theme(plot.margin = margin(b = 0, r = 2, t = 3))
  
  
  list_loading_plts[[i]] <- patchworkGrob(plt_loadings_patchwork_i)
  
}
```

# Figure

```{r}
panel_label_pond <- gTree(children = gList(textGrob("POND+", x = 0.53, gp = gpar(fontsize = 8)),
                                           segmentsGrob(x0 = 0.10, x1 = 1, y0 = 0.07, y1 = 0.07)))
panel_label_hbn <- gTree(children = gList(textGrob("HBN", x = 0.53, gp = gpar(fontsize = 8)),
                                          segmentsGrob(x0 = 0.08, x1 = 1, y0 = 0.07, y1 = 0.07)))
```

```{r}
legend_height <- 20
padding_width <- 10
panel_width <- (fig_width - padding_width)/2
padding_height <- 4
panel_auc_height <- 100
panel_loadings_height <- 310
panel_label_height <- 15

fig_widths <- c(panel_width, padding_width, panel_width)
fig_heights <- c(panel_label_height, panel_auc_height, padding_height, panel_loadings_height, legend_height)

fig_layout <- rbind(c(01, 02, 03),
                    c(04, 05, 06),
                    c(07, 07, 07),
                    c(08, 09, 10),
                    c(11, 11, 11))

fig_grob <- arrangeGrob(panel_label_pond,
                        zeroGrob(),
                        panel_label_hbn,
                        list_auc_plts[[1]],
                        zeroGrob(),
                        list_auc_plts[[2]],
                        # rectGrob(),
                        zeroGrob(),
                        list_loading_plts[[1]],
                        zeroGrob(),
                        list_loading_plts[[2]],
                        # gTree(children = gList(loadings_legend_grob, rectGrob(gp = gpar(fill = NA)))),
                        loadings_legend_grob,
                        layout_matrix = fig_layout,
                        widths = unit(fig_widths, "bigpts"),
                        heights = unit(fig_heights, "bigpts"))

fig_height_pt <- sum(fig_heights)
fig_width_pt <- sum(fig_widths)

fig_height_in <- fig_height_pt/72
fig_width_in <- fig_width_pt/72



outfile <- paste0(outfile_prefix, ".pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(fig_width_in, "in"),
    height = unit(fig_height_in, "in"))
grid.draw(fig_grob)

# pushViewport(viewport(y = unit(fig_height_pt - panel_label_height - panel_auc_height + 11, "bigpts"),
#                       just = "top",
#                       width = unit(100, "bigpts"),
#                       height = unit(20, "bigpts")))

pushViewport(viewport(y = unit(fig_height_pt - panel_label_height - 8, "bigpts"),
                      x = unit(fig_width_pt - 7, "bigpts"),
                      just = c("right", "top"),
                      width = unit(100, "bigpts"),
                      height = unit(20, "bigpts")))
grid.draw(auc_legend)
grid.text("Cluster solution (K)",
          x = unit(1.0, "npc"),
          y = unit(0.25, "npc"),
          just = "right",
          gp = gpar(fontsize = 6))
# grid.rect()
popViewport()


grid.text(label = c("A", "B"),
          x = unit(c(6, 6), "bigpts"),
          y = unit(c(fig_height_pt - 10, fig_height_pt - panel_label_height - panel_auc_height), "bigpts"),
          gp = gpar(fontsize = 10, fontface = "bold"))

invisible(dev.off())
```

```{r}
df_lda_grid %>% 
  filter(dataset == "HBN", nk == 7)
```

```{r}
df_pond_scores <- bind_rows(list_lda[[4]]$data,
                     list_lda[[5]]$data,
                     list_lda[[6]]$data) %>% 
  distinct() %>% 
  mutate(dataset = "POND")


df_hbn_scores <- bind_rows(list_lda[[16]]$data,
                           list_lda[[17]]$data,
                           list_lda[[18]]$data) %>% 
  distinct() %>% 
  mutate(dataset = "HBN")
```

```{r}
pond_common_cols <- c("cbcl_ep_ts", "rbsallt", "cbcl_ip_ts", "fsiq", "scqtot", "adhd_i_sub", "adhd_hi_sub")

colnames_new <- c("dataset", "group", "CBCL_EP", "RBS", "CBCL_IP", "FSIQ", "SCQ", "SWAN_I", "SWAN_HI")

df_pond_scores_common <- df_pond_scores[,c("dataset", "group", pond_common_cols)]
colnames(df_pond_scores_common) <- colnames_new

hbn_common_cols <- c("CBCL_EP_T", "Score_Total", "CBCL_IP_T", "FSIQ", "SCQ_Total", "ADHD_I", "ADHD_HI")
df_hbn_scores_common <- df_hbn_scores[,c("dataset", "group", hbn_common_cols)]
colnames(df_hbn_scores_common) <- colnames_new

df_scores_common <- bind_rows(df_pond_scores_common, df_hbn_scores_common)
```

```{r}
mat_scores_common <- df_scores_common %>% 
  select(-dataset, -group) %>% 
  as.matrix() %>% 
  scale()

set.seed(123)
umap_out <- uwot::umap2(X = mat_scores_common, n_components = 2)
colnames(umap_out) <- paste0("U", 1:2)

df_umap <- as_tibble(umap_out) %>% 
  mutate(dataset = df_scores_common$dataset,
         group = df_scores_common$group)

df_umap_centroids <- df_umap %>% 
  group_by(dataset, group) %>% 
  summarise(U1_mean = mean(U1),
            U2_mean = mean(U2)) %>% 
  ungroup()

ggplot(df_umap_centroids, aes(x = U1_mean, y = U2_mean, col = group, shape = dataset)) + 
  geom_point(size = 5) +
  labs(x = NULL, y = NULL) + 
  # coord_equal(xlim = c(-0.5, 0.5),
  #             ylim = c(-0.5, 0.5)) + 
  scale_color_manual(values = c("darkorchid1", "seagreen2", "springgreen4")) +
  # scale_shape_manual(values = c(21, 24)) + 
  theme_bw()
```

```{r}
mat_pond_scores_common <- df_pond_scores_common %>% 
  select(-dataset, -group) %>% 
  as.matrix() %>% 
  scale()

mat_hbn_scores_common <- df_hbn_scores_common %>% 
  select(-dataset, -group) %>% 
  as.matrix() %>% 
  scale()

mat_scores_common <- rbind(mat_pond_scores_common, mat_hbn_scores_common)

set.seed(123)
umap_out <- uwot::umap2(X = mat_scores_common, n_components = 2)
colnames(umap_out) <- paste0("U", 1:2)

df_umap <- as_tibble(umap_out) %>% 
  mutate(dataset = df_scores_common$dataset,
         group = df_scores_common$group)

df_umap_centroids <- df_umap %>% 
  group_by(dataset, group) %>% 
  summarise(U1_mean = mean(U1),
            U2_mean = mean(U2)) %>% 
  ungroup()

ggplot(df_umap_centroids, aes(x = U1_mean, y = U2_mean, col = group, shape = dataset)) + 
  geom_point(size = 5) +
  labs(x = NULL, y = NULL) + 
  coord_equal(xlim = c(-0.5, 0.5),
              ylim = c(-0.5, 0.5)) + 
  scale_color_manual(values = c("darkorchid1", "seagreen2", "springgreen4")) +
  # scale_shape_manual(values = c(21, 24)) + 
  theme_bw()
```

```{r}
df_pond_loadings <- bind_rows(list_lda[[4]]$loadings_common,
                              list_lda[[5]]$loadings_common,
                              list_lda[[6]]$loadings_common) %>% 
  distinct() %>% 
  mutate(dataset = "POND")

df_pond_loadings <- df_pond_loadings %>% 
  select(dataset, comparison, acronym, LD1) %>% 
  pivot_wider(id_cols = c("dataset", "comparison"), names_from = "acronym", values_from = "LD1")


df_hbn_loadings <- bind_rows(list_lda[[16]]$loadings_common,
                             list_lda[[17]]$loadings_common,
                             list_lda[[18]]$loadings_common) %>% 
  distinct() %>% 
  mutate(dataset = "HBN")

df_hbn_loadings <- df_hbn_loadings %>% 
  select(dataset, comparison, acronym, LD1) %>% 
  pivot_wider(id_cols = c("dataset", "comparison"), names_from = "acronym", values_from = "LD1")

df_loadings <- bind_rows(df_pond_loadings, 
                         df_hbn_loadings)

mat_loadings <- df_loadings %>% 
  select(-dataset, -comparison)

set.seed(123)
umap_out <- uwot::umap2(X = mat_loadings, n_components = 2, n_neighbors = 5)
colnames(umap_out) <- paste0("U", 1:2)

df_umap <- as_tibble(umap_out) %>% 
  mutate(dataset = df_loadings$dataset,
         comparison = df_loadings$comparison)

ggplot(df_umap, aes(x = U1, y = U2, col = comparison, shape = dataset)) + 
  geom_point(size = 5) +
  theme_bw()
```

```{r}
neighbours <- 15

mat_pond_scores <- df_pond_scores %>% 
  select(-ID, -dataset, -group) %>% 
  as.matrix() %>% 
  scale()

set.seed(123)
pond_umap_out <- uwot::umap2(X = mat_pond_scores, n_components = 2, n_neighbors = neighbours)
colnames(pond_umap_out) <- paste0("U", 1:2)

df_pond_umap <- as_tibble(pond_umap_out) %>% 
  mutate(dataset = df_pond_scores$dataset,
         group = df_pond_scores$group)

mat_hbn_scores <- df_hbn_scores %>% 
  select(-ID, -dataset, -group) %>% 
  as.matrix() %>% 
  scale()

set.seed(123)
hbn_umap_out <- uwot::umap2(X = mat_hbn_scores, n_components = 2, n_neighbors = neighbours)
colnames(hbn_umap_out) <- paste0("U", 1:2)

df_hbn_umap <- as_tibble(hbn_umap_out) %>% 
  mutate(dataset = df_hbn_scores$dataset,
         group = df_hbn_scores$group)

df_umap_full <- bind_rows(df_pond_umap, df_hbn_umap)

df_umap_full_means <- df_umap_full %>% 
  group_by(dataset, group) %>% 
  summarise(x = mean(U1),
            y = mean(U2)) %>% 
  ungroup()

ggplot(df_umap_full_means, aes(x = x, y = y, col = group, shape = dataset)) + 
  geom_point(size = 5) + 
  coord_equal(xlim = c(-0.3, 0.3),
                  ylim = c(-0.3, 0.3)) + 
  scale_colour_manual(values = c("darkorchid1", "seagreen2", "springgreen4")) + 
  theme_bw()
```

```{r}
pond_pca_out <- prcomp(x = mat_pond_scores)
mat_pond_pca <- pond_pca_out$x[,1:2]

df_pond_pca <- as_tibble(mat_pond_pca) %>% 
  mutate(dataset = df_pond_scores$dataset,
         group = df_pond_scores$group)

hbn_pca_out <- prcomp(x = mat_hbn_scores)
mat_hbn_pca <- hbn_pca_out$x[,1:2]

df_hbn_pca <- as_tibble(mat_hbn_pca) %>% 
  mutate(dataset = df_hbn_scores$dataset,
         group = df_hbn_scores$group)

df_pca_full <- bind_rows(df_pond_pca, df_hbn_pca)

df_pca_full_means <- df_pca_full %>% 
  group_by(dataset, group) %>% 
  summarise(x = mean(PC1),
            y = mean(PC2)) %>% 
  ungroup()
```

```{r}
ggplot(df_pca_full_means, aes(x = x, y = y, col = group, shape = dataset)) + 
  geom_point(size = 5) + 
  facet_grid(.~dataset) +
  coord_equal(xlim = c(-0.5, 0.5), ylim = c(-0.5, 0.5)) +
  scale_colour_manual(values = c("darkorchid1", "seagreen2", "springgreen4")) + 
  theme_bw()
```

```{r}
library(ggbiplot)

ggbiplot(hbn_pca_out, groups = df_hbn_pca$group, ellipse = TRUE) +
  theme_bw()
```
```{r}
ggbiplot(pond_pca_out, groups = df_pond_pca$group, ellipse = TRUE, circle = TRUE) +
  theme_bw()
```


```{r}
as_tibble(pond_pca_out$rotation, rownames = "measure") %>% 
  arrange(desc(abs(PC1))) %>% 
  filter(measure %in% pond_common_cols)
```

```{r}
as_tibble(hbn_pca_out$rotation, rownames = "measure") %>% 
  arrange(desc(abs(PC1))) %>% 
  filter(measure %in% hbn_common_cols)
```

