---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(RMINC)
library(MRIcrotome)
```

```{r}
PROJECTPATH <- Sys.getenv("PROJECTPATH")
```


```{r}
nlinFile <- file.path(PROJECTPATH, "data/mouse/registration/reference_files/scanbase_second_level-nlin-3.mnc")
labelFile <- file.path(PROJECTPATH, "data/mouse/registration/reference_files/scanbase_second_level-nlin-3_labels.mnc")

nlin <- mincArray(mincGetVolume(nlinFile))
labels <- mincArray(mincGetVolume(labelFile))


defs <- file.path(PROJECTPATH, "data/mouse/registration/reference_files/DSURQE_40micron_R_mapping.csv")
abijson <- file.path(PROJECTPATH, "data/mouse/registration/reference_files/Allen_hierarchy_definitions.json")

hdefs <- makeMICeDefsHierachical(defs, abijson)

sliceList <- map(seq(50, 350, length.out=8), ~ c(round(.x), 2))
sliceList[[length(sliceList)+1]] <- c(140,1)
sliceOffset <- 5

sl <- MRIcrotome(nlin, labels, hdefs, sliceList, assembleDir = "X", sliceOffset = sliceOffset)
```

```{r}
peaks <- read_csv("resources/MICe_peaks_new_cluster_labs.csv")
```


```{r}
peaks2 <- peaks %>% rowwise() %>% 
  mutate(voxel=list(mincConvertWorldToVoxel(nlinFile, x, y, z)),
         sliceDist = list(pointToSlicesDistance(sliceList, voxel)),
         keepSlice = list(which(abs(sliceDist)<21))) %>% 
  unnest_longer(keepSlice) %>% 
  rowwise() %>%
  mutate(point = list(convertPointToMRIcrotome(voxel, sl, keepSlice))) %>%
  unnest_wider(point, names_sep = "p")
```

```{r}
defs2 <- read_csv(defs) %>% 
  select(Structure, ABI)
peaks2 <- left_join(peaks2 %>% mutate(bilatstructure = str_remove_all(structure, "\\s*left\\s*|\\s*right\\s*")), 
                    defs2,
          by=c("bilatstructure" = "Structure"))
peaks2 <- peaks2 %>% 
  filter(!is.na(structure)) %>%
  rowwise() %>% 
  mutate(hierarchy = list(FindNode(hdefs, ABI)), 
         l2 = hierarchy$path[2],
         l3 = hierarchy$path[3],
         l4 = hierarchy$path[4],
         l5 = hierarchy$path[5],
         lb = ifelse(l4 == "Cerebral cortex", hierarchy$path[6], l4))

```


```{r}
MRIcroscope(sl) %>%
  add_anatomy() +
  geom_point(data=left_join(peaks2, motifs, by="cluster_id") %>% 
               filter(nk.x>6) %>% 
               filter(!is.na(motif) & motif != "androgen"),
             aes(x=pointpx, y=pointpy, colour=peak)) + 
  scale_colour_posneg_alpha(low=0.2, high=1) + 
  geom_sf(data=sl$data, fill=NA) + 
  facet_wrap(~motif, ncol=1)
```
```{r}

```

