---
title: "Untitled"
output: html_document
date: "2025-11-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initialization

```{r}
library(tidyverse)
library(RMINC)
library(ggalluvial)
library(patchwork)
library(MRIcrotome)
library(grid)
library(gridExtra)
library(RColorBrewer)
library(ggnewscale)
```

```{r}
PROJECTPATH <- Sys.getenv("PROJECTPATH")
SRCPATH <- Sys.getenv("SRCPATH")
```

```{r}
source(file.path(SRCPATH, "utils.R"))
source(file.path(SRCPATH, "processing.R"))
source(file.path(SRCPATH, "analysis.R"))
```

```{r}
output_dir <- file.path("outputs", "figure2_draft_4_1")
if (!(dir.exists(output_dir))) {dir.create(path = output_dir, recursive = TRUE)}
outfile_prefix <- "figure2_draft_4_1"
```

```{r}
pipeline_dir <- file.path(PROJECTPATH, "data/cross_species/v3")

human_datasets <- c("POND", "HBN")

params_ids <- c("POND" = "375", "HBN" = "861")
# params_ids <- c("POND" = "852", "HBN" = "021")
metadata <- file.path(pipeline_dir, "metadata.csv")
human_params_ids <- character(2)
for (i in 1:length(params_ids)) {
  pipeline_params <- fetch_params_metadata(metadata = metadata,
                                           params = list(id = params_ids[i]))
  
  human_params_ids[i] <- pipeline_params[["input_1_id"]]
}
mouse_params_id <- pipeline_params[["input_2_id"]]
```

```{r}
human_pipeline_dirs <- file.path(PROJECTPATH, "data/human/derivatives/v3/", human_params_ids)

human_cluster_dirs <- file.path(human_pipeline_dirs, "clusters", "resolution_3.0")
human_centroid_dirs <- file.path(human_pipeline_dirs, "centroids", "resolution_0.8")
```

```{r}
mouse_pipeline_dir <- file.path(PROJECTPATH, "data/mouse/derivatives/v3/", mouse_params_id)

mouse_cluster_dir <- file.path(mouse_pipeline_dir, "clusters", "resolution_0.2")
mouse_centroid_dir <- file.path(mouse_pipeline_dir, "centroids", "resolution_0.05")
```


```{r}
# Total figure dimensions in pts
fig_width <- 612
fig_height <- 792

# Figure border dimensions in pts
border_padding_width <- 4
border_padding_height <- border_padding_width

# Vertical padding between panels
# panel_padding_height <- 50
panel_padding_height <- border_padding_height

# Total width and height of all panels, excluding padding
panel_tot_width <- fig_width - 2*border_padding_width
panel_tot_height <- fig_height - 2*border_padding_height - 2*panel_padding_height

# Individual panel height
panel_height <- panel_tot_height/3
```

```{r}
nk_subset <- c(2, 4, 8)
```


# Cluster similarity

```{r eval = TRUE}
mouse_cluster_file <- file.path(mouse_cluster_dir, "clusters.csv")
df_mouse_clusters <- read_csv(mouse_cluster_file, show_col_types = FALSE)

df_mouse_cluster_counts <- df_mouse_clusters %>% 
  pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = as.numeric(str_remove(nk_name, "nk"))) %>% 
  select(-nk_name) %>% 
  unite(col = "cluster_id", "nk", "k", sep = "-", remove = FALSE) %>% 
  group_by(cluster_id) %>% 
  count() %>% 
  ungroup()
```

```{r eval = TRUE}
human_cluster_files <- file.path(human_cluster_dirs, "clusters.csv")
list_human_clusters <- map(human_cluster_files, read_csv, show_col_types = FALSE)
names(list_human_clusters) <- human_datasets

list_human_clusters_long <- map(.x = list_human_clusters, 
    .f = function(x) {
      x %>% 
        pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>%
        mutate(nk = as.numeric(str_remove(nk_name, "nk"))) %>%
        select(-nk_name) %>%
        unite(col = "cluster_id", "nk", "k", sep = "-", remove = FALSE)
    })

# df_human_cluster_counts <- human_clusters %>%
#   pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
#   mutate(nk = as.numeric(str_remove(nk_name, "nk"))) %>% 
#   select(-nk_name) %>% 
#   unite(col = "cluster_id", "nk", "k", sep = "-", remove = FALSE) %>% 
#   group_by(cluster_id) %>% 
#   count() %>% 
#   ungroup()
```

```{r eval = TRUE}
list_similarity <- vector(mode = "list", length = length(human_datasets))
names(list_similarity) <- human_datasets
for (i in 1:length(list_similarity)) {
  
  df_similarity <- compute_similarity_significance(
    similarity = import_similarity(param_id = params_ids[i], 
                                   pipeline_dir = pipeline_dir), 
    permutations = import_similarity_permutations(param_id = params_ids[i], 
                                                  pipeline_dir = pipeline_dir)
  )
  
  colnames(df_similarity) <- colnames(df_similarity) %>% 
    str_replace("img1", "human") %>% 
    str_replace("img2", "mouse")
  
  cluster_ids <- df_similarity %>% 
    select(human_cluster_id, human_nk, human_k) %>% 
    arrange(human_nk, human_k) %>% 
    distinct() %>% 
    pull(human_cluster_id)
  
  df_cluster_grid <- expand_grid(human_cluster_id = cluster_ids,
                                 mouse_cluster_id = cluster_ids) 
  
  df_matches <- df_similarity %>% 
    mutate(match = pval < 0.05) %>% 
    right_join(df_cluster_grid) %>% 
    mutate(match = ifelse(is.na(match), FALSE, match))
  
  list_similarity[[i]] <- df_matches
  
}
```


```{r}
list_cluster_groups <- list("A" = c("5-1", "6-1", "7-1", "8-1", "9-1", "10-1"),
                            "B" = c("5-3", "6-3", "7-3", "8-5", "9-4", "10-3"),
                            "C" = c("5-5", "6-4", "7-4", "8-2", "9-5", "10-5"),
                            "D" = c("5-4", "6-5", "7-7", "8-6", "9-2", "10-4"))
                            # "E" = c("5-1", "6-6", "7-6", "8-7", "9-9", "10-9"),
                            # "F" = c("5-2", "6-2", "7-2", "8-8", "9-6", "10-2"))


df_cluster_groups <- as_tibble(list_cluster_groups) %>% 
  pivot_longer(cols = everything(), names_to = "group", values_to = "mouse_cluster_id")

df_cluster_groups <- bind_rows(tibble(group = c("A", "D"), 
                                      mouse_cluster_id = c("2-1", "2-2")),
                               tibble(group = c("D", "B", "A"),
                                      mouse_cluster_id = c("4-1", "4-3", "4-4")),
                               df_cluster_groups) %>% 
  separate(col = "mouse_cluster_id", into = c("nk", "k"), sep = "-", remove = FALSE) %>% 
  mutate(nk = as.numeric(nk), k = as.numeric(k))

list_similarity_groups <- vector(mode = "list", length = length(human_datasets))
names(list_similarity_groups) <- human_datasets
for (i in 1:length(list_similarity_groups)) {
  list_similarity_groups[[i]] <- df_cluster_groups %>% 
    semi_join(filter(list_similarity[[i]], match),
              by = "mouse_cluster_id")
}
```

```{r}
col2hex <- function(x, alpha = FALSE) {
  args <- as.data.frame(t(col2rgb(x, alpha = alpha)))
  args <- c(args, list(names = x, maxColorValue = 255))
  do.call(rgb, args)
}

col2hex("springgreen4")
col2hex("darkorchid1")
col2hex("seagreen2")
```


# Mouse slices

```{r}
# Jacobians to display
jacobians <- "relative"

# # Threshold method
# threshold <- pipeline_params %>% 
#   filter(id == params_ids[["POND"]]) %>% 
#   pull(threshold)
# 
# # Threshold value
# threshold_value <- pipeline_params %>% 
#   filter(id == params_ids[["POND"]]) %>% 
#   pull(threshold_value)
# 
# # Threshold symmetric option
# threshold_symmetric <- pipeline_params %>% 
#   filter(id == params_ids[["POND"]]) %>% 
#   pull(threshold_symmetric)

threshold <- "top_n"
threshold_value <- 0.2
threshold_symmetric <- TRUE

# Mouse centroid map directory
mouse_centroid_dir <- file.path(mouse_centroid_dir, jacobians)

# Mouse anatomy
mouse_anat_file <- file.path(PROJECTPATH, "data/mouse/atlas/DSURQE_CCFv3_average_50um.mnc")
mouse_anat <- mincGetVolume(mouse_anat_file)
mouse_anat_vol <- mincArray(mouse_anat)

# Mouse mask
mouse_mask_file <- file.path(PROJECTPATH, "data/mouse/atlas/coronal_50um_coverage_bin0.8.mnc")
mouse_mask <- mincGetVolume(mouse_mask_file)

overlay_low <- 0.19
overlay_high <- 1.0

# Mouse anatomy thresholds
mouse_anat_low <- 700
mouse_anat_high <- 1400

mouse_slc_dim <- 1
mouse_slc <- 92
```

```{r}
list_mouse_slices_POND <- vector(mode = "list", length = length(nk_subset))
names(list_mouse_slices_POND) <- nk_subset
list_mouse_slices_HBN <- list_mouse_slices_POND
for (i in 1:length(list_mouse_slices_POND)) {
  
  nki <- nk_subset[i]
  list_mouse_slices_POND[[i]] <- vector(mode = "list", length = nki)
  for (k in 1:nki) {
    
    img <- import_cluster_map(imgdir = mouse_centroid_dir,
                              mask = mouse_mask_file,
                              nk = nki, k = k, 
                              threshold = threshold,
                              threshold_value = threshold_value,
                              threshold_symmetric = threshold_symmetric)
    
    # Compute overlay thresholds
    overlay_threshold <- numeric(2)
    overlay_threshold[1] <- min(abs(img[img != 0]))
    overlay_threshold[2] <- 0.8*max(abs(img[img != 0]))
    overlay_threshold <- round(overlay_threshold, 2)
    
    img <- mincArray(img)
    
    img_grob_POND <- sliceSeries(nrow = 1, ncol = 1, 
                            dimension = mouse_slc_dim, 
                            slices = mouse_slc) %>% 
      anatomy(mouse_anat_vol, low = mouse_anat_low, high = mouse_anat_high) %>% 
      overlay(img, 
              low = overlay_threshold[1], high = overlay_threshold[2], 
              symmetric = TRUE) %>% 
      grobify()
    
    img_grob_HBN <- sliceSeries(nrow = 1, ncol = 1, 
                            dimension = mouse_slc_dim, 
                            slices = mouse_slc) %>% 
      anatomy(mouse_anat_vol, low = mouse_anat_low, high = mouse_anat_high) %>% 
      overlay(img, 
              low = overlay_threshold[1], high = overlay_threshold[2], 
              symmetric = TRUE) %>% 
      grobify()
    
    list_mouse_slices_POND[[i]][[k]] <- img_grob_POND
    list_mouse_slices_HBN[[i]][[k]] <- img_grob_HBN
    
  }
}

```


# Human slices

```{r}
# Jacobians to display
jacobians <- "relative"

# # Threshold method
# threshold <- pipeline_params %>% 
#   filter(id == params_id) %>% 
#   pull(threshold)
# 
# # Threshold value
# threshold_value <- pipeline_params %>% 
#   filter(id == params_id) %>% 
#   pull(threshold_value)
# 
# # Threshold symmetric option
# threshold_symmetric <- pipeline_params %>% 
#   filter(id == params_id) %>% 
#   pull(threshold_symmetric)

# Mouse centroid map directory
human_centroid_dirs <- file.path(human_centroid_dirs, jacobians)

# Mouse mask
human_mask_file <- file.path(PROJECTPATH, "data/human/registration/v3/reference_files/mask_0.8mm.mnc")
human_mask <- mincGetVolume(human_mask_file)

# human anatomy
human_anat_file <- file.path(PROJECTPATH, "data/human/registration/v3/reference_files/model_0.8mm.mnc")
human_anat <- mincGetVolume(human_anat_file)
human_anat[human_mask < 0.5] <- 0
human_anat_vol <- mincArray(human_anat)

slices_dim_1 <- 27:220
slices_dim_2 <- 10:280
slices_dim_3 <- 1:220
human_anat_vol_cropped <- human_anat_vol[slices_dim_1, slices_dim_2, slices_dim_3]

overlay_low <- 0.19
overlay_high <- 1.0

# Human anatomy thresholds
human_anat_low <- 40
human_anat_high <- 110

human_slc_dim <- 1
human_slc <- 82
```

```{r}
df_matches_POND <- tibble(mouse_cluster_id = c("2-1", "2-2", "4-1", "4-4", "8-1", "8-2", "8-5", "8-6"),
                          human_cluster_id = c("3-3", "2-1", "4-1", "4-2", "9-5", "8-7", "8-4", "8-2"))


list_human_slices_POND <- vector(mode = "list", length = length(nk_subset))
names(list_human_slices_POND) <- nk_subset
for (i in 1:length(list_human_slices_POND)) {
  
  nki <- nk_subset[i]
  list_human_slices_POND[[i]] <- vector(mode = "list", length = nki)
  for (k in 1:nki) {
    
    cluster_id <- paste0(nki, "-", k)
    
    if (cluster_id %in% df_matches_POND$mouse_cluster_id) {
      
      human_cluster_id <- df_matches_POND %>% 
        filter(mouse_cluster_id == cluster_id) %>% 
        pull(human_cluster_id)
      
      human_nk <- str_split(human_cluster_id, pattern = "-")[[1]][1]
      human_k <- str_split(human_cluster_id, pattern = "-")[[1]][2]
      
      img <- import_cluster_map(imgdir = human_centroid_dirs[1],
                                mask = human_mask_file,
                                nk = human_nk, k = human_k, 
                                threshold = threshold,
                                threshold_value = threshold_value,
                                threshold_symmetric = threshold_symmetric)
      
      # Compute overlay thresholds
      overlay_threshold <- numeric(2)
      overlay_threshold[1] <- min(abs(img[img != 0]))
      overlay_threshold[2] <- 0.8*max(abs(img[img != 0]))
      overlay_threshold <- round(overlay_threshold, 2)
      
      img <- mincArray(img)
      img <- img[slices_dim_1, slices_dim_2, slices_dim_3]
      
      img_grob <- sliceSeries(nrow = 1, ncol = 1, 
                              dimension = human_slc_dim, 
                              slices = human_slc) %>% 
        anatomy(human_anat_vol_cropped, low = human_anat_low, high = human_anat_high) %>% 
        overlay(img, 
                low = overlay_threshold[1], high = overlay_threshold[2], 
                symmetric = TRUE) %>% 
        grobify()
      
      list_human_slices_POND[[i]][[k]] <- img_grob
      
    } else {
      
      list_human_slices_POND[[i]][[k]] <- rectGrob(gp = gpar(fill = "grey90"))
    
    }
  }
}

```


```{r}
df_matches_HBN <- tibble(mouse_cluster_id = c("2-1", "2-2", "4-1", "4-3", "4-4", "8-1", "8-2", "8-3", "8-4", "8-5", "8-6"),
                         human_cluster_id = c("3-3", "2-2", "4-3", "4-4", "4-2", "8-4", "8-8", "9-8", "7-2", "7-3", "8-2"))


list_human_slices_HBN <- vector(mode = "list", length = length(nk_subset))
names(list_human_slices_HBN) <- nk_subset
for (i in 1:length(list_human_slices_HBN)) {
  
  nki <- nk_subset[i]
  list_human_slices_HBN[[i]] <- vector(mode = "list", length = nki)
  for (k in 1:nki) {
    
    cluster_id <- paste0(nki, "-", k)
    
    if (cluster_id %in% df_matches_HBN$mouse_cluster_id) {
      
      human_cluster_id <- df_matches_HBN %>% 
        filter(mouse_cluster_id == cluster_id) %>% 
        pull(human_cluster_id)
      
      human_nk <- str_split(human_cluster_id, pattern = "-")[[1]][1]
      human_k <- str_split(human_cluster_id, pattern = "-")[[1]][2]
      
      img <- import_cluster_map(imgdir = human_centroid_dirs[2],
                                mask = human_mask_file,
                                nk = human_nk, k = human_k, 
                                threshold = threshold,
                                threshold_value = threshold_value,
                                threshold_symmetric = threshold_symmetric)
      
      # Compute overlay thresholds
      overlay_threshold <- numeric(2)
      overlay_threshold[1] <- min(abs(img[img != 0]))
      overlay_threshold[2] <- 0.8*max(abs(img[img != 0]))
      overlay_threshold <- round(overlay_threshold, 2)
      
      img <- mincArray(img)
      img <- img[slices_dim_1, slices_dim_2, slices_dim_3]
      
      img_grob <- sliceSeries(nrow = 1, ncol = 1, 
                              dimension = human_slc_dim, 
                              slices = human_slc) %>% 
        anatomy(human_anat_vol_cropped, low = human_anat_low, high = human_anat_high) %>% 
        overlay(img, 
                low = overlay_threshold[1], high = overlay_threshold[2], 
                symmetric = TRUE) %>% 
        grobify()
      
      list_human_slices_HBN[[i]][[k]] <- img_grob
      
    } else {
      
      list_human_slices_HBN[[i]][[k]] <- rectGrob(gp = gpar(fill = "grey90"))
    
    }
  }
}

```


```{r}
# Human registration directory
human_registration_dir <- file.path(PROJECTPATH, "data/human/registration/v3")

# Import human demographics data
demographics <- file.path(human_registration_dir, "subject_info", "demographics.csv")
demographics <- read_csv(demographics, show_col_types = FALSE)

# Redefine diagnostic categories
list_diagnoses <- list(
  "POND" = tibble(DX = c("ASD", "OCD", "ADHD", "Sub-threshold OCD",
                         "Anxiety", "Sub-threshold ADHD",
                         "Intellectual Disability only", 
                         "Tourette Syndrome", "Other", "Fragile X"),
                  DX_new = c("ASD", "OCD", "ADHD", "OCD", "Other", 
                             "ADHD", "Other", "Other", "Other", "Other")),
  "HBN" = tibble(DX = c("ASD", "OCD", "ADHD", "Tourette Syndrome", "ID"),
                 DX_new = c("ASD", "OCD", "ADHD", "Other", "Other"))
)

cluster_ids <- list_human_clusters_long[[1]] %>% 
  filter(nk %in% nk_subset) %>% 
  arrange(nk, k) %>% 
  pull(cluster_id) %>% 
  unique()

# Diagnostic category levels
dx_lvls <- c("ASD", "ADHD", "OCD", "Other")

# Full grid of cluster and DX
dx_grid <- expand_grid(DX_new = dx_lvls,
                       cluster_id = cluster_ids)  %>% 
  separate(col = "cluster_id", into = c("nk", "k"), 
           sep = "-", remove = FALSE) %>% 
  mutate(nk = as.numeric(nk), k = as.numeric(k))

list_cluster_dx <- vector(mode = "list", length = length(list_human_clusters))
list_human_groups <- vector(mode = "list", length = length(list_human_clusters))
list_rect <- vector(mode = "list", length = length(list_human_clusters))
names(list_cluster_dx) <- names(list_human_clusters)
names(list_human_groups) <- names(list_human_clusters)
names(list_rect) <- names(list_human_clusters)
for (i in 1:length(list_human_clusters)) {
  list_cluster_dx[[i]]  <- list_human_clusters_long[[i]] %>%
    left_join(select(demographics, ID = file, DX), by = "ID") %>% 
    left_join(list_diagnoses[[i]], by = "DX") %>% 
    filter(nk %in% nk_subset) %>% 
    group_by(nk, k) %>% 
    mutate(n_cluster = n()) %>% 
    ungroup() %>% 
    group_by(nk, k, DX_new) %>% 
    mutate(n_cluster_dx = n()) %>% 
    ungroup() %>% 
    mutate(prop_cluster_dx = n_cluster_dx/n_cluster) %>% 
    select(cluster_id, nk, k, DX_new, prop_cluster_dx) %>% 
    distinct() %>% 
    right_join(dx_grid, by = c("cluster_id", "nk", "k", "DX_new")) %>% 
    mutate(prop_cluster_dx = ifelse(is.na(prop_cluster_dx), 0, prop_cluster_dx))

  
}
```


```{r}
list_POND_dx <- vector(mode = "list", length = length(nk_subset))
for (i in 1:length(list_POND_dx)) {
  
  list_POND_dx[[i]] <- vector(mode = "list", length = nk_subset[i])
  for (k in 1:nk_subset[i]) {

    cluster_id <- paste0(nk_subset[i], "-", k)
    
    if (cluster_id %in% df_matches_POND$mouse_cluster_id) {
      
      df_donut <- list_cluster_dx[["POND"]] %>% 
        rename(clust = k) %>% 
        filter(nk == nk_subset[i], 
               clust == k) %>% 
        mutate(DX_new = factor(DX_new, levels = dx_lvls)) %>% 
        arrange(DX_new) %>% 
        mutate(ymax = cumsum(prop_cluster_dx))
      
      df_donut$ymin <- c(0, head(df_donut$ymax, n = -1))
      
      plt_donut <- ggplot(df_donut, aes(ymax = ymax, ymin = ymin, xmax = 1, xmin = 0, fill = DX_new)) + 
        geom_rect() +
        coord_polar(theta = "y") +
        xlim(c(-1, 1)) +
        theme_void() +
        theme(legend.position = "none")
      
      list_POND_dx[[i]][[k]] <- ggplotGrob(plt_donut)
      
    } else {
      
      list_POND_dx[[i]][[k]] <- zeroGrob()
      
    }
  }
}  
```

```{r}
df_donut <- list_cluster_dx[["POND"]] %>% 
  rename(clust = k) %>% 
  filter(nk == nk_subset[i], 
         clust == k) %>% 
  mutate(DX_new = factor(DX_new, levels = dx_lvls)) %>% 
  arrange(DX_new) %>% 
  mutate(ymax = cumsum(prop_cluster_dx))
  

df_donut$ymin <- c(0, head(df_donut$ymax, n = -1))

ggplot(df_donut, aes(ymax = ymax, ymin = ymin, xmax = 1, xmin = 0, fill = DX_new)) + 
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(-1, 1))
```


```{r}
list_HBN_dx <- vector(mode = "list", length = length(nk_subset))
for (i in 1:length(list_HBN_dx)) {
  
  list_HBN_dx[[i]] <- vector(mode = "list", length = nk_subset[i])
  for (k in 1:nk_subset[i]) {
    
    cluster_id <- paste0(nk_subset[i], "-", k)
    
    if (cluster_id %in% df_matches_HBN$mouse_cluster_id) {
    
    df_donut <- list_cluster_dx[["HBN"]] %>% 
      rename(clust = k) %>% 
      filter(nk == nk_subset[i], 
             clust == k) %>% 
      mutate(DX_new = factor(DX_new, levels = dx_lvls)) %>% 
      arrange(DX_new) %>% 
      mutate(ymax = cumsum(prop_cluster_dx))
    
    df_donut$ymin <- c(0, head(df_donut$ymax, n = -1))
    
    plt_donut <- ggplot(df_donut, aes(ymax = ymax, ymin = ymin, xmax = 1, xmin = 0, fill = DX_new)) + 
      geom_rect() +
      coord_polar(theta = "y") +
      xlim(c(-1, 1)) +
      theme_void() +
      theme(legend.position = "none")
    
    list_HBN_dx[[i]][[k]] <- ggplotGrob(plt_donut)
    
          
    } else {
      
      list_HBN_dx[[i]][[k]] <- zeroGrob()
      
    }
    
  }
}  
```


```{r}
df_donut <- list_cluster_dx[["HBN"]] %>% 
  rename(clust = k) %>% 
  filter(nk == nk_subset[i], 
         clust == k) %>% 
  mutate(DX_new = factor(DX_new, levels = dx_lvls)) %>% 
  arrange(DX_new) %>% 
  mutate(ymax = cumsum(prop_cluster_dx))

df_donut$ymin <- c(0, head(df_donut$ymax, n = -1))

ggplot(df_donut, aes(ymax = ymax, ymin = ymin, xmax = 1, xmin = 0, fill = DX_new)) + 
  geom_rect() +
  coord_polar(theta = "y") +
  xlim(c(-1, 1))
```


```{r}
# Parameters for slice series
list_ss_params <- list(
  # K = 2
  list(ss_slc_w = 60,
       ss_pad_w = 5),
  # K = 4
  list(ss_slc_w = 50,
       ss_pad_w = 5),
  # K = 8
  list(ss_slc_w = 40,
       ss_pad_w = 4)
)

# Dimensions of slice series 
list_ss_dims <- vector(mode = "list", length = length(nk_subset)) 
for (i in 1:length(list_ss_dims)) {
  
  list_ss_dims[[i]][["widths"]] <- c(list_ss_params[[i]][["ss_slc_w"]],
                                     list_ss_params[[i]][["ss_pad_w"]],
                                     list_ss_params[[i]][["ss_slc_w"]],
                                     list_ss_params[[i]][["ss_pad_w"]],
                                     list_ss_params[[i]][["ss_slc_w"]])
  
  list_ss_dims[[i]][["heights"]] <- rep(list_ss_params[[i]][["ss_slc_w"]], 2)
  
}
  
# Parameters for plot grid
list_grid_params <- list(
  # K = 2
  list(grid_padding_h = 10,
       grid_y_multipliers = 0.5:-0.5,
       grid_x = 10 + sum(list_ss_dims[[1]][["widths"]])/2),
  # K = 4
  list(grid_padding_h = 10,
       grid_y_multipliers = 1.5:-1.5,
       grid_x = fig_width/2 + 20),
  # K = 8
  list(grid_padding_h = 10,
       grid_y_multipliers = 3.5:-3.5,
       grid_x = 537)
)

# Parameters for viewports
list_vp_params <- vector(mode = "list", length = length(nk_subset))
list_vps <- list_vp_params
for (i in 1:length(list_vps)) {
  
  list_vps[[i]] <- vector(mode = "list", length = nk_subset[i])
  list_vp_params[[i]] <- vector(mode = "list", length = nk_subset[i])
  for (k in 1:nk_subset[i]) {
    
    x <- list_grid_params[[i]][["grid_x"]]
    y <- fig_height/2 + list_grid_params[[i]][["grid_y_multipliers"]][[k]]*(list_grid_params[[i]][["grid_padding_h"]] + sum(list_ss_dims[[i]][["heights"]]))
    w <- sum(list_ss_dims[[i]][["widths"]])
    h <- sum(list_ss_dims[[i]][["heights"]])
    
    list_vp_params[[i]][[k]] <- list(x = x, y = y, w = w, h = h)
    
    list_vps[[i]][[k]] <- viewport(
      x = unit(x, "bigpts"),
      y = unit(y, "bigpts"),
      width = unit(w, "bigpts"),
      height = unit(h, "bigpts")
    )
    
  }
}



list_connections <- vector(mode = "list", length = length(nk_subset)-1)
for (i in 1:length(list_connections)) {
  
  cols <- paste0("nk", nk_subset[c(i, i+1)])
  tmp <- df_mouse_clusters[,cols]
  colnames(tmp) <- c("nk_start", "nk_end")
  
  nk_grid <- expand_grid(nk_start = 1:nk_subset[i],
                         nk_end = 1:nk_subset[i+1])
  
  df_nk_props <- tmp %>% 
    group_by(nk_start) %>% 
    mutate(n_start = n()) %>% 
    ungroup() %>% 
    group_by(nk_start, nk_end, n_start) %>% 
    count() %>% 
    ungroup() %>% 
    mutate(prop = n/n_start) %>% 
    right_join(nk_grid, by = c("nk_start", "nk_end")) %>% 
    mutate(prop = ifelse(is.na(prop), 0, prop)) %>% 
    select(nk_start, nk_end, prop)
  
  x0 <- map_dbl(list_vp_params[[i]], ~ .x[["x"]])
  y0 <- map_dbl(list_vp_params[[i]], ~ .x[["y"]])
  x1 <- map_dbl(list_vp_params[[i+1]], ~ .x[["x"]])
  y1 <- map_dbl(list_vp_params[[i+1]], ~ .x[["y"]])
  
  x0 <- x0 + sum(list_ss_dims[[i]][["widths"]])/2
  x1 <- x1 - sum(list_ss_dims[[i+1]][["widths"]])/2
  
  df_start <- tibble(nk_start = 1:nk_subset[i],
                     x0 = x0, y0 = y0)
  
  df_end <- tibble(nk_end = 1:nk_subset[i+1],
                   x1 = x1, y1 = y1)
  

  df_segment_coords <- bind_cols(expand_grid(x0 = x0, x1 = x1),
                                 expand_grid(y0 = y0, y1 = y1))  
  
  df_segment_coords <- df_segment_coords %>% 
    left_join(df_start, by = c("x0", "y0")) %>% 
    left_join(df_end, by = c("x1", "y1")) %>% 
    left_join(df_nk_props, by = c("nk_start", "nk_end"))


  list_connections[[i]] <- vector(mode = "list", length = nrow(df_segment_coords))
  for (r in 1:nrow(df_segment_coords)) {
    
    list_connections[[i]][[r]] <- segmentsGrob(x0 = unit(df_segment_coords[[r, "x0"]], "bigpts"),
                                               y0 = unit(df_segment_coords[[r, "y0"]], "bigpts"),
                                               x1 = unit(df_segment_coords[[r, "x1"]], "bigpts"),
                                               y1 = unit(df_segment_coords[[r, "y1"]], "bigpts"),
                                               gp = gpar(alpha = df_segment_coords[[r, "prop"]],
                                                         lwd = 2))
    
  }
}


ss_layout <- matrix(1:10, nrow = 2, ncol = 5, byrow = TRUE)


list_grobs <- vector(mode = "list", length = length(nk_subset))
for (i in 1:length(list_grobs)) {
  
  list_grobs[[i]] <- vector(mode = "list", length = nk_subset[i])
  for (k in 1:nk_subset[i]) {
    
    # list_grobs[[i]][[k]] <- 
      
    cluster_grob <- arrangeGrob(list_mouse_slices_POND[[i]][[k]], 
                                rectGrob(),
                                list_human_slices_POND[[i]][[k]],
                                rectGrob(),
                                list_human_slices_HBN[[i]][[k]],
                                zeroGrob(),
                                zeroGrob(),
                                list_POND_dx[[i]][[k]],
                                zeroGrob(),
                                list_HBN_dx[[i]][[k]],
                                layout_matrix = ss_layout,
                                widths = unit(list_ss_dims[[i]][["widths"]], "bigpts"),
                                heights = unit(list_ss_dims[[i]][["heights"]], "bigpts"))
    
    list_grobs[[i]][[k]] <- gTree(children = gList(rectGrob(), cluster_grob),
                                  vp = list_vps[[i]][[k]])
    
  }
}

tmp <- c(reduce(list_grobs, c), reduce(list_connections, c))

grobs_list <- do.call(gList, tmp)

grobs <- gTree(children = gList(grobs_list))


ss_width <- sum(ss_widths)
ss_height <- sum(ss_heights)


outfile <- paste0(outfile_prefix, ".pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(fig_width/72, "in"),
    height = unit(fig_height/72, "in"))
grid.draw(grobs)
dev.off()
```

