---
title: "Untitled"
output: html_document
date: "2025-12-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Initialization

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(ggbeeswarm))
suppressPackageStartupMessages(library(patchwork))
# suppressPackageStartupMessages(library(viridis))
# suppressPackageStartupMessages(library(rcartocolor))
```

```{r env}
PROJECTPATH <- Sys.getenv("PROJECTPATH")
SRCPATH <- Sys.getenv("SRCPATH")

source(file.path(SRCPATH, "utils.R"))
source(file.path(SRCPATH, "processing.R"))
source(file.path(SRCPATH, "analysis.R"))
source(file.path(SRCPATH, "enrichment.R"))
```

```{r functions}
consolidate_visits <- function(df, cols) {
  
  subject_ids <- df %>% 
    pull(subject_id) %>% 
    unique()
  
  df_init <- df %>% 
    select(subject_id, visit_instance, all_of(cols)) %>% 
    mutate(n_missing = rowSums(!is.na(across(all_of(cols)))))
  
  df_complete <- df_init %>% 
    filter(n_missing > 0) %>% 
    group_by(subject_id) %>% 
    filter(visit_instance == max(visit_instance)) %>% 
    ungroup() %>% 
    select(subject_id, all_of(cols))
  
  # Participants with completed ABAS
  ids_complete <- df_complete %>% 
    pull(subject_id) %>% 
    unique()
  
  # Participants with no ABAS scores
  ids_missing <- setdiff(subject_ids, ids_complete)
  
  # Create a data frame of NAs for particpants with no scores
  df_missing <- matrix(nrow = length(ids_missing), ncol = length(cols))
  rownames(df_missing) <- ids_missing
  colnames(df_missing) <- cols
  df_missing <- as_tibble(df_missing, rownames = "subject_id")
  
  df_out <- bind_rows(df_complete, df_missing)
  
  return(df_out)
  
}


bootstrap_sample_estimate <- function(x, groups = NULL, estimate = "mean", 
                                      B = 1000, set_seed = TRUE) {
  
  if (estimate == "mean") {
    estimator <- mean
  } else if (estimate == "median") {
    estimator <- median
  } else if (estimate == "sd") {
    estimator <- sd
  } else {
    stop()
  }
  
  n_groups <- ifelse(is.null(groups), 1, length(unique(groups)))
  if (n_groups > 1) {
    if (!is.factor(groups)) {
      stop("groups must be factor")
    }
  }
  groups_lvls <- levels(groups)
  
  bootstrap_samples <- matrix(data = 0, nrow = B, ncol = n_groups)
  colnames(bootstrap_samples) <- groups_lvls
  for (i in 1:nrow(bootstrap_samples)) {
    if (n_groups == 1) {
      if (set_seed) {set.seed(i)}
      bootstrap_samples[[i]] <- estimator(sample(x = x, size = length(x), 
                                                 replace = TRUE))
    } else {
      x_split <- split(x = x, f = groups)
      n_split <- lapply(x_split, length)
      if (set_seed) {set.seed(i)}
      x_split_sample <- mapply(FUN = sample, x = x_split, size = n_split, 
                               MoreArgs = list(replace = TRUE))
      bootstrap_samples[i,] <- sapply(X = x_split_sample, FUN = estimator)
    }
  }
  
  return(bootstrap_samples)
  
}

bootstrap_sample_estimate_ci <- function(x, groups = NULL, estimate = "mean", 
                                         interval = c(0.025, 0.975), B = 1000, 
                                         set_seed = TRUE) {
  bootstrap_samples <- bootstrap_sample_estimate(x = x, groups = groups, 
                                                 estimate = estimate,
                                                 B = B, set_seed = set_seed)
  bootstrap_ci <- apply(bootstrap_samples, MARGIN = 2, quantile, interval)
  bootstrap_ci <- t(bootstrap_ci)
  colnames(bootstrap_ci) <- c("lower", "upper")
  return(bootstrap_ci)
}

group_summary <- function(x, groups, B = 1000) {
  
  means <- split(x = x, f = groups) %>% 
    sapply(mean) %>% 
    matrix(ncol = 1, nrow = length(levels(groups)))
  colnames(means) <- "mu"
  
  ci <- bootstrap_sample_estimate_ci(x = x, groups = groups, B = B)
  
  out <- cbind(means, ci)
  rownames(out) <- levels(groups)
  
  return(out)
  
}
```

```{r outputs}
outfile_prefix <- "figure4_draft_4_2"
output_dir <- file.path("outputs", outfile_prefix)
if (!(dir.exists(output_dir))) {dir.create(path = output_dir, recursive = TRUE)}
```

```{r pipeline-paths}
pipeline_dir <- file.path(PROJECTPATH, "data/cross_species/v3")

human_datasets <- c("POND", "HBN")

params_ids <- c("POND" = "375", "HBN" = "861")
# params_ids <- c("POND" = "852", "HBN" = "021")
metadata <- file.path(pipeline_dir, "metadata.csv")
human_params_ids <- character(2)
for (i in 1:length(params_ids)) {
  pipeline_params <- fetch_params_metadata(metadata = metadata,
                                           params = list(id = params_ids[i]))
  
  human_params_ids[i] <- pipeline_params[["input_1_id"]]
}
mouse_params_id <- pipeline_params[["input_2_id"]]

# Human pipeline directory
human_pipeline_dirs <- file.path(PROJECTPATH, "data/human/derivatives/v3/", human_params_ids)

# Human cluster and centroid directories
human_cluster_dirs <- file.path(human_pipeline_dirs, "clusters", "resolution_3.0")
human_centroid_dirs <- file.path(human_pipeline_dirs, "centroids", "resolution_0.8")

# Human registration directory
human_registration_dir <- file.path(PROJECTPATH, "data/human/registration/v3/")
```

```{r fig-params}
# Total figure dimensions in pts
fig_width <- 7.25*72
fig_height <- 792
```


# Transcriptomic cluster similarity

```{r}
params_ids <- c(params_ids, "POND_HBN" = "779")
list_similarity <- vector(mode = "list", length = length(params_ids))
names(list_similarity) <- names(params_ids)
for (i in 1:length(list_similarity)) {
  
  df_similarity <- compute_similarity_significance(
    similarity = import_similarity(param_id = params_ids[i], 
                                   pipeline_dir = pipeline_dir), 
    permutations = import_similarity_permutations(param_id = params_ids[i], 
                                                  pipeline_dir = pipeline_dir)
  )
  
  cluster_ids <- df_similarity %>% 
    select(img1_cluster_id, img1_nk, img1_k) %>% 
    arrange(img1_nk, img1_k) %>% 
    distinct() %>% 
    pull(img1_cluster_id)
  
  df_cluster_grid <- expand_grid(img1_cluster_id = cluster_ids,
                                 img2_cluster_id = cluster_ids) 
  
  
  df_matches <- df_similarity %>% 
    mutate(match = pval < 0.05) %>% 
    right_join(df_cluster_grid,
               by = c("img1_cluster_id", "img2_cluster_id")) %>% 
    mutate(match = ifelse(is.na(match), FALSE, match))
  
  list_similarity[[i]] <- df_matches
  
}  

```


# Import cluster information

```{r}
list_clusters <- vector(mode = "list", length = length(human_datasets))
names(list_clusters) <- human_datasets
for (i in 1:length(human_datasets)) {
  clusters_file <- file.path(human_cluster_dirs[i], "clusters.csv")
  list_clusters[[i]] <- read_csv(clusters_file, show_col_types = FALSE)
}
```

```{r}
library(ggalluvial)

sankey_palette_files <- c("human_cluster_colours_POND.xlsx",
                          "human_cluster_colours_HBN.xlsx")
for (i in 1:length(list_clusters)) {
  
  df_clusters_long <- list_clusters[[i]] %>% 
    select(ID, contains("nk")) %>%
    pivot_longer(cols = c(-ID), names_to = "nk_name", values_to = "k") %>%
    mutate(nk = str_remove(nk_name, "nk"),
           nk = as.numeric(nk),
           cluster_id = paste0(nk, "-", k))
  
  df_sankey_palette <- readxl::read_excel(file.path("resources", sankey_palette_files[i]))
  sankey_palette <- df_sankey_palette$colour
  names(sankey_palette) <- df_sankey_palette$cluster_id
  
  plt_sankey <- ggplot(df_clusters_long,
                       aes(x = factor(nk), stratum = k,
                           alluvium = ID, fill = cluster_id)) +
    geom_flow(stat = "alluvium", aes.flow = "forward",
              linewidth = 0.15) +
    geom_stratum() +
    scale_fill_manual(values = sankey_palette, guide = "none") +
    theme_bw()
  
  outfile <- paste0("sankey_", human_datasets[i], ".pdf")
  outfile <- file.path(output_dir, outfile)
  pdf(file = outfile,
      width = unit(10, "in"),
      height = unit(6, "in"))
  print(plt_sankey)
  dev.off()
  
}
```

```{r}
# Import demographics
demographics_file <- file.path(human_registration_dir, "subject_info",
                               "demographics.csv")
df_demographics <- read_csv(demographics_file, show_col_types = FALSE)

for (i in 1:length(list_clusters)) {
  
  # Subset demographics variables
  df_demographics_subset <- df_demographics %>% 
    filter(Dataset == human_datasets[i]) %>% 
    select(file, subject_id = Subject_ID, 
           age = Age, sex = Sex, dx = DX)
  
  # Join demographics information
  list_clusters[[i]] <- list_clusters[[i]] %>% 
    inner_join(df_demographics_subset, by = c("ID" = "file"))
  
}
```



# Process clinical data

## Process POND data

```{r import-pond-db}
# Import full POND database
pond_db_file <- "POND_database_export_20251210.csv"
pond_db_file <- file.path(human_registration_dir, "subject_info/POND", pond_db_file)
df_pond_db <- read_csv(pond_db_file, show_col_types = FALSE)
```

```{r clean-pond-db}
# List of database data columns
list_data_cols <- list(
  CBCL = c("cb68ipts", "cb68epts", "cbipts", "cbepts"),
  ABAS = c("ab05gccs", "ab21gccs", "ab89gccs"),
  BOT2 = c("bot2_bltc_ss", "bot2_bal_ss", "bot2_bdyc_stds"),
  KINDL = c("kkid_tot", "kkdo_tot", "kkdy_tot"),
  NEPSY = c("nepsyii_a516_ar_ss", "nepsyii_a516_mf_ss", "nepsyii_a516_mfd_ss", 
            "nepsyii_a516_mf_mfd_ccs", "nepsyii_a516_tm_ss",
            "nepsyii_a716_as_tcssc", "nepsyii_a716_as_css"),
  OWL = c("owllcss", "owloess", "owlocss"),
  OWL2 = c("owl2lcss", "owl2oess", "owl2olcss"),
  RBS = "rbsallt",
  SCQ = "scqtot",
  SSP = c("ssp_tactile_rs", "ssp_taste_smell_rs", "ssp_movement_rs", "ssp_underresp_seeks_rs",
          "ssp_aud_filter_rs", "ssp_low_enrgy_weak_rs", "ssp_vis_aud_rs", "ssp_total_rs"),
  SpatialNBack = c("s0b_tgt_accuracy", "s0b_nontgt_accuracy", "s1b_tgt_accuracy", "s1b_nontgt_accuracy",
                   "s2b_tgt_accuracy", "s2b_nontgt_accuracy"),
  StopTask = c("mt_st_pcrt", "mt_st_mcrtt", "mt_st_crtsdt", "mt_st_psit", "mt_st_ssrtt",
               "mt_st_itssrt", "mt_st_psrrt"),
  SWAN = c("adhd_i_sub", "adhd_hi_sub"),
  TOCS = "tpocs_tot",
  IQ = c("wasi_ii_fsiq_4", "wasi_fsiq_4", "wisc_v_fsiq", "wisc_iv_fsiq",
         "sbfulliq", "wppsi47_full", "wppsi_iv47_fsiq_cs", "wasi_ii_fsiq_2",
         "wasi_fsiq_2")
)

# Reduce data columns into a vector
pond_db_data_cols <- reduce(list_data_cols, c)

# Database columns to include
pond_db_cols <- c("subject_id", "sub_id", "redcap_event_name", "redcap_repeat_instance",
                  "site", "dob", "primary_diagnosis", "research_confirm_diag", 
                  pond_db_data_cols)

# Subset for desired columns
df_pond_db_subset <- df_pond_db[,pond_db_cols]

# Remove deprecated and cross-visit arms
events_exclude <- c("deprecated_arm_1", "cross_visit_arm_1")
df_pond_db_subset <- df_pond_db_subset %>% 
  filter(!(redcap_event_name %in% events_exclude)) %>% 
  filter(str_detect(subject_id, "deprecated", negate = TRUE))

# Dictionary for site codes
df_site_codes <- tibble(site_acronym = c("HBK", "HSC", "LHR", "MCU", "QNS"),
                        site_code = c("105", "088", "113", "114", "394"))

# Redefine site codes based on subject site acronym
df_pond_db_subset <- df_pond_db_subset %>% 
  mutate(site_acronym = subject_id %>% 
           str_trunc(9, ellipsis = "") %>% 
           str_trunc(3, side = "left", ellipsis = "")) %>% 
  left_join(df_site_codes, by = "site_acronym") 

# Clean up IDs
df_pond_db_subset <- df_pond_db_subset %>% 
  mutate(subject_id_test = str_trunc(subject_id, 4, side = "left", ellipsis = "")) %>% 
  mutate(pond_id = paste0(site_code, subject_id_test)) %>% 
  select(-subject_id_test, -sub_id, -site) %>% 
  rename(site = site_code,
         redcap_id = subject_id,
         subject_id = pond_id)  

# Clean up visits information
df_pond_db_subset <- df_pond_db_subset %>% 
  mutate(redcap_repeat_instance = ifelse(is.na(redcap_repeat_instance), 0, redcap_repeat_instance)) %>% 
  mutate(visit_type = ifelse(redcap_event_name == "baseline_arm_1", "baseline", "longitudinal")) %>% 
  rename(visit_instance = redcap_repeat_instance) %>% 
  select(-redcap_event_name)

# Correct ABAS values 
df_pond_db_subset <- df_pond_db_subset %>% 
  mutate(ab21gccs = ifelse(ab21gccs == "<40", NA, ab21gccs),
         ab21gccs = as.numeric(ab21gccs))  

# Consolidate missing values
df_pond_db_subset <- df_pond_db_subset %>% 
  mutate(across(all_of(pond_db_data_cols), ~ ifelse(.x %in% c(-9999, 999), NA, .x)))
```

```{r consolidate-clinical-scores}
# Initialize data frame for POND clinical scores
df_clinical_scores_pond <- df_pond_db_subset %>% 
  select(redcap_id, subject_id) %>% 
  distinct()


# Consolidate CBCL scores -----------------------------------------------------

# If cb68 scores present, use those. If not, use cb scores
df_cbcl_init <- df_pond_db_subset %>% 
  select(subject_id, visit_instance, starts_with("cb")) %>% 
  mutate(cbcl_ep_ts = ifelse(!is.na(cb68epts), cb68epts, cbepts),
         cbcl_ip_ts = ifelse(!is.na(cb68ipts), cb68ipts, cbipts)) %>% 
  select(subject_id, visit_instance, cbcl_ep_ts, cbcl_ip_ts)

df_cbcl <- consolidate_visits(df = df_cbcl_init, cols = c("cbcl_ep_ts", "cbcl_ip_ts"))

df_clinical_scores_pond <- df_clinical_scores_pond %>% 
  left_join(df_cbcl, by = "subject_id")


# Consolidate ABAS scores -----------------------------------------------------
# Unsure of the order to use scales here, when they have multiple in the same visit

df_abas_init <- df_pond_db_subset %>%
  select(subject_id, visit_instance, starts_with("ab")) %>% 
  mutate(abas_gccs = ifelse(!is.na(ab89gccs), ab89gccs,
                            ifelse(!is.na(ab21gccs), ab21gccs, ab05gccs))) %>% 
  select(subject_id, visit_instance, abas_gccs)

df_abas <- consolidate_visits(df = df_abas_init, cols = "abas_gccs")

df_clinical_scores_pond <- df_clinical_scores_pond %>% 
  left_join(df_abas, by = "subject_id")


# Consolidate KINDL scores ----------------------------------------------------
# Not sure if I can compare scores here?
# Some scores are 0. What is the range? Scores above 100.

df_kindl_init <- df_pond_db_subset %>%
  select(subject_id, visit_instance, kkid_tot, kkdo_tot, kkdy_tot) %>% 
  mutate(kindl_tot = ifelse(!is.na(kkdo_tot), kkdo_tot, 
                            ifelse(!is.na(kkid_tot), kkid_tot, kkdy_tot))) %>% 
  select(subject_id, visit_instance, kindl_tot)

df_kindl <- consolidate_visits(df = df_kindl_init, cols = "kindl_tot")

df_clinical_scores_pond <- df_clinical_scores_pond %>% 
  left_join(df_kindl, by = "subject_id")


# Consolidate OWL scores ------------------------------------------------------

df_owl_init <- df_pond_db_subset %>%
  select(subject_id, visit_instance, starts_with("owl")) %>% 
  mutate(owl_lc_ss = ifelse(!is.na(owl2lcss), owl2lcss, owllcss),
         owl_oe_ss = ifelse(!is.na(owl2oess), owl2oess, owloess),
         owl_olc_ss = ifelse(!is.na(owl2olcss), owl2olcss, owllcss)) %>% 
  select(subject_id, visit_instance, starts_with("owl"))  

df_owl <- consolidate_visits(df = df_owl_init, cols = c("owl_lc_ss", "owl_oe_ss", "owl_olc_ss"))

df_clinical_scores_pond <- df_clinical_scores_pond %>% 
  left_join(df_owl, by = "subject_id")


# Consolidate IQ scores ------------------------------------------------------

df_fsiq_init <- df_pond_db_subset %>% 
  select(subject_id, visit_instance, all_of(list_data_cols[["IQ"]])) %>% 
  mutate(fsiq = ifelse(!is.na(wasi_ii_fsiq_4), wasi_ii_fsiq_4,
                       ifelse(!is.na(wasi_fsiq_4), wasi_fsiq_4,
                              ifelse(!is.na(wisc_v_fsiq), wisc_v_fsiq,
                                     ifelse(!is.na(wisc_iv_fsiq), wisc_iv_fsiq,
                                            ifelse(!is.na(sbfulliq), sbfulliq,
                                                   ifelse(!is.na(wppsi47_full), wppsi47_full,
                                                          ifelse(!is.na(wppsi_iv47_fsiq_cs), wppsi_iv47_fsiq_cs,
                                                                 ifelse(!is.na(wasi_ii_fsiq_2), wasi_ii_fsiq_2,
                                                                        ifelse(!is.na(wasi_fsiq_2), wasi_fsiq_2, NA)))))))))) %>% 
  select(subject_id, visit_instance, fsiq)


df_fsiq <- consolidate_visits(df = df_fsiq_init, cols = "fsiq")

df_clinical_scores_pond <- df_clinical_scores_pond %>% 
  left_join(df_fsiq, by = "subject_id")


# Consolidate remaining variables ---------------------------------------------

idx_vars <- !(names(list_data_cols) %in% c("CBCL", "ABAS", "KINDL", "OWL", "OWL2", "IQ"))
list_data_cols_sub <- list_data_cols[idx_vars]
for (cols in list_data_cols[idx_vars]) {
  df_clinical_scores_pond <- df_clinical_scores_pond %>% 
    left_join(consolidate_visits(df = df_pond_db_subset, cols = cols),
              by = "subject_id")
}

# Update subject IDs to match clusters and demographics
df_clinical_scores_pond <- df_clinical_scores_pond %>% 
  mutate(subject_id = paste0("sub-", subject_id))
```

```{r}
# Join clinical scores and cluster information
df_clusters_clinical_POND <- list_clusters$POND %>% 
  left_join(df_clinical_scores_pond, by = "subject_id") %>% 
  select(-redcap_id)
```


## Process HBN data


```{r}
list_HBN_assessments <- list(
  ACE = list(code = "ACE", skip = TRUE, vars = c("ACE_Score")),
  ARI_P = list(code = "ARI_P",
               skip = TRUE,
               vars = c("ARI_P_Total_Score")),
  ARI_S = list(code = "ARI_S",
               skip = TRUE,
               vars = c("ARI_S_Total_Score")),
  ASSQ = list(code = "ASSQ",
              skip = TRUE,
              vars = c("ASSQ_Total")),
  CDI_P = list(code = "CDI2_P",
               skip = TRUE,
               vars = c("CDI2P_Total_T")),
  CDI_S = list(code = "CDI2_SR",
               skip = TRUE,
               vars = c("CDI2_Total_T")),
  CGAS = list(code = "CGAS",
              skip = TRUE,
              vars = c("CGAS_Score")),
  CIS_P = list(code = "CIS_P",
               skip = TRUE,
               vars = c("CIS_P_Score")),
  CIS_SR = list(code = "CIS_SR",
                skip = TRUE,
                vars = c("CIS_SR_Total")),
  EVT = list(code = "EVT",
             skip = TRUE,
             vars = c("EVT2_StandardScore")),
  GFTA = list(code = "GFTA",
              skip = TRUE,
              vars = c("GFTA_SIW_Stnd", "GFTA_SIS_Stnd")),
  ICU_P = list(code =  "ICU_P",
               skip = TRUE,
               vars = c("ICU_P_Callous", "ICU_P_Uncaring", 
                        "ICU_P_Unemotional", "ICU_P_Total")),
  ICU_SR = list(code = "ICU_SR",
                skip = TRUE,
                vars = c("ICU_SR_Callous", "ICU_SR_Uncaring",
                         "ICU_SR_Unemotional", "ICU_SR_Total")),
  KBIT = list(code = "KBIT",
              skip = TRUE,
              vars = c("KBIT_IQ_Comp")),
  MFQ_P = list(code = "MFQ_P",
               skip = TRUE,
               vars = c("MFQ_P_Total")),
  MFQ_SR = list(code = "MFQ_SR",
                skip = TRUE,
                vars = c("MFQ_SR_Total #1")),
  NIH_Scores = list(code = "NIH_Scores",
                    skip = TRUE,
                    vars = c("NIH7_Card", "NIH7_Cog", "NIH7_Flanker", 
                             "NIH7_List", "NIH7_Pattern", "NIH7_Picture")),
  PPVT = list(code = "PPVT",
              skip = TRUE,
              vars = c("PPVT4_StandardScore")),
  Quotient = list(code = "Quotient",
                  skip = TRUE,
                  vars = c("quotient_global_scaled")),
  RANRAS = list(code = "RANRAS",
                skip = TRUE,
                vars = c("RR_Let_Stnd", "RR_Obj_Stnd", "RR_Two_Stnd", "RR_Col_Stnd",
                         "RR_Num_Stnd", "RR_Three_Stnd")),
  RBS = list(code = "RBS",
             skip = TRUE,
             vars = c("Score_Total")),
  SCARED_P = list(code = "SCARED_P",
                  skip = TRUE,
                  vars = c("SCARED_P_Total")),
  SCARED_SR = list(code = "SCARED_SR",
                   skip = TRUE,
                   vars = c("SCARED_SR_Total")),
  SCQ = list(code = "SCQ",
             skip = TRUE,
             vars = c("SCQ_Total")),
  SDQ = list(code = "SDQ",
             skip = TRUE,
             vars = c("SDQ_Difficulties_Total")),
  SDS = list(code = "SDS",
             skip = TRUE,
             vars = c("SDS_Total_T")),
  STAI = list(code = "STAI",
              skip = TRUE,
              vars = c("STAI_SA", "STAI_TA")),
  SWAN = list(code = "SWAN",
              skip = TRUE,
              vars = c("ADHD_HI", "ADHD_I")),
  TOWRE = list(code = "TOWRE",
               skip = TRUE,
               vars = c("TOWRE_PDE_Scaled", "TOWRE_SWE_Scaled", "TOWRE_Total_Scaled")),
  Vineland = list(code = "Vineland",
                  skip = TRUE,
                  vars = c("VL_Comm_Scale", "VL_DLS_Scale", "VL_Social_Scale")),
  WHODAS_P = list(code = "WHODAS_P",
                  skip = TRUE,
                  vars = c("WHODAS_P_Score")),
  WHODAS_SR = list(code = "WHODAS_SR",
                   skip = TRUE,
                   vars = c("WHODAS_SR_Score")),
  YSR = list(code = "YSR",
             skip = TRUE,
             vars = c("YSR_Total_T"))
)
```


```{r}
path_HBN_assessments <- file.path(human_registration_dir, "subject_info", 
                                  "HBN", "assessment_data")

df_clusters_clinical_HBN <- list_clusters$HBN

for (x in list_HBN_assessments) {
  
  file <- paste0("9994_", x$code, "_20220728.csv")
  file <- file.path(path_HBN_assessments, file)
  df <- read_csv(file, show_col_types = FALSE)
  if (x$skip) {df <- df[2:nrow(df),]}
  
  df <- df[,c("EID", x$vars)]
  colnames(df) <- c("subject_id", x$vars)
  df <- df %>% 
    mutate(across(x$vars, as.numeric)) %>% 
    distinct()
  
  n_multiple <- df %>% 
    group_by(subject_id) %>% 
    count() %>% 
    filter(n > 1) %>% 
    nrow()
  
  if (n_multiple > 0) {
    df <- df %>% 
      group_by(subject_id) %>% 
      sample_n(size = 1) %>% 
      ungroup() 
  }
  
  df_clusters_clinical_HBN <- df_clusters_clinical_HBN %>% 
    left_join(df, by = "subject_id")
}


## CBCL

file <- file.path(path_HBN_assessments, "9994_CBCL_20220728.csv")
df <- read_csv(file, show_col_types = FALSE)

df_cbcl <- df %>% 
  select(subject_id = EID, CBCL_IP_T = CBCL_Int_T, CBCL_EP_T = CBCL_Ext_T)

file <- file.path(path_HBN_assessments, "9994_CBCL_Pre_20220728.csv")
df <- read_csv(file, show_col_types = FALSE)

df <- df[2:nrow(df),]

df_cbcl_pre <- df %>% 
  select(subject_id = EID, CBCL_IP_T = CBCL_Pre_Int_T, CBCL_EP_T = CBCL_Pre_Ext_T) %>% 
  mutate(CBCL_IP_T = as.numeric(CBCL_IP_T),
         CBCL_EP_T = as.numeric(CBCL_EP_T))

df_cbcl <- bind_rows(df_cbcl, df_cbcl_pre)

df_clusters_clinical_HBN <- df_clusters_clinical_HBN %>% 
  left_join(df_cbcl, by = "subject_id")


## IQ

file <- file.path(path_HBN_assessments, "9994_WISC_20220728.csv")
df_wisc <- read_csv(file, show_col_types = FALSE)

df_wisc <- df_wisc[2:nrow(df_wisc),]

df_wisc <- df_wisc %>% 
  select(subject_id = EID, WISC_FSIQ) %>% 
  mutate(WISC_FSIQ = as.numeric(WISC_FSIQ)) %>% 
  group_by(subject_id) %>% 
  mutate(WISC_FSIQ_MEAN = mean(WISC_FSIQ)) %>% 
  ungroup() %>% 
  select(subject_id, WISC_FSIQ = WISC_FSIQ_MEAN) %>% 
  distinct()

file <- file.path(path_HBN_assessments, "9994_WASI_20220728.csv")
df_wasi <- read_csv(file, show_col_types = FALSE)

df_wasi <- df_wasi[2:nrow(df_wasi),]

df_wasi <- df_wasi %>% 
  select(subject_id = EID, WASI_FSIQ) %>% 
  mutate(WASI_FSIQ = as.numeric(WASI_FSIQ))

df_fsiq <- full_join(df_wisc, df_wasi, by = "subject_id")

df_fsiq <- df_fsiq %>% 
  mutate(FSIQ = ifelse(!is.na(WASI_FSIQ), WASI_FSIQ, WISC_FSIQ)) %>% 
  select(subject_id, FSIQ)

df_clusters_clinical_HBN <- df_clusters_clinical_HBN %>% 
  left_join(df_fsiq, by = "subject_id")



## CELF

file <- file.path(path_HBN_assessments, "9994_CELF_Full_5to8_20220728.csv")
df_celf_5to8 <- read_csv(file, show_col_types = FALSE)

df_celf_5to8 <- df_celf_5to8[2:nrow(df_celf_5to8),]

df_celf_5to8 <- df_celf_5to8 %>% 
  select(subject_id = EID, CELF_CLS_Stnd, CELF_RLI_Stnd, CELF_ELI_Stnd, CELF_LCI_Stnd) %>% 
  mutate(CELF_CLS_Stnd = as.numeric(CELF_CLS_Stnd),
         CELF_RLI_Stnd = as.numeric(CELF_RLI_Stnd),
         CELF_ELI_Stnd = as.numeric(CELF_ELI_Stnd),
         CELF_LCI_Stnd = as.numeric(CELF_LCI_Stnd))


file <- file.path(path_HBN_assessments, "9994_CELF_Full_9to21_20220728.csv")
df_celf_9to21 <- read_csv(file, show_col_types = FALSE)

df_celf_9to21 <- df_celf_9to21[2:nrow(df_celf_9to21),]

df_celf_9to21 <- df_celf_9to21 %>% 
  select(subject_id = EID, CELF_CLS_Stnd, CELF_RLI_Stnd, CELF_ELI_Stnd, CELF_LCI_Stnd) %>% 
  mutate(CELF_CLS_Stnd = as.numeric(CELF_CLS_Stnd),
         CELF_RLI_Stnd = as.numeric(CELF_RLI_Stnd),
         CELF_ELI_Stnd = as.numeric(CELF_ELI_Stnd),
         CELF_LCI_Stnd = as.numeric(CELF_LCI_Stnd))


df_celf <- bind_rows(df_celf_5to8, df_celf_9to21)

df_clusters_clinical_HBN <- df_clusters_clinical_HBN %>% 
  left_join(df_celf, by = "subject_id")

df_clusters_clinical_HBN <- df_clusters_clinical_HBN %>% 
  select(-contains("_SR_"), -ARI_S_Total_Score, -CDI2_Total_T)

```

```{r}
list_clusters_clinical <- list(POND = df_clusters_clinical_POND,
                               HBN = df_clusters_clinical_HBN)
```



# Clinical scores analysis

## Complete case analysis

```{r}
list_complete_cases <- vector(mode = "list", length = length(list_clusters_clinical))
names(list_complete_cases) <- names(list_clusters_clinical)
for (l in 1:length(list_clusters_clinical)) {
  
  df_completion <- list_clusters_clinical[[l]] %>% 
    select(-contains("nk"), -ID, -age, -sex, -dx) %>% 
    pivot_longer(cols = -subject_id, names_to = "variable", values_to = "score") %>% 
    mutate(complete = !is.na(score)) %>% 
    group_by(variable) %>% 
    summarise(n_completed = sum(complete)) %>% 
    ungroup() %>% 
    arrange(desc(n_completed))
  
  df_complete_cases <- df_completion %>% 
    mutate(n_complete = 0, n_included = 0)
  
  for (i in 1:nrow(df_complete_cases)) {
    
    variables <- df_completion %>% 
      slice_max(order_by = n_completed, n = i) %>% 
      pull(variable)
    
    df_clinical_subset <- list_clusters_clinical[[l]][, variables]
    
    df_complete_cases[[i, "n_complete"]]  <- sum(complete.cases(df_clinical_subset))
    df_complete_cases[[i, "n_included"]] <- i
    
  }
  
  list_complete_cases[[l]] <- df_complete_cases
  
  plt_complete_cases <- ggplot(df_complete_cases, aes(x = n_included, y = n_complete)) + 
    geom_line() + 
    geom_point() +
    scale_x_continuous(breaks = seq(0, 100, by = 4)) +
    scale_y_continuous(breaks = seq (0, 1000, by = 50)) + 
    labs(x = "Number of variables included",
         y = "Number of complete cases") +
    theme_bw()
  
  outfile <- paste0("questionnaire_completion_", human_datasets[l], ".pdf")
  outfile <- file.path(output_dir, outfile)
  pdf(file = outfile,
      width = unit(10, "in"),
      height = unit(6, "in"))
  print(plt_complete_cases)
  dev.off()
  
}

```


## Synaptic vs. chromatin LDA


```{r}
clinical_acronyms_POND <- c("scqtot" = "SCQ",
                            "rbsallt" = "RBS-R",
                            "tpocs_tot" = "TOCS",
                            "adhd_i_sub" = "SWAN I",
                            "adhd_hi_sub" = "SWAN HI",
                            "fsiq" = "FSIQ",
                            "abas_gccs" = "ABAS GAC",
                            "cbcl_ep_ts" = "CBCL EP",
                            "cbcl_ip_ts" = "CBCL IP",
                            "ssp_total_rs" = "SSP TOT",
                            "ssp_aud_filter_rs" = "SSP AF",
                            "ssp_low_enrgy_weak_rs" = "SSP LEW",
                            "ssp_movement_rs" = "SSP MS",
                            "ssp_tactile_rs" = "SSP TAC",
                            "ssp_taste_smell_rs" = "SSP TSS",
                            "ssp_underresp_seeks_rs" = "SSP URSS",
                            "ssp_vis_aud_rs" = "SSP VAS",
                            "owl_lc_ss" = "OWLS LC",
                            "owl_oe_ss" = "OWLS OE",
                            "owl_olc_ss" = "OWLS OLC",
                            "nepsyii_a516_ar_ss" = "NEPSY AR",
                            "nepsyii_a516_mf_ss" = "NEPSY MF",
                            "nepsyii_a516_mfd_ss" = "NEPSY MFD",
                            "nepsyii_a516_mf_mfd_ccs" = "NEPSY MF vs. MFD",
                            "bot2_bal_ss" = "BOT 2 Bal.",
                            "bot2_bltc_ss" = "BOT 2 Bil. Coord.",
                            "bot2_bdyc_stds" = "BOT 2 Body Coord.")

clinical_acronyms_HBN <- c("ACE_Score" = "ACE",
                           "ARI_P_Total_Score" = "ARI PR",
                           "ARI_S_Total_Score" = "ARI SR",
                           "ASSQ_Total" = "ASSQ",
                           "CDI2P_Total_T" = "CDI2 PR",
                           "CDI2_Total_T" = "CDI2 SR",
                           "CGAS_Score" = "CGAS",
                           "CIS_P_Score" = "CIS PR",
                           "CIS_SR_Total" = "CIS SR",
                           "EVT2_StandardScore" = "EVT2",
                           "GFTA_SIW_Stnd" =  "GFTA SIW",
                           "GFTA_SIS_Stnd" = "GFTA SIS",
                           "ICU_P_Callous" = "ICU PR Call.",
                           "ICU_P_Uncaring" = "ICU PR Uncar.",
                           "ICU_P_Unemotional" = "ICU PR Unemot.",
                           "ICU_P_Total" = "ICU PR TOT",
                           "ICU_SR_Callous" = "ICU SR Call.",
                           "ICU_SR_Uncaring" = "ICU SR Uncar.",
                           "ICU_SR_Unemotional" = "ICU SR Unemot.",
                           "ICU_SR_Total" = "ICU SR TOT",
                           "KBIT_IQ_Comp" = "KBIT IQ",
                           "MFQ_P_Total" = "MFQ PR TOT",
                           "MFQ_SR_Total #1" = "MFQ SR TOT",
                           "NIH7_Card" = "NIH Card",
                           "NIH7_Cog" =  "NIH Cog.",
                           "NIH7_Flanker" =  "NIH Flank.",
                           "NIH7_List" = "NIH List",
                           "NIH7_Pattern" = "NIH Patt.",
                           "NIH7_Picture" = "NIH Pic.",
                           "PPVT4_StandardScore" = "PPVT4",
                           "quotient_global_scaled" = "Quotient",
                           "RR_Let_Stnd" = "RR Let.",
                           "RR_Obj_Stnd" =  "RR Obj.",
                           "RR_Two_Stnd" = "RR Two.",
                           "RR_Col_Stnd" = "RR Col.",
                           "RR_Num_Stnd" =  "RR Num.",
                           "RR_Three_Stnd" = "RR Three",
                           "Score_Total" = "RBS-R",
                           "SCARED_P_Total" = "SCARED PR",
                           "SCARED_SR_Total" = "SCARED SR",
                           "SCQ_Total" = "SCQ",
                           "SDQ_Difficulties_Total" = "SDQ",
                           "SDS_Total_T" = "SDS",
                           "STAI_SA" = "STAI SA", 
                           "STAI_TA" = "STAI TA",
                           "ADHD_HI" = "SWAN HI", 
                           "ADHD_I" = "SWAN I",
                           "TOWRE_PDE_Scaled" = "TOWRE PDE",
                           "TOWRE_SWE_Scaled" = "TOWRE SWE",
                           "TOWRE_Total_Scaled" = "TOWRE TOT",
                           "VL_Comm_Scale" = "VL Comm.",
                           "VL_DLS_Scale" = "VL DLS", 
                           "VL_Social_Scale" = "VL Soc.",
                           "WHODAS_P_Score" = "WHODAS PR",
                           "WHODAS_SR_Score" = "WHODAS SR",
                           "YSR_Total_T" = "YSR",
                           "CBCL_IP_T" = "CBCL IP", 
                           "CBCL_EP_T" = "CBCL EP",
                           "FSIQ" =  "FSIQ",
                           "CELF_CLS_Stnd" = "CELF CLS",
                           "CELF_RLI_Stnd" = "CELF RLI",
                           "CELF_ELI_Stnd" = "CELF ELI",
                           "CELF_LCI_Stnd" = "CELF LCI")

clinical_acronyms <- list(POND = clinical_acronyms_POND,
                          HBN = clinical_acronyms_HBN)

list_clinical_acronyms <- map(.x = clinical_acronyms, 
                              .f = function(x){enframe(x, name = "variable", value = "acronym")})
```

```{r}
df_common <- list_clinical_acronyms$POND %>% 
  rename(POND_variable = variable) %>% 
  inner_join(list_clinical_acronyms$HBN, by = "acronym") %>% 
  rename(HBN_variable = variable)
```


```{r}
list_cluster_pathways <- list(
  POND = list(synaptic = c("7-4", "8-7", "9-4"),
              chromatin = c("7-1", "8-1", "8-2", "9-7")),
  HBN = list(synaptic = c("7-1", "7-2", "7-7", "8-3", "8-8", "9-1"),
             chromatin = c("7-2", "7-6", "8-2", "8-8", "9-6"))
)


list_cluster_groups <- vector(mode = "list", length = length(list_cluster_pathways))
names(list_cluster_groups) <- human_datasets
for (i in 1:length(list_cluster_pathways)) {
  
  df_synaptic <- tibble(cluster_id = list_cluster_pathways[[i]]$synaptic) %>% 
    separate(col = cluster_id, into = c("nk", "k"), sep = "-", remove = FALSE) %>% 
    mutate(nk = as.numeric(nk),
           k = as.numeric(k),
           group = "synaptic")
  
  df_chromatin <- tibble(cluster_id = list_cluster_pathways[[i]]$chromatin) %>% 
    separate(col = cluster_id, into = c("nk", "k"), sep = "-", remove = FALSE) %>% 
    mutate(nk = as.numeric(nk),
           k = as.numeric(k),
           group = "chromatin")
  
  list_cluster_groups[[i]] <- bind_rows(df_synaptic, df_chromatin)
  
}
```

```{r}
list_similarity$POND %>% 
  filter(img1_cluster_id == "7-1", match)
```

```{r}
list_similarity$HBN %>% 
  filter(img1_cluster_id == "5-5") %>% 
  arrange(pval)
```

```{r}
list_similarity$POND_HBN %>% 
  filter(img2_cluster_id == "7-6", match)
```


```{r}
list_clusters_compare <- list(
  POND = c("7-1", "7-4"),
  HBN = c("7-7", "7-6")
)

nki <- 7
n_variables <- c(20, 27)

list_lda_inputs <- vector(mode = "list", length = length(human_datasets))
names(list_lda_inputs) <- human_datasets
list_lda_fit <- list_lda_inputs
list_lda_roc <- list_lda_inputs
for (i in 1:length(list_lda_inputs)) {

df_cluster_compare <- list_cluster_groups[[i]] %>% 
  filter(cluster_id %in% list_clusters_compare[[i]])

# Fetch variables with the desired completion level
variables <- list_complete_cases[[i]] %>% 
  slice_max(order_by = n_complete, n = n_variables[i]) %>% 
  pull(variable)

# Extract variable scores
cols <- c("ID", paste0("nk", nki), variables)
df_multivariate <- list_clusters_clinical[[i]][,cols]
colnames(df_multivariate) <- c("ID", "k", variables)

# Filter for complete cases
df_multivariate <- df_multivariate[complete.cases(df_multivariate),]

# Include information about pathway
df_multivariate <- df_multivariate %>% 
  inner_join(df_cluster_compare %>% 
               filter(nk == nki) %>% 
               select(k, group), by = "k") %>% 
  mutate(group = factor(group)) %>% 
  select(-k)


list_lda_inputs[[i]] <- df_multivariate

# Extract feature matrix and labels
X <- as.matrix(df_multivariate[,variables])
X <- scale(X)
y <- df_multivariate$group

# Fit LDA
lda_fit <- MASS::lda(x = X, grouping = y, prior = c(0.5, 0.5))

# Extract class probabilities
lda_pred_prob <- predict(lda_fit, X)[["posterior"]][,2]

# Run LDA ROC analysis
lda_roc <- pROC::roc(response = y,
                     predictor = lda_pred_prob,
                     direction = "<", 
                     quiet = TRUE)

# Store LDA outputs
list_lda_fit[[i]] <- lda_fit
list_lda_roc[[i]] <- lda_roc

}
```


```{r}
list_vars_flip <- list(
  POND = c("scqtot", "tpocs_tot", "rbsallt", "cbcl_ep_ts", "cbcl_ip_ts"),
  HBN = c("ARI_P_Total_Score", "ASSQ_Total", "CBCL_IP_T", "CBCL_EP_T", "CIS_P_Score",
          "ICU_P_Callous", "ICU_P_Total", "ICU_P_Uncaring", "ICU_P_Unemotional",
          "MFQ_P_Total", "SCARED_P_Total", "SCQ_Total", "SDQ_Difficulties_Total",
          "SDS_Total_T", "Score_Total", "WHODAS_P_Score")
)

dataset_labels <- c("POND+", "HBN")

list_lda_scores <- vector(mode = "list", length = length(human_datasets))
list_lda_loadings <- vector(mode = "list", length = length(human_datasets))
list_lda_loadings_common <- vector(mode = "list", length = length(human_datasets))

names(list_lda_scores) <- dataset_labels
names(list_lda_loadings) <- dataset_labels
names(list_lda_loadings_common) <- dataset_labels
for (i in 1:length(human_datasets)) {
  
  X <- list_lda_inputs[[i]] %>% 
    select(-ID, -group) %>% 
    as.matrix() %>% 
    scale()
  
  y <- list_lda_inputs[[i]] %>% 
    pull(group)
  
  lda_pred <- predict(list_lda_fit[[i]], X)
  lda_pred_y <- lda_pred[["class"]]
  lda_pred_prob <- lda_pred[["posterior"]][,2]
  
  df_mv_scores <- lda_pred[["x"]] %>% 
    as_tibble() %>% 
    mutate(y = y,
           y_pred = lda_pred_y,
           y_pred_prob = lda_pred_prob) 
  
  df_mv_loadings <- cor(x = X, y = df_mv_scores$LD1) %>% 
    as_tibble(rownames = "variable") %>% 
    rename(LD1 = V1) %>% 
    mutate(LD1 = ifelse(variable %in% list_vars_flip[[i]], -1*LD1, LD1))
  
  df_mv_loadings <- df_mv_loadings %>% 
    left_join(list_clinical_acronyms[[i]], by = "variable") 
  
  df_mv_loadings <- df_mv_loadings %>% 
    mutate(group = ifelse(LD1 >= 0, "synaptic", "chromatin"))
  
  df_mv_loadings_common <- df_mv_loadings %>% 
    semi_join(df_common, by = "acronym") 
  
  # df_mv_loadings <- df_mv_loadings %>% 
  #   mutate(acronym = str_pad(acronym, width = max(str_length(acronym)), side = "left"))
  # 
  # acronym_len <- df_mv_loadings %>% 
  #   pull(acronym) %>% 
  #   str_length() %>% unique()
  # 
  # df_mv_loadings_common <- df_mv_loadings_common %>% 
  #   mutate(acronym = str_pad(acronym, width = acronym_len, side = "left"))
  
  if (i == 1) {
    df_mv_loadings_common <- df_mv_loadings_common %>% 
      mutate(variable = factor(variable, levels = variable[order(LD1)]),
             acronym = factor(acronym, levels = acronym[order(LD1)]))
    
    lvls_common <- levels(df_mv_loadings_common$acronym)
  } else {
    df_mv_loadings_common <- df_mv_loadings_common %>% 
      mutate(acronym = factor(acronym, levels = lvls_common))
  }
  
  
  df_mv_loadings <- df_mv_loadings %>% 
    mutate(variable = factor(variable, levels = variable[order(LD1)]),
           acronym = factor(acronym, levels = acronym[order(LD1)]))
  
  list_lda_scores[[i]] <- df_mv_scores
  list_lda_loadings[[i]] <- df_mv_loadings
  list_lda_loadings_common[[i]] <- df_mv_loadings_common
  
}
```

```{r}
cex_vals <- c(5.0, 4.0)

df_lda_scores <- bind_rows(list_lda_scores, .id = "Dataset") %>% 
  mutate(Dataset = factor(Dataset, levels = dataset_labels))

set.seed(123)
plt_lda_scores <- ggplot(df_lda_scores, aes(x = y, y = LD1, fill = y_pred_prob)) + 
  geom_beeswarm(cex = 3.5,
                shape = 21,
                size = 1.0,
                col = "grey50") +
  # geom_jitter(height = 0, width = 0.35, shape = 21, size = 1.0, col = "grey50") +
  facet_grid(.~Dataset) + 
  coord_cartesian(ylim = c(-3.5, 4.5)) +
  scale_x_discrete(labels = c("Transcription", "Synaptic-Immune"), expand = expansion(add = 0.8)) + 
  scale_y_continuous(breaks = seq(-6, 6, by = 2)) + 
  scale_fill_gradientn(colours = c("darkorchid1", "grey70", "seagreen2"),
                       values  = scales::rescale(c(0, 1), from = c(0, 1)),
                       limits  = c(0, 1),
                       breaks = c(0, 0.5, 1.0),
                       guide = guide_colourbar(barwidth = unit(8, "bigpts"),
                                               barheight = unit(50, "bigpts"),
                                               # label.theme = element_text(margin = margin()),
                                               title.position = "right", title.hjust = 0.5)) +
  labs(col = "LDA predicted class",
       y = "LD scores",
       x = "Molecular cluster group",
       fill = "Probability") + 
  theme_bw() +
  theme(legend.margin = margin(),
        legend.box.margin = margin(l = -8),
        legend.spacing = unit(0, "pt"),
        legend.title = element_text(size = 6, angle = 270, margin = margin()),
        legend.text = element_text(size = 6, margin = margin(l = 2, r = 2)),
        axis.title = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        axis.text.x = element_text(size = 6, 
                                   colour = c("darkorchid1", "seagreen2"), 
                                   hjust = c(0.6, 0.4)),
        strip.text = element_text(size = 7),
        plot.margin = margin(l = 0, r = 0, t = 0, b = 0))
```




```{r}
df_lda_roc <- map_dfr(.x = list_lda_roc, .f = function(x) {
  tibble(tpr = x$sensitivities,
         fpr = 1-x$specificities,
         thresholds = x$thresholds,
         AUC = x$auc[1]) %>% 
    arrange(tpr)
}, .id = "Dataset")

df_lda_roc <- df_lda_roc %>% 
  mutate(Dataset = ifelse(Dataset == "POND", "POND+", Dataset),
         Dataset = factor(Dataset, levels = dataset_labels))

df_lda_roc_auc <- df_lda_roc %>% 
  select(Dataset, AUC) %>% 
  distinct() %>% 
  mutate(fpr = 0.8, tpr = 0.2, 
         label = paste0("AUC = ", round(AUC, 3)))

plt_lda_roc <- ggplot(df_lda_roc, aes(x = fpr, y = tpr)) +
  annotate(geom = "segment",
           x = 0, y = 0,
           xend = 1, yend = 1,
           linetype = "dashed",
           linewidth = 0.4) +
  geom_line(linewidth = 0.4) +
  geom_text(data = df_lda_roc_auc, 
            mapping = aes(label = label),
            size = 6 * 0.3527) + 
  facet_grid(.~Dataset) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.2)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.2)) +
  labs(x = "False positive rate",
       y = "True positive rate") +
  theme_bw() +
  theme(axis.title = element_text(size = 6),
        axis.text = element_text(size = 6),
        strip.text = element_text(size = 7),
        plot.margin = margin(l = 0, r = 0, t = 0, b = 5.5))
```

```{r}
palette_binary <- c("synaptic" = "seagreen2",
                    "chromatin" = "darkorchid1")

list_plt_loadings_common <- vector(mode = "list", length = length(list_lda_loadings))
list_plt_loadings <- vector(mode = "list", length = length(list_lda_loadings))
for (i in 1:length(list_lda_loadings)) {
  
  df_lda_loadings_common <- list_lda_loadings_common[[i]] %>% 
    mutate(Dataset = names(list_lda_loadings_common)[i])
  
  plt_loadings_common <- ggplot(df_lda_loadings_common, aes(x = LD1, y = acronym, col = group)) +
    geom_vline(xintercept = 0) +
    geom_segment(mapping = aes(xend = 0, yend = acronym)) +
    geom_point(size = 0.9) +
    facet_grid(.~Dataset) + 
    coord_cartesian(xlim = c(-0.5, 0.5)) +
    scale_x_continuous(breaks = seq(-1, 1, by = 0.5)) +
    scale_colour_manual(values = palette_binary) +
    labs(x = "LD loadings",
         y = NULL) +
    theme_bw() +
    theme(legend.position = "none") +
    theme(axis.title.y = element_text(size = 6),
          axis.text.y = element_text(size = 6),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks.x = element_blank(),
          strip.text = element_text(size = 7))
  
  plt_loadings <- ggplot(list_lda_loadings[[i]], aes(x = LD1, y = acronym, col = group)) +
    geom_vline(xintercept = 0) +
    geom_segment(mapping = aes(xend = 0, yend = acronym)) +
    geom_point(size = 0.9) +
    coord_cartesian(xlim = c(-0.5, 0.5)) +
    scale_x_continuous(breaks = seq(-1, 1, by = 0.5)) +
    scale_colour_manual(values = palette_binary) +
    labs(x = "LD loadings",
         y = "Clinical variable") +
    theme_bw() +
    theme(legend.position = "none") +
    theme(axis.title.x = element_text(size = 6),
          axis.title.y = element_text(size = 6, hjust = 0.6),
          axis.text = element_text(size = 6))
  
  if (i == 1) {
    plt_loadings_common <- plt_loadings_common +
      theme(axis.title.y = element_text(size = 6),
            axis.text.y = element_text(size = 6),
            axis.text.x = element_blank(),
            axis.title.x = element_blank(),
            axis.ticks.x = element_blank())
    
    plt_loadings <- plt_loadings +
      theme(axis.title = element_text(size = 6),
            axis.text = element_text(size = 6))
    
  } else {
    plt_loadings_common <- plt_loadings_common +
      theme(axis.title.y = element_blank(),
            axis.text.y = element_text(size = 6),
            axis.text.x = element_blank(),
            axis.title.x = element_blank(),
            axis.ticks.x = element_blank())
    
    plt_loadings <- plt_loadings + 
      theme(axis.title.x = element_text(size = 6),
            axis.title.y = element_blank(),
            axis.text = element_text(size = 6))
      
  }
  
  loadings_patchwork <- (plt_loadings_common / plt_loadings) + plot_layout(heights = c(0.2, 0.8)) &
    theme(plot.margin = margin(b = 3, r = 2, t = 2))
  
  list_plt_loadings[[i]] <- patchworkGrob(loadings_patchwork)
  
  
}

loadings_grob <- arrangeGrob(list_plt_loadings[[1]],
                             list_plt_loadings[[2]],
                             layout_matrix = rbind(c(1,2)))

outfile <- "loadings_panel.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(235/72, "in"),
    height = unit(320/72, "in"))
grid.draw(loadings_grob)

invisible(dev.off())
```


```{r}
fig_widths <- c(270, 15, 235)
fig_heights <- c(100, 10, 100, 10, 100)
  
fig_layout <- rbind(c(01, 06, 07),
                    c(02, 06, 07),
                    c(03, 06, 07),
                    c(04, 06, 07),
                    c(05, 06, 07))

fig_grob <- arrangeGrob(rectGrob(),
                        rectGrob(), #Pad
                        ggplotGrob(plt_lda_scores), # LDA scores
                        rectGrob(), #Pad
                        ggplotGrob(plt_lda_roc), # ROC
                        rectGrob(), #Pad
                        loadings_grob, # Loadings
                        layout_matrix = fig_layout,
                        widths = unit(fig_widths, "bigpts"),
                        heights = unit(fig_heights, "bigpts"))

  
  fig_height_pt <- sum(fig_heights)
  fig_width_pt <- fig_width
  
  fig_height_in <- fig_height_pt/72
  fig_width_in <- fig_width_pt/72

  
outfile <- paste0(outfile_prefix, ".pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(fig_width_in, "in"),
    height = unit(fig_height_in, "in"))
grid.draw(fig_grob)

grid.text(label = c("A", "B", "C", "D"),
          x = unit(c(6, 6, 6, 290), "bigpts"),
          y = unit(c(312, 215, 105, 312), "bigpts"),
          gp = gpar(fontsize = 10, fontface = "bold"))

invisible(dev.off())
```

