---
title: "Untitled"
output: html_document
date: "2025-10-08"
---

# Initialization

```{r}
library(tidyverse)
library(RMINC)
library(MRIcrotome)
library(grid)
library(gridExtra)
library(RColorBrewer)
```

```{r}
PROJECTPATH <- Sys.getenv("PROJECTPATH")
SRCPATH <- Sys.getenv("SRCPATH")
```

```{r}
source(file.path(SRCPATH, "utils.R"))
source(file.path(SRCPATH, "processing.R"))
source(file.path(SRCPATH, "analysis.R"))
```

```{r}
output_dir <- file.path("outputs", "figure2_draft_1")
outfile_prefix <- "figure2_draft_1"
```

```{r}
pipeline_dir <- file.path(PROJECTPATH, "data/cross_species/v3")

params_id <- "375"
metadata <- file.path(pipeline_dir, "metadata.csv")
pipeline_params <- fetch_params_metadata(metadata = metadata,
                                         params = list(id = params_id))

human_params_id <- pipeline_params[["input_1_id"]]
mouse_params_id <- pipeline_params[["input_2_id"]]
```

```{r}
human_params_id <- pipeline_params[["input_1_id"]]

human_pipeline_dir <- file.path(PROJECTPATH, "data/human/derivatives/v3/", human_params_id)

human_cluster_dir <- file.path(human_pipeline_dir, "clusters", "resolution_3.0")
human_centroid_dir <- file.path(human_pipeline_dir, "centroids", "resolution_0.8")
```

```{r}
mouse_params_id <- pipeline_params[["input_2_id"]]

mouse_pipeline_dir <- file.path(PROJECTPATH, "data/mouse/derivatives/v3/", mouse_params_id)

mouse_cluster_dir <- file.path(mouse_pipeline_dir, "clusters", "resolution_0.2")
mouse_centroid_dir <- file.path(mouse_pipeline_dir, "centroids", "resolution_0.05")
```


# Mouse-human cluster correspondence

```{r}
mouse_cluster_file <- file.path(mouse_cluster_dir, "clusters.csv")
mouse_clusters <- read_csv(mouse_cluster_file, show_col_types = FALSE)

df_mouse_cluster_counts <- mouse_clusters %>% 
  pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = as.numeric(str_remove(nk_name, "nk"))) %>% 
  select(-nk_name) %>% 
  unite(col = "cluster_id", "nk", "k", sep = "-", remove = FALSE) %>% 
  group_by(cluster_id) %>% 
  count() %>% 
  ungroup()
```

```{r}
human_cluster_file <- file.path(human_cluster_dir, "clusters.csv")
human_clusters <- read_csv(human_cluster_file, show_col_types = FALSE)

df_human_cluster_counts <- human_clusters %>% 
  pivot_longer(cols = -ID, names_to = "nk_name", values_to = "k") %>% 
  mutate(nk = as.numeric(str_remove(nk_name, "nk"))) %>% 
  select(-nk_name) %>% 
  unite(col = "cluster_id", "nk", "k", sep = "-", remove = FALSE) %>% 
  group_by(cluster_id) %>% 
  count() %>% 
  ungroup()
```

```{r}
df_similarity <- compute_similarity_significance(
  similarity = import_similarity(param_id = params_id, 
                                 pipeline_dir = pipeline_dir), 
  permutations = import_similarity_permutations(param_id = params_id, 
                                                pipeline_dir = pipeline_dir)
  )

colnames(df_similarity) <- colnames(df_similarity) %>% 
  str_replace("img1", "human") %>% 
  str_replace("img2", "mouse")

cluster_ids <- df_similarity %>% 
  select(human_cluster_id, human_nk, human_k) %>% 
  arrange(human_nk, human_k) %>% 
  distinct() %>% 
  pull(human_cluster_id)

df_cluster_grid <- expand_grid(human_cluster_id = cluster_ids,
                               mouse_cluster_id = cluster_ids) 

df_matches <- df_similarity %>% 
  mutate(match = pval < 0.05) %>% 
  select(human_cluster_id, mouse_cluster_id, match, similarity, pval) %>% 
  right_join(df_cluster_grid) %>% 
  mutate(match = ifelse(is.na(match), FALSE, match))
```




```{r}
df_cluster_coords <- tibble(cluster_id = cluster_ids) %>% 
  separate(col = "cluster_id", into = c("nk", "k"), sep = "-", remove = FALSE) %>% 
  mutate(nk = as.numeric(nk), k = as.numeric(k),
         x = 1:nrow(.))

x_gap <- 1

df_cluster_coords <- tibble(nk = 2:10, 
                            gap = x_gap*0:8) %>% 
  right_join(df_cluster_coords, by = "nk") %>% 
  mutate(x = x + gap)
```



```{r}
# list_nk10 <- vector(mode = "list", length = 8)
# for (nk in 2:9) {
# cols <- paste0("nk", c(nk, 10))
# mouse_clusters_nk <- mouse_clusters[,cols]
# colnames(mouse_clusters_nk) <- c("k", "nk10")
# list_nk10[[nk-1]] <- mouse_clusters_nk %>% 
#   mutate(cluster_id = paste0(nk, "-", k)) %>% 
#   group_by(cluster_id, nk10) %>% 
#   summarise(n_in_10 = n(), .groups = "drop") %>% 
#   left_join(df_mouse_cluster_counts, by = "cluster_id") %>% 
#   mutate(prop_in_10 = n_in_10/n)
# }
# 
# df_nk10 <- bind_rows(list_nk10)
```

```{r}
# tmp <- df_cluster_coords %>% 
#     select(cluster_id, nk, k, x) %>% 
#   left_join(df_nk10, by = "cluster_id") 
# 
# ggplot(tmp, aes(x = x, y = n_in_10, fill = factor(nk10))) + 
#   geom_col() +
#   theme_bw()
```


```{r}
# h_max <- 0.5
# 
# coords_9 <- df_cluster_coords %>% 
#   filter(nk == 9) %>% 
#   select(cluster_id, nk, k, x) %>% 
#   left_join(tmp, by = "cluster_id") %>% 
#   mutate(xmin = x-w/2, xmax = x+w/2,
#          y = 1, ymin = y, h_tot = ymin + n*(h_max/max(n)))
#   
# ggplot(coords_9, aes(x = x, y = n_in_10, fill = factor(nk10))) + 
#   geom_col()
```

```{r}
w <- 0.8
h <- 0.5

df_cluster_coords_human <- df_cluster_coords %>% 
  select(cluster_id, nk, k, x) %>% 
  left_join(df_human_cluster_counts, by = "cluster_id") %>% 
  mutate(xmin = x-w/2, xmax = x+w/2,
         y = 0, ymin = y, ymax = ymin - n*(h/max(n)))

# df_cluster_coords_human <- df_cluster_coords %>% 
#   select(cluster_id, x) %>% 
#   mutate(y = 0, ymin = y, ymax = ymin-h)

df_cluster_coords_mouse <- df_cluster_coords %>% 
  select(cluster_id, nk, k, x) %>% 
  left_join(df_mouse_cluster_counts, by = "cluster_id") %>% 
  mutate(xmin = x-w/2, xmax = x+w/2,
         y = 1, ymin = y, ymax = ymin + n*(h/max(n)))

# df_cluster_coords_mouse <- df_cluster_coords %>% 
#   select(cluster_id, x) %>% 
#   mutate(y = 1, ymin = y, ymax = ymin+h)

df_cluster_bars <- bind_rows(df_cluster_coords_human,
                              df_cluster_coords_mouse)
```



```{r}
df_segments <- df_matches %>% 
  filter(match) %>% 
  select(-match) %>% 
  left_join(df_cluster_coords_human %>% 
              select(cluster_id, x, y),
            by = c("human_cluster_id" = "cluster_id")) %>% 
  left_join(df_cluster_coords_mouse %>% 
              select(cluster_id, xend = x, yend = y),
            by = c("mouse_cluster_id" = "cluster_id"))


h_block <- 0.3

df_cluster_blocks_human <- df_cluster_coords_human %>% 
    group_by(nk) %>% 
  mutate(xmin = min(xmin),
         xmax = max(xmax)) %>% 
  ungroup() %>% 
  select(nk, xmin, xmax, ymin) %>% 
  mutate(ymax = ymin - h - h_block,
         xmin = xmin - 0.3*x_gap,
         xmax = xmax + 0.3*x_gap) %>% 
  distinct()

df_cluster_labels_human <- df_cluster_blocks_human %>%
  mutate(label = paste0("K = ", nk),
         x = (xmin + xmax)/2,
         y = ymax + 0.1,
         ymin = y + 0.1) 

df_cluster_blocks_mouse <- df_cluster_coords_mouse %>% 
    group_by(nk) %>% 
  mutate(xmin = min(xmin),
         xmax = max(xmax)) %>% 
  ungroup() %>% 
  select(nk, xmin, xmax, ymin) %>% 
  mutate(ymax = ymin + h + h_block,
         xmin = xmin - 0.3*x_gap,
         xmax = xmax + 0.3*x_gap) %>% 
  distinct()

df_cluster_labels_mouse <- df_cluster_blocks_mouse %>%
  mutate(label = paste0("K = ", nk),
         x = (xmin + xmax)/2,
         y = ymax - 0.1,
         ymin = y - 0.1) 


df_cluster_blocks <- bind_rows(df_cluster_blocks_human, df_cluster_blocks_mouse)

df_cluster_labels <- bind_rows(df_cluster_labels_human, df_cluster_labels_mouse)

plt <- ggplot(df_segments, aes(x = x, y = y)) + 
  geom_segment(aes(xend = xend, yend = yend, colour = pval), alpha = 1.0) +
  geom_rect(data = df_cluster_blocks, 
            mapping = aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            inherit.aes = FALSE,
            alpha = 0.2) +
  geom_rect(data = df_cluster_labels, 
            mapping = aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            inherit.aes = FALSE,
            fill = "white",
            col = "black",
            linewidth = 0.3) + 
  geom_text(data = df_cluster_labels,
            mapping = aes(x = x, y = y, label = label), 
            inherit.aes = FALSE, 
            size = 3) + 
  geom_rect(data = df_cluster_bars, 
            mapping = aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            inherit.aes = FALSE) + 
  scale_x_continuous(expand = expansion()) + 
  scale_y_continuous(expand = expansion()) + 
  # scale_color_gradientn(colors = rev(brewer.pal(n = 9, name = "PuBu")[c(1:4, 8)])) +
  scale_color_gradientn(colors = rev(brewer.pal(n = 9, name = "PuBu")[3:9])) +
  theme_bw()

plt <- plt +
theme(axis.title = element_blank(),
      axis.text = element_blank(),
      axis.ticks = element_blank())

plt <- plt + theme_void()

outfile <- "mouse_human_matches.pdf"
outfile <- paste(outfile_prefix, outfile, sep = "_")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(8.5, "in"),
    height = unit(3, "in"))
print(plt)
dev.off()

```



```{r}
matches_grob <- ggplotGrob(plt)
```

```{r}
fig_widths <- c(border_padding_width, panel_tot_width, border_padding_width)
fig_heights <- c(border_padding_height, panel_height, panel_padding_height, panel_height, panel_padding_height, panel_height, border_padding_height)

fig_layout <- rbind(c(NA, NA, NA),
                    c(NA,  1, NA),
                    c(NA, NA, NA),
                    c(NA,  2, NA),
                    c(NA, NA, NA),
                    c(NA,  3, NA),
                    c(NA, NA, NA))

fig_grob <- arrangeGrob(
  mouse_neuro_grob,
  matches_grob,
  human_neuro_grob, #
  layout_matrix = fig_layout,
  widths = unit(fig_widths, "bigpts"),
  heights = unit(fig_heights, "bigpts")
)

fig_width_pt <- sum(fig_widths)
fig_height_pt <- sum(fig_heights)

fig_width_in <- fig_width_pt/72
fig_height_in <- fig_height_pt/72

outfile <- paste0(outfile_prefix, ".pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(fig_width_in, "in"),
    height = unit(fig_height_in, "in"))
grid.draw(fig_grob)
dev.off()
```


# Mouse slices

```{r}
# Jacobians to display
jacobians <- "relative"

# Threshold method
threshold <- pipeline_params %>% 
  filter(id == params_id) %>% 
  pull(threshold)

# Threshold value
threshold_value <- pipeline_params %>% 
  filter(id == params_id) %>% 
  pull(threshold_value)

# Threshold symmetric option
threshold_symmetric <- pipeline_params %>% 
  filter(id == params_id) %>% 
  pull(threshold_symmetric)

# Mouse centroid map directory
mouse_centroid_dir <- file.path(mouse_centroid_dir, jacobians)

# Mouse anatomy
mouse_anat_file <- file.path(PROJECTPATH, "data/mouse/atlas/DSURQE_CCFv3_average_50um.mnc")
mouse_anat <- mincGetVolume(mouse_anat_file)
mouse_anat_vol <- mincArray(mouse_anat)

# Mouse mask
mouse_mask_file <- file.path(PROJECTPATH, "data/mouse/atlas/coronal_50um_coverage_bin0.8.mnc")
mouse_mask <- mincGetVolume(mouse_mask_file)

overlay_low <- 0.19
overlay_high <- 1.0

# Mouse anatomy thresholds
mouse_anat_low <- 800
mouse_anat_high <- 2000
```

```{r}
# HIGH LEVEL FIG PARAMS

# Total figure dimensions in pts
fig_width <- 612
fig_height <- 792

# Figure border dimensions in pts
border_padding_width <- 4
border_padding_height <- border_padding_width

# Vertical padding between panels
panel_padding_height <- 50

# Total width and height of all panels, excluding padding
panel_tot_width <- fig_width - 2*border_padding_width
panel_tot_height <- fig_height - 2*border_padding_height - 2*panel_padding_height

# Individual panel height
panel_height <- panel_tot_height/3

```


```{r}
# Layout for mouse neuro panel
mouse_neuro_layout <- rbind(c(1, NA, 2, NA, 3))

# Padding between mouse neuro panels
mouse_neuro_padding_width <- 10

# Total width of neuro panels, excluding padding
mouse_neuro_tot_width <- fig_width - 2*border_padding_width - 2*mouse_neuro_padding_width

# Mouse neuro widths
mouse_neuro_widths <- c(0.2*mouse_neuro_tot_width,
                        mouse_neuro_padding_width,
                        0.3*mouse_neuro_tot_width,
                        mouse_neuro_padding_width,
                        0.5*mouse_neuro_tot_width)

# Mouse neuro height
mouse_neuro_height <- panel_height
```

```{r}
nk_mouse <- 2
list_mouse_centroids <- vector(mode = "list", length = nk_mouse)
for (k in 1:nk_mouse) {
  
  # Import centroid
  img <- import_cluster_map(imgdir = mouse_centroid_dir,
                            mask = mouse_mask_file,
                            nk = nk_mouse, k = k, 
                            threshold = threshold,
                            threshold_value = threshold_value,
                            threshold_symmetric = threshold_symmetric)
  
  list_mouse_centroids[[k]] <- mincArray(img)
  
}


ss_nslices <- 6
mouse_slices <- floor(seq(20, 200, length.out = ss_nslices))

mouse_nk2_neuro_ss_grob <- sliceSeries(nrow = ss_nslices, ncol = 1, slices = mouse_slices) %>% 
  anatomy(mouse_anat_vol, low = mouse_anat_low, high = mouse_anat_high) %>% 
  overlay(list_mouse_centroids[[1]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_mouse_centroids[[2]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  grobify()

mouse_nk2_neuro_title_grob <- gTree(
  children = gList(rectGrob(gp = gpar(fill = "black")),
                   textGrob(c("2-1", "2-2"), 
                            x = c(0.25, 0.75),
                            gp = gpar(col = "white")))
)

# Mouse neuro layout for nk = 2
mouse_nk2_neuro_layout <- rbind(1, NA, 2)

#
mouse_nk2_neuro_padding_height <- 2
mouse_nk2_neuro_title_height <- 20
mouse_nk2_neuro_ss_height <- mouse_neuro_height - mouse_nk2_neuro_title_height - mouse_nk2_neuro_padding_height

mouse_nk2_neuro_widths <- 0.2*mouse_neuro_tot_width
mouse_nk2_neuro_heights <- c(mouse_nk2_neuro_title_height, mouse_nk2_neuro_padding_height, mouse_nk2_neuro_ss_height)


mouse_nk2_neuro_grob <- arrangeGrob(mouse_nk2_neuro_title_grob,
                                    mouse_nk2_neuro_ss_grob,
                                    layout_matrix = mouse_nk2_neuro_layout,
                                    widths = unit(mouse_nk2_neuro_widths, units = "bigpts"),
                                    heights = unit(mouse_nk2_neuro_heights, units = "bigpts"))

mouse_nk2_neuro_grob <- gTree(children = gList(rectGrob(gp = gpar(fill = "black")),
                                               mouse_nk2_neuro_grob))
```



```{r}
nk_mouse <- 6
list_mouse_centroids <- vector(mode = "list", length = nk_mouse)
for (k in 1:nk_mouse) {
  
  # Import centroid
  img <- import_cluster_map(imgdir = mouse_centroid_dir,
                            mask = mouse_mask_file,
                            nk = nk_mouse, k = k, 
                            threshold = threshold,
                            threshold_value = threshold_value,
                            threshold_symmetric = threshold_symmetric)
  
  list_mouse_centroids[[k]] <- mincArray(img)
  
}

ss_nslices <- 3
mouse_slices <- floor(seq(20, 200, length.out = ss_nslices))

mouse_nk6_neuro_ss_grob_1 <- sliceSeries(nrow = ss_nslices, ncol = 1, slices = mouse_slices) %>% 
  anatomy(mouse_anat_vol, low = mouse_anat_low, high = mouse_anat_high) %>% 
  overlay(list_mouse_centroids[[1]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_mouse_centroids[[2]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_mouse_centroids[[3]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  grobify()

mouse_nk6_neuro_ss_grob_2 <- sliceSeries(nrow = ss_nslices, ncol = 1, slices = mouse_slices) %>% 
  anatomy(mouse_anat_vol, low = mouse_anat_low, high = mouse_anat_high) %>% 
  overlay(list_mouse_centroids[[4]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_mouse_centroids[[5]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_mouse_centroids[[6]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  grobify()

mouse_nk6_neuro_title_grob_1 <- gTree(
  children = gList(rectGrob(gp = gpar(fill = "black")),
                   textGrob(c("6-1", "6-2", "6-3"), 
                            x = c(0.25, 0.5, 0.75),
                            gp = gpar(col = "white")))
)

mouse_nk6_neuro_title_grob_2 <- gTree(
  children = gList(rectGrob(gp = gpar(fill = "black")),
                   textGrob(c("6-4", "6-5", "6-6"), 
                            x = c(0.25, 0.5, 0.75),
                            gp = gpar(col = "white")))
)

# Mouse neuro layout for nk = 2
mouse_nk6_neuro_layout <- rbind(1, NA, 2, NA, 3, NA, 4)

#
mouse_nk6_neuro_padding_height <- mouse_nk2_neuro_padding_height
mouse_nk6_neuro_padding_height_2 <- 2*mouse_nk6_neuro_padding_height
mouse_nk6_neuro_title_height <- mouse_nk2_neuro_title_height
mouse_nk6_neuro_ss_height <- mouse_neuro_height - 2*mouse_nk2_neuro_title_height - 2*mouse_nk2_neuro_padding_height - mouse_nk6_neuro_padding_height_2
mouse_nk6_neuro_ss_height <- mouse_nk6_neuro_ss_height/2

mouse_nk6_neuro_widths <- 0.3*mouse_neuro_tot_width
mouse_nk6_neuro_heights <- c(mouse_nk6_neuro_title_height, 
                             mouse_nk6_neuro_padding_height, 
                             mouse_nk6_neuro_ss_height, 
                             mouse_nk6_neuro_padding_height_2, 
                             mouse_nk6_neuro_title_height,
                             mouse_nk6_neuro_padding_height, 
                             mouse_nk6_neuro_ss_height)

mouse_nk6_neuro_grob <- arrangeGrob(mouse_nk6_neuro_title_grob_1,
                                    mouse_nk6_neuro_ss_grob_1,
                                    mouse_nk6_neuro_title_grob_2,
                                    mouse_nk6_neuro_ss_grob_2,
                                    layout_matrix = mouse_nk6_neuro_layout,
                                    widths = unit(mouse_nk6_neuro_widths, units = "bigpts"),
                                    heights = unit(mouse_nk6_neuro_heights, units = "bigpts"))

# mouse_nk6_neuro_grob <- gTree(children = gList(rectGrob(gp = gpar(fill = "black")),
#                                                mouse_nk6_neuro_grob))
```

```{r}
nk_mouse <- 10
list_mouse_centroids <- vector(mode = "list", length = nk_mouse)
for (k in 1:nk_mouse) {
  
  # Import centroid
  img <- import_cluster_map(imgdir = mouse_centroid_dir,
                            mask = mouse_mask_file,
                            nk = nk_mouse, k = k, 
                            threshold = threshold,
                            threshold_value = threshold_value,
                            threshold_symmetric = threshold_symmetric)
  
  list_mouse_centroids[[k]] <- mincArray(img)
  
}

ss_nslices <- 3
mouse_slices <- floor(seq(20, 200, length.out = ss_nslices))

mouse_nk10_neuro_ss_grob_1 <- sliceSeries(nrow = ss_nslices, ncol = 1, slices = mouse_slices) %>% 
  anatomy(mouse_anat_vol, low = mouse_anat_low, high = mouse_anat_high) %>% 
  overlay(list_mouse_centroids[[1]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_mouse_centroids[[2]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_mouse_centroids[[3]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_mouse_centroids[[4]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_mouse_centroids[[5]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  grobify()

mouse_nk10_neuro_ss_grob_2 <- sliceSeries(nrow = ss_nslices, ncol = 1, slices = mouse_slices) %>% 
  anatomy(mouse_anat_vol, low = mouse_anat_low, high = mouse_anat_high) %>% 
  overlay(list_mouse_centroids[[6]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_mouse_centroids[[7]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_mouse_centroids[[8]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_mouse_centroids[[9]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_mouse_centroids[[10]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  grobify()


mouse_nk10_neuro_title_grob_1 <- gTree(
  children = gList(rectGrob(gp = gpar(fill = "black")),
                   textGrob(c("10-1", "10-2", "10-3", "10-4", "10-5"), 
                            x = seq(0, 1, length.out = 7)[c(-1, -7)],
                            gp = gpar(col = "white")))
)

mouse_nk10_neuro_title_grob_2 <- gTree(
  children = gList(rectGrob(gp = gpar(fill = "black")),
                   textGrob(c("10-6", "10-7", "10-8", "10-9", "10-10"), 
                            x = seq(0, 1, length.out = 7)[c(-1, -7)],
                            gp = gpar(col = "white")))
)

# Mouse neuro layout for nk = 2
mouse_nk10_neuro_layout <- rbind(1, NA, 2, NA, 3, NA, 4)

#
mouse_nk10_neuro_padding_height <- mouse_nk6_neuro_padding_height
mouse_nk10_neuro_padding_height_2 <- 2*mouse_nk10_neuro_padding_height
mouse_nk10_neuro_title_height <- mouse_nk2_neuro_title_height
mouse_nk10_neuro_ss_height <- mouse_neuro_height - 2*mouse_nk2_neuro_title_height - 2*mouse_nk2_neuro_padding_height - mouse_nk10_neuro_padding_height_2
mouse_nk10_neuro_ss_height <- mouse_nk10_neuro_ss_height/2

mouse_nk10_neuro_widths <- 0.5*mouse_neuro_tot_width
mouse_nk10_neuro_heights <- c(mouse_nk10_neuro_title_height, 
                             mouse_nk10_neuro_padding_height, 
                             mouse_nk10_neuro_ss_height, 
                             mouse_nk10_neuro_padding_height_2, 
                             mouse_nk10_neuro_title_height,
                             mouse_nk10_neuro_padding_height, 
                             mouse_nk10_neuro_ss_height)

mouse_nk10_neuro_grob <- arrangeGrob(mouse_nk10_neuro_title_grob_1,
                                    mouse_nk10_neuro_ss_grob_1,
                                    mouse_nk10_neuro_title_grob_2,
                                    mouse_nk10_neuro_ss_grob_2,
                                    layout_matrix = mouse_nk10_neuro_layout,
                                    widths = unit(mouse_nk10_neuro_widths, units = "bigpts"),
                                    heights = unit(mouse_nk10_neuro_heights, units = "bigpts"))

# mouse_nk10_neuro_grob <- gTree(children = gList(rectGrob(gp = gpar(fill = "black")),
#                                                mouse_nk10_neuro_grob))
```


```{r}
mouse_neuro_grob <- arrangeGrob(mouse_nk2_neuro_grob,
                                mouse_nk6_neuro_grob,
                                mouse_nk10_neuro_grob,
                                layout_matrix = mouse_neuro_layout, 
                                widths = unit(mouse_neuro_widths, units = "bigpts"),
                                heights = unit(mouse_neuro_height, units = "bigpts"))
```


# Human slices

```{r}
# Jacobians to display
jacobians <- "relative"

# Threshold method
threshold <- pipeline_params %>% 
  filter(id == params_id) %>% 
  pull(threshold)

# Threshold value
threshold_value <- pipeline_params %>% 
  filter(id == params_id) %>% 
  pull(threshold_value)

# Threshold symmetric option
threshold_symmetric <- pipeline_params %>% 
  filter(id == params_id) %>% 
  pull(threshold_symmetric)

# Mouse centroid map directory
human_centroid_dir <- file.path(human_centroid_dir, jacobians)

# Mouse mask
human_mask_file <- file.path(PROJECTPATH, "data/human/registration/v3/reference_files/mask_0.8mm.mnc")
human_mask <- mincGetVolume(human_mask_file)

# human anatomy
human_anat_file <- file.path(PROJECTPATH, "data/human/registration/v3/reference_files/model_0.8mm.mnc")
human_anat <- mincGetVolume(human_anat_file)
human_anat[human_mask < 0.5] <- 0
human_anat_vol <- mincArray(human_anat)

slices_dim_1 <- 27:220
slices_dim_2 <- 10:280
slices_dim_3 <- 1:220
human_anat_vol_cropped <- human_anat_vol[slices_dim_1, slices_dim_2, slices_dim_3]

overlay_low <- 0.19
overlay_high <- 1.0

# Human anatomy thresholds
human_anat_low <- 40
human_anat_high <- 110
```


```{r}
# Layout for mouse neuro panel
human_neuro_layout <- rbind(c(1, NA, 2, NA, 3))

# Padding between human neuro panels
human_neuro_padding_width <- 10

# Total width of neuro panels, excluding padding
human_neuro_tot_width <- fig_width - 2*border_padding_width - 2*human_neuro_padding_width

# human neuro widths
human_neuro_widths <- c(0.2*human_neuro_tot_width,
                        human_neuro_padding_width,
                        0.3*human_neuro_tot_width,
                        human_neuro_padding_width,
                        0.5*human_neuro_tot_width)

# human neuro height
human_neuro_height <- panel_height
```

```{r}
nk_human <- 2
list_human_centroids <- vector(mode = "list", length = nk_human)
for (k in 1:nk_human) {
  
  # Import centroid
  img <- import_cluster_map(imgdir = human_centroid_dir,
                            mask = human_mask_file,
                            nk = nk_human, k = k, 
                            threshold = threshold,
                            threshold_value = threshold_value,
                            threshold_symmetric = threshold_symmetric)
  
  img <- mincArray(img)
  img <- img[slices_dim_1,,slices_dim_3]
  
  list_human_centroids[[k]] <- img
  
}


ss_nslices <- 6
human_slices <- floor(seq(60, 230, length.out = ss_nslices))


human_nk2_neuro_ss_grob <- sliceSeries(nrow = ss_nslices, ncol = 1, slices = human_slices) %>% 
  anatomy(human_anat_vol_cropped, low = human_anat_low, high = human_anat_high) %>% 
  overlay(list_human_centroids[[1]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_human_centroids[[2]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  grobify()

human_nk2_neuro_title_grob <- gTree(
  children = gList(rectGrob(gp = gpar(fill = "black")),
                   textGrob(c("2-1", "2-2"), 
                            x = c(0.25, 0.75),
                            gp = gpar(col = "white")))
)

# human neuro layout for nk = 2
human_nk2_neuro_layout <- rbind(1, NA, 2)

#
human_nk2_neuro_padding_height <- 2
human_nk2_neuro_title_height <- 20
human_nk2_neuro_ss_height <- human_neuro_height - human_nk2_neuro_title_height - human_nk2_neuro_padding_height

human_nk2_neuro_widths <- 0.2*human_neuro_tot_width
human_nk2_neuro_heights <- c(human_nk2_neuro_title_height, human_nk2_neuro_padding_height, human_nk2_neuro_ss_height)


human_nk2_neuro_grob <- arrangeGrob(human_nk2_neuro_title_grob,
                                    human_nk2_neuro_ss_grob,
                                    layout_matrix = human_nk2_neuro_layout,
                                    widths = unit(human_nk2_neuro_widths, units = "bigpts"),
                                    heights = unit(human_nk2_neuro_heights, units = "bigpts"))

human_nk2_neuro_grob <- gTree(children = gList(rectGrob(gp = gpar(fill = "black")),
                                               human_nk2_neuro_grob))
```


```{r}
nk_human <- 6
list_human_centroids <- vector(mode = "list", length = nk_human)
for (k in 1:nk_human) {
  
  # Import centroid
  img <- import_cluster_map(imgdir = human_centroid_dir,
                            mask = human_mask_file,
                            nk = nk_human, k = k, 
                            threshold = threshold,
                            threshold_value = threshold_value,
                            threshold_symmetric = threshold_symmetric)
  
  img <- mincArray(img)
  img <- img[slices_dim_1,,slices_dim_3]
  list_human_centroids[[k]] <- img
  
}

ss_nslices <- 3
human_slices <- floor(seq(60, 230, length.out = ss_nslices))

human_nk6_neuro_ss_grob_1 <- sliceSeries(nrow = ss_nslices, ncol = 1, slices = human_slices) %>% 
  anatomy(human_anat_vol_cropped, low = human_anat_low, high = human_anat_high) %>% 
  overlay(list_human_centroids[[1]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_human_centroids[[2]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_human_centroids[[3]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  grobify()

human_nk6_neuro_ss_grob_2 <- sliceSeries(nrow = ss_nslices, ncol = 1, slices = human_slices) %>% 
  anatomy(human_anat_vol_cropped, low = human_anat_low, high = human_anat_high) %>% 
  overlay(list_human_centroids[[4]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_human_centroids[[5]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_human_centroids[[6]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  grobify()

human_nk6_neuro_title_grob_1 <- gTree(
  children = gList(rectGrob(gp = gpar(fill = "black")),
                   textGrob(c("6-1", "6-2", "6-3"), 
                            x = c(0.25, 0.5, 0.75),
                            gp = gpar(col = "white")))
)

human_nk6_neuro_title_grob_2 <- gTree(
  children = gList(rectGrob(gp = gpar(fill = "black")),
                   textGrob(c("6-4", "6-5", "6-6"), 
                            x = c(0.25, 0.5, 0.75),
                            gp = gpar(col = "white")))
)

# human neuro layout for nk = 2
human_nk6_neuro_layout <- rbind(1, NA, 2, NA, 3, NA, 4)

#
human_nk6_neuro_padding_height <- human_nk2_neuro_padding_height
human_nk6_neuro_padding_height_2 <- 2*human_nk6_neuro_padding_height
human_nk6_neuro_title_height <- human_nk2_neuro_title_height
human_nk6_neuro_ss_height <- human_neuro_height - 2*human_nk2_neuro_title_height - 2*human_nk2_neuro_padding_height - human_nk6_neuro_padding_height_2
human_nk6_neuro_ss_height <- human_nk6_neuro_ss_height/2

human_nk6_neuro_widths <- 0.3*human_neuro_tot_width
human_nk6_neuro_heights <- c(human_nk6_neuro_title_height, 
                             human_nk6_neuro_padding_height, 
                             human_nk6_neuro_ss_height, 
                             human_nk6_neuro_padding_height_2, 
                             human_nk6_neuro_title_height,
                             human_nk6_neuro_padding_height, 
                             human_nk6_neuro_ss_height)

human_nk6_neuro_grob <- arrangeGrob(human_nk6_neuro_title_grob_1,
                                    human_nk6_neuro_ss_grob_1,
                                    human_nk6_neuro_title_grob_2,
                                    human_nk6_neuro_ss_grob_2,
                                    layout_matrix = human_nk6_neuro_layout,
                                    widths = unit(human_nk6_neuro_widths, units = "bigpts"),
                                    heights = unit(human_nk6_neuro_heights, units = "bigpts"))

# human_nk6_neuro_grob <- gTree(children = gList(rectGrob(gp = gpar(fill = "black")),
#                                                human_nk6_neuro_grob))
```

```{r}
nk_human <- 10
list_human_centroids <- vector(mode = "list", length = nk_human)
for (k in 1:nk_human) {
  
  # Import centroid
  img <- import_cluster_map(imgdir = human_centroid_dir,
                            mask = human_mask_file,
                            nk = nk_human, k = k, 
                            threshold = threshold,
                            threshold_value = threshold_value,
                            threshold_symmetric = threshold_symmetric)
  
    img <- mincArray(img)
  img <- img[slices_dim_1,,slices_dim_3]
  list_human_centroids[[k]] <- img
  
}

ss_nslices <- 3
human_slices <- floor(seq(60, 230, length.out = ss_nslices))

human_nk10_neuro_ss_grob_1 <- sliceSeries(nrow = ss_nslices, ncol = 1, slices = human_slices) %>% 
  anatomy(human_anat_vol_cropped, low = human_anat_low, high = human_anat_high) %>% 
  overlay(list_human_centroids[[1]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_human_centroids[[2]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_human_centroids[[3]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_human_centroids[[4]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_human_centroids[[5]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  grobify()

human_nk10_neuro_ss_grob_2 <- sliceSeries(nrow = ss_nslices, ncol = 1, slices = human_slices) %>% 
  anatomy(human_anat_vol_cropped, low = human_anat_low, high = human_anat_high) %>% 
  overlay(list_human_centroids[[6]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_human_centroids[[7]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_human_centroids[[8]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_human_centroids[[9]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(list_human_centroids[[10]], low = overlay_low, high = overlay_high, symmetric = TRUE) %>% 
  grobify()


human_nk10_neuro_title_grob_1 <- gTree(
  children = gList(rectGrob(gp = gpar(fill = "black")),
                   textGrob(c("10-1", "10-2", "10-3", "10-4", "10-5"), 
                            x = seq(0, 1, length.out = 7)[c(-1, -7)],
                            gp = gpar(col = "white")))
)

human_nk10_neuro_title_grob_2 <- gTree(
  children = gList(rectGrob(gp = gpar(fill = "black")),
                   textGrob(c("10-6", "10-7", "10-8", "10-9", "10-10"), 
                            x = seq(0, 1, length.out = 7)[c(-1, -7)],
                            gp = gpar(col = "white")))
)

# human neuro layout for nk = 2
human_nk10_neuro_layout <- rbind(1, NA, 2, NA, 3, NA, 4)

#
human_nk10_neuro_padding_height <- human_nk6_neuro_padding_height
human_nk10_neuro_padding_height_2 <- 2*human_nk10_neuro_padding_height
human_nk10_neuro_title_height <- human_nk2_neuro_title_height
human_nk10_neuro_ss_height <- human_neuro_height - 2*human_nk2_neuro_title_height - 2*human_nk2_neuro_padding_height - human_nk10_neuro_padding_height_2
human_nk10_neuro_ss_height <- human_nk10_neuro_ss_height/2

human_nk10_neuro_widths <- 0.5*human_neuro_tot_width
human_nk10_neuro_heights <- c(human_nk10_neuro_title_height, 
                             human_nk10_neuro_padding_height, 
                             human_nk10_neuro_ss_height, 
                             human_nk10_neuro_padding_height_2, 
                             human_nk10_neuro_title_height,
                             human_nk10_neuro_padding_height, 
                             human_nk10_neuro_ss_height)

human_nk10_neuro_grob <- arrangeGrob(human_nk10_neuro_title_grob_1,
                                    human_nk10_neuro_ss_grob_1,
                                    human_nk10_neuro_title_grob_2,
                                    human_nk10_neuro_ss_grob_2,
                                    layout_matrix = human_nk10_neuro_layout,
                                    widths = unit(human_nk10_neuro_widths, units = "bigpts"),
                                    heights = unit(human_nk10_neuro_heights, units = "bigpts"))

# human_nk10_neuro_grob <- gTree(children = gList(rectGrob(gp = gpar(fill = "black")),
#                                                human_nk10_neuro_grob))
```


```{r}
human_neuro_grob <- arrangeGrob(human_nk2_neuro_grob,
                                human_nk6_neuro_grob,
                                human_nk10_neuro_grob,
                                layout_matrix = human_neuro_layout, 
                                widths = unit(human_neuro_widths, units = "bigpts"),
                                heights = unit(human_neuro_height, units = "bigpts"))
```







# Figure

```{r}
fig_widths <- c(border_padding_width, panel_tot_width, border_padding_width)
fig_heights <- c(border_padding_height, panel_height, panel_padding_height, panel_height, panel_padding_height, panel_height, border_padding_height)

fig_layout <- rbind(c(NA, NA, NA),
                    c(NA,  1, NA),
                    c(NA, NA, NA),
                    c(NA,  2, NA),
                    c(NA, NA, NA),
                    c(NA,  3, NA),
                    c(NA, NA, NA))

fig_grob <- arrangeGrob(
  mouse_neuro_grob,
  matches_grob,
  human_neuro_grob, #
  layout_matrix = fig_layout,
  widths = unit(fig_widths, "bigpts"),
  heights = unit(fig_heights, "bigpts")
)

fig_width_pt <- sum(fig_widths)
fig_height_pt <- sum(fig_heights)

fig_width_in <- fig_width_pt/72
fig_height_in <- fig_height_pt/72

outfile <- paste0(outfile_prefix, ".pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile,
    width = unit(fig_width_in, "in"),
    height = unit(fig_height_in, "in"))
grid.draw(fig_grob)
dev.off()
```



# Misc


```{r}
cp <- data.frame(
  x = c(
    0, -5, -5, 5, 5, 2.5, 5, 7.5, 5, 2.5, 5, 7.5, 5, -2.5, -5, -7.5, -5,
    -2.5, -5, -7.5, -5
  ),
  y = c(
    0, -5, 5, -5, 5, 5, 7.5, 5, 2.5, -5, -7.5, -5, -2.5, 5, 7.5, 5, 2.5,
    -5, -7.5, -5, -2.5
  ),
  class = sample(letters[1:3], 21, replace = TRUE)
)


paths <- data.frame(
  ind = c(
    7, 5, 8, 8, 5, 9, 9, 5, 6, 6, 5, 7, 7, 5, 1, 3, 15, 8, 5, 1, 3, 17, 9, 5,
    1, 2, 19, 6, 5, 1, 4, 12, 7, 5, 1, 4, 10, 6, 5, 1, 2, 20
  ),
  group = c(
    1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7,
    7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10
  )
)

paths$x <- cp$x[paths$ind]
paths$y <- cp$y[paths$ind]
paths$class <- cp$class[paths$ind]

paths %>% filter(group == 10) %>% 
ggplot() +
  geom_bspline(aes(x = x, y = y, group = group, colour = after_stat(index))) +
  geom_point(aes(x = x, y = y), data = cp, color = 'steelblue')
```
```{r}
paths %>% filter(group == 10) %>% arrange(x)
```


```{r}
library(ggforce)

ggplot(tibble(x = c(1, 2, 3), y = c(0, 0.25, 1)), aes(x = x, y = y)) +
  geom_bspline() + 
geom_point()
```
