---
title: "Human and mouse cluster diagnostics"
author: "Antoine Beauchamp"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(SNFtool))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(RColorBrewer))
```

```{r functions, }
source("../../src/utils.R")

estimate_cluster_metrics <- function (W, NUMC = 2:5){
  if (min(NUMC) == 1) {
    warning("Note that we always assume there are more than one cluster.")
    NUMC <- NUMC[NUMC > 1]
  }
  W <- (W + t(W))/2
  diag(W) <- 0
  if (length(NUMC) <= 0) {
    warning(paste("Invalid NUMC provided, must be an integer vector", 
                  "with atleast one other number than 1.", "Using default NUMC=c(2,3,4,5)", 
                  sep = ""))
    NUMC <- 2:5
  }
  degs <- rowSums(W)
  degs[degs == 0] <- .Machine$double.eps
  D <- diag(degs)
  L <- D - W
  Di <- diag(1/sqrt(degs))
  L <- Di %*% L %*% Di
  eigs <- eigen(L)
  eigs_order <- sort(eigs$values, index.return = T)$ix
  eigs$values <- eigs$values[eigs_order]
  eigs$vectors <- eigs$vectors[, eigs_order]
  eigengap <- abs(diff(eigs$values))
  quality <- list()
  for (c_index in 1:length(NUMC)) {
    ck <- NUMC[c_index]
    UU <- eigs$vectors[, 1:ck]
    EigenvectorsDiscrete <- SNFtool:::.discretisation(UU)[[1]]
    EigenVectors <- EigenvectorsDiscrete^2
    temp1 <- EigenVectors[do.call(order, lapply(1:ncol(EigenVectors), 
                                                function(i) EigenVectors[, i])), ]
    temp1 <- t(apply(temp1, 1, sort, TRUE))
    quality[[c_index]] <- (1 - eigs$values[ck + 1])/(1 - 
                                                       eigs$values[ck]) * sum(sum(diag(1/(temp1[, 1] + .Machine$double.eps)) %*% 
                                                                                    temp1[, 1:max(2, ck - 1)]))
  }
  
  out <- tibble(nk = NUMC,
                eigengap = eigengap[NUMC],
                rotation = unlist(quality))
  
  return(out)
}
```

```{r parameters}
#Parameters
output_dir <- "outputs"
mouse_dataset <- "Models_135"
human_dataset <- "POND_SickKids"

#Mouse clustering directory
mouse_cluster_dir <- "../../data/mouse/derivatives/"
mouse_cluster_dir <- file.path(mouse_cluster_dir, mouse_dataset, "clusters")

#Human parameters
es_method <- 'normative-growth'
# es_method <- 'propensity-matching'
es_df <- 3
# es_df <- NA
es_ncontrols <- NA
# es_ncontrols <- 10
cluster_sigma <- 0.5
cluster_K <- 10

#Human_clustering directory
human_cluster_dir <- "../../data/human/derivatives/v1/"
human_cluster_dir <- file.path(human_cluster_dir, human_dataset, "clusters")
human_metadata <- file.path(human_cluster_dir, "metadata.csv")
df_metadata <- fetch_params_metadata(metadata = human_metadata, 
                                     es_method = es_method,
                                     es_df = es_df,
                                     es_ncontrols = es_ncontrols,
                                     cluster_sigma = cluster_sigma, 
                                     cluster_K = cluster_K)

human_cluster_params_id <- pull(df_metadata, "id")
human_cluster_dir <- file.path(human_cluster_dir, human_cluster_params_id, "resolution_0.8")

output_dir <- file.path(output_dir, str_c("H", human_cluster_params_id))
if (!(dir.exists(output_dir))) {
  dir.create(output_dir, recursive = TRUE)
}
```


```{r import}
#Human cluster assignments
human_cluster_file <- file.path(human_cluster_dir, "clusters.csv")
df_human_clusters <- read_csv(human_cluster_file, show_col_types = FALSE)

#Mouse cluster assignments
mouse_cluster_file <- file.path(mouse_cluster_dir, "clusters.csv")
df_mouse_clusters <- read_csv(mouse_cluster_file, show_col_types = FALSE, col_names = str_c("ID", str_c("nk", 2:10)))

#Human affinity matrix
human_affinity_file <- file.path(human_cluster_dir, "affinity.csv")
df_human_affinity <- read_csv(human_affinity_file, show_col_types = FALSE)
mat_human_affinity <- as.matrix(df_human_affinity)
rownames(mat_human_affinity) <- colnames(mat_human_affinity)

#Mouse affinity matrix
mouse_affinity_file <- file.path(mouse_cluster_dir, "affinity.RData")
load(mouse_affinity_file)
mat_mouse_affinity <- W
df_mouse_affinity <- as_tibble(mat_mouse_affinity)
```

# Mouse and human affinity distributions

```{r fig.width = 10, fig.height = 3}
#Human affinity df long form
df_human_affinity_long <- df_human_affinity %>% 
  mutate(patient_1 = colnames(df_human_affinity)) %>% 
  pivot_longer(cols = -patient_1, names_to = "patient_2", values_to = "affinity")

#Mouse affinity df long form
df_mouse_affinity_long <- df_mouse_affinity %>% 
  mutate(model_1 = colnames(df_mouse_affinity)) %>% 
  pivot_longer(cols = -model_1, names_to = "model_2", values_to = "affinity")

#Compare mouse and human affinity
df_affinity_compare <- bind_rows(df_human_affinity_long %>% 
                                   select(affinity) %>% 
                                   mutate(species = "human"),
                                 df_mouse_affinity_long %>% 
                                   select(affinity) %>% 
                                   mutate(species = "mouse"))

p_affinity_dist <- ggplot(df_affinity_compare, 
                          aes(x = affinity, fill = species, y = ..density..)) + 
  geom_histogram(binwidth = 0.0001, position = "dodge") + 
  coord_cartesian(xlim = c(0, 0.01)) + 
  labs(fill = "Species",
       x = "Affinity",
       y = "Density",
       title = "Distribution of affinity values",
       caption = "Note: Maximal affinity is 0.5") + 
  theme_bw()

outfile <- "affinity_distributions.pdf"
outfile <- file.path(output_dir, outfile)
pdf(file = outfile, 
    width = 10,
    height = 5)
print(p_affinity_dist)
dev.off()

p_affinity_dist
```

# Optimal number of human clusters

```{r}
#Max nk to examine
nk_max <- 100

#Human optimal nk
estimateNumberOfClustersGivenGraph(W = mat_human_affinity, NUMC = 2:nk_max)
```

```{r fig.width = 6, fig.height = 5}
#Get human cluster labels for given nk
nk_human <- 3
df_human_labels_nk <- tibble(patient = colnames(df_human_affinity),
                             k = spectralClustering(affinity = mat_human_affinity,
                                                    K = nk_human))

#Arrange patients by cluster assignment
patient_lvls <- df_human_labels_nk %>% 
  arrange(k) %>% 
  pull(patient)

#Clamp affinity values
threshold <- 0.01
df_human_affinity_long_clamped <- df_human_affinity_long %>% 
  mutate(affinity = ifelse(affinity >= threshold, threshold, affinity),
         patient_1 = factor(patient_1, levels = patient_lvls),
         patient_2 = factor(patient_2, levels = patient_lvls))

p_human_affinity_matrix <- ggplot(df_human_affinity_long_clamped, 
                                  aes(x = patient_1,
                                      y = fct_rev(patient_2),
                                      fill = affinity)) + 
  geom_tile() + 
  scale_x_discrete(expand = expansion()) +
  scale_y_discrete(expand = expansion()) +
  scale_fill_gradientn(colours = c("white", brewer.pal(n = 9, name = "Reds")), na.value = "white") + 
  labs(fill = "Affinity",
       x = "Patient",
       y = "Patient",
       title = paste("Human affinity matrix for nk =", nk_human),
       caption = paste("Affinity values clamped at", threshold)) + 
  theme_bw() + 
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

outfile <- paste0("human_affinity_matrix_nk_", nk_human, ".pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile, 
    width = 10,
    height = 8)
print(p_human_affinity_matrix)
dev.off()

p_human_affinity_matrix
```
```{r fig.width = 10, fig.height = 5}
df_human_cluster_metrics <- estimate_cluster_metrics(W = mat_human_affinity, NUMC = 2:nk_max)

xbreaks <- seq(0, nk_max, by = 4)

p_human_eigengap <- ggplot(df_human_cluster_metrics,
                           aes(x = nk, y = eigengap)) + 
  geom_hline(yintercept = 0,
             linetype = "dashed",
             col = "grey50") + 
  geom_line() + 
  geom_point() +
  scale_x_continuous(breaks = xbreaks) + 
  labs(y = "Eigengap") +
  theme_bw()

p_human_rotation <- ggplot(df_human_cluster_metrics,
                           aes(x = nk, y = rotation)) + 
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = xbreaks) + 
  labs(y = "Rotation best") +
  theme_bw()

(p_human_eigengap / p_human_rotation) +
  plot_annotation(title = "Human cluster metric distribution")
```


# Optimal number of mouse clusters

```{r}
#Mouse optimal nk
estimateNumberOfClustersGivenGraph(W = mat_mouse_affinity, NUMC = 2:nk_max)
```

```{r fig.width = 6, fig.height = 5}
#Get human cluster labels for given nk
nk_mouse <- 4
df_mouse_labels_nk <- tibble(model = colnames(df_mouse_affinity),
                             k = spectralClustering(affinity = mat_mouse_affinity,
                                                    K = nk_mouse))

#Arrange models by cluster assignment
model_lvls <- df_mouse_labels_nk %>% 
  arrange(k) %>% 
  pull(model)

#Clamp affinity values
threshold <- 0.01
df_mouse_affinity_long_clamped <- df_mouse_affinity_long %>% 
  mutate(affinity = ifelse(affinity >= threshold, threshold, affinity),
         model_1 = factor(model_1, levels = model_lvls),
         model_2 = factor(model_2, levels = model_lvls))

p_mouse_affinity_matrix <- ggplot(df_mouse_affinity_long_clamped, 
                                  aes(x = model_1,
                                      y = fct_rev(model_2),
                                      fill = affinity)) + 
  geom_tile() + 
  scale_x_discrete(expand = expansion()) +
  scale_y_discrete(expand = expansion()) +
  scale_fill_gradientn(colours = c("white", brewer.pal(n = 9, name = "Reds")), na.value = "white") + 
  labs(fill = "Affinity",
       x = "Model",
       y = "Model",
       title = paste("Mouse model affinity matrix for nk =", nk_mouse),
       caption = paste("Affinity values clamped at", threshold)) + 
  theme_bw() + 
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

outfile <- paste0("mouse_affinity_matrix_nk_", nk_mouse, ".pdf")
outfile <- file.path(output_dir, outfile)
pdf(file = outfile, 
    width = 10,
    height = 8)
print(p_mouse_affinity_matrix)
dev.off()

print(p_mouse_affinity_matrix)
```


```{r fig.width = 10, fig.height = 5}
df_mouse_cluster_metrics <- estimate_cluster_metrics(W = mat_mouse_affinity, NUMC = 2:nk_max)

xbreaks <- seq(0, nk_max, by = 4)

p_mouse_eigengap <- ggplot(df_mouse_cluster_metrics,
                           aes(x = nk, y = eigengap)) + 
  geom_hline(yintercept = 0,
             linetype = "dashed",
             col = "grey50") + 
  geom_line() + 
  geom_point() +
  scale_x_continuous(breaks = xbreaks) + 
  labs(y = "Eigengap") +
  theme_bw()

p_mouse_rotation <- ggplot(df_mouse_cluster_metrics,
                           aes(x = nk, y = rotation)) + 
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = xbreaks) + 
  labs(y = "Rotation best") +
  theme_bw()

(p_mouse_eigengap / p_mouse_rotation) +
  plot_annotation(title = "Mouse cluster metric distribution")
```


